### ISSUE TITLE
Bug: Chat PDF-Link leads to Warehouse23

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1014]
When a chat output with a PDF-Link is created from the ADD, clicking the link in chat will not only open the PDF but also the Warehouse23 page.

![ADD Chat Warhouse](https://user-images.githubusercontent.com/80178910/138077576-2c62296b-ecdb-4d2a-ac82-555e9179d098.JPG)

**Comment by crnormand** [comment]
The user click was generating 2 events.   One with "B420" and one with "(B420)".   The second one could not be parsed correctly, so it opens a W23 link.   I updated the code to kill the event propagation after the first event is received.  

https://github.com/crnormand/gurps/pull/1032
