### ISSUE TITLE
Bug: Tabbed View Sheet doesn't show equipment

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1023]
Equipment created in Foundry doesn't show on the tabbed view sheet.

But it does show on the full view sheet.

Already tried to reimport the characters - doesn't help!
No error in the console.

![no equipment](https://user-images.githubusercontent.com/80178910/138600764-62bbcea0-6176-4860-930f-b661e1a4cdba.JPG)

https://www.transfernow.net/dl/20211022CHVtceMz

**Comment by josmardias** [comment]
This was also happening to me before 0.12, seems to be working fine now
