### ISSUE TITLE
Feature Request: Compatability with the Token Hud Module

### ISSUE THREAD

**Issue by OberusPing** [crnormand/gurps#1033]
Being able to use Token Hud module is a great QoL feature for any system. It basically allows users to quickly make certain checks or rolls from their character sheet via a hud that pops up when a token is selected: https://github.com/Drental/fvtt-tokenactionhud

The developer maintaining the module wrote this guide for system developers that are looking to add support for the module to their system: https://github.com/Drental/fvtt-tokenactionhud/blob/master/adding_systems.md.

Thanks!

**Comment by Farmeroz** [comment]
This could be great - it looks like a really useful module.

**Comment by Volksters** [comment]
I second this too, this is what I would like to speed up simple mook combats without doing too much prep work to add all the scripts and macros.
