### ISSUE TITLE
Feature Request: extend the /show command 

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1035]
Could you please extend the `/show` command to return the values of Basic Move, Current Move, Basic Speed and Fright Check.

`/show move` would return
Basic Move / Current Move

`/show speed` would return
Basic Speed

`/show fright` would return
Fright Check

**Comment by crnormand** [comment]
Done.   BTW, you could already do Fright Check with either:
```
/show frightcheck
/show "fright check"
```
but for you, our loyal customer, I added
`/show fright`

![image](https://user-images.githubusercontent.com/8931036/144095961-7eade1ec-6d01-499d-b8d0-1ab9975f1d0f.png)

It will be in the next release.
