### ISSUE TITLE
Bug: /ev command broken

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1036]
The `/ev` command seems to be broken.

![ev](https://user-images.githubusercontent.com/80178910/139863356-f1e59061-6513-4232-a7bd-b44ba39838b9.png)

![ev error](https://user-images.githubusercontent.com/80178910/139863374-198ff4bf-758f-4014-8389-42979fe699e9.JPG)

**Comment by crnormand** [comment]
Actually, the chat command are not broken.    You just need to enter the full command (the pattern matching is expecting arguments, etc.).

So if you type:
`/ev [st]`
All of the player characters will roll vs their strength attribute, or if you type:
`/ev fp -2`
All of the player characters will lose 2 points of FP.

This stems from the fact that I was worried about overlapping with some other chat system, so I wanted to make our chat commands as specific as possible.

But I see that we are basically "the only game in town", so I will look into implementing a help response if the user just types the first word of the chat command (so they can better see the operations).
