### ISSUE TITLE
Bug: /remote command broken

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1037]
The `/remote` command seems to be broken.

![remote](https://user-images.githubusercontent.com/80178910/139870935-33a4cb0c-9fce-481c-a008-fc25ad6c538d.png)

![remote error](https://user-images.githubusercontent.com/80178910/139870950-9625664f-9f63-41e0-a3f0-e6d7f868bab5.JPG)

**Comment by crnormand** [comment]
Same as https://github.com/crnormand/gurps/issues/1036
