### ISSUE TITLE
Resource trackers might duplicate

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#1069]
LOW Priority, but if I refresh using F5, on some actors, the resource trackers duplicate:

![image](https://user-images.githubusercontent.com/8931036/141366445-3226eac8-9f4a-429f-9442-3cac37f76c62.png)

It doesn't happen to all actors... and the actor it is currently happening on is brand new.   I just created him and imported the XML file.

Note certain if this is an indicator of something else... of just a bad actor.

**Comment by LordOHelmet** [comment]
It als also happened when I created a new resource tracker, it instantly duplicated.

**Comment by Farmeroz** [comment]
Expanding on thiis, I was running a game last night and one of the playuers has a custom resouorce tracker.  Neither he nor I as GM could add or subtract to it or even change the base value.  This was resource tracker 0.  Then I realised that resource tracker 4 had sprung into existence and was actually changing in relation to anything attempted on resource tracker 0 (which sort of gave us a work around).

**Comment by Farmeroz** [comment]
More on this.  I had a token with borked resource tracking showing on the character sheet.  So I deleted the actor and the token and recreated and now there are no additional resource trackers available in the Full GCS, the Editor, the Combat, or the Tabbed.  Just the HP and FP.  Other tokens that still had additional resource trackers still have them, but new ones can't add them.  Going to post this as a new issue, too.

**Comment by mjeffw** [comment]
I think all these issues are fixed.
