### ISSUE TITLE
maneuver is disabled

### ISSUE THREAD

**Issue by josmardias** [crnormand/gurps#1076]
Foundry 0.8.9
GURPS Game Aid 0.12.3

I just can't set a maneuver for a character token.

Right click on the token then clicking on any of the maneuver don't do anything
![image](https://user-images.githubusercontent.com/413430/141606470-a7b8c703-d1e4-4d68-a4f7-2b2180cb22f6.png)

maneuver dropdown is disabled on conditions section
![image](https://user-images.githubusercontent.com/413430/141606507-55496df1-8922-41e9-8480-f385a2809de0.png)

Either way there are no logs on Developer Console

**Comment by LordOHelmet** [comment]
@josmardias Make sure your combat is on an _**active**_ scene.
I had the same issue and noticed that it works when the combat is on the active scene, but does not on deactivated scenes.

**Comment by josmardias** [comment]
Oh, didn't test on the active scene yet, but you are probably right cause I clearly remember testing on a scene that was not active.

Thanks for the help, that was quick!

On that same subject, I assume we are looking for the active scene as source of truth for "which tokens are involved in the combat". Shouldn't we just check the combat tracker then?

Anyway I'll test it in a bit but that fixes it for me so I'm closing the issue, I can reopen it later if I find more problems. Thanks again!
