### ISSUE TITLE
Characters exported with GCA are combining the Advantage Name with its description.

### ISSUE THREAD

**Issue by solidsingularity** [crnormand/gurps#1079]
I'm having a problem where the skills are not showing up on character sheets. They'll show up on the table sheet but not on the full sheet. 
Nick Coffin has stated that this is because "characters is that the Advantages/Disadvantages have REALLY LONG names, which isn't handled well by the character sheet.  It looks to me like you are combining the Advantage Name with its description. For example, on Julia Michelson's sheet, the first advantage in the Cairns group is:
"Hope Fountain Cairn (Energy Reserve) (4) (Gadget/Breakable: Cannot repair; Gadget/Breakable: DR 16-25; Gadget/Breakable: Size -1 or -2; Magical; Slow Recharge (1 pt/day))"

[Julia Michelson (DuCiel).gca4.TXT](https://github.com/crnormand/gurps/files/7534900/Julia.Michelson.DuCiel.gca4.TXT)

**Comment by crnormand** [comment]
Stevil fixed the GCA4 export script to put those modifiers in the notes section of the advantage, instead of the name.   This should help alleviate this issue.    https://github.com/crnormand/gurps/pull/1104     It will be in the next release.
