### ISSUE TITLE
Checking/Unchecking Weapons in Other Equipment

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#1089]
Allow the user to check or uncheck items in the Other Equipment.

This way it would not also clutter up the screen if the user drops the items in the Other Equipment section.

**Comment by mjeffw** [comment]
I'd prefer that any item moved to Other Equipment was automatically unequipped.

**Comment by Volksters** [comment]
That works as well, I'm no coder so I don't know which part is easier for you guys.

**Comment by crnormand** [comment]
Done.   The equipped status mirrors the carried status.   Items will become unequipped when moved into the "other" list.   I am not completely certain this is what you asked for, but there it is ;-)
