### ISSUE TITLE
Feature Request: Persistent or recallable Modifier Bucket

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1092]
So, there are times when you might have a number of modifiers that are consistent for more than one attack.  Maybe you have multiple attacks or just repeating the same one under the same or similar conditions.

It would be great to have either (and maybe this already exists as a possibility):

1. The ability to choose from some recent modifier sets
2. To save some modifier sets or create a macro that "loads" them
3. To select "don't clear" or similar when using them so they remain for next time (even if you slightly adjust them).

**Comment by crnormand** [comment]
You can do this by setting up your modifier bucket as you wish it, and dragging and dropping the modifier bucket (the red square) onto a macro box.   It will create a macro for you that applies all of the modifiers.   You can then create multiple macros that set each of the variations.

Note, the drag and drop code to the macros has been changed to now use only chat macros, so if you set up a few modifiers, and drag them to a macro, it will appear as a chat macro, something like this:
```
!/clearmb
/r [+2 All-Out Defense]
/r [+2 Feverish Defense *Cost 1FP]
```

I had to fix a few bugs, so it will work "best" in the next release ;-)

**Comment by Farmeroz** [comment]
This is awesome - thanks, Chris!
