### ISSUE TITLE
Query: Can you check a skill's level?

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1094]
In a script macro, can you check a skill's level and then do something as a result?

For example, if skill x = or > or < etc. y then...

**Comment by crnormand** [comment]
let skill = GURPS.findSkillSpell(GURPS.LastActor, "Skillname")
if (!!skill) console.log(skill.level)

You can also use: 
GURPS.findAdDisad(GURPS.LastActor, "Ad name")
or
GURPS.findAttack(GURPS.LastActor, "Attack Name")

**Comment by Farmeroz** [comment]
Also excellent and thank again!

**Comment by Farmeroz** [comment]
So trying to work this into the Fireball macro so if the spell skill is high enough (15) it reduces the energy usage by one.

The Fireball is:

```
function fireballDamage(energy) {
 GURPS.executeOTF(`/r [${energy}d burn]`)
 GURPS.executeOTF(`/tr(Threshold) +${energy}`)
}

new Dialog({
  title: `Spell Damage # Dice`,
  content: `<div><label for="energy"># Dice</label><input id="energy" type="text" /></div>`,
  buttons: {
    confirm: {
      label: "Confirm",
      callback: async (html) => fireballDamage(html.find('#energy').val())
    }
  }
}).render(true);
```

But not sure how to get the spell level check in there for "Fireball" to reduce that energy cost by 1 (or by 2 if it's even higher - 18 or 20 I'd have to check the actual limit).

Any suggestions?

The ability to check advantages is great, too.  Is an Attack as in a particular weapon attack?
