### ISSUE TITLE
Feature Request: Combine multiple damage rolls into one

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1102]
When someone casts a spell like Breathe Fire he can put in multiple FP to increase the damage output.

![multiple rolls](https://user-images.githubusercontent.com/80178910/143315562-7db4cb63-831e-4ab4-b172-e35fd2811cc4.JPG)

Multiple dice are rolled - very nice so far.

![rolls](https://user-images.githubusercontent.com/80178910/143315566-948e0788-5f26-458e-adc7-3918031fb014.JPG)

But when it comes to applying the damage there is no option to apply _all the damage_ in one go.
In the example below there are three dice of damage 2; 5 and 6.
So every dice of damage is compared individually against the DR. Thus the first dice (2) inflicts no damage, the second dice (5) 1 point damage and the last (6) inflicts 2 points damage, 3 points in total.

There should be an option to apply the sum of all dice rolled at once.
So it would be 2 + 5 + 6 = 13.
Than DR would be subtracted only once from the total damage rolled for a damage of 9 points.

![ADD](https://user-images.githubusercontent.com/80178910/143315569-14a06073-316a-498f-87c4-56577ea2edc8.JPG)

**Comment by Farmeroz** [comment]
This is a good idea.  You probably want two options for "all".

1. Total sum in one hit
2. Apply all of them but as single hits

**Comment by mjeffw** [comment]
I'd push back on this idea and suggest what you really want is either: multiple OtFs in the attack notes that handle different FP costs (1d-1, 2d-2, 3d-3, etc) or a macro to prompt the user for the number of energy points and then creating a roll with the correct damage.

**Comment by Farmeroz** [comment]
Makes sense, Jeff.  Sort of relates to #1094 where I haven't quite figured out how to modify the "fireball" macro to do the unmodified skill check to then adjust the FP (or other resource tracker) down (or up) appropriately based on energy used.  If that could be finessed into working you can use it as a template of sorts to cater for different spells with different damage dice, but all driven by "energy" to determine damage and FP or Threshold or whatever tracker is being used in one click (and maybe even trigger animations and sounds, I guess).

**Comment by crnormand** [comment]
Jeff fixed this in 2 ways.
1. He added a "Combine" button to the "Resolve Damage" dialog (right clicking on any damage button will bring it up).   This will merge all of the rolls into a single damage.
2. He expanded the OTF damage formula to allow accumulated damage (and FP cost): 
[+1d burn *per 1 FP]
Clicking this will accumulate the roll (just above the modifier bucket).   Clicking the accumulator will "fire it off", rolling the appropriate damage (and paying the appropriate cost).
