### ISSUE TITLE
Query: Syntax to perform multiple D:weapon rolls after a successful A:weapon roll

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1103]
Using a chat macro, doing a simple if/then setup it's easy to check a weapon hit and then roll damage.  In the case of a ranged weapon with a ROF, though, if I want a macro to roll damage for all possible hits (which can then manually apply ones that hit based on the ROF success ratio) how can I add the additional D:weapon rolls in?

I've tried just adding them, but they get ignored.  I've tried putting them on new lines and using the \\syntax, but I can't figure out how to have 1 A:weapon and then if successful roll the number of individual D:weapon rolls that I want.

Any guidance appreciated :-)

**Comment by Farmeroz** [comment]
PS: it would be ideal to get the "apply all" option for the damage rolls and then choose which to apply if it's possible to call that dialogue?  Otherwise individual hits to drag is fine.

**Comment by crnormand** [comment]
We don't have a way of doing this in a chat command.   With a script command, you could do this:

```
await GURPS.executeOTF('R:Pump Shotgun')
if (!GURPS.lastTargetedRoll.failure) {
  let times = GURPS.lastTargetedRoll.rofrcl
  for (let i = 0; i < times; i++)
    GURPS.executeOTF('D:Pump Shotgun')
}
```

You must "await" the first executeOTF() command so that it will complete and update the "lastTargetedRoll" information.

**Comment by Farmeroz** [comment]
Thanks, Chris!  Good to learn about "await", This is perfect :-)

**Comment by Farmeroz** [comment]
Got this working really well.  I run a chat macro that tests ammo supplies against a tracker and then if OK it calls the script macro to run this (couldn't quite figure how to add the ammo check into the same script, but this solution is great - thanks!).
