### ISSUE TITLE
Minimizing the bottom tab with two actor sheets open, wrong one minimizes.

### ISSUE THREAD

**Issue by mehalforc** [crnormand/gurps#1107]
Depending on what one was opened first, will determine which one minimizes the bottom tabs. I even tried it opening three actor sheets, same issue. The first one opened is the only one that minimizes, regardless the actor sheet clicked to minimize.

**Comment by crnormand** [comment]
Ah, you mean the Navigation buttons at the bottom of the character sheet.   Yes, I see this behavior.   I will link it with https://github.com/crnormand/gurps/issues/1059    There seems to be some issues with the Nav bar.

Until they are resolved, you can remove the Nav bar completely by unchecking the system setting:
![image](https://user-images.githubusercontent.com/8931036/143932145-dbe3b011-bff8-4532-bdca-f3715eb4b4cf.png)

And then closing and reopening the character sheets.
