### ISSUE TITLE
Bug: macros pulled from the modifier bucket broken

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1113]
1. Issue:

I set **_two_** modifiers in the bucket:
![current mod](https://user-images.githubusercontent.com/80178910/143956551-c4308ccb-2238-46c3-9cb1-2203d4d5be77.JPG)

Grab the bucket and drag it to the macro bar:
![macro](https://user-images.githubusercontent.com/80178910/143956553-c7eb1237-e3c3-46de-b7a3-2b56e27833ad.JPG)

When I try to run the macro the total modifier set in the bucket is wrong.
![macro ex](https://user-images.githubusercontent.com/80178910/143956555-d558cb21-446d-45be-8373-6e0688c7f66f.JPG)
![macro error](https://user-images.githubusercontent.com/80178910/143956556-7a8147b7-f8e1-4225-81ed-3a8ae4213b5b.JPG)

2. Issue:

- I set **_one_** modifier in the bucket.
- Drag it to the macro bar.
- Clear the bucket.
- Set another **_one_** modifier to the bucket.
- Drag it to the macro created with the first bucket.
- Select "merge"
- Get weird results when I try to run the macro

![macro merge](https://user-images.githubusercontent.com/80178910/143956912-ec6cac1c-3de4-43a4-90f5-740962527e5a.JPG)
![weird macro merge](https://user-images.githubusercontent.com/80178910/143956914-e881b3f9-84bb-4b02-8adc-03d896c79643.JPG)

**Comment by crnormand** [comment]
Yes.   I saw this problem this evening and coded up a fix. If nothing else comes in, I'll try to release again this week.
