### ISSUE TITLE
Bug: Unable to enter 0 for "hexes from center" for explosive damage in the damage dialogue

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1126]
Unable to enter 0 for "hexes from center" for explosive damage in the damage dialogue.  Anything below 1 reverts to 1, meaning you can't have someone at the point of explosion.  I'm sure this worked previously, but I was just testing blowing up some mooks with Explosive Fireballs and noticed it.

**Comment by crnormand** [comment]
Explosion with a range of zero is just regular damage (turning on the Large-Area Injury), correct?   I don't know if it ever worked at 0, but I guess it could.    I will leave for Nick, since the ADD is his baby.

**Comment by mjeffw** [comment]
Yes, this might be a rules interpretation question. From B414:

> The listed damage only applies “as is” to the target struck. For everything else caught in the blast, roll this damage but divide it by (3 x distance in yards from the center of the blast), rounding down. 

My interpretation of that text is that anyone in the target hex takes damage as listed for the attack; others outside the hex take explosive damage. 

In fact, if targets in the hex take the explosive damage, the formula above results in an error: 3 x distance in yards from the center of the explosion would evaluate to zero, which leads to trying to divide by zero. Which can't be done.

**Comment by Farmeroz** [comment]
Thanks Jeff and Chris.

Yep, I agree with your rules interpretation.  For some reason I thought this "worked" before.  II think I need a holiday :-)

On a side note, the damage type "ex" (for explosive) doesn't seem to be recognised.  GCA includes it on appropriate things like Explosive Fireball.  Could the ADD capture that and select Explosive by default?  And in such a case setting range to 0 would change the damage from Explosive to Large Area within the ADD?  Perfectly workable as it is, of course.
