### ISSUE TITLE
Make /show command sortable by alphabetical or numerical order

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#1138]
As title above, allow the GM to sort by highest number in the /show command list or alphabetical order.

**Comment by crnormand** [comment]
Done.
`/show` (`/sh`) sorts numerically
`/showa` (`/sha`) sorts alphabetically
![image](https://user-images.githubusercontent.com/8931036/148500418-9e469625-51f2-4412-96c4-afcfa4d9bd5e.png)
