### ISSUE TITLE
[Feature Request] Vehicle Sheets

### ISSUE THREAD

**Issue by justinthejaguar** [crnormand/gurps#114]
Would it be possible to add the option for vehicle actors into the GURPS system? My particular interest is in setting up space ships using GURPS Spaceships 4e.

**Comment by mjeffw** [comment]
I will add it to the feature list, but we are focused on PC actors first.

**Comment by crnormand** [comment]
The biggest issue is the display.   We would have to build a new HTML page to display the vehicle, and that takes time (especially since neither of us are web designers).    If you happen to have an HTML layout for a vehicle display, please send it to us.

**Comment by justinthejaguar** [comment]
I will take a look around tonight for ideas, and maybe try to throw something together.

**Comment by crnormand** [comment]
Duplicate of  https://github.com/crnormand/gurps/issues/1042
