### ISSUE TITLE
@target for things like First Aid?

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1152]
Is there a way for things like rolling healing from First Aid to target another token?  So something like in the skill First Aid where you might have /hp + 1d-3! for "Pass" you could have /select @target\\/hp +1d-3! to be able to apply it to someone else?

Maybe there should even be a ranged check that you can build in so skills like that you need to be within 1 yard?  That's probably making it too complex for the Pass section, maybe it's better in a macro to be called from there?

**Comment by crnormand** [comment]
Done:  https://github.com/crnormand/gurps/pull/1286

You can now use:

`/hp <formula> @target`

And on the target owner's client, it will pop up:
![image](https://user-images.githubusercontent.com/8931036/155262472-72146505-d26b-482d-a54d-372c519051b7.png)

Which they can accept (or not).   But they get to see the command that will be executed.

**Comment by Farmeroz** [comment]
That's excellent - thanks, Chris!
