### ISSUE TITLE
Possible bug with @self and using dodge. 

### ISSUE THREAD

**Issue by jackisfast** [crnormand/gurps#1166]
I built a simple macro as follows: "!/select @self /r [Dodge]". 

When I run the macro on a reeling player it rolls their adjusted dodge. However when a player rolls it, it rolls their original dodge. 

If I switch the @self tag to their character it functions perfectly. 

I recall there being a "currentdodge" variable or something but I could not find it yet.

**Comment by crnormand** [comment]
You should not need to use the `/select `command.  `/select `changes the Foundry "selection", which is the orange highlight around tokens.

Our OtF commands work on the "LastActor".   We display the name of the LastActor above the Modifier Bucket.   For most users, the LastActor will ALWAYS be their character.

So your macro should just be `/r [Dodge]`.   

However, to be sure, I tested `/sel @self\\/r [Dodge]`, and the client rolled their current dodge.      

And yes, in the code there is a "currentdodge", but to OtF, dodge is always "currentdodge".
