### ISSUE TITLE
[Feature Request] System option to roll attack + plus damage

### ISSUE THREAD

**Issue by Grayscalae** [crnormand/gurps#1168]
For melee and ranged attacks, have a toggle (per actor or system wide) allowing for automatically rolling damage after a to hit roll is made - perhaps even having both in the same chat card, for better parsing and organization. Thus if defense fails, it is just a matter of applying the damage.

**Comment by crnormand** [comment]
You can accomplish this now using On the Fly formulas.   You could add something like this to the note section of your attack:

["Click for Attack"/if [A:_AttackName_] [D:_AttackName_]]

But this is a good suggestion.   I'll see how hard it would be to do.

**Comment by Farmeroz** [comment]
> But this is a good suggestion. I'll see how hard it would be to do.

Might need to consider how the ADD is applied?  At the moment, you setup "to hit" bonuses/minuses and then you do damage next so the pluses/minuses affect the right things.  I think this would need to be able to set everything up front in ADD then pull the right numbers to the right rolls?

Would be nice to be able to do on a per actor or even per attack basis (toggle).

**Comment by crnormand** [comment]
Instead of the automatic roll, we will display a button in the attack chat message (if successful).   This way additional modifiers can be applied and then damage rolled, without having to find the attack again on the character sheet.
https://github.com/crnormand/gurps/pull/1387
