### ISSUE TITLE
[BUG V9] Screen Layout

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1170]
Now, with the stable V9 release of Foundry I would like to start reporting on V9 specific issues.

Foundry V9.238: local App, locally hosted 
GURPS: V0.12.10
Modules: none

The gaming screen is slightly offset to the bottom and to the right. This cuts off small parts of the gaming area.

![GURPS V9 screen layout](https://user-images.githubusercontent.com/80178910/146895258-2948badf-2536-4eb2-92ac-93877f709420.png)

DND is rendered properly.

![DND V9 screen layout](https://user-images.githubusercontent.com/80178910/146895404-4e15f822-6d3b-4aa4-9a7e-f76ef53cc81a.png)

**Comment by r-valyar** [comment]
I second this bug, it can be fully replicated in blank new world. 
![image](https://user-images.githubusercontent.com/63558984/146896444-ea718702-090e-485e-a27d-dacc8e6310fd.png)
