### ISSUE TITLE
[Bug] Conditional Modifier messes up when editing the sheet directly in Foundry.

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#1193]
![Bug1](https://user-images.githubusercontent.com/78762498/147395298-04575109-f11f-46f6-b542-8e6e4eeb5faa.jpg)

The Conditional Modifier suddenly piled up all the conditional modifiers together into one entry. Deleting the entry doesn't do anything, it appears again once the sheet is "saved" in Foundry.

**Comment by mjeffw** [comment]
Fixed
