### ISSUE TITLE
GCS no longer exports XML

### ISSUE THREAD

**Issue by neillc** [crnormand/gurps#12]
Since v4.20 GCS no longer saves characters in XML, but uses JSON instead.

Do you plan to support the new JSON format?

**Comment by crnormand** [comment]
I apologize, but I am not certain what you are referring to.  

If you are talking about the Foundry import... it uses the GCS Output template function, and the template that we are using generates XML.     The Foundry import does not read the GCS files directly.

You can create the XML by selecting the menu options:  “File” -> “Export To...” -> “Master Library Output Templates”, and then select the correct template.   We are currently using the “Fantasy Grounds PC…” template.

**Comment by crnormand** [comment]
Sorry, when I first saw the issue, I thought it came from the GCS repo... and I was a bit confused.    My apologies.
