### ISSUE TITLE
Feature Request: Automatically apply SM modifier in Mod Bucket when you open it for and have targeted a token

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1201]
If SM is loaded on the token/actor when you target and open the ADD, have it apply the correct modifier automatically - would be handy when consistently fighting creates with SM other than 0.

**Comment by mjeffw** [comment]
In what cases does SM modify damage? I'm unfamiliar with those rules.

**Comment by Farmeroz** [comment]
Sorry, Chris - I shouldn't make feature requests in the middle of running a combat with the PCs, a spider demon lord and his hordes, and a dragon...

Not the AAD, the Bucket.  So with a token selected and a token targeted, clicking open the mod bucket would automatically look at the SM of the target and apply it (rather than having to use the drop down each time).  Good for the players, and also for the GM running multiple NPCs fighting against the SM2 spider demon lord!

**Comment by crnormand** [comment]
Done.    This will be in the 0.12.17 release.

**Comment by Farmeroz** [comment]
Thanks!

**Comment by Farmeroz** [comment]
Just tried this - not sure I have the process right to get the functionality?  I had a PC selected, then targeted an SM4 creature, and opened the mod bucket - no SM modifier showing.  Tried rolling an attack and modifier applied.  Not sure if I should be doing this a little differently to get it?

**Comment by crnormand** [comment]
Sorry, that was my fault. I did not explain it well. The size modifier shows up in that "effects modifier" window. It does not get automatically added to the modifier bucket.

**Comment by mjeffw** [comment]
The button on the character sheet was always meant to be a backup and not the primary way to open the window. On the floating tool bar on the upper left of Foundry, make sure that the Token button is selected in the first column, and there should be a button with an icon that looks like a list at the bottom of the second column. That's the main way to open the Effects Window.

**Comment by Farmeroz** [comment]
Thanks, Jeff - I never realised that.  Perfect!
