### ISSUE TITLE
Change default darkness penalties in the modifier bucket 

### ISSUE THREAD

**Issue by Grayscalae** [crnormand/gurps#1203]
The illumination/darkness level in the modifier bucket use what I believe are pre-errata levels from Enhanced Sense.
 The newer, and more sensible, ones are available from here:

http://forums.sjgames.com/showpost.php?p=1879114&postcount=415, should you guys wish to implement it.

![image](https://user-images.githubusercontent.com/86167546/147612431-a5ee6f1c-76ae-4197-9e88-36d57757550c.png)

**Comment by crnormand** [comment]
Done.   Will be in 0.12.17 release
