### ISSUE TITLE
Block skill level not importing correctly when creating an actor and importing directly from a GCS file

### ISSUE THREAD

**Issue by TheFabulousIronChef** [crnormand/gurps#1207]
When importing directly from GCS, the characters' block skills do not translate correctly. It will show either 0 or +0, but not the correct level. Only happens with block, oddly, not parry. I'm running Foundry v. 0.8.9 (Latest Stable Release), GGA v. 0.12.15, hosted by ForgeVTT. This has happened to both a game in which I'm the GM and a game in which I am a player (both on Forge, separate accounts). Both GCS files created by me. 

First pic is in GCS. Second pic is after importing to FoundryVTT. 

<img width="732" alt="Screen Shot 2021-12-31 at 7 51 53 AM" src="https://user-images.githubusercontent.com/46587602/147824397-3c4cb12f-355d-4be1-9ca3-6c30d988fa8a.png">

<img width="857" alt="Screen Shot 2021-12-31 at 7 53 06 AM" src="https://user-images.githubusercontent.com/46587602/147824453-9845c931-65ba-42c9-a25d-8e7a1d270328.png">

**Comment by crnormand** [comment]
It seems to be fixed by @rinickolous 's latest pull request https://github.com/crnormand/gurps/pull/1214 so I am going to close this issue.
