### ISSUE TITLE
[Bug] Disappearing Movement Speed and Dodge

### ISSUE THREAD

**Issue by rcsanders96** [crnormand/gurps#1219]
Hi, I've had a strange issue for a couple months now.

During my games, the list of movement speed/dodge values of my player characters based on encumbrance (the table in the right-hand corner) appears as zeros for everything. What's strange is that this issue doesn't occur when I'm alone setting up the game, it only seems to happen once my players join. 

This may be related to a similar issue I've had occasionally where my foundry vtt client will error out when trying to draw the canvas/token layer. Again, this issue only seems to occur once my players join, and it happens more often when I have more players and/or switch scenes more frequently.

I'm running Windows 10 Home, 64bit, with 32GB of RAM and an Intel i7 processor.
Foundry version 0.8.9 running from the application, not web
I have GURPS 0.12.17 as my system and I'm running the following modules:
-GM Notes
-GM Screen
-Image Hover
-Keybind Lib
-libWrapper
-Multilevel Tokens (This is new, these problems happened before installation)
-PDFoundry
-Pings
-Settings Extender
-Shared Token Visibility
-Token Magic FX

Any help or advice would be greatly appreciated.

Thank you,
-Connor

**Comment by Farmeroz** [comment]
This is interesting.  I also sometimes get the "zeroes in the movement column" issue as a player and a GM at times - but the dodge seems OK.  Logging in now (by myself), it's fine.  I hadn't noticed the pattern of it happening with multiple people logged in, so I'll try to check that.

**Comment by crnormand** [comment]
Do you have the system setting "Maneuver Updates Move" turned on?   If so, this will set the Move value to 0 when the character's combat maneuver is "Do Nothing".    Move is set to 1 when performing Attacks, etc, and to the character's full move value when selecting Move or Move and Attack.

**Comment by Farmeroz** [comment]
> 

I do, but we rarely set maneuvers.  TBH, I haven't seen this for ages - probably not since V9.

**Comment by rcsanders96** [comment]
Hi,

Thank you both for responding. Turns out I did have that setting turned on. We don't set maneuvers, so it's likely that's the cause. Our next game is tonight so I'll let you know if that worked.

Thank you,
-Connor

**Comment by rcsanders96** [comment]
Hi,

So the game went well and we didn't encounter that glitch. I think that setting fixed it. Thank you!
