### ISSUE TITLE
Unable To Edit SW/THR Field In Sheet (Mook Generator Related)

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#1220]
Mooks created via the Mook Generator seems to lack the Sw/thr values, so if anyone drops a weapon on them from the item compendium, will result in issues since most of the weapons are sw/thr based. 

The only long workaround is to make a weapon and have a fix value (Which is a bit time consuming if one has a sudden NPC generated via the Mook Generator requiring a bonk on the PC's head with a club, for example)

**Comment by crnormand** [comment]
As a short term fix, before you drop the Item on the mook, switch the character sheet to the Editor.   In the Editor, you can edit and change the SW and THR values.    Then switch back to whatever character sheet you want, and drop the Item on the mook.

**Comment by Volksters** [comment]
I can't edit the fields, whether it's from Mook Generator or from an imported sheet.

**Comment by crnormand** [comment]
LOL, you are right.    Well, they should be ;-)    

A hidden feature in the Mook generator... you can enter the SW damage in the "Dmg:" field.    If you want to enter both, just separate them with a /.    `THR / SW`   If you only enter one, it is treated as SW.

![image](https://user-images.githubusercontent.com/8931036/148436480-ef12ab71-828a-4056-b495-9cc7f21de6ae.png)

**Comment by crnormand** [comment]
Since you can enter the Th/Sw values in the Mook generator, I changed the label to make it more obvious:
![image](https://user-images.githubusercontent.com/8931036/149027796-d029bb41-0b68-470d-b393-b84ff2212c9c.png)

And I have fixed the full editor so you can manually edit these values.   It will be in the next release
