### ISSUE TITLE
*Costs for trackers do not work if the Tracker Name has a space

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#1227]
Discovered in my game this past weekend: I entered an OTF like this:

`[2d burn *Costs tr(Energy Reserve)]`.

This failed because of the space in the tracker name 'Energy Reserve'.

The Regex in parseDamage does not look for a space in between the parenthesis, only /w (word characters).

**Comment by Farmeroz** [comment]
Interesting - it works for other uses such as:

`/if [/tr(Standard Arrows) -1] {/if [R:"Composite Bow (ST 15)"] [D:"Composite Bow (ST 15)"]}`

I got lucky that for *Costs my only usage at the moment is against Threshold magic which I named "Threshold".

**Comment by crnormand** [comment]
Yes, the bug only occurs if you use the /tr command in a Damage OtF.   For example:
[[2d burn *costs 1 tr(ammo)]](url)
I've got a fix for this, and will be merging it soon.

**Comment by crnormand** [comment]
https://github.com/crnormand/gurps/pull/1228
