### ISSUE TITLE
Character Import from GCS Levelled Reaction Modifiers Off

### ISSUE THREAD

**Issue by Snailramp** [crnormand/gurps#1230]
When importing directly from GCS, Reaction Modifiers are incorrect for levelled Advantages.  When exporting then importing, Reaction Mods are correct.  
For example:
Voice (+2 non levelled) imports fine.
Charisma (3) imports with a +1 to influence rolls and +1 from sapient being with whom you actively interact. 
A talent that gives +1 reaction per level also imports at +1.

**Comment by crnormand** [comment]
This is a question for @rinickolous ;-)

**Comment by crnormand** [comment]
Fixed with: https://github.com/crnormand/gurps/pull/1231

**Comment by Snailramp** [comment]
Wow, thanks!  Sorry I directed it to the wrong venue initially - you are
the bomb!

Gerald Rose
