### ISSUE TITLE
[Feature Request] Add modifiers for Knockdown and Stun rolls from Major Wounds to Skull, Eye, Face, Vitals and Groin on the Major Wound chat card

### ISSUE THREAD

**Issue by Grayscalae** [crnormand/gurps#1232]
In the ADD, when clicking the Major Wound button under Calculation and Results, the following chat card is displayed:

![image](https://user-images.githubusercontent.com/86167546/148962491-a315d9bc-8088-4d8d-9bf2-c1c7ba8bb598.png)

It would be handy if the same card also displayed the following (B420):

- -5 for Major Wound to Face, Vitals or Groin
- -10 for Major Wound to Skull or Eye

That's it.

**Comment by crnormand** [comment]
We actually already put that into the damage calculator.   If you pick the Face or Vitals/Groin as the Hit Location, you will see that the button already has the -5 built into the roll (HT-5) 
![image](https://user-images.githubusercontent.com/8931036/149026634-14dad188-cee7-47c0-a4d5-86fd166cb6e7.png)
The top one is a Face hit, and the bottom to the groin (admittedly, it doesn't say anything about groin/vitals, but it DOES already include the -5 on the HT roll.

And an attack to the Eye or Skull produces:
![image](https://user-images.githubusercontent.com/8931036/149026854-13caf567-b166-40e0-ba45-eff4d7450d9f.png)
(or it will say Eye).

So I am going to close this issue.

**Comment by Grayscalae** [comment]
Ah, didn't know about that. Thanks for sharing.
