### ISSUE TITLE
[BUG] Natural weapons are not usable

### ISSUE THREAD

**Issue by Legendsmith** [crnormand/gurps#1235]
For some reason, using some natural weapons is not working properly with 0.13.0. The result when clicking on usage or level (as would normally roll it to hit) is an error message as such:
![](https://cdn.discordapp.com/attachments/788878698349723669/930344016506159154/unknown.png)
An example of a sheet experiencing this bug:
[fvtt-Actor-alicia.zip](https://github.com/crnormand/gurps/files/7855094/fvtt-Actor-alicia.zip)

**Comment by crnormand** [comment]
Short term.. it is the added parentheses in the attack name "(Feet)".   Remove them (or change them to [] or {}) and the attack will work.   But I will try to fix the parser to be able to handle that.

**Comment by ssveter1** [comment]
Innate attacks from advantages, specifically the skill roll are not working correctly.
![image](https://user-images.githubusercontent.com/10831302/149258064-80f66d84-c68d-4f66-8d36-f0798092be75.png)

**Comment by crnormand** [comment]
Yep, same problem... the parentheses in the attack name are not being parse correctly.   For a shortterm fix, change to 'Innate Attack {Crush}' or 'Innate Attack [Crush]', and it will work.
