### ISSUE TITLE
Latest version is 0.13.0 but latest version showing up on The Forge is 0.12.17

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1236]
Latest version is 0.13.0 but latest version showing up on The Forge is 0.12.17 (where FVTT version is set to 0.8.9).

Is 0.13.0 V9+ only?

**Comment by crnormand** [comment]
Yes.   Foundry changed underlying data structures so the 0.13.x versions will only work on Foundry v9 or higher.  

On Forge, you have to update the Foundry level first, before it will show you the 0.13.x versions.
