### ISSUE TITLE
Import of special characters like ü, ö, ä or ß doesn't work.

### ISSUE THREAD

**Issue by GanoTheDug** [crnormand/gurps#1247]
![image](https://user-images.githubusercontent.com/51094207/150330279-6540e140-86c5-4eca-85cc-1400bd5c1b13.png)

**Comment by crnormand** [comment]
Try changing the system setting for "Import file encoding" to UTF-8:
![image](https://user-images.githubusercontent.com/8931036/150647753-ab735492-ad92-4f73-b4a5-9a7f433ffd85.png)

I know we can import and display unicode characters... so it may just be the file encoding.

**Comment by GanoTheDug** [comment]
That was my mistake. Thank you!
