### ISSUE TITLE
Provide function to allow GM top "secretly" roll [PER] for all players

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#1253]
Maybe !/ev [PER]?
or /ev [!PER]

**Comment by mjeffw** [comment]
Why not set the chat to "private" before you roll?

**Comment by mjeffw** [comment]
The '!' generally means the logical negation. Wouldn't this be confusing?

**Comment by crnormand** [comment]
Agreed.    I was leaning towards:
!/ev [PER]
Which means a private chat command (and everything that results from it... which should include the [PER] roll).   I just doesn't work that way at the moment.

**Comment by Farmeroz** [comment]
Would it be possible for this to automatically check the range from the PC to the target and adjust the rolls accordingly?  If you do it one at a time, you can obviously use the Mod Bucket, but for different PCs with at different ranges you need something that checks individually.  This might be a bridge too far, but just throwing it out there for consideration.  Also, different senses have different range modifiers.  Sometimes you want to restrict to a specific sense, other times you are allowing whichever is best.

Sometimes, too, it's a straight perception roll, other times it's a contest against the target's stealth.  Again, the mod bucket can help with all these things, just wondering how much could be done automatically or specifically added as selectable modifiers for the Mod Bucket?  From Fantasy to Spec Ops to Espionage and others, perception checks are pretty common and always take some effort to get right.

**Comment by crnormand** [comment]
Sorry, I can't do that yet.   But we can now support:

!/ev [PER]

Which is a quiet chat command that rolls [PER] against every player character.

https://github.com/crnormand/gurps/pull/1287

**Comment by crnormand** [comment]
But I was thinking about your situation.   If every player has a different sent of modifiers, you could ask them to set their bucket up correctly (or you could do it yourself, using the tooltip buttons or the /sendmb chat command), and then execute:

`/rem [!PER]`

Which will send a remote command to each player, which will have them execute the Blind perception roll on their active character.   Since each roll is occurring on the client, it will use that player's modifier bucket to affect the roll.

**Comment by Farmeroz** [comment]
That's a really good solution, Chris - thanks!
