### ISSUE TITLE
Unable to create new tokens after upgrading to foundryvtt v9

### ISSUE THREAD

**Issue by pspinler** [crnormand/gurps#1259]
Since I upgraded to version 9, I'm unable to drag actors onto a scene and create a new token.

Here's  a video screencap illustrating the issue: https://drive.google.com/file/d/1gihB8H1NZtogrAxe83oGNwBcH9qMNXuW/view?usp=sharing

Foundry  Version 9 - Build 245
GURPS game aid version 0.13.2

I'm also attaching to this issues a zipped test world with no modules enabled in which I was able to re-create the issue.  There are 3 actors and 3 scenes in this test world, and I see the same issue in all three scenes with all three actors.

Note I was able to create tokens before upgrading to v9 -- you can see at least 2 old tokens from before the upgrade still in place.

Thank you !
-- Pat
[test_world_gurps.zip](https://github.com/crnormand/gurps/files/7964210/test_world_gurps.zip)

**Comment by pspinler** [comment]
An additional couple of data points from some testing just now:

It's not a GURPS specific thing.  I created a new world using the Simple world building system, and replicated the issue there.

It appears to be a  chrome specific issue.  I'm running chrome Version 97.0.4692.71 (Official Build) (64-bit) on linux.   However, firefox on linux 96.0 (64-bit) works as expected, and I'm able to create new tokens using firefox.

**Comment by pspinler** [comment]
Attempting some basic debugging -- I enabled developer tools, viewed the console, set the log level to include all levels, and recreated the issue.   I'll include the console log below, but I don't see any errors, nor does it produce any output at all when I attempt to drag and drop a actor to the scene.

module.mjs:82 Foundry VTT | Foundry Commons Framework Loaded
foundry.js:191 Foundry VTT | Registered callback for init hook
foundry.js:191 Foundry VTT | Registered callback for hotbarDrop hook
foundry.js:191 Foundry VTT | Registered callback for getActorDirectoryEntryContext hook
foundry.js:191 Foundry VTT | Registered callback for getItemDirectoryEntryContext hook
foundry.js:62414 _______________________________________________________________
 _____ ___  _   _ _   _ ____  ______   __ __     _______ _____ 
|  ___/ _ \| | | | \ | |  _ \|  _ \ \ / / \ \   / |_   _|_   _|
| |_ | | | | | | |  \| | | | | |_) \ V /   \ \ / /  | |   | |  
|  _|| |_| | |_| | |\  | |_| |  _ < | |     \ V /   | |   | |  
|_|   \___/ \___/|_| \_|____/|_| \_\|_|      \_/    |_|   |_|  
===============================================================
foundry.js:62424 Foundry VTT | Reestablishing existing session 47e4b582c1b6d7b312587d72
foundry.js:5304 Foundry VTT | Connected to server socket using session 47e4b582c1b6d7b312587d72
foundry.js:191 Foundry VTT | Registered callback for renderChatMessage hook
foundry.js:5409 Foundry VTT | Initializing Foundry Virtual Tabletop Game
foundry.js:232 Foundry VTT | Unregistered callback for init hook
simple.js:23 Initializing Simple Worldbuilding System
foundry.js:2456 Foundry VTT | Synchronized official game time in 32ms
foundry.js:4660 Foundry VTT | Retrieved and compiled template systems/worldbuilding/templates/parts/sheet-attributes.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template systems/worldbuilding/templates/parts/sheet-groups.html
foundry.js:4553 Foundry VTT | Loaded localization file systems/worldbuilding/lang/en.json
foundry.js:4553 Foundry VTT | Loaded localization file lang/en.json
foundry.js:5595 Foundry VTT | Prepared World Documents in 8ms
foundry.js:3053 Foundry VTT | Rendering SceneNavigation
foundry.js:3053 Foundry VTT | Rendering Notifications
foundry.js:3053 Foundry VTT | Rendering Sidebar
foundry.js:3053 Foundry VTT | Rendering PlayerList
foundry.js:3053 Foundry VTT | Rendering Hotbar
foundry.js:3053 Foundry VTT | Rendering Pause
foundry.js:3053 Foundry VTT | Rendering SceneControls
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/hud/navigation.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/sidebar.html
foundry.js:3053 Foundry VTT | Rendering ActorDirectory
foundry.js:3053 Foundry VTT | Rendering CardsDirectory
foundry.js:3053 Foundry VTT | Rendering ChatLog
foundry.js:3053 Foundry VTT | Rendering CombatTracker
foundry.js:3053 Foundry VTT | Rendering CompendiumDirectory
foundry.js:3053 Foundry VTT | Rendering ItemDirectory
foundry.js:3053 Foundry VTT | Rendering JournalDirectory
foundry.js:3053 Foundry VTT | Rendering PlaylistDirectory
foundry.js:3053 Foundry VTT | Rendering SceneDirectory
foundry.js:3053 Foundry VTT | Rendering Settings
foundry.js:3053 Foundry VTT | Rendering RollTableDirectory
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/user/players.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/hud/hotbar.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/hud/pause.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/hud/controls.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/document-partial.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/document-partial.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/chat-log.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/combat-tracker.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/compendium-directory.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/document-partial.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/document-partial.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/scene-partial.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/settings.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/document-partial.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/playlist-partial.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5702 Foundry VTT | Document fonts loaded and ready
utils.min.js:8 
    PixiJS 6.2.1 - ✰ WebGL 2 ✰      http://www.pixijs.com/    ♥♥♥ 
foundry.js:17739 Foundry VTT | Viewing Scene Test Scene
foundry.js:19942 Foundry VTT | Drawing game canvas for scene Test Scene
2foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/chat-message.html
4foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/sidebar/playlists-directory.html
foundry.js:22945 Foundry VTT | Loaded icons/svg/combat.svg (2%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/mystery-man.svg (4%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/cowled.svg (6%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/aura.svg (8%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/up.svg (10%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/padlock.svg (13%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/down.svg (15%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/skull.svg (17%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/light.svg (19%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/explosion.svg (21%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/light-off.svg (23%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/sound.svg (25%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/sound-off.svg (27%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/door-secret-outline.svg (29%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/door-closed-outline.svg (31%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/door-open-outline.svg (33%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/unconscious.svg (35%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/door-locked-outline.svg (38%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/sleep.svg (40%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/daze.svg (42%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/falling.svg (44%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/wing.svg (46%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/paralysis.svg (48%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/net.svg (50%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/blind.svg (52%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/deaf.svg (54%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/silenced.svg (56%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/terror.svg (58%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/fire.svg (60%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/frozen.svg (63%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/lightning.svg (65%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/acid.svg (67%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/blood.svg (69%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/biohazard.svg (71%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/radiation.svg (73%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/poison.svg (75%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/regen.svg (77%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/degen.svg (79%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/downgrade.svg (81%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/upgrade.svg (83%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/target.svg (85%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/eye.svg (88%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/sun.svg (90%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/angel.svg (92%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/ice-shield.svg (94%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/fire-shield.svg (96%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/mage-shield.svg (98%)
foundry.js:22945 Foundry VTT | Loaded icons/svg/holy-shield.svg (100%)
foundry.js:3053 Foundry VTT | Rendering HeadsUpDisplay
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/hud/hud.html
foundry.js:20576 Foundry VTT | Initializing Canvas culling using ScreenCulling backend
pixi.min.js:8 [Violation] 'requestAnimationFrame' handler took 136ms

**Comment by crnormand** [comment]
It has to be something about your setup.   I downloaded test_world_gurps and opened it up.   I was able to drag all three actors to the scene and they created tokens.

Are you still experiencing this issue?
