### ISSUE TITLE
[Feature Request] Add a small checkbox next to the Modifier Bucket, which when toggled act as "Keep modifiers after roll"

### ISSUE THREAD

**Issue by Grayscalae** [crnormand/gurps#1283]
Add a small checkbox next to the Modifier Bucket; when "On', the bucket will not empty after a roll, keeping the same modifiers for future rolls - until the bucket is emptied manually or the box is unchecked and a roll is made.

**Comment by crnormand** [comment]
Until we can do this, remember that you can drag the modifier bucket to a macro button (or most places on a character sheet) to save it

**Comment by crnormand** [comment]
Ok, I've got something.   There is now a "magnet" button in the modifier bucket:
![image](https://user-images.githubusercontent.com/8931036/155248608-c4fcf0d9-9e48-4196-9194-083d55e98ca9.png)

And when you click it:
![image](https://user-images.githubusercontent.com/8931036/155248694-66f05b8c-f6cf-4da3-a383-04cc2fa1abfa.png)

Modifiers will be "stuck" to the bucket... ha ha.   The best I could come up with.   I didn't think a checkbox would convey the same idea.

Of course, we can change this easily enough, if we can find a better icon in the Font Awesome library: https://fontawesome.com/search
