### ISSUE TITLE
[BUG] Combat Maneuvers disappear from Combat Tracker when using Set Maneuver button

### ISSUE THREAD

**Issue by Klasodeth** [crnormand/gurps#1300]
When right-clicking on a token and selecting 'Set Maneuver', choosing a Maneuver causes the icon to appear next to that token on the Combat Tracker. However, when moving to the next token in initiative order, the Maneuver icon disappears from the previous token. Also, when attempting to use the 'Set Maneuver' button to set Maneuvers for multiple tokens without cycling through initiative, the Maneuver icon for the previous token disappears whenever a Maneuver is set on the currently selected token. Double-clicking on the token to open its character sheet shows that the Maneuver did set properly, but does not display the icon on the Combat Tracker.

This behavior only affects tokens that had their Maneuvers set via the 'Set Maneuver' button. If Maneuvers are set by opening the token's character sheet and setting the Maneuver from the Maneuver drop-down in the Conditions section, the Maneuver icons display properly in the Combat Tracker.

Tested on two different systems.

System 1
Foundry Virtual Tabletop Version 9 Build 249
GURPS 4th Ed. Game Aid (Unofficial) v. 0.13.4
Modules Installed:
Dice So Nice! v. 4.4.0
Foundry VTT Arms Reach v.2.1.18
libWrapper v. 1.12.4.0
PDFoundry v. 0.9.1
Stairways (Teleporter) v. 0.8.6

System 2
Foundry Virtual Tabletop Version 9 Build 249
GURPS 4th Ed. Game Aid (Unofficial) v. 0.13.5
Modules Installed: None

**Comment by crnormand** [comment]
Well darn, that is a bummer... I cannot recreate this issue.
When I start a combat, and use the Set Maneuver button, the maneuver continues to be displayed even after I move to the next token in the combat order.  
![image](https://user-images.githubusercontent.com/8931036/156102141-39163a3b-fd01-4925-a4c7-72920a215a8a.png)
I went through 8 rounds of changing maneuvers through various means, and the icons will always displayed.

Gamemaster
Modules:
About Face
Chat Portrait
CodeMirror
Compendium Folders
Dice So Nice!
Forien'd Quest Log
Forien's Unidentified Items
FXMaster
GM Notes
Image Previewer
lib - Color settings
libWrapper
Math.js
Not Your Turn!
NPC Chatter
Patrol
PDFoundry
Permission Viewer
Pin Cushion
Sequencer
Settings Extender
Sidebar Expander
socketlib
SortableJS
Splatter
Target Recall
Tidy UI
Token Attacher
Token Chat link
Token Magic FX
Token Tooltip Alt
TriggerHappy
Turn Alert
Turn Marker

Wow, I never knew I so many modules enabled... I will try a new world with no modules to see if I can recreate.

**Comment by crnormand** [comment]
Nope, sorry.   I created a world with NO modules, and (once I set the system setting for "Maneuver Icon Visibility" to "everyone") I always saw the maneuver icons.

**Comment by Klasodeth** [comment]
That helped! I don't recall changing "Maneuver Icon Visibility", but I checked that setting and it was set to "No One". Changing it to "GM and Owner Only" restored the behavior I was expecting to see on my end. 

That being the case, I guess the actual bug I'm experiencing is that if "Maneuver Icon Visibility" is set to "No One", the "Set Maneuver" button works properly, but the "Maneuver" drop down on the character sheet causes the Maneuver to appear for all players when it should not. Fortunately, that's a bug I can deal with, though I'm sure for more secretive GMs that could be a potential issue.
