### ISSUE TITLE
Apply Damage Dialog chat buttons not functioning

### ISSUE THREAD

**Issue by Battenhatch** [crnormand/gurps#1312]
Well, the Major Wound button at least. This has been in 13.6 & .7 afaict. Maybe 13.5 as well.
![oddoutput](https://user-images.githubusercontent.com/24476876/156708177-49a8c359-23fd-4689-a8e6-1f2a19f92638.jpg)

**Comment by Farmeroz** [comment]
Can confirm.  Also, in the ADD at the top bar it just comes up as "Apply {basic} point(s) of [{damage}] damage to {name}".

Shock dialog the same.

**Comment by crnormand** [comment]
weird... looking into it.

**Comment by crnormand** [comment]
Found it.   Fixing.   Will be released tonight.
