### ISSUE TITLE
Dragging Modifier Bucket to Macro doesn't work.

### ISSUE THREAD

**Issue by Battenhatch** [crnormand/gurps#1313]
After the 13.5-7 developments, the dragging of the modifier bucket to the macros does not work.

**Comment by crnormand** [comment]
I am unable to recreate this issue.    I can create a modifier bucket:
![image](https://user-images.githubusercontent.com/8931036/156869771-2acf01b5-f04c-4f94-a276-62dd572276b8.png)
And when I drag it to a macro button, it creates a script called "Modifier Bucket", which contains the modifiers in chat form:
![image](https://user-images.githubusercontent.com/8931036/156869799-00699de5-67c5-4285-869a-8c9eae4d97da.png)

Can you confirm this is still happening for you, and if so, can you describe the steps you take to recreate it?

**Comment by Battenhatch** [comment]
It turn out to be a Foundry bug - the latest update states that it had introduced a bug that didn't allow drags to the hotbar. I works now with the new update.
