### ISSUE TITLE
Fright check command with @margin

### ISSUE THREAD

**Issue by rjdejonghe** [crnormand/gurps#1323]
The new @margin command works great with skill and attribute rolls, but when you use the \fc command, it doesn't save the margin of success/failure.  

I was hoping to use @margin for the fright check table I made.   Also, is the \fc command supposed to call up a rollable table with the name input at the bottom of the fright check window on a failed roll?  If so it wasn't working for me.

**Comment by crnormand** [comment]
Yes, there was a bug in the `/fc` command concerning the margin of success.   It will work in the next release.  

As for the Roll Table name... it worked for me:
![image](https://user-images.githubusercontent.com/8931036/157150151-a03607c2-7f2c-4a32-9a48-5fca4f9e562d.png)

![image](https://user-images.githubusercontent.com/8931036/157150489-06672fa0-400f-4906-85e2-e9f3f5e3ec20.png)
