### ISSUE TITLE
Make Add Damage (Quietly) as the default option

### ISSUE THREAD

**Issue by TheFabulousIronChef** [crnormand/gurps#1325]
Or at least have it as a switch. It would be a lot easier for the GM to make it public than having the “cat’s out of the bag” scenario and then having the GM scramble to quickly hide it. THANKS!

**Comment by crnormand** [comment]
Can do.  

I am going to see if I can add a 3rd option... change the default based on the target.

When the ADD is brought up on a player character, it will default to "Apply", but when it is brought up on an NPC, it will default to "Apply Quietly".

**Comment by crnormand** [comment]
Cool... got it to work.   I will be in the next release.

**Comment by TheFabulousIronChef** [comment]
Awesome, thanks!

**Comment by TheFabulousIronChef** [comment]
> Can do.
> 
> I am going to see if I can add a 3rd option... change the default based on the target.
> 
> When the ADD is brought up on a player character, it will default to "Apply", but when it is brought up on an NPC, it will default to "Apply Quietly".

I didn't even realize this at first. This is **really** awesome.
