### ISSUE TITLE
[Bug] Adding items with a 0 in the parry bonus spot corrupts the character record

### ISSUE THREAD

**Issue by engurrand** [crnormand/gurps#1326]
When adding any item with a melee attack to a character record, if the melee attack has just a zero in the parry bonus spot (a 0U does not cause the bug) the error appears, the item is not added to the record, and though the record remains responsive, if closed it will not open again.
I'm in Chrome.

![Screen Shot 2022-03-07 at 12 24 45 PM](https://user-images.githubusercontent.com/80167921/157098080-4e97c90d-539a-4184-bd16-e4bcabbcb8e7.png)
![Screen Shot 2022-03-07 at 12 25 00 PM](https://user-images.githubusercontent.com/80167921/157098094-05745d05-4483-44d1-82c6-8ba32fcc80d4.png)
![Screen Shot 2022-03-07 at 12 25 55 PM](https://user-images.githubusercontent.com/80167921/157098118-f140cb9a-b53a-4b00-9b55-a1269b24b738.png)

**Comment by crnormand** [comment]
It should be fixed with this update:   https://github.com/crnormand/gurps/pull/1328
