### ISSUE TITLE
Equipping and Unequipping Foundry Gear Items does not correctly add or remove their bonuses

### ISSUE THREAD

**Issue by engurrand** [crnormand/gurps#1330]
The easiest test is with armor. A simple pair of boots that lists "DR +3/2 Foot" in the Bonuses tab will correctly apply that bonus when the gear is added to the character record, but toggling its equipped state (the checkbox in the carried equipment section) will not affect the listed DR values on the character record. The expected behavior (which I think used to work fine?) was unequipping gear should remove its bonuses e.g. no DR from boots you're not wearing.

This holds true with other bonuses. Gear that gives +1 to a skill will not remove that bonus if the gear is unequipped. 

Also, possibly related, unequipping an item with both melee and ranged attack modes removes the melee listings from the melee attack block but not the ranged listings from the ranged attack block.

In the System Settings I have Remove Unequipped Weapons enabled.

**Comment by crnormand** [comment]
Fixed:  https://github.com/crnormand/gurps/pull/1334
