### ISSUE TITLE
Advanced Damage Dialogue - links to Campaigns book not working

### ISSUE THREAD

**Issue by Kirzai** [crnormand/gurps#134]
With PDFoundry installed and configured to work correctly elsewhere.

Example: the link to B400 for "Large-Area Injury"

**Comment by mjeffw** [comment]
This works for me. Do you have the combined Characters and Campaigns PDF? Or one PDF for each book? If you have separate PDFs, you need to set the System Setting "Basic Set PDF(s)" to "Separate Basic Set Characters, code "B". Basic Set Campaigns, code "BX"". Then change the PDF Code for the Campaigns book to "BX".

![image](https://user-images.githubusercontent.com/7349413/103093375-24510f80-45c8-11eb-8d3c-2e43fcc31b4c.png)

![image](https://user-images.githubusercontent.com/7349413/103093393-33d05880-45c8-11eb-90ad-d4be2113ecb7.png)

**Comment by mjeffw** [comment]
@Kirzai Did you have a chance to review my comments above and verify that you are configured properly? If I don't hear from you in the next week I'm closing this issue.

**Comment by Kirzai** [comment]
Correct. Sorry for wasting your time, I was sure I had tested this at least twice.
The issue is not occurring for me since changing the PDFoundry config to use BX for the second book.
