### ISSUE TITLE
[BUG] Apply damage from spells with damage per pt to targets with DR

### ISSUE THREAD

**Issue by rjdejonghe** [crnormand/gurps#1341]
When you take "all the damage" computed for a spell which does damage per point (e.g. fireball) and drag it onto a target with DR, the DR subtracts from each die individually, rather than from the total amount of damage.  It looks like it basically treats each die as a separate damage allocation rather than grouping it together into one single allocation of damage (so it has the behavior you'd want for something like a gun with RoF 2+, but not for a spell like fireball).

**Comment by mjeffw** [comment]
@rjdejonghe The feature is meant to resolve multi-shot weapons such as automatic firearms or shot guns, where each die roll represents a separate projectile hitting the target. For those attacks, subtracting the DR per roll is the correct rule. We don't have a shortcut yet for spell-like damage, where you get (for example) 1d burn damage per energy point and the intent is to sum all the damage before subtracting DR once.

In the very near future look for a way to accumulate dice of damage for things like these spells.
