### ISSUE TITLE
Query - is there a way to track the duration of things during combat?

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1348]
I've looked for a module to track things like spell duration, time someone is stunned, and so on, during combat but they seem to be system specific (or "About Time" but that is expecting to be deprecated), so then I wondered if there was a way to do it in GGA already that I had missed?

Something that could track, by token, a specific effect / spell / etc. and alert when it "runs out"?

**Comment by mjeffw** [comment]
Not yet, but when Active Effects is *finally* implemented, you can do that with an effect.

**Comment by Farmeroz** [comment]
Thanks - sounds good.  I've found the module Turn Alert in the meantime.  Seems to work fine under V9.
