### ISSUE TITLE
[Bug] Token Action Hud Items With Multiple Attack Modes Roll the Wrong Damage

### ISSUE THREAD

**Issue by engurrand** [crnormand/gurps#1353]
If an item has multiple attack modes then Token Action Hud damage buttons will only roll the first damage listing for the item, not the correct one for the row they're on.

https://www.youtube.com/watch?v=YNNBICiCQMw

**Comment by crnormand** [comment]
This was fixed in the last release of the Token Action HUD.   The code I wrote was not looking at the "Usage" (mode).   Now it does, and it will select the correct damage based on the usage
