### ISSUE TITLE
[Feature Request] — Unconscious status effect

### ISSUE THREAD

**Issue by NagBoard** [crnormand/gurps#1355]
> **Suggestion**

How about adding new status effect with icon - **unconscious** and adding it into OTF for major wounds, so GGA will apply it on target if target fails major wound HT roll for 10 or more?

Idea for the icon:
![image](https://user-images.githubusercontent.com/100212155/159756939-6c22d130-f78c-4b50-9aef-396324f5124e.png)

**Comment by crnormand** [comment]
We already have a "disabled" effect icon.
`/st + disabled`
![image](https://user-images.githubusercontent.com/8931036/181085147-29f2bd99-1718-475f-b7d5-1bccc234a47c.png)
Would that work?
