### ISSUE TITLE
Weapons with a double quote in the name will only use one of two "usages" regardless of which is pressed.

### ISSUE THREAD

**Issue by woefulhc** [crnormand/gurps#1358]
Part of the round/ammo description for shotguns in the length of cartridge (2.5", 2.75" or 3"). This is listed at the end of the weapon name in HighTech. As such, the weapon listings in GCS (and I believe GCA) include that in the name. However, when I created attack lines for both a slug buckshot, only the buckshot was used for making attacks. The damage amounts, damage types, rate of fire and recoil are different for the two different uses. Attaching a sample character sheet. Changing the double quote character to two single quote character preserves how the weapon name looks, but allows the two different usages to be triggered appropriately. The second version of the attached sheet has been modified in this fashion
[nels.zip](https://github.com/crnormand/gurps/files/8346541/nels.zip)
.

**Comment by crnormand** [comment]
Fixed with: https://github.com/crnormand/gurps/pull/1380
