### ISSUE TITLE
Mook Generator Importer does not respect tabs as field delimiters

### ISSUE THREAD

**Issue by Kirzai** [crnormand/gurps#136]
Import removes tabs and must manually add spaces as replacements. Discovered while attempting to import templates from the GURPS Monster Repository. See this link for an example which I've tested:
http://gurpswiki.wikidot.com/m:bodak

I don't think compatibility with this site was ever mentioned, however it should implicitly work with more sources if tabs are also recognized.

**Comment by mjeffw** [comment]
Fixed, it should go out with the next release. I'm including a screen shot where I imported the Bodak unchanged.

![Screen Shot 2020-12-28 at 6 04 26 PM](https://user-images.githubusercontent.com/7349413/103248065-218f4b00-4937-11eb-988d-ec43bd379ead.png)
