### ISSUE TITLE
Mook Generator cannot parse XdY+Z format

### ISSUE THREAD

**Issue by Legendsmith** [crnormand/gurps#1374]
Like it says on the tin. The Mook Generator cannot parse XdY+Z format. It only takes Xd+Z and assumes d6. My group are using other dice for damage in some cases and while we can edit the damage values manually it's rather tedious. Especially as the solution for this is rather simple.

**Comment by crnormand** [comment]
I've updated the RegEx to accept other formats.
![image](https://user-images.githubusercontent.com/8931036/163868136-5b42f3f7-b40c-4988-9667-b40d2aa56f87.png)
