### ISSUE TITLE
NPC Sheet: HP and FP values are not centered in their cells/fields.

### ISSUE THREAD

**Issue by Kirzai** [crnormand/gurps#138]
All other values are centered, these would look better if they were consistent with the others.

**Comment by mjeffw** [comment]
On the list. Lower priority since this is purely UI/appearance.

**Comment by mjeffw** [comment]
Fixed. It will be in the next release.

![image](https://user-images.githubusercontent.com/7349413/103294445-de2cef00-49bf-11eb-9eb8-dc3ec5205289.png)
