### ISSUE TITLE
[bug] DR no longer displaying correctly on NPC/mini and simple character sheets

### ISSUE THREAD

**Issue by rjdejonghe** [crnormand/gurps#1385]
With the NPC/mini and the simple sheet, instead of displaying the number for torso DR instead it just displays the string "[object Object]".  I believe this was still working fine in 0.13.13 so maybe this has to do with the split DR implementation.

**Comment by crnormand** [comment]
Can you ZIP up the character that is showing this and attach it to this issue?   I cannot recreate the bug.

**Comment by rjdejonghe** [comment]
Hi Chris,

I can do that with a few - but it happens with all of the 20+ characters I've checked it for, some were created by the mook generator, some imported from GCS, and some from GCA4.  The problem also occurs in both worlds that I have created - one with a bunch of modules active, and the other which has no modules active at all.

I first noticed the issue after I updated foundry to build 269, so maybe that has something to do with it.  I'll attach a few characters to the issue (and also this email in case that is easier) - is there any more information I could send that might be useful?

Best regards,
Rick DeJonghe

________________________________

**Comment by crnormand** [comment]
Found it, thanks!    It will be fixed in the next release.
https://github.com/crnormand/gurps/pull/1394
