### ISSUE TITLE
Character Sheet Damage Field does not recognize "On the Fly" damage formulas

### ISSUE THREAD

**Issue by Kirzai** [crnormand/gurps#139]
The formulas do work if placed in the Name/Description section, but not in the actual damage section.
E.g. [SW +2 cut]

**Comment by mjeffw** [comment]
It looks like the damage fields currently understand a normal dice expression like "2d+2 cut", but not one that references the basic damage such as your example ("sw+2 cut"). I'll take a look at this today.

**Comment by mjeffw** [comment]
Fixed and will be in the next release.
