### ISSUE TITLE
Problem communicating with Mythic Game Master Emulator (GME) when using Dice so Nice

### ISSUE THREAD

**Issue by LordNigel** [crnormand/gurps#1414]
I've been starting to mess with Mything Game Master Emulator (GME) and it seems to be an amazing tool to help me improvise while GMing. I am particularly interested in making this work to help me in my next campaign, allowing me to truly play off the cuff when needed, and using it on the side for an extra zing.
My eyes glittered when I saw that someone had made an actual full module for GME and it's amazing! 
Unfortunately, however, due to the way that she GURPS Game Aid deals with dice (or something like that), the GME module doesn't work properly everytime Dice So Nice is active. And that's a bummer because we all love to see the dice, right?
Anyway, the maker of the aforementioned module saw the problems shown on the attached image
![image](https://user-images.githubusercontent.com/17715447/168824714-773170aa-2c83-4cda-ab1b-1471a4622b92.png)
He told me that it looks like someone that has to be solved on GURPS's side
Apparently I'm not the first person to have issues with this, but it seem that the person mentioned this on another GitHub so it was not seen by you guys. 
It's clear that everything works as it should when Dice so Nice is deactivated, but the GME module is made to work with it, so it should have something to do with how the GURPS module deals with dice or something. I remember that when I started using GURPS Game Aid I wanted to use "dotted" d6's but they always came with numbers, until something was patched. This makes me believe that the fact that GURPS basically just uses d6's makes the module deal differently with the code behind rolling things. 
I'm a complete amateur when it comes to programming and stuff, so I'm literally just trying to guess. That's probably not useful at all, so I'll just shut up, haha.

**Comment by LordNigel** [comment]
Just to make things clear. The problem is not with the dice themselves. When Dice so Nice is active, the dice are rolled and show up, it's the MACROS that stop working. Answers which should show up on the chat don't show up at all.

**Comment by crnormand** [comment]
Thanks for the issue.  When I get back from vacation, I'll take a look at it.  

We want to support as many 3rd party modules as we can 😄

**Comment by Calmquist** [comment]
When using the Foundry VTT Electron application on Linux, I get the Action Meaning, Event Focus, Subject Meaning and Backstory Focus table results that appear correct. I don't see the 3d dice on the table rolls, but the dice appear with normal rolls.

@LordNigel Could you provide other details?

I tested on Foundry: 9 build 269, GGA 0.13.19, Dice So Nice!: 4.5.0 and Mythic GME Tools 2.4.6. I had no other modules active.

**Comment by Calmquist** [comment]
I can confirm my results on Firefox: 100.0.1 and Chromium: 101,0.4951.64.

**Comment by Calmquist** [comment]
@LordNigel Can you provide the specific Foundry, module and browser version numbers and specific steps to reproduce the error? Can you reproduce the problem with new world and a minimal set of modules?

**Comment by saif-ellafi** [comment]
Hi @Calmquist - remember to configure Dice so Nice! for the first time, following this chat entry
![image](https://user-images.githubusercontent.com/27952699/169410103-82803bcc-c9dd-468e-8dd4-f2f12b4ee3e8.png)

Then simply drag the Macro **Random Event** from the **Mythic GME Macros** Compendium.

If you don't see 3D dice rolling, it is already an issue. But I get just this:
![image](https://user-images.githubusercontent.com/27952699/169410263-ef8d342a-00ee-43e3-b686-6ad4982ca0a2.png)

New world. Not sure what is GGA 0.13.19 but I am in GURPS system 0.14.0

**Comment by Calmquist** [comment]
I am able to replicate the error with the Random Even macro specifically.

**Comment by LordNigel** [comment]
> @LordNigel Can you provide the specific Foundry, module and browser version numbers and specific steps to reproduce the error? Can you reproduce the problem with new world and a minimal set of modules?

Yes, I had the same problemas when creating a new world (using GURPS) and ZERO other modules except for the GME tools and Dice So Nice.
As for the information that you mentioned:
Foundry version 9 - Builds 269
GURPS Game Aid vesrion 0.14.0
Mythic GME Tools version 2.4.6
Dice So Nice version 4.5.0
Lordu's Custom Dice for Dice so Nice version 0.33 (the problem persists with this on or off)
Browser: I don't play on a browser, I use the Foundry standalone UI. Nevertheless, I tried opening a new player using my two Browsers (Firefox and Vivaldi) and had the same issue.

**Comment by LordNigel** [comment]
You asked for the steps:
I just installed the module, then tried to use in my GURPS campaign with the problems already described. Then I tried creating a new world, just to be sure, and the same thing happens.
Some funcions do work, like the Fate Chart Question, which gives me an answer of Yes, No, Exceptional Yes or Exceptional No. However, whenever a roll a double number that would trigger a Random Event, the event words are not shown (Exacly like @saif-ellafi showed). 
The same happens with other Macros that should show words coming from different rolltables (like the Complex Question Macro, from Mythic Variations 1).
Other, simpler macros, work, like showing the Chaos Level and the ones for raising and lowering such level.

**Comment by LordNigel** [comment]
Another piece of information that might be relevant:
I don't actually need to turn OFF the Dice so Nice module for my world. I just need to go to the settings for Dice So Nice and turn the 3D dice off for me ONLY.
Here's a print of the chat log, showing the non-working Random Event Roll when the 3D dice were ON, followed by a roll when the 3D dice were off (and then it worked):
![image](https://user-images.githubusercontent.com/17715447/169573554-d9005d35-d838-4ab7-ae48-57fc021a8d28.png)

**Comment by LordNigel** [comment]
Here are some other prints.
The first one shows the chat log and terminal while rolling Random Events and Complex Questions with 3D dice turned OFF, but with Dice So Nice turned ON as a module (available for other players):
![image](https://user-images.githubusercontent.com/17715447/169573989-7a0d0d0a-d236-48ff-a709-9a615f40970c.png)

Now, here's the terminal and chat log showing what happens when I roll Fate Chart Questions, Random Event and Complex Question. As you can see, Fate Chart Questions work properly (and I can see the 3D dice rolling)
![image](https://user-images.githubusercontent.com/17715447/169574311-9c8c8227-9412-4c6e-ba6d-3a8f03dc6e11.png)

**Comment by LordNigel** [comment]
Here is my regular word, where my campaign is happening and where I will start using Mythic GME for the first time.
Here we can see Mythic GME working, even for Scene Alterations that roll an "interruption" result, because I have 3D dice DISABLED (but Dice so Nice is ON as a module).
![image](https://user-images.githubusercontent.com/17715447/169575308-0f942461-8f7b-478a-91e6-0a2edd908606.png)

**Comment by LordNigel** [comment]
Here I roll the Backstory Generation macro, asking for a sequence of 7 Backstories. Again no issues with 3D dice DISABLED.

![image](https://user-images.githubusercontent.com/17715447/169575594-f2cf57a4-158c-4fee-a5b0-cebcad18fbd0.png)

**Comment by LordNigel** [comment]
Now trying to roll 7 Backstories again, but with 3D dice ACTIVATED.

![image](https://user-images.githubusercontent.com/17715447/169576364-7b94fe30-3aad-45cd-adf8-c6cc25a78c67.png)
 
As you can see, it doesn't even continue after the first problem.

**Comment by LordNigel** [comment]
Now trying to use 3 other complex rolls, Action Questions, Description Questions and Detail Check (with BOTH checkboxes on)

![image](https://user-images.githubusercontent.com/17715447/169576812-02f61391-70b8-45d5-8f86-15884f9dc027.png)

**Comment by LordNigel** [comment]
And now, my last one, the same three Macros from the test above, but working with 3D dice DISABLED:
![image](https://user-images.githubusercontent.com/17715447/169577319-15dae0e5-e837-422e-b9ec-664c49866b84.png)

**Comment by crnormand** [comment]
Wow, thank you for all the information!   I will definitely look into this when I get back from vacation.

**Comment by LordNigel** [comment]
> Wow, thank you for all the information! I will definitely look into this when I get back from vacation.

Thank **_you_** for caring and trying to help! =)

**Comment by Lothex91** [comment]
Hello there!
I was pointed to this thread by Jeansen Vaars, the creator of the GME module.
I'm having the same exact issue @LordNigel has described, and was wondering if there's any news on this?
Currently I had to turn off Dice so Nice so that I could use the GME module with the GURPS Aid

And - by the way - thank you so much for such an amazing Aid!

**Comment by LordNigel** [comment]
Hey there! 

> Hello there! I was pointed to this thread by Jeansen Vaars, the creator of the GME module. I'm having the same exact issue @LordNigel has described, and was wondering if there's any news on this? Currently I had to turn off Dice so Nice so that I could use the GME module with the GURPS Aid
> 
> And - by the way - thank you so much for such an amazing Aid!

Hey there! No news yet. 
As for the moment, since I'm always using Mythic in my GURPS campaigns, I activate the Dice so Nice as a module, so that my players can see the pretty dice, but then I go to the module settings and deactivate it for me only. It's a shame that I can't see my dice rolling, but at least I can use the tools I want and my players can have fun with the dice. Also, when I roll, they see my dice rolling as well, which is a plus. Only the person actively using the Mythic Macros needs to "lose" this feature.
Of course that if the idea is to play a GM-less co-op game, then everybody would have access to Mythic, and that will be a problem (if everybody wants to see the dice rolling, which they should, because who wouldn't?).

**Comment by saif-ellafi** [comment]
Hi @LordNigel @Lothex91 will take a look at this in a moment from Mythic tools side. Perhaps I can do something to hack this until @crnormand can help us.

**Comment by Lothex91** [comment]
> Hi @LordNigel @Lothex91 will take a look at this in a moment from Mythic tools side. Perhaps I can do something to hack this until @crnormand can help us.

Thank you so much Jeansen!

**Comment by Lothex91** [comment]
> @LordNigel @Lothex91 Mythic version 2.4.9 has a hotfix for this. It is not a solution, only temporary so you can see 3D Dice. But we really need @crnormand to fix this in order to have the "tension feeling" of rolling 3D dice one at a time. But at least no errors.

Thank you so much Jeansen!

**Comment by crnormand** [comment]
Hey all, I think I found it.   I will be making a release today, and let's hope ;-)

**Comment by LordNigel** [comment]
> Hey all, I think I found it. I will be making a release today, and let's hope ;-)

That is GREAAAT news!!! I'm hyped!

**Comment by crnormand** [comment]
https://github.com/crnormand/gurps/pull/1458

**Comment by LordNigel** [comment]
GREAT NEWS and also not so great news.
It started to WORK! The fate checks are working, also the random events and complex questions.
However, some rolls that depend on other tables/macros still don't work (Backstory Generator, Detail Check)
![image](https://user-images.githubusercontent.com/17715447/177864340-2b31e055-e536-46dd-ac99-bb693440075b.png)

**Comment by LordNigel** [comment]
> Well, at least we are further along. We did not properly replace the 'Die' with the 'GurpsDie' class, which was causing the error in Dice so nice. With that resolved, now the error seems to be in m-gme. Possible we did not implement enough information in GurpsDie.

We are certainly further along! This is super great. I guess that now that the first part was fixed you apparently know what needs to be changed as well. Hopefully this will help with future integrations between modules, Dice so Nice and GGA!

**Comment by saif-ellafi** [comment]
Thank you @crnormand - tried your fix and works perfectly.
Issue is now on Mythic side indeed, I messed up to workaround GURPS in the meantime.
Just bad timing, now I will revert my workaround and GURPS is all good and Mythic too
Releasing Mythic in a moment
FYI @LordNigel @Lothex91
Cheers
