### ISSUE TITLE
GCS parsing issue on Linux when using special characters

### ISSUE THREAD

**Issue by LordNigel** [crnormand/gurps#1415]
I use both Foundry VTT and GCS on Linux (Ubuntu 20.04.4)
When importing .gcs files directly into foundry (without exporting them as .xml), all special characters from my language, Portuguese, become other symbols (usually two symbols). Characters such as á, à, ã, â, ç, õ, etc. Changing the module's settings to use UTF-8 made no difference.
![image](https://user-images.githubusercontent.com/17715447/168851785-a3eed5f2-b02f-4a46-8e91-5ce1381e6e50.png)
It should say "parça"
![image](https://user-images.githubusercontent.com/17715447/168851840-c8d0c534-abaf-4e13-95c7-4983246670e0.png)
Here it should say "Português"
![image](https://user-images.githubusercontent.com/17715447/168851904-b2ac4785-407b-455d-981f-69951c6190d9.png)
Many others here like "Japão","não", "lá", "até", "organização". (some are correct because I started to fix them manually, then I gave up, knowing that I'd lose it with the next import),

Chris tried to recreate the issue, but his import worked on Windows, which makes this likely to be a Linux thing.
I can still use the "old way" of exporting to XML and importing, but I lose much of the usefulness of being able to update the sheet on GCS quickly and import it immediately.

The problem mas also reported to Rich on the GCS Discord server, but the apparent conclusion is that it's a problem in the parsing on the GURPS Game Aid Side. Here is a screenshot of the discussion:
![image](https://user-images.githubusercontent.com/17715447/168853392-a59011c5-e06d-460c-9ef1-82923b32c740.png)

I've also attached my GCS files for testing.
[BrazilianGCSfiles.zip](https://github.com/crnormand/gurps/files/8709646/BrazilianGCSfiles.zip)

**Comment by crnormand** [comment]
This may have been fixed by this update: https://github.com/crnormand/gurps/pull/1456

**Comment by crnormand** [comment]
LOL, we aim to please.    You might try deleting the token, and creating a new one by dragging it from the Actor tab.   Sometimes the tokens become corrupted.
