### ISSUE TITLE
Apparent issue with the melee parsing code of the Mook Generator

### ISSUE THREAD

**Issue by LordNigel** [crnormand/gurps#1424]
Officializing issue here as per our conversation on Discord.
Trying to create a Mook with any piercing attach with a symbol causes a problem. In other words, "pi" works fine, but variations like "pi+", "pi-" and "pi++" do not work. 
Here is what Foundry shows:
![image](https://user-images.githubusercontent.com/17715447/169891976-74021198-d134-4dcf-bd37-27a53af7d80e.png)

I have tested with items and the damage is parsed correctly, it's just on the Mook Generator.

**Comment by crnormand** [comment]
Well, I can get "pi+" working... but still having an issue with "pi++".
