### ISSUE TITLE
Showing The Flavour Text After Rolling If There Is Any Written

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#1426]
A suggestion for the text when one writes something as part of a "package" in the OTFs. When there's a text involved, can it show on the chatlog too?

For example: I have an OTF that says  ["Fire that machine gun!" S:"Gunner*(Machine Gun)"|dx-4|S:"Gunner"-4] 
It appears on the chat and can be clicked, but when you roll for it, it doesn't show up as "Fire that machine gun!". 

I don't know if it would be a clutter but it helps me knowing what kind of OTFs that my players had roll for if it was a text written there.

**Comment by crnormand** [comment]
I sort of got it working... for one level.    If a player clicks on that button, it will display:
![image](https://user-images.githubusercontent.com/8931036/180309597-37cd502a-7f0f-4452-8724-a6b1c2a22f4b.png)
But if they click on the "Roll Vs" button (to roll it again), 
![image](https://user-images.githubusercontent.com/8931036/180309708-2e1e6ad9-2004-4159-8eaa-d33a9398f48d.png)
we lose the override text.

**Comment by crnormand** [comment]
But it better than nothing... and it would be next to impossible to save that text.. so I am going to close this.
