### ISSUE TITLE
Notes Within Weapons From GCS Not Showing Up in Character Sheet

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#1427]
When there are notes written inside say, a ranged weapon (The one below Usage), it does not appear inside the sheet.

**Comment by crnormand** [comment]
I cannot recreate.   Any notes on the equipment (that appear on the ranged attack) also appear in Foundry.

**Comment by Volksters** [comment]
![Foundry_Bug](https://user-images.githubusercontent.com/78762498/180652837-fd4aad2d-1ef0-4518-a680-ebcf35b1d70c.jpg)

Here's what happens when I import the sheet. 

In GCS: I have additional notes within the field as shown here.

![Foundry_Bug_2](https://user-images.githubusercontent.com/78762498/180652890-30f48652-5b9f-4161-871a-18d8259705b9.jpg)

However, once imported into Foundry, it doesn't appear. I am not sure if it's just an oversight or a bug or just maybe my problem.

**Comment by crnormand** [comment]
Are you editing equipment, or is that and Advantage?   Can you zip up the .gcs file and drop it into this issue?

**Comment by Volksters** [comment]
That's an advantage. I haven't tested equipment but I think it might be fine with equipment. 

I will see if I can do that. I am out of town at the moment.

**Comment by crnormand** [comment]
> That's an advantage. I haven't tested equipment but I think it might be fine with equipment.
> 
> I will see if I can do that. I am out of town at the moment.

When you get a chance, can you zip up a .gcs file that is showing this issue?

**Comment by Volksters** [comment]
[Skylos_GCS.zip](https://github.com/crnormand/gurps/files/9418773/Skylos_GCS.zip)

Here's the file. We messed around a lot in the advantages' inner section, maybe that's the reason why it's not appearing in GGA.

**Comment by crnormand** [comment]
Found it.   They are called "usage notes"... and we were looking for "notes".
