### ISSUE TITLE
Importing a .gcs file doesn't respect utf-8 encoding even if set to that in System Settings

### ISSUE THREAD

**Issue by mdonovan5** [crnormand/gurps#1451]
<img width="742" alt="Screen Shot 2022-06-28 at 22 14 20" src="https://user-images.githubusercontent.com/346141/176338182-f7b1f3c9-f4ab-43ad-a7c2-4473faa69e09.png">
<img width="800" alt="Screen Shot 2022-06-28 at 22 14 13" src="https://user-images.githubusercontent.com/346141/176338202-1e6e7b5c-d29e-43b9-9b2e-c6e0a62d786b.png">
<img width="584" alt="Screen Shot 2022-06-28 at 22 17 05" src="https://user-images.githubusercontent.com/346141/176338216-480a4145-0afb-473b-9060-198afde518f0.png">
[Idar Hegdahl.gcs.zip](https://github.com/crnormand/gurps/files/9006761/Idar.Hegdahl.gcs.zip)

**Comment by mdonovan5** [comment]
On MacOS 10.15.7 in the desktop app

**Comment by crnormand** [comment]
This may be fixed by this update:   https://github.com/crnormand/gurps/pull/1456

**Comment by crnormand** [comment]
Update and give it a try... I think it may be fixed.

**Comment by mdonovan5** [comment]
I can confirm it is fixed.
