### ISSUE TITLE
GCS Same Technique with Different Skill Specializations Conflicts

### ISSUE THREAD

**Issue by ingeanus** [crnormand/gurps#1453]
When importing [this character](https://mega.nz/file/l0pRSKpB#lK_26jfXcnRq-ciH6yWH7MD6y26ZLRn4X2_Ij7kkogA), the two techniques for **Close-Combat Shooting** are specialized by **Guns (Pistol)** and **Guns (Long Arm)** while in GCS. After import they lose the specializations and when rolling the Guns (Pistol) one, it instead rolls the Guns (Long Arm) one (The skill 19 Technique instead of the skill 15). If you change the name at all (e.g. adding (Pistol) or (Long Arm) to the name of either) then the conflict dissapears, but it should have some way of differentiating between them on import.

**Comment by crnormand** [comment]
Solved.   If we detect that it is a technique, we will append the skill default to the name:
![image](https://user-images.githubusercontent.com/8931036/180258041-8503ebef-7203-45b9-ac55-97b66660c4c0.png)
https://github.com/crnormand/gurps/pull/1468
