### ISSUE TITLE
GCS Import Broken

### ISSUE THREAD

**Issue by Snailramp** [crnormand/gurps#1463]
Getting an error when re-importing a char from GCS export.  Worked once, then made a change to the GCS sheet, exported that.  Now getting this error.  Using most recent version of GGA, main v9 version of FVTT.  Tried with all modules deactivated, same error.

![unknown](https://user-images.githubusercontent.com/85088198/179428294-496c5d4a-5564-4b1a-8b21-090daf607575.png)

**Comment by crnormand** [comment]
Merged
