### ISSUE TITLE
Portrait issues

### ISSUE THREAD

**Issue by GuineaThePig** [crnormand/gurps#147]
The character sheet portrait distorts any hexagonal or square portraits, and foundry itself crops rectangular portraits on the sidebar making it impossible to get the portrait to not get messed up in some way on some screen right now

The character sheet portrait also seems to crop a small chunk of the image at the very bottom, I tried using various W/H ratios and all had the issue.

![hank](https://user-images.githubusercontent.com/75427583/103285104-7dacaa80-49dd-11eb-9297-5381aec79ff2.png)

**Comment by trev-dev** [comment]
I can think of a few ways to address this issue. Just out of curiosity where is this image occurring:
![Screenshot_20210128_113444](https://user-images.githubusercontent.com/28788713/106189316-fc237600-615c-11eb-8b87-3b5acc92e885.png)

I feel like we can set the aspect ratio to the expected 3:4 GCS size and use a background-image and set the image to `cover center` for anything that might be bigger than expected. It would only end up cropping things that are not 3:4.

**Comment by GuineaThePig** [comment]
> I can think of a few ways to address this issue. Just out of curiosity where is this image occurring:
> ![Screenshot_20210128_113444](https://user-images.githubusercontent.com/28788713/106189316-fc237600-615c-11eb-8b87-3b5acc92e885.png)

That image is from the Actor Directory sidebar

**Comment by trev-dev** [comment]
Got it. That is quite the mighty crop! I guess I didn't notice it due to my guys still being there from the chin-up with no border around the image. I'll see what I can do.

**Comment by crnormand** [comment]
You all will have to tell me if this is resolved.   When I use my hex token images as portraits, they still come out a little stretched.

![image](https://user-images.githubusercontent.com/8931036/106354331-107f8400-62bf-11eb-807a-dfae08a10567.png)

Which I don't mind... but may be an indicator of something else.

**Comment by GuineaThePig** [comment]
Using all the updated stuff:

Hex portraits work
![Screenshot 2021-01-30 123710](https://user-images.githubusercontent.com/75427583/106355416-0168f800-62f8-11eb-8a25-90965d06597d.png)

Hex sidebar is still slightly cropped
![Screenshot 2021-01-30 123724](https://user-images.githubusercontent.com/75427583/106355427-0c238d00-62f8-11eb-9eed-c3a980f8d8a7.png)

4x3 portrait seems slightly stretched and is cropped
![Screenshot 2021-01-30 124053](https://user-images.githubusercontent.com/75427583/106355474-73414180-62f8-11eb-889f-4f07faa49db7.png)

4x3 sidebar still cropped
![Screenshot 2021-01-30 124103](https://user-images.githubusercontent.com/75427583/106355479-7b997c80-62f8-11eb-9a6f-fe65be140abe.png)

**Comment by crnormand** [comment]
Yeah, sorry, it would have helped if I had actually pulled in the code.   Brain damage from insomnia.  This is how it looks now.
![image](https://user-images.githubusercontent.com/8931036/106355680-a15a5d80-62c7-11eb-9a90-83d6a7360159.png)

**Comment by trev-dev** [comment]
Should've seen how long it took me to even get the templates to update on my end. Most of my time working on this issue was realizing that the name property in the `system.json` file was derived for a whole bunch of things that were ambiguously broken because I wanted to call my dev environment `gurps-dev` and separate it from my game world/system. Had to copy my game world system into a `gurps-bak` folder instead.

**Comment by trev-dev** [comment]
Also bog seems terrifying.

**Comment by trev-dev** [comment]
@crnormand I was really specific with my CSS selectors so that my rules wouldn't cause unintended side effects. As such, I'm realizing the directory-list images that are in a _subfolder_ aren't receiving the style updates. Will fix this.

**Comment by trev-dev** [comment]
@GuineaThePig Would you be able to close this issue? Please let us know if there's more we can do.

**Comment by GuineaThePig** [comment]
Awesome! I didn't realize it had been fixed, everything seems to be working perfectly now!
