### ISSUE TITLE
VTT Notes not showing in first import

### ISSUE THREAD

**Issue by Nedorus** [crnormand/gurps#1476]
### Environment:
Foundry v9 build 269 running on The Forge
![VTT Note Foundry Version](https://user-images.githubusercontent.com/25143888/180399435-f05ec42c-406a-4f5c-ab04-20fa3139a6fa.png)
All modules have been deactivated for this test.
![VTT Note No active Modules](https://user-images.githubusercontent.com/25143888/180401522-e318c4ca-fd6d-4718-bacd-95d948aa9066.png)

Browser is Chrome (latest version)

GCS is most recent version:
![VTT Note GCS Version](https://user-images.githubusercontent.com/25143888/180399599-5a8d1868-0e01-478f-b3a7-076a688f8062.png)

### Issue description:
After creating a GCS character with a VTT Note in a piece of equipment and importing this into a new actor the VTT note will not show. After re-importing the same (unchanged) file the VTT appears.
This is independent of the "use non-locally hosted import dialog" setting. It occurs with both option.
![VTT Note Missing (first import)](https://user-images.githubusercontent.com/25143888/180401362-033ae031-416b-42cc-9f59-bf3f41d185af.png)
![VTT Note Visible (second import)](https://user-images.githubusercontent.com/25143888/180401402-d6a9da2c-2f50-4bb1-9b90-9c524b527512.png)

### How to re-create issue:
This issue is re-creatable using this GCS character:
[Test Actor 4.zip](https://github.com/crnormand/gurps/files/9166221/Test.Actor.4.zip)

**Comment by crnormand** [comment]
Got it, thanks.   Fixed in the next release.
