### ISSUE TITLE
Issue importing character with no advantages

### ISSUE THREAD

**Issue by Gloogirl** [crnormand/gurps#1486]
Uploading a character with no advantages (removed the natural attack advantage) and skills. It will add things like the name and description but does not add skills. Seems likely that it throws an error when its trying to go through advantages and stops the import process.

![image](https://user-images.githubusercontent.com/108194881/181166608-372cde4a-1a78-471d-998f-1643b6defaeb.png)
![image](https://user-images.githubusercontent.com/108194881/181166050-4619be20-aa89-48c6-9746-e3294c1b0a0a.png)
[Imported.zip](https://github.com/crnormand/gurps/files/9195207/Imported.zip)

**Comment by crnormand** [comment]
Thanks, the stack trace pin pointed the error.   It will be fixed in the next release
