### ISSUE TITLE
Ranged Weapon Extreme Damage Calculation Bug

### ISSUE THREAD

**Issue by Legendsmith** [crnormand/gurps#149]
As you can see, rolling 3d(2) damage here gives an impossible result. This was the laser pistol found in UT, imported on a sheet via GCS as usual. I'm not sure what causes this, but it's a very serious bug. The image below shows rolling 3d+8 damage from a melee weapon, that rolls as normal. Then the 3d(2) from the laser pistol ends up totally incomprehensibly high.
![image](https://user-images.githubusercontent.com/1914417/103414787-7e0e9680-4bd3-11eb-832b-d655032506d1.png)

![image](https://user-images.githubusercontent.com/1914417/103414967-3ccab680-4bd4-11eb-9629-230ee703224e.png)

Replication:
1. Create a character sheet in GCS
2. Give it a Laser Pistol from the Ultra Tech Equipment library.
3. Import into Foundry
4. Roll the Laser Pistol's damage by clicking on the damage listing in the sheet.
5. Discover somehow you've obtained the MIB Noisy Cricket and that it is doing an order of magnitude more damage than a regular laser pistol.

**Comment by mjeffw** [comment]
Do you mind sending me the xml file you imported for this character? I was not able to reproduce this. It could be a bug in the version you are using which I've since fixed. (What version of the GURPS foundry system are you using?)

**Comment by Legendsmith** [comment]
Whoops, it was on an old version.
