### ISSUE TITLE
[Feature Request] /show for PCs only

### ISSUE THREAD

**Issue by sdJasper** [crnormand/gurps#1493]
I'd like to be able to use a command like /show that was limited to player characters. When on a map that has many times the enemies as players, it makes finding player values hard.

**Comment by crnormand** [comment]
Done.   
![image](https://user-images.githubusercontent.com/8931036/187937226-13ee41c8-467a-4dc7-9a2c-a278a33ed408.png)
You can now add -pc or -npc to limit the scope.   And -a to sort the output alphabetically, instead of numerically.
