### ISSUE TITLE
Persist information

### ISSUE THREAD

**Issue by Boifuba** [crnormand/gurps#1496]
In Apply Damage Dialog must have a option to persist some information  like unliving, homogenous or difuse. If you are fighting against zombie, you need to check this field in every roll damage check.

It could be better if the character sheel had unliving, homogenous and diffuse properties. So we could create a shield sheet so we don't have to configure its RD all the time in the tracker

**Comment by Volksters** [comment]
It was one of the few things I suggested to Nick and Nose very early on in GGA. And it was implemented a while back, I was able to attack the zombie who is unliving and I don't need to check it. 

Perhaps your sheet is in Portuguese and GGA can't match the words?

**Comment by crnormand** [comment]
Really? I didn't know we did that. When I get from Jen, I'll have to check and make certain it is internationalized

**Comment by Boifuba** [comment]
was right in english works fine!
