### ISSUE TITLE
Rolls off of character sheet do not show individual dice

### ISSUE THREAD

**Issue by Stormycorgins** [crnormand/gurps#1500]
On July 21st 2022 rolls performed by using character sheet links [such as clicking on a skill's level] would show the individual dice rolled, on August 4th 2022 I updated to the newest system and now when rolling off the character sheet it no longer displays the individual dice. Attached below are captures of a July 21st 2022 roll and an August 4th 2022 roll.

![A-Precise Dice July 22 2022](https://user-images.githubusercontent.com/110708477/183232854-eb7f8b9a-9aac-4fc4-a02a-0c37c1f91471.png)
![A-Precise Dice Missing August 4 2022](https://user-images.githubusercontent.com/110708477/183232856-fd4587f3-6cd8-4e37-b5e1-052619920275.png)

**Comment by crnormand** [comment]
Thank you!    Yup, I figure out where I made the mistake.   It will be fixed in the next release.
