### ISSUE TITLE
min value for rolls

### ISSUE THREAD

**Issue by Boifuba** [crnormand/gurps#1502]
When you doing a first aid check sometimes the value returns negative (like 1d-4), remember in first aid success chek you always heals at least 1 so could be nice have something like 
```/hp +1d6-4 min1```

**Comment by Gloogirl** [comment]
There is a way. If you use +1d6-4! it will roll with a minimum of 1.

**Comment by mjeffw** [comment]
@Gloogirl is correct, a die roll expression with a trailing '!' means the roll value has a minimum of 1.
