### ISSUE TITLE
When Importing GCS Character Sheets into The Forge, Disadvantages (and other things) fail to show up.

### ISSUE THREAD

**Issue by Navaronegun** [crnormand/gurps#1503]
So convoluted to describe.  It essentially, after a lot of troubleshooting Here (https://discord.com/channels/228546929494065152/788878698349723669/1005920642991923290) seems that using containers screws up the import from GCS to the VTT on the Forge (but not on a self host).  The imported GCS sheet in the Forge will not count Disadvantages as such (though they will show up on the sheet normally) as "Disadvantages" in the Point Total in the upper right hand corner.  This seems to be only if you use "Containers" (like in created templates, etc.).

**Comment by crnormand** [comment]
The ad/dis add counting logic has been updated in the 0.15.x releases, so it may be correct again.   But in any case, we won't be doing any more work on this since it it handled completely differently in v1.0.0
