### ISSUE TITLE
[bug] Ref to page numbers containing a range of pages fail.

### ISSUE THREAD

**Issue by engurrand** [crnormand/gurps#1505]
If the Ref field is filled with an entry for multiple pages, as is common in the Psychic Powers files for GCA4, then the link doesn't find the pdf.
For example, the ESP Awareness power has a ref value of PP39-40. Clicking it opens the Warehouse23 Store instead of the Psionic Powers Book to page 39. It's easily fixed on a per item bases by deleting the dash and second page number, but I thought you might like to know.

**Comment by crnormand** [comment]
Fixed... it will now go to the first page in the list.
