### ISSUE TITLE
rolltable not found

### ISSUE THREAD

**Issue by devakm** [crnormand/gurps#1507]
Using 

/rolltable CritHit

alone works fine since I have that table, but if I put this in an OtF I get an error message saying table not found.

Here's how I am using it:
[/if [A:Vic\*Narwhal\*Thrust] crit:{/rolltable CritHit} {/r [+2 damage bonus \*Cost 1FP] \\\\/r [D:Vic\*Narwhal\*Thrust]}]

**Comment by crnormand** [comment]
Fixed

**Comment by devakm** [comment]
Thank you!
