### ISSUE TITLE
Control Roll With Name as OTF

### ISSUE THREAD

**Issue by kbrownridge** [crnormand/gurps#1509]
When importing from GCS, disadvantages with a Control Roll (CR) do show up as a clickable OTF but the name of the disadvantage is not part of it. This means when the button is clicked you get a control roll result but no idea for what.
Our group has been manually updating the OTF in Foundry to correct this but it has to be repeated on every import, or a duplicate entry in VTT Notes added which leads to confusion.

**Comment by crnormand** [comment]
![image](https://user-images.githubusercontent.com/8931036/185483043-31869c10-c6cd-4909-93a8-55584f5d8bab.png)
If we detect a control roll, we append the name of the advantage to the control roll.
Will that work?

**Comment by kbrownridge** [comment]
Absolutely. That's all we're doing manually now. Automated is better!
