### ISSUE TITLE
Unable to open any character sheet in a specific scene

### ISSUE THREAD

**Issue by mdonovan5** [crnormand/gurps#1526]
<img width="853" alt="Screen Shot 2022-08-28 at 18 14 52" src="https://user-images.githubusercontent.com/346141/187097895-3c6343c8-0bec-404f-a745-d086132a6ba2.png">

It seemed that on that scene I had a few characters in combat mode without the combat started. In all other scenes, the sheets opened correctly. When I removed everyone in combat, it worked, even if I added a few later. This problem occurred to one of my players during my game too, but at that time it wasn't happening to me.

**Comment by crnormand** [comment]
It seems that the token is "bad"... it doesn't have an actor.   But I will change our code so that it doesn't throw an exception when this happens, so it should just be skipped over.
