### ISSUE TITLE
Allow Disabling Actor Name Changes on Inport

### ISSUE THREAD

**Issue by Hubok** [crnormand/gurps#155]
Simple request, I'd love a per-world module setting that prevents the name of an actor being changed when using the GCS/GCA importer.

Players frequently list their character names differently in GCS and then they need to be fixed repeatedly on import. I also use special characters in names to force Foundry to not split names on space in the player list, so this feature would be a nice QoL improvement.

**Comment by crnormand** [comment]
Done.   It will be in the next release.
