### ISSUE TITLE
Non-ascii characters don't survive import from .gcs file

### ISSUE THREAD

**Issue by woefulhc** [crnormand/gurps#1566]
![image](https://user-images.githubusercontent.com/77212217/189571557-404fd9c9-9592-4394-8cca-0eb7eb438dce.png)
Is what is displayed when importing the gcs sheet (which I'll attach) that looks like this in gcs
![image](https://user-images.githubusercontent.com/77212217/189571662-d69cdd89-75e3-4893-9243-5e7a6495c60c.png)
[Ricardo Gomez.zip](https://github.com/crnormand/gurps/files/9544481/Ricardo.Gomez.zip)
I filed a similar issue long ago for exports from GCA, but that was addressed. I'm not sure if this is a regression or because I'm importing a raw gcs file.

**Comment by crnormand** [comment]
What environment are you running?   I am running Foundry on Windows, running in Chrome, and it seems to display correctly:

![image](https://user-images.githubusercontent.com/8931036/189723628-6b715974-f604-47ac-8573-a55d79930aed.png)

**Comment by woefulhc** [comment]
I am hosting on a Linux machine. I am using Chrome to view the site. However, I do see the unexpected characters in Firefox 
Specifics from uname -a are:
`Linux <vm_name> 5.13.0-1027-oracle #32~20.04.1-Ubuntu SMP Fri Apr 15 06:01:57 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`

I also see this in the relevant actors.db file
     `,"name":"Ricardo GÃ³mez"`
Since it works on Windows,, I still suspect there is a PEBKAC involved. 

I'd say backlog this until you get the update for v10 of foundry out. I'll do a little digging and see if there is a system or application setting I can change to get it to work.

**Comment by Boifuba** [comment]
Just to add some info here.  Maybe it could help.
I'm generating the  GCS  on Windows 10 
Portuguese language
my leyboard is USA International


Using the same file in Windows 10 or Ubuntu 20.04 both are working fine.

**Comment by woefulhc** [comment]
Solved this by changing the import encoding drop-down under system settings from ISO-8859-1 to UTF-8.

**Comment by woefulhc** [comment]
Solved this by changing the import encoding drop-down under system settings from ISO-8859-1 to UTF-8.

**Comment by crnormand** [comment]
Ahhh... right.   A while ago we changed the default to UTF-8.   But you would only see it if you created a new world.  Sorry for the confusion.

Glad you figured it out!
