### ISSUE TITLE
tabbed sheet spells link

### ISSUE THREAD

**Issue by devakm** [crnormand/gurps#1575]
The Full Sheet (not tabbed sheet) should include a nav link for spells.

**Comment by crnormand** [comment]
It does.    Your character has to have spells for the TAB to appear.

![image](https://user-images.githubusercontent.com/8931036/189792195-6db42be5-b3c9-4b16-ae0c-8710e3809ade.png)

**Comment by devakm** [comment]
I stand corrected. It's the Full View that oddly lacks a nav link to Spells.

**Comment by crnormand** [comment]
And that has been fixed in the V10 port!     Sorry, it will be another day or so before we can release.
