### ISSUE TITLE
Support for GCS rules page links

### ISSUE THREAD

**Issue by Delubear** [crnormand/gurps#158]
So one feature I love is that you carry over the page/reference links from GCS for things like skills and advantages for use with PDFoundry.
![image](https://user-images.githubusercontent.com/9277335/103681917-bacceb80-4f4d-11eb-84f5-50e2de59e4e8.png)

Would there be a way to support this for the rules you can add to a GCS character? Inside of GCS they show up under notes with the reference link at the end.
![image](https://user-images.githubusercontent.com/9277335/103681685-6aee2480-4f4d-11eb-8d64-851a755502d9.png)

But inside of Foundry, it drops the reference column and then makes it useless.

Mainly, this would be nice so my players can add rules related to their characters or just ones they may need to reference often to their character sheets for a quick open reference when bundled with PDFoundry.

Or if there is a better way to accomplish the above, please let me know.  This is an absolutely fantastic project.  Thank you.

**Comment by crnormand** [comment]
Agreed, that should be there (and it was, at some point).   I can't remember why I got rid of it :-(

As for other ways to make links... you can always embed an On-the-Fly reference in the name or notes of the "thing" (Skill, Advantage, Equipment, Attack, etc.).

Just add something like `[PDF:DFE40]` and it will create a PDFoundry link.   You can see it in this equipment entry:
![image](https://user-images.githubusercontent.com/8931036/103684672-f1a8fe80-4f59-11eb-92f9-bc57ae21d662.png)

The armor comes from the basic set, but I wanted to include the reference to the Slam rules that we use.

**Comment by Delubear** [comment]
Thanks, that's good to know so I can manually add a few.

If you have plans to add it back to the Notes block later, that would be great and time-saving.

**Comment by crnormand** [comment]
Ah, now I know why I removed them... GCS doesn't have an export key for the page ref of a note.   It would require a code change to GCS to make that happen.   I COULD add the page ref column back into the character sheet and you could bring it up in the Editor and enter a PDFoundry book reference (e.g. B101), BUT this value will get lost upon re-import.    So for now, it seems safer to just use the On-the-Fly formulas in the note itself.   

I will leave this issue open, just in case the page ref key is added to the GCS output templates.

**Comment by mjeffw** [comment]
Create an issue on GCS. Rich agreed to add hit locations table name for me when I asked.

**Comment by Delubear** [comment]
Just wanted to follow up that the GCS request appears to be added in one of the latest commits.  Not sure on the turnaround time to get that into a GCS release.

**Comment by crnormand** [comment]
Oh, dang... I guess I had better get on that...

Oh wait...

I already am!
![image](https://user-images.githubusercontent.com/8931036/105642603-b747c880-5e58-11eb-9df9-d302ccef030e.png)

And a free "Note Editor" also (along with a bunch of other new treats).    

Unfortunately, it will take a few days for me to update the GCS export... he added some of our other feature requests, and I want to combine them all into one update.

**Comment by crnormand** [comment]
And he actually released the code... it is in v4.27... so I had better get crackin!

**Comment by mjeffw** [comment]
Gee, that story sounds amazing!

**Comment by crnormand** [comment]
And you wouldn't believe how it ends!  OMG, what an adventure.

**Comment by crnormand** [comment]
It has been integrated and will be in the next release.

**Comment by Delubear** [comment]
Installed the latest GCS and this for foundry.  See the slot for the page reference now, but it's still coming through blank.  Anything I'm missing?

![image](https://user-images.githubusercontent.com/9277335/106407294-53497500-6401-11eb-8370-6d871a02a85d.png)

![image](https://user-images.githubusercontent.com/9277335/106407384-82f87d00-6401-11eb-98f0-6661146e9a53.png)

**Comment by crnormand** [comment]
Well fudge... you are correct.   Dang, I see it in the exported file...

**Comment by crnormand** [comment]
Well crap.... you leave one little line of code out... ok, I promise, this time it will work.
![image](https://user-images.githubusercontent.com/8931036/106409791-5b101600-640f-11eb-9716-4536e84e9454.png)
