### ISSUE TITLE
Rule shows NaN yards in Foundry v10.285

### ISSUE THREAD

**Issue by SrAndros** [crnormand/gurps#1586]
![Gurps Aid NaN Ruler](https://user-images.githubusercontent.com/11762868/190495501-153f7806-1210-4287-b86f-903e3d93c438.png)

I've checked this problem while I was creating this request and I've come to the conclusion that the parameter "segmentDistance" was not a number, but had a variable "distance" which is the value we are looking for, so I modified the dist use to assign value to "label" at its instantiation to use "segmentDistance.distance" instead of "segmentDistance". This solves the problem and now it properly  displays the numbers of yards.

![Gurps Aid NaN Ruler Solved](https://user-images.githubusercontent.com/11762868/190504937-556f1687-c251-48f6-abd9-e635c81d3a42.png)

Should I create a pull request to push it or will you change it on your end? It's just one line.

**Comment by crnormand** [comment]
Actually a pull request would be better. Then we have a reminder.  Thank you!
