### ISSUE TITLE
Can't open damage rolls.

### ISSUE THREAD

**Issue by Pronana** [crnormand/gurps#1587]
When rolling damage, you can no longer open the drop down to see what the dice rolls are. Doing so will either do nothing, or may crash foundry. Tested on a new world and issue still persisted.
![image](https://user-images.githubusercontent.com/66055347/190527453-25ad7787-1a14-4429-ae04-72478f0b642b.png)

**Comment by crnormand** [comment]
I am assuming Foundry V10?
Yeah, when I click to expand the damage, my chat goes from this:
![image](https://user-images.githubusercontent.com/8931036/190639494-3e6042ee-6de9-4ade-ac94-75cdfb8b345c.png)

to this:
![image](https://user-images.githubusercontent.com/8931036/190639654-98ba70d5-334c-4cd9-95f4-6d5aebe199a3.png)

You will notice the chat log (and the players list and hotbar and modifierbucket...) have all moved up.    At least the dice did display (you have to scroll the chat log to see them).

Now if I can just play on 1/2 the screen.  :-(

I've been searching for a bit, and I can't find the code that is expanding the dice area... I assume we have clobbered some of Foundry's newly changed CSS.

**Comment by crnormand** [comment]
I've put something in for the next release... but I honestly can't tell if it is fixing it.   But I can't seem to recreate it with the fix in, so I am going to assume.   Please test with the new version when you get a chance.

NOTE:   A work around "seems" to be deleting the chat log and restarting (F5).

**Comment by rinickolous** [comment]
Closed as fixed
