### ISSUE TITLE
(v10) Measure distance tool doesn't work (NaN)

### ISSUE THREAD

**Issue by jmcconn18** [crnormand/gurps#1592]
**Gurps 4e Game Aid Version**: 0.15.2
**Foundry Version**: 10.285

**Issue**:
The measure distance tool shows NaN instead of the measured distance. The range penalty is correctly displayed.

**Expected Behavior**:
The measure distance tool should display the measured distance.

**To reproduce the issue**:
Use the measure distance tool anywhere on a scene with a hex grid.

To narrow down the culprit I deactivated all add-on modules and this issue persisted with no modules activated.

No errors in the console.

![NaN_measure](https://user-images.githubusercontent.com/50793696/190874543-fc43243f-6c08-41d0-8480-fded3be4ff0d.png)

**Comment by crnormand** [comment]
Thanks!   We have a fix for this already.

**Comment by jmcconn18** [comment]
> Thanks! We have a fix for this already.

Thank you friend.
