### ISSUE TITLE
Encumbrance, Move & Dodge Tab Bug

### ISSUE THREAD

**Issue by Hamrick12** [crnormand/gurps#1601]
The Heavy (3) line always displays 1 Move for a character with 5 Basic Move, even when the original GCS sheet had the correct number (2) displayed. Editing it manually doesn't work either. 
![movement](https://user-images.githubusercontent.com/53463464/190994576-43eef47e-8802-447e-aa8f-0495dc5c8377.PNG)
[Geraldine Geissel.zip](https://github.com/crnormand/gurps/files/9607132/Geraldine.Geissel.zip)

**Comment by crnormand** [comment]
Can you zip up your character and attach it to this issue?   I have not been able to recreate it.

**Comment by Hamrick12** [comment]
The default GCS character I attached causes this issue, even on a new world with no modules. This happens to me with every character.

**Comment by crnormand** [comment]
Found it.   Javascript was calculating 0.2 * 3 = 0.399999999999999.     Fixed in next release.
