### ISSUE TITLE
Refinement: Handlebar Helpers - Be Careful

### ISSUE THREAD

**Issue by typhonrt** [crnormand/gurps#1603]
Greets... I debugged a reported issue for Forien's Quest Log that w/ the Gurps system showing quest objectives didn't work. 

https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/issues/25

This is due to the override of `or` / providing a custom handlebar helper for `or` that differs from Foundry core:

https://github.com/crnormand/gurps/blob/main/lib/moustachewax.js#L115-L130

```
  Handlebars.registerHelper('or', function () {
    for (let arg in arguments) {
      if (arguments[arg] == true) {
        return true
      }
    }
    return false
  })
```

There also is a problem with `and` quite likely. 

This is definitely not what the default Foundry core helpers do and they are defined as such:

```
  and() {return Array.prototype.every.call(arguments, Boolean);},
  or() {return Array.prototype.slice.call(arguments, 0, -1).some(Boolean);}
```

The Gurps override caused logic in FQL Handlebars template usage of `or` to always be false. Consider that any numerical value that is above `0` is essentially "true" when cast to a Boolean. 

A general suggestion is to not override the default Foundry core Handlebar helpers and to namespace any additional helpers that the system adds with `gurps_<helper name>` so that there are no clashes with Foundry core.

-----

I likely can work around this issue w/ FQL, but something to keep in mind.

**Comment by mjeffw** [comment]
Thanks. We'll take a look at removing these helpers. Truthfully, we didn't know the existence of the Foundry handlebar helpers when that code was written.

**Comment by crnormand** [comment]
Done, I've removed the duplicates.
