### ISSUE TITLE
Trade/Give Item Bug

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#1614]
My players are having issue with trading with each other. Upon giving the item, the usual dialog windows appear but once the player press Accept, an error pops up and no items were transferred. 

![Itembug1](https://user-images.githubusercontent.com/78762498/192506925-171306bb-50f5-4704-96aa-0165bf58a312.jpg)

The screenshot above shows the error.

On top of the screen, this error appears: `TypeError: Cannot read properties of undefined (reading 'globalid')`

**Comment by crnormand** [comment]
Got it.   fixed in the next release
