### ISSUE TITLE
Token Action HUD - OtF display issues

### ISSUE THREAD

**Issue by The-Fleeb** [crnormand/gurps#1625]
OtF formulas on character sheets show up and work fine, but in the Token Action HUD they show up as a long string of 'code'.
Example Image:
![image](https://user-images.githubusercontent.com/114795745/193394426-1989a76b-25bb-4b80-9a24-977d9568e0b0.png)

**Comment by crnormand** [comment]
Yes, this is an issue with TAH.   I've already provided a fix.  It will appear in the next release of TAH.
