### ISSUE TITLE
Weird integration with Token Action HUD

### ISSUE THREAD

**Issue by TheFabulousIronChef** [crnormand/gurps#1626]
Neither skills nor spells show; disadvantages list the disadvantage name but then a string of random numbers after it. Interestingly, you can click that weird string and it will roll the control roll ... it's just the TAH display that is off. 
![image](https://user-images.githubusercontent.com/46587602/193455641-cc0dfc12-aa9e-4d7b-838a-811c52182e7d.png)

**Comment by crnormand** [comment]
Yes, that is exactly the problem. It will be fixed in TAH 3.10.0

**Comment by TheFabulousIronChef** [comment]
Awesome!
