### ISSUE TITLE
[Bug] No damage roll from Foundry Item out of chat window

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1639]
I use a Foundry item (weapon), placed on a character.
![Axe item](https://user-images.githubusercontent.com/80178910/196870209-33e2ae6f-3d09-4442-bce2-c0740834fde1.JPG)
I roll a successful attack. Then try to roll the damage from the chat window.
![Attack](https://user-images.githubusercontent.com/80178910/196870258-db40a634-4440-4726-9d22-7411431ae81b.JPG)
I get this error and no damage is being rolled.
![not found](https://user-images.githubusercontent.com/80178910/196870298-317c7141-848a-419c-897b-212a82d3cdd4.JPG)

[Foundry stand alone V10 288; GGA 0.15.7]

**Comment by LordOHelmet** [comment]
Error code:
`foundry.js:58721 No melee or ranged attack named 'Axe (Swung)' found on StandardSpieler`

**Comment by crnormand** [comment]
Unfortunately, I cannot re-create this.   When I create an Axe item, and this give it to some actors, both are able to roll damage after a hit.
![image](https://user-images.githubusercontent.com/8931036/199527124-b121e983-7aa5-47df-a11a-bc94128a4b86.png)

I know we have had problems in the past with matching attack names, but I thought things were pretty good.   I don't know where to go next.

**Comment by LordOHelmet** [comment]
Strange, I can't replicate it again!
I guess it was due to using Firefox on my players side - have to watch out for that in the future.
