### ISSUE TITLE
[Bug] Players cannot set Maneuver via chat command

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1640]
When the GM tries to set a maneuver for a selected token with the chat command 
`/man ready`
it works just fine.
But when a player tries to do the same, an error pops up 
`Unable to find a maneuver named 'ready'`

[Foundry stand alone V10 288; GGA 0.15.7]

**Comment by crnormand** [comment]
Again, I cannot duplicate this issue.   Running stand alone Foundry V10, a player in Chrome is able to set the maneuvers.   I tried:

```
/man conc
/man ready
```
And they work (while in combat, of course).

But we are matching against the i18n names.    What do you see when you just type `/man` ?

![image](https://user-images.githubusercontent.com/8931036/199531752-9416153f-d972-4f9c-a171-83a1b73018d9.png)

**Comment by LordOHelmet** [comment]
Strange, I can't replicate it again!
I guess it was due to using Firefox on my players side - have to watch out for that in the future.
