### ISSUE TITLE
[Bug] Drag and drop items between non-GM characters broken

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1641]
Drag and drop of Foundry items between non-GM characters does not work.
The item does not appear on the character even though some strange numbers of weight and value are added to the carried equipment section.

[Foundry stand alone V10 288; GGA 0.15.7]

**Comment by crnormand** [comment]
What kind of Item?   I don't know if that would matter, but it doesn't hurt to have that information. Was it a weapon, or some thing that added bonuses?

**Comment by LordOHelmet** [comment]
First I noticed it with an item that doesn't give bonuses, but just has something in the notes section.

But it really doesn't make a difference, it happens with all Foundry items.

I have now looked at it a bit more closely and noticed that after dragging, the number of the last item already on the character increases.

Before the drag:
![before drag](https://user-images.githubusercontent.com/80178910/197454169-9404b91b-a15a-4d92-82c5-0f9fd9ea6bf2.JPG)


After the drag:
![after drag](https://user-images.githubusercontent.com/80178910/197454184-91138afc-21b1-416e-a2af-d83aee5970bf.JPG)

That happened after dragging a 'Minor Healing Potion'.

**Comment by crnormand** [comment]
I think I fixed it with the latest patch.   There was some f**ked up code, again, because of the data->system name change that I have sorted out.   

However, I will leave this issue open, just in case.   If you get a chance to confirm (after the 0.15.9 release), please let me know.

**Comment by LordOHelmet** [comment]
After 0.15.9

The item(s) is correctly taken from the giving character.

But on the receiving character the item count is just added to whatever item is the last in the euqipment list.

**Comment by crnormand** [comment]
I "think" I fixed it (again)  ;-)
