### ISSUE TITLE
Mod Bucket doesn't update for multiple selections

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1644]
Odd one, other players and GMs trying it and it works, but for me as a GM or player in multiple games, when I click items in the Mod Bucket the first one works and shows up, all others do nothing.  I have to close the mod bucket and reopen and then again, the first works and no others do.

What I can look for to help narrow this one down?

**Comment by Farmeroz** [comment]
OK - interestingly, this is happening for me on Edge (either through the normal browser or through The Forge applet (which is really just Edge anyway).  Others are not having this issue on Edge.  If I run in Chrome, it's working correctly.

OK - checking the Console in Dev mode:

![image](https://user-images.githubusercontent.com/89975749/198851470-ca7fb1e5-4996-4d6d-aaee-3344c90c2c58.png)

So I assume that's at least part of the issue?

I tried clearing the cache (ctrl-F5) and hard clearing the cache via settings (all images and files), followed by a ctrl-F5 of the window.

Everything is OK on load (no error), but once I click the mod bucket and then click an item:

![image](https://user-images.githubusercontent.com/89975749/198851597-bb24eb44-2fe9-4bb7-a051-8b208384da00.png)

So same again.

Any ideas?

**Comment by Farmeroz** [comment]
OK - this WAS working on Chrome for me, but it's stopped.  Console shows this when clicking the trash on the Mod Bucket icon:

![image](https://user-images.githubusercontent.com/89975749/198858934-1ce3f98d-a0c4-4348-afa4-ef3e1ce661a4.png)

Opening the Mod Bucket and clicking on one mod:

![image](https://user-images.githubusercontent.com/89975749/198858950-584b90c2-b9eb-438b-8faf-095799e94711.png)

Clicking on any other mods does nothing (and no further errors generated).

I don't know why it was working and then stopped.

**Comment by mjeffw** [comment]
Is this only on The Forge? Are you also using the Nordlond Bestiary?

**Comment by Farmeroz** [comment]
> Is this only on The Forge? Are you also using the Nordlond Bestiary?

The Forge and Nordlond, yes.

**Comment by mjeffw** [comment]
See if you can recreate the problem without the bestiary?

**Comment by Farmeroz** [comment]
> See if you can recreate the problem without the bestiary?

Without the Bestiary, same issue.  First click works, others don't.  Same error messages.  Reloaded game to make sure, same issue.  Reloaded Bestiary, same issue.

**Comment by Farmeroz** [comment]
Is there any other info I can grab that might help with this one, guys?

**Comment by mjeffw** [comment]
I'm sorry I haven't responded but I'm stumped as well. Can you verify the problem still exists without any modules? Is it possible to test it locally on your PC instead of on Forge?

**Comment by Farmeroz** [comment]
So, I created a new GGA world on The Forge, with nothing loaded but GGA (I think "The Forge" module loads, but you can't change that).  Everything at default - changed nothing at all.  Open Mod Bucket and all good.  Reloaded the app a couple of times, still all good.

Changed the config for GGA to switch Mod Bucket from Mouseover to Click (i.e. Mouseover off).  Problem exists.  Reload game world.  Problem still exists.  Change back to Mouseover On for Mod Bucket and reload, and problem gone.

Something seems to be affecting it only when the Mod Bucket is not set to come up on Mouseover.

**Comment by mjeffw** [comment]
Okay now we're talking. I will take a look today to see if it happens to me too. If so there's a good chance we can solve this.

**Comment by mjeffw** [comment]
I got a fix, it will go out with the next 0.15.x release.

**Comment by Farmeroz** [comment]
Awesome - thanks, @mjeffw :-)

**Comment by Farmeroz** [comment]
@mjeffw FYI this is still a bug as of 0.15.8
