### ISSUE TITLE
Custom Modifier Tooltip Enhancements

### ISSUE THREAD

**Issue by Legendsmith** [crnormand/gurps#165]
Like so:
![image](https://user-images.githubusercontent.com/1914417/103873266-a93d3c80-5123-11eb-9255-35f3d1801955.png)

**Comment by crnormand** [comment]
Do you expect to have a lot of different modifiers during your gameplay, or do you expect that you would use a few specific ones?

I ask because we plan to make the content of these windows a "system setting", meaning that the GM will be able to define what they want in each panel.   So if you want a recently used list so that you only have to type in X number of specific modifiers once, this future update would solve that issue.

If, however, you really do expect to use a variety of different modifiers, and want the FIFO list to save some typing, we could accommodate that as well.

**Comment by Legendsmith** [comment]
That's a good question. I think I'm against it being global; the modifiers I use in my apocalyptic cyberpunk game are quite different to my dungeon fantasy game.
I have an idea though using the existing systems within foundry: load modifiers from a journal entry! That way we can have per-campaign modifiers that area also easily modified; a GM can simply copy paste the text from one to another.
Here's a regex that will extract the modifier code, with a capture group to extract it from the square bracket syntax it's wrapped in.  It even allows more than one modifier to be written on a line. 
(I think square brackets are a good choice to fit in with the precedent established by the on the fly rolling.)
```regex
\[([+-][\w+ ]*)\]```

**Comment by crnormand** [comment]
The system setting would be "per world", so you could define different sets for each game.   It seems like that is what you are asking for... the ability to define a set of modifiers specific to your world.    A list of recent modifiers is just one way to do that.

Great minds think alike.... the data format for the Modifier Tooltip already uses the On-the-Fly formulas.   For example, the "Ranged" section is created by parsing this string:
const RangedMods = `[+1 Aim]
[+1 to hit (Determined Attack)]
${horiz("Actions")}
[WILL check to maintain Aim]`;

There is no HTML/CSS involved.

So the plan is to enhance this format a bit and allow the GM to edit it directly.    I am not certain if it will be per panel, or if we will encode the complete tooltip in a single parsed string (much harder to do, but more flexible for the user).

I will leave this issue open until we rewrite the Modifier tooltip.

**Comment by crnormand** [comment]
https://github.com/crnormand/gurps/issues/304#issue-807955516

**Comment by crnormand** [comment]
I discussed work-arounds for this in https://github.com/crnormand/gurps/issues/356 (with pictures).   Until we can get around to implementing this.

**Comment by crnormand** [comment]
@mjeffw had a good idea... change the Modifier Bucket sections to use Journal entries (kind of like the GM Screen module).   Then GMs can edit to their heart's content.

**Comment by crnormand** [comment]
Jeff has started this work with the "Bucket Journals".
