### ISSUE TITLE
[Bug] OTFs not recognized

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1651]
[Foundry stand alone V10 (288); GGA 0.15.8; no Mods)

Some OTFs are not recognized in the Journal (they are not converted into a button).
![OtF Commands](https://user-images.githubusercontent.com/80178910/200833200-6470ed5f-df65-4e1b-99b0-a63a0323f811.JPG)
The same OTFs work fine in the chat window or on a character sheet.

The OTFs also work fine when copied into a new, completely blank Journal.
But in some Journals they do not work. I guess it has something to do with formatting of that text/journal.
But I couldn't systematically figure out what causes it.

**Comment by LordOHelmet** [comment]
I guess I found the culprit.

When there is a syntax error with a square bracket in any OTF there is an issue with OTFs after that error.

```
[Block]

[Block]

[Block]]

[Block]

[Block]
```

e.g. in the block above the first three OTFs will be parsed correctly. But after the superfluous second closing bracket in line three, all OTFs after that point won't work correctly.

**Comment by crnormand** [comment]
Lol.  Yeah.   I never built a full fledged compiler into the parsing 🤓

Glad you figured it out.

**Comment by crnormand** [comment]
Another issue can occur if you accidentally get HTML formatting "hidden" inside of the OTF... which will screw up the parser.
