### ISSUE TITLE
Conditional Injury Mode needs a max HP tooltip on RT

### ISSUE THREAD

**Issue by Legendsmith** [crnormand/gurps#166]
Even when using CI, there are a few cases where knowing the exact HP of a character is important (such as when they are providing 'cover DR to another target; their HP = that DR). Putting this info in a tool-tip on RT means we can access it without taking up more page space.

**Comment by Exxar** [comment]
I think there's also space there to make it look like `[15] RT 5 / 14 HP`. Unfortunately my unfamiliarity with the CSS grid system being used prevents me from quickly trying it out so I can't do it right now.

Something else occurred to me. You can "buy" RT in two ways - by purchasing HP from which you then figure out your RT, but also by "packing" that into buying RT directly. The editor sheet supports both methods, but currently only the points edited in for RT bought directly are shown on the normal sheet. If we want to show HP directly here, we should also likely display the points invested into them, if that method was used by the player. So something like `[15] RT 5 / [0] 14 HP` or `[0] RT 5 / [15] 14 HP`. But that could likely be too much to fit in there.

**Comment by Exxar** [comment]
If I abuse the current grid layout it stretches it too wide:
![currentgrid](https://user-images.githubusercontent.com/330181/104036838-3344de00-51d4-11eb-82e7-7ac819b7e13a.png)

So yeah, will have to look at it properly later. @crnormand what do you think? Put HP into popup or try to fit it in here with a more compact grid layout?

**Comment by mjeffw** [comment]
@Exxar @Legendsmith I reworking the resource tracker layout right now, you may want to wait until I'm done with this refactor.

Here's WIP view of the new layout:
![image](https://user-images.githubusercontent.com/7349413/104056911-3aadbc80-51bf-11eb-836f-b437813bf178.png)

**Comment by Exxar** [comment]
👍

**Comment by mjeffw** [comment]
@Exxar @Legendsmith   How does this look?
![image](https://user-images.githubusercontent.com/7349413/104060034-4bacfc80-51c4-11eb-917e-7678ffde570a.png)

**Comment by mjeffw** [comment]
> Something else occurred to me. You can "buy" RT in two ways - by purchasing HP from which you then figure out your RT, but also by "packing" that into buying RT directly.

Does it make sense to ever spend points on both RT and HP? If not, we could conditionally show whichever cp value is greater than zero.

**Comment by Exxar** [comment]
> @Exxar @Legendsmith How does this look?

Great, except using brackets for both noting the points invested in RT and the amount of HP is not good. I'd prefer if brackets would only be used for point costs on the sheet.

But as you suggested, you will indeed only ever spend points on either RT or HP, never both at once. So the CP value could be shown conditionally, yes. Maybe something like `[15] 5 RT / 18 HP` if you spent points on RT, or `5 RT / [6] 18 HP` if you spent it on HP?

Truncating Instantly Fatal is of course fine.

**Comment by mjeffw** [comment]
This is what I ended up with:

![image](https://user-images.githubusercontent.com/7349413/104078753-b292db80-51ed-11eb-8221-348c4570b61e.png)

The cp total is the value for RT, if not zero; otherwise it is the value for HP. The condition field ("None" in this example) also hosts the tooltip that shows the thresholds.

In my testing I see that the HP character point field does not work as expected.

The editor is mostly unchanged:

![image](https://user-images.githubusercontent.com/7349413/104078836-11f0eb80-51ee-11eb-8974-8baa04925f22.png)

**Comment by mjeffw** [comment]
@Legendsmith , is this support good enough to close this Issue?

**Comment by Legendsmith** [comment]
Yes, this seems fine to me.
However, I don't think that it's actually possible to buy RT directly though, because it has no consistent cost per level. You *always* buy HP and convert it to RT. I also agree that truncating the "wound" off everything is fine, we already know it's a wound.
