### ISSUE TITLE
GCA 5 Update Breaking Change

### ISSUE THREAD

**Issue by jhymesba** [crnormand/gurps#1665]
GCA5 now includes a formatted notes field and an unformatted VTT Notes field. The former field inserts text that looks like this: 

{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Microsoft Sans Serif;}}<br>\viewkind4\uc1\pard\f0\fs17 Familiarity: EX-Gear\par<br>}

This was generated by typing "Familiarity: EX-Gear" into the Notes field in a skill in GCA5 5.0.202.0 and produced on GGA 0.15.11.

**Comment by ArminSykes** [comment]
I've made an update to correct for the RTF elements. I'll do a pull request soon, and if accepted I will update for GCA's package manager after that.
