### ISSUE TITLE
When importing a character, an error is generated. 

### ISSUE THREAD

**Issue by jhymesba** [crnormand/gurps#1666]
With this character, an error is generated. The error is 

An error occured while importing Gaia Medica, TypeError:t.trim is not a function in foundry.js:58721

[Gaia Medica (Rob).zip](https://github.com/crnormand/gurps/files/9994038/Gaia.Medica.Rob.zip)

**Comment by crnormand** [comment]
Hmmm... when I exported to XML and imported, I got a different error.   I assume there is some issue with XML like characters in a field where they have not been "escaped".   Usually a "notes" field.   It is contains things like "<" or ">", it will screw up the parser.   

We should be escaping that text before we export it.  I just don't know where that is.

**Comment by ArminSykes** [comment]
I originally thought that maybe this was a problem with an accidentally concatenated Trim command was appended to a string somewhere, but that doesn't appear to be the case, as there's no use of .Trim, only Trim(). 🤷 

I've gone and updated the escaping of the UserNotes in the exporter to escape the non-RTF version of those, instead. Maybe that'll fix this issue as a result.

**Comment by jhymesba** [comment]
This seems to work.
