### ISSUE TITLE
Everything except canvas disapearing on click on chat log

### ISSUE THREAD

**Issue by ssveter1** [crnormand/gurps#1680]
Without clearing chat log when damage drop-down or show-the-math is clicked everything except canvas disapears.

**Comment by crnormand** [comment]
Yeah.  And we have no idea why.  The only solution we have, at the moment, is to clear the chat log and refresh.

**Comment by Farmeroz** [comment]
Interestingly, when I have chat using PopOut! there's no issue.  When I leave the chat as a normal FVTT UI window, clicking on damage drop down does nothing (won't expand or collapse).  Either way, no issue with anything disappearing.

Tested on Brave, Chrome, and Edge - same results on all.
