### ISSUE TITLE
Exporter does not export ranged innate attacks from GCA

### ISSUE THREAD

**Issue by woefulhc** [crnormand/gurps#169]
The export to foundry vtt script does not export innate attacks that are ranged. It does export weapon based ranged attacks (e.g., knife or gun) and does export innate attacks that have the melee modifier added to them.

**Comment by crnormand** [comment]
From Armin (GCA):

If the ranged attacks in question appear on GCA's sheets, but are not getting exported correctly, it may be that the routine isn't checking correctly for a valid ranged attack. All ranged attacks should have a 'charrangemax' tag with a value (and all melee attacks should have a 'charreach' tag with a value). Such attacks may be of any trait type, not just Equipment. CharacterSheet.GCS includes a PrintRangedWeapons routine that uses the DamageModeX routines, and finds any trait with ranged modes and moves through those modes (if more than 1) to get the data needed to print. Same system would work for exporting data.
It's not the greatest code, but it shows a way to get the data needed.

**Comment by crnormand** [comment]
From woefulhc

[GCA characters.zip](https://github.com/crnormand/gurps/files/5816854/GCA.characters.zip)

**Comment by crnormand** [comment]
I may have found the issue.   It seems the original script was checking for Equipment only when writing out ranged attacks, but NOT when writing our melee attacks.    Once I removed that restriction, it seems to export everything.

![image](https://user-images.githubusercontent.com/8931036/105877567-22ff7200-5fce-11eb-8c92-8b3a3ccaa131.png)

I am going to close the issue.  However, it may be a release or two before I get the script out there... my version handling for GCA imports kind of stinks... and I need to fix that before I can release the next version of the GCA script.
