### ISSUE TITLE
Rcl less than 1

### ISSUE THREAD

**Issue by The-Fleeb** [crnormand/gurps#1698]
Ive been playing around with a lot of automatic firearms at the minute, and it's RAD that GGA works out the number of hits from recoil.
What I want to know is, would it be possible to have GGA recognise a Rcl value of 0.5, i.e. have it recognise Two hits per point of success, a la the Very Rapid Fire enhancement from Powers/some of the high-cyclic controlled burst guns in High-Tech? 
I've tried it already and it seems to count the Rcl as 0, and then make every bullet hit.

**Comment by crnormand** [comment]
Do you have a GCS character that I can use as a test case?  If so, can you just ZIP it up and drop it into a comment.   I think I have the code correct... but need a different testcase.

**Comment by The-Fleeb** [comment]
Hi Chris,

I've attached the character here. He has a multi-mode gun, and one version of it has Rcl 0.5.

Thank you so much for looking at this, you guys are AMAZING!

Cheers,

The Fleeb

________________________________

**Comment by The-Fleeb** [comment]
[Adam Barneby - Cowboy, Illicit Entry, CQB, Detective Work.zip](https://github.com/crnormand/gurps/files/10217277/Adam.Barneby.-.Cowboy.Illicit.Entry.CQB.Detective.Work.zip)

**Comment by crnormand** [comment]
Thank you and it will be in the next release.
