### ISSUE TITLE
[0.8.5] Conditional Injury Severity does not show actual severity level

### ISSUE THREAD

**Issue by Legendsmith** [crnormand/gurps#172]
The severity box is just blank, no matter what. Whether it's entered manually or with the tickers.
![image](https://user-images.githubusercontent.com/1914417/104528114-7f6fa280-565a-11eb-9de2-e025f1a7e013.png)

I re-installed Exxar's Fork Branch ``feature/conditional_injury`` and it does not have this issue.

**Comment by mjeffw** [comment]
Sorry, I broke this in my current set of changes for the resource trackers. I just pushed a bug fix, it should work on the main branch now. Let me know so we can close it.

**Comment by Legendsmith** [comment]
It's fixed, thanks!
