### ISSUE TITLE
[Feature request] Let the ADD accept input of negative values

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1731]
Would it be possible to make the ADD accept manual inputs of negative values?

I am asking cause I have set up a Resource Tracker for Control Points using Fantastic Dungeon Grappling. The tracker is setup to increase when damage in form of Control Points [ctrl] is applied to it. But according to the Fantastic Dungeon Grappling rules you can also reduce the Control Points that have been applied to you. And for that reason I would like to have negative values in the ADD to actually reduce Control Points.

![ADD negative](https://user-images.githubusercontent.com/80178910/212124758-ca261e6f-61a8-46f3-ac02-4904428bb340.JPG)

**Comment by crnormand** [comment]
Done.
