### ISSUE TITLE
Having ^ in the skill won't let it roll

### ISSUE THREAD

**Issue by Babipoki** [crnormand/gurps#1733]
![GIF 2023-01-14 11-13-46 PM](https://user-images.githubusercontent.com/13620623/212499807-81402ac8-9f12-4461-9b22-2da2672bd6ea.gif)

**Comment by crnormand** [comment]
Interesting.   I'll get on it tonight.

**Comment by crnormand** [comment]
Can you ZIP up your character and attach it?   gca or gcs file?

**Comment by Babipoki** [comment]
The character isn't mine, but player's as they upload it themselves. I could make a new one a bit later

**Comment by crnormand** [comment]
No worries... I think I have it

**Comment by crnormand** [comment]
Found it.    I can make a patch release in a few minutes.
