### ISSUE TITLE
[Bug?] Unable to Input negatives in the HP/FP box from the tokens

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#1735]
As the title above, my players and I aren't able to deduct the HP/FP manually by a value when you select the token and use the boxes there, instead we have to change the value from the sheet.

With ADD it works fine, but there are cases where we don't use ADD for really quick and dirty damage.

**Comment by crnormand** [comment]
I'll take a look at it, but unfortunately that user interface is provided by Foundry.

And as Nick said, you can always use the chat command:

/hp -X

Where X is any number, and it will remove that much HP from the current character.

**Comment by crnormand** [comment]
Yeah... this one isn't in our control.   You would need to report a BUG on the Foundry issues list.  https://github.com/foundryvtt/foundryvtt/issues

The offending code is in the modifyTokenAttribute() method:

```
  async modifyTokenAttribute(attribute, value, isDelta=false, isBar=true) {
    const current = foundry.utils.getProperty(this.system, attribute);

    // Determine the updates to make to the actor data
    let updates;
    if ( isBar ) {
      if (isDelta) value = Math.clamped(0, Number(current.value) + value, current.max);
      updates = {[`system.${attribute}.value`]: value};
    } else {
      if ( isDelta ) value = Number(current) + value;
      updates = {[`system.${attribute}`]: value};
    }
```
isBar and isDelta are true, so it "clamps" the number between 0 and the max value.    It will not allow the number to be lower than zero.
