### ISSUE TITLE
Does GGA calculate HP injury from crippled limbs correctly?

### ISSUE THREAD

**Issue by jhymesba** [crnormand/gurps#1744]
NPC with 12 HP takes 9 points of penetrating damage to the leg. I expect the bad guy to take 6 HP of injury on top of the leg being crippled. Instead, this happens. 

![image](https://user-images.githubusercontent.com/4042155/213896804-04d5a922-f7da-46bb-9769-372da821bc94.png)

It could be I'm misreading B420, but I always read 'damage above HP/2 is lost' to mean you halve the base HP of 12 on the character that number (6) is the max injury you can take from a crippled limb.

**Comment by mjeffw** [comment]
Works as intended by the rules.
