### ISSUE TITLE
PDF width

### ISSUE THREAD

**Issue by beahtriss** [crnormand/gurps#1747]
Could be possible pass an argument to set width on command /r [!PDF:B1]? something like /r [!PDF:B1] *800. PDF always open too small for me. Thanks you!

**Comment by crnormand** [comment]
Unfortunately, we don't have a lot of control over the PDF window... that is a Foundry feature.    They "should" try to at least remember that last size that it was opened to... but it doesn't seem to.    This might be something that you put on the Foundry issues board instead.
