### ISSUE TITLE
[Feature Request] Quick way to reopen effect modifiers window after closed

### ISSUE THREAD

**Issue by rjdejonghe** [crnormand/gurps#1766]
I can't seem to find any way to open the effect modifier window if I close it (and I close things without thinking all the time).  Maybe there is an easy way to open this already that I don't know about, but I couldn't find it in the program or in the documentation.  Sorry for the trouble if there is something like this that I just missed.

I would be happy with a simple chat command /effectwindow or something like that (which would be listed among the command given with the /help command), or maybe an option in the setting to automatically reopen the window any time a status was added to any token.      Either of those would be fantastic.  Thanks!

**Comment by mjeffw** [comment]
Historically, we didn't open that window by default. So there is already a way to open it.

![image](https://user-images.githubusercontent.com/7349413/218318318-b1013f23-7094-4b8f-918f-ad21f54fc65e.png)
