### ISSUE TITLE
Nordlond Bestiary V1.2.3?

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1775]
Currently have V1.1.3 installed and have been prompted to update to V1.2.3, but get the following errors on The Forge:

![image](https://user-images.githubusercontent.com/89975749/219899366-f7e85e11-0e99-49a3-ae66-2c31acb8137c.png)

![image](https://user-images.githubusercontent.com/89975749/219899375-5b7fe10a-3ee5-431a-94cf-fa1d783a4bad.png)

**Comment by mjeffw** [comment]
Delete the module and reinstall. That will fix it.

**Comment by Farmeroz** [comment]
Thanks, mate - that sorted it!
