### ISSUE TITLE
System Breaks Inline Rolls

### ISSUE THREAD

**Issue by ElPresidentePoole** [crnormand/gurps#1778]
Basically, if you have a macro or chat message that reads like this:

```
Greyhawk initiative

Ranged: [[/roll 2d6-@basicspeed.value]]
Other: [[/roll 3d6-@basicspeed.value]]
Melee: [[/roll 4d6-@basicspeed.value]]
Spell: [[/roll 5d6-@basicspeed.value]]
```

it will render like so:

![image](https://user-images.githubusercontent.com/39707978/220173088-55538a97-c825-4980-a316-a4f9d6090efe.png)

This can be repeated by having more than one inline roll in a chat message.

```
[[/r 3d6]]
[[/r 3d6]]
```

gives us

![image](https://user-images.githubusercontent.com/39707978/220173270-a345283d-46e9-4175-ae15-712d17bd20e8.png)

On Foundry v10 build 291, GURPS 4e Game Aid 0.15.30

**Comment by SrAndros** [comment]
Finally got it fixed. It was the gurpslink not resetting properly so from the second OTF formula onwards it was treating them as gurpslinks, not OTF.

![image](https://user-images.githubusercontent.com/11762868/220554516-6e9e4d78-6889-4e34-808a-5dce6206a65f.png)
