### ISSUE TITLE
Move shows as 0 in Tabbed Sheet but correct in Editor

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1795]
Move shows as 0 in Tabbed Sheet but correct in Editor as per below:

Tabbed:

![image](https://user-images.githubusercontent.com/89975749/227703258-12c6ce56-639b-4fe8-8a8f-5a9dea48e99b.png)

Editor:

![image](https://user-images.githubusercontent.com/89975749/227703286-c1d9bada-08e5-452e-8f52-3724c4776761.png)

**Comment by crnormand** [comment]
Unfortunately, I can not recreate.        Is the character in combat?    A combat maneuver of None or Change Posture will set the Move to 0, if the system setting 'Maneuver Updates Move' is turned on.

**Comment by Farmeroz** [comment]
Thanks, Chris.  This was a while ago and we're on V11 and many GGA versions ahead, let's close this and if it comes up again I'll collect more info.
