### ISSUE TITLE
[0.8.4] Too many player names distort break Modifier tooltip layout

### ISSUE THREAD

**Issue by Legendsmith** [crnormand/gurps#180]
Seen below. They need to form a new row or something instead of doing this.
![image](https://user-images.githubusercontent.com/1914417/104809180-6c69f780-583f-11eb-85e1-98dc7919759d.png)

**Comment by crnormand** [comment]
Ah, the joys of not knowing CSS (back then).     It will now display like this:
![image](https://user-images.githubusercontent.com/8931036/104816899-1324a880-57ec-11eb-9b93-5a05d623b1d6.png)
