### ISSUE TITLE
Unescaped XML characters in trait names cause import errors.

### ISSUE THREAD

**Issue by jhymesba** [crnormand/gurps#1801]
What I did: Imported this character.
What I expected: Imported Character. 
What actually happened: Error: mismatched tag <text> and <pick>. Character failed to import.

The character had a few traits named Language: <Pick> to represent language slots in the template that I had not picked for the character. These unescaped < and > XML characters caused a failure to import the character. This file is attached first. 
[Seth-Khufu (NPC) export pre-Sanitising.zip](https://github.com/crnormand/gurps/files/11238302/Seth-Khufu.NPC.export.pre-Sanitising.zip)

Fixing the <pick> by rendering them as &lt;pick&gt;. This fixed the import. Corrected XML here: 
[Seth-Khufu (NPC) export clean up unescaped xml.zip](https://github.com/crnormand/gurps/files/11238306/Seth-Khufu.NPC.export.clean.up.unescaped.xml.zip)

Side note: Visual Studio marks the <br> as syntactically incorrect, burying the actual problems under 101 'expecting end tag</br>' and 'tag was not closed' errors. However, fixing these to <br  /> causes Foundry to throw a t.trim error. Learning experience for me for sure, and not sure if that's your fix or Foundry's. I'm not sure if <br></br> might be acceptable here. I'll test when I get some time, and let you know if that works.

**Comment by mjeffw** [comment]
XML fields that include unescaped < or > characters are invalid. They must be escaped like this:

`<name type = "string">&lt;Pick&gt;</name>`

Whoever is creating this file (GCA?) needs to fix this issue. There should be no other changes needed to make it possible to import this file. I did so successfully on the current version of GGA.

I didn't see any other errors when importing this character so I am going to close this issue.
