### ISSUE TITLE
[BUG] Mook error for ranged attacks

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1806]
The Guide for the game aid states for the Mook generator under ranged attacks:

```
Ex: Longbow (12) 1d+1 imp range x1/x2.5 bulk -3 acc 4

NOTE: The “range” value “50/100” does not contain a space, and can be of the form “xN” or “xN/xM” which indicates a ST based range.
```

But using something like:
`Javelin (12) 1d-1 imp range x1.5/x2.5 bulk -4 acc 3`

which adheres to the above format, results in an error:
`???: unknown pattern "range x1.5/x2.5"`

**Comment by crnormand** [comment]
Fixed.
