### ISSUE TITLE
[BUG] Importing Rifles with scoped accuracy Fails with "NaN"

### ISSUE THREAD

**Issue by RevenantBob** [crnormand/gurps#1808]
GURPS allow refiles to be scoped and their `Acc` becomes values such as `4+2`. 4 base, and +2 from scope. There may be other times this comes into effect I'm not aware of.

When importing these values, the sheet shows "NaN" or "Not a Number" from trying to parse it as a number. I would suggest that it import it as 4 and keep track of the +2. The +2 might become a modifier that can show elsewhere as "Scope".

**Comment by crnormand** [comment]
Fixed.   I assume this was for a GCA character... but in either case, we now parse the ACC and move the additional modifier to the note section as an OTF.
EX: "4+2" becomes "4" with a note of "+2 Acc".
