### ISSUE TITLE
[Suggestion] HUD Integration - Allow Half ACC Modifiers

### ISSUE THREAD

**Issue by RevenantBob** [crnormand/gurps#1809]
The HUD integration is a beautiful thing. Convenient access to rolls and some modifiers. One thing that would help is allowing Half Accuracy to be added as well as full. Why?

Some players have Gunslinger and can use half accuracy in some situation to shoot at enemies. Another situation is if using the optional rule from GURPS Tactical Shooting which allows follow up shots made at half accuracy.

**Comment by mjeffw** [comment]
You can do this without a code enhancement. On the Ranged attack on the character sheet add an OTF like this "[+2 Half-Accuracy]" and that will show up in the HUD, as will any other modifiers you want to add.
