### ISSUE TITLE
Mook generation can not parse pi-,pi+, and pi++

### ISSUE THREAD

**Issue by SparklySheep** [crnormand/gurps#181]
#### Description of issue

The /mook generation feature is unable to parse pi-, pi+, and pi++ 

#### Difference between expected and actual behavior

Mook generation would be able to parse these damage types, currently only pi can be parsed.

#### Steps to reproduce

Type in /mook, put in a ranged weapon that has either of the three pi types with a symbol in it.

#### Length of time in which bug has been known to occur

Since 1/16/2021

#### Issue bingo bongo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different people
- [x] Issue could be reproduced in multiple instances
- [x] Issue happened in a recent (less than 7 days ago) revision

**Comment by crnormand** [comment]
I found the problem.   A minor update to the RegEx pattern, and it works now.   It will be in the next release.
