### ISSUE TITLE
[BUG] Stacked maneuvers, status and positions

### ISSUE THREAD

**Issue by Ade75se** [crnormand/gurps#1813]
When the characters are placed in the Combat Tracker, it is not possible to change their position. If they have, for example, ended up prone, it is not possible to remove it. Likewise, old maneuvers remain and are piled up one after the other so that it is possible to see what previous actions they have done. They can't be erased. The same applies to statuses such as Disarmed, for example. When a combatant gets a Shock penalty, it wears off after each turn, however. But all other statuses and maneuvers are unchanged.

**Comment by crnormand** [comment]
Thank you for filling this out.   Which version of Foundry are you using, and which version of the GGA?

**Comment by Ade75se** [comment]
Hi! I am using Foundry v11 Build 302, and GGA 0.16.0. It seems like Nedorus on Discord reported a similar problem, and he also provided some screenshots: https://discord.com/channels/228546929494065152/788878698349723669/1121437694791270400
Best regards!
