### ISSUE TITLE
Enhancements to IT:DR on the Damage Calculator

### ISSUE THREAD

**Issue by PrinceOfIonia** [crnormand/gurps#1817]
Hello, I will be short and simple.

The first suggestion is to allow decimals for IT:DR (aka the Damage Reduction checkbox), the reason being that it actually appears in Dungeon Fantasy Monsters 3, Page 22.

The next suggestion is a togglable setting that changes IT:DR to be calculated BEFORE regular DR instead of after Injury, this allows normal DR to remain useful when taking in bigger attacks.

Thank you.

**Comment by mjeffw** [comment]
The first item is completed. I'm going to clone this issue and move the second item into its own issue, to keep things clean. Moving IT:DR to the first step in the calculation might be trickier than you'd think.

**Comment by mjeffw** [comment]
Done.
