### ISSUE TITLE
[BUG] Canvas drawing failed error 

### ISSUE THREAD

**Issue by SageThalcos** [crnormand/gurps#1824]
Was playing last night on release 0.16.1 on Foundry V10 (build 303) -- about halfway through the game, I started getting Canvas Loading Failed errors loading maps. Also, I could not double-click on characters to see their statistics, and damage was no longer applying to characters as it normally does.. Not sure if this is a GURPS issue, or one of my other modules is causing the issue.

Here is the console error:

![image](https://github.com/crnormand/gurps/assets/92134248/28a79f46-3d2c-4a47-a15b-506eaefa9702)

I also updated to 0.16.2 this morning, but get the same errors. Also disabled all modules, still get this error.

**Comment by SageThalcos** [comment]
And another set of errors - seems like it's a combination of the scene and tokens on it that causes this issue.: 
<img width="726" alt="image" src="https://github.com/crnormand/gurps/assets/92134248/75a3562c-5378-4303-b6a9-2d9067d4b9bf">

**Comment by TheFabulousIronChef** [comment]
I also cannot load the canvas after updating to v 0.16.2, also using v. 10 Build 330
![image](https://github.com/crnormand/gurps/assets/46587602/99d26cb4-3617-4572-bce2-6cd51bbef550)

**Comment by mjeffw** [comment]
Closing -- any version of GGA after 0.16.0 has breaking changes for Foundry v10. It is only compatible with Foundry v11. If you need someone to blame, I forgot to set the minimum compatibility version to 11. (Or else, blame Foundry for making breaking changes every single time they upgrade...).
