### ISSUE TITLE
Show individual dice rolls (not just dice totals)

### ISSUE THREAD

**Issue by TheFabulousIronChef** [crnormand/gurps#183]
It would be great to show the individual dice rolls instead of just the totals (like can be enabled for damage). I'm in two groups (one I am the GM, the other a player) and the GM of the group that I play in prefers to see the individual dice rolls. I'd like to move from Roll20 to FoundryVTT, and this is probably not a deal breaker, but I figure if it can be done for damage, it can be done for other rolls (hah--I am not a programmer, and this is probably *far* easier said than done). It would be great if that can be enabled. Thanks!

**Comment by mjeffw** [comment]
Implemented for most/all remaining die rolls. 

https://media.discordapp.net/attachments/774330748500836372/803347680943931392/image0.jpg
