### ISSUE TITLE
Feature Request: Adding Automated Animations Support

### ISSUE THREAD

**Issue by MEK98-DEV** [crnormand/gurps#1836]
Hi,

If at all possible, could we look into integrating the game system with the Automated Animations module? I'm not entirely sure how big this ask is, but it looks like you'd simply need a way to tag an advantage/item/skill as a melee, ranged, or an on token effect somewhere in the foundry character sheet (it would be neat if we could do so in GCS as well). Then all that would be needed after that would be to implement a pull request for Automated Animations providing the module the ability to implement the animations and sounds configured in the setup menu when tagged advantages/items/skills are used.

![image](https://github.com/crnormand/gurps/assets/58311857/f0f3abb5-8b4b-4f11-b5f3-5380d5eb4dd9)

I absolutely love running GURPS in foundryvtt though the lack of support for Automated Animations is the only thing holding me back from converting all my play groups over to GURPS.

Module Link: https://foundryvtt.com/packages/autoanimations

**Comment by mjeffw** [comment]
@MEK98-DEV  We are not planning to enhance GGA 0.16.x in the future. We are working on a new implementation which we call GCSGA or GGA 1.0. If you would like this added to GCSGA, add a "New Discussion" with this request here:
https://github.com/gcsga/gcsga/discussions
