### ISSUE TITLE
[Bug] Numerous "This character does not have a viable skill" messages on startup. 

### ISSUE THREAD

**Issue by jhymesba** [crnormand/gurps#1838]
When loading Foundry, numerous "This character does not have a viable skill (effective level 3 or higher) that can be rolled messages scroll. 

World is too large to load. Please request access to https://drive.google.com/file/d/10W58wgaJ9R6oCprq0PbCjvV8TnkWLcnf/view?usp=sharing for access to world data.

**Comment by mjeffw** [comment]
@jhymesba Apologies that one of us didn't get back to you immediately. Five months is unacceptable. Is this still a problem? If so, can you verify that the google drive share is still available?
