### ISSUE TITLE
Canvas drawing failed

### ISSUE THREAD

**Issue by Ganthad** [crnormand/gurps#1844]
![image](https://github.com/crnormand/gurps/assets/143288460/2122fc7b-29da-474a-93ac-26d8488c8b4b)

![image](https://github.com/crnormand/gurps/assets/143288460/51f1bf31-2657-4bbf-9f17-dd282351b80b)

I'm getting an error message. Specifically during loading a scene. 
removing and remaking a scene does not fix the issue, the problem is universal for both the players and the gm.
or removing modules
"Canvas drawing failed, cannot read properties of undefined (reading 'find')"
"Canvas drawing failed, cannot read properties of null (reading 'refCount')"

**Comment by Farmeroz** [comment]
If you're using GGA 0.16.3 or later and you're still on Foundry V10, this will happen.  You need to be on Foundry V11 or, if staying on V10, you need GGA 0.16.2 or lower.

If you're not on V11 already, I can confirm it all works nicely with GGA 0.16.0 and later and all the other modules I've been running have been updated, so it's all working well.
