### ISSUE TITLE
PDF Viewing

### ISSUE THREAD

**Issue by WickedZen** [crnormand/gurps#1848]
Longtime GURPS fan, going back to Man-to-Man when it first came out, but I am a new to Foundry and GURPS game aid. 

I provide some things for my players through  Journals in the PDF format and we are having an issue with the viewing window.

After some help from Foundry Support and Discord, I have confirmed that with D&D 5E system installed and an new world, when viewing PDFS I can fully adjust both width and length wise.

However, in my current world with GURPS Game Aid, and no modules installed, while I can adjust the width of the Journal window as, when I adjust the length the PDF size will increase but the actual PDF window will not lengthen, resulting if a small viewing window of the PDF requiring a lot of scrolling just to read one page.

![Normal View No Mods](https://github.com/crnormand/gurps/assets/39884245/a9092f9a-d28a-49be-aa4f-a42ba05ebd0d)
![Expanded View No Mods](https://github.com/crnormand/gurps/assets/39884245/2beeb5a3-fc38-45f6-b39b-15587fdeca20)

**Comment by Farmeroz** [comment]
Not a fix, but maybe a workaround - have you tried the PopOut! module?

https://foundryvtt.com/packages/popout

Let's you break VTT windows out into their own browser windows, which might let you resize things a little better?

**Comment by TheFabulousIronChef** [comment]
Any update on this?

**Comment by mjeffw** [comment]
Fixed in the next release.
