### ISSUE TITLE
Chat Processor /: needs to be updated

### ISSUE THREAD

**Issue by mclemente** [crnormand/gurps#1849]
Hello, I'm the dev of Advanced Macros and noticed there's a chat command (`/:`) to quick call macros, but it seems that command needs to be updated.

With V11's release, the Advanced Macros module started to use Foundry's own /macro chat commands, which now accept arguments in a way different from how the module did it.

I'm not sure how the whole `process` method works (the `chatreturn`, `this.send`, and `chatargs` are mysterious to me), but here is my suggestion:

```js
process(line) {
  let [command, match] = ui.chat.constructor.parse(line.replace("/:", "/macro")
  ui.chat._processMacroCommand(command, match);
}
```

**Comment by crnormand** [comment]
Hey, thank you for reaching out to us!   

I will look into it!

**Comment by mjeffw** [comment]
I've made a different change (for another GitHub issue) that might make this work but @crnormand I really would like you to take a look.
