### ISSUE TITLE
Saving new resource tracker template with non-unique alias or name deletes all work

### ISSUE THREAD

**Issue by Exxar** [crnormand/gurps#1859]
If you create a new resource tracker template via Settings -> GGA -> View and Edit Trackers and give it the same name or alias as an already existing tracker template, GGA shows "Tracker name (<name>) or alias (<alias>) is not unique" and closes the tracker editing window. While that is a fine error, the end result is that the newly configured tracker is discarded completely, which is quite irritating when you already spent a bunch of effort configuring the thresholds, colors, and other settings.

Please change this behavior so that the work is not lost.

I suggest either leaving the tracker window open when this error displays, or setting the alias to nothing and randomizing the name.

**Comment by mjeffw** [comment]
I'll fix this to append " (copy)" to a duplicate tracker name or alias.
