### ISSUE TITLE
Calling macros from OTFs doesn't work

### ISSUE THREAD

**Issue by Exxar** [crnormand/gurps#1860]
You can find how to reproduce the bug here: https://discord.com/channels/228546929494065152/788878698349723669/1176972886985154622

It doesn't matter if I put the macro name into quotes or not, same result.

**Comment by Cranal** [comment]
I already reported similar issue in #1837 here and even managed to find a temporary fix. But it looks like that even my temporary fix stopped working.
Have no idea if our issues related, but I think it's still good to mention it here.
