### ISSUE TITLE
the chat damage button doesn't work

### ISSUE THREAD

**Issue by 3darkman** [crnormand/gurps#1868]
I opened a standard character from the Basic Set in GCS, and added a dagger to him. I imported him into the foundry and rolled his attack. After the result appeared in the chat, I pressed the button to roll the damage of the attack, but I received the information that the character did not have any attack with that name.

[fvtt-Actor-dai-blackthorn-texJbmG1ajQB02Bc.json](https://github.com/crnormand/gurps/files/13854010/fvtt-Actor-dai-blackthorn-texJbmG1ajQB02Bc.json)

**Comment by mjeffw** [comment]
Reimporting the character fixed the issue.
