### ISSUE TITLE
Weapon range is not imported from a GCS character sheet

### ISSUE THREAD

**Issue by isfgames1064** [crnormand/gurps#1885]
Foundry VTT v11 build 315
GURPS 4e Game Aid v0.16.8
GCS v5.20.4

Summary: weapon range is not imported from a GCS character sheet

To recreate:

+ Add a ranged weapon to a character in GCS (say, Gauss Rifle)
+ Save GCS character
+ Open Foundry and select actor; import GCS character file
+ Range field in the Ranged Weapons section of the character sheet is empty

**Comment by mjeffw** [comment]
Should be fixed -- reopen an issue if it is not.
