### ISSUE TITLE
No system manifest found

### ISSUE THREAD

**Issue by henrypickler** [crnormand/gurps#1891]
When trying to install/update the system I get the following error:

![image](https://github.com/crnormand/gurps/assets/78927417/44fc087d-815e-4783-818a-175c03e04eac)

I'm using the most recent version of foundry (V11 Build 315). I believe the error is caused by a mistake in the naming of the latest release which was named 0.6.19 instead of 0.16.9 and thus the link foundry tries to access does not exist.

**For anyone having this issue:** This is a really well mantained repo and I'm sure this will be fixed very soon, however in the meantime anyone looking to install the latest version I believe it's just a matter of using the following manifest URL to install the system:

`https://github.com/crnormand/gurps/releases/download/0.6.19/system.json`

Foundry will thin

**Comment by crnormand** [comment]
Right... was a bit shaky... it was the first release in a while ;-)

I'll fix it.

**Comment by crnormand** [comment]
OK, "should" be fixed!
