### ISSUE TITLE
[BUG] Effect Modifier Panel ignores Scene's Grid Units

### ISSUE THREAD

**Issue by ZacharyHinds** [crnormand/gurps#1892]
The Range Modifier that appears in the Effect Modifier Panel for any targeted tokens treats all scenes as though their Grid Units is in yards. For example, I have a scene which uses "mi" instead of "yd" for the Grid Units and the range penalty when measuring distances works as expected, but the Effect Modifier Panel determines its Range Modifier based on yards.

![image](https://github.com/crnormand/gurps/assets/67064643/b302330f-9afa-4656-a4b8-2b20eb027e91)

Steps to recreate:
- Create a new scene or modify an existing scene
- Under **Grid**, Set the Grid Scale Units to a non-yard unit
- With any token selected, target another token

GGA 0.16.10, Foundry 11.315

**Comment by crnormand** [comment]
Figured it out... whew.   It will be in 0.17.6
