### ISSUE TITLE
Chat bugs

### ISSUE THREAD

**Issue by ShadwDrgn** [crnormand/gurps#1893]
It looks like if i click apply damage with the bottom button after  clicking the shock or major wound button or w/e other buttons add something to chat The entire chat history disappears leaving only the damage application message.

Steps to reproduce.

1. put 2 actors down.
2. Make a damage roll
3. Drag the damage over an actor
4. Click the shock button message button so it puts the shock text in chat (Btw there should, in my opinion, be an option in addition to the chat help button to just put the appropriate shock penalty in the effect modifiers box for the target JUST like clicking it in the caht window does so that i don't have to spam chat.)
5. Click Apply (not quietly) in the lower right.
Chat history vanishes, the text box at the bottom moves way up and only the message from damage apply button is left on the screen. refreshing doesn't fix it. Deleting the one message on the screen does seem to restore chat, though.

Hope this all helps.

**Comment by ShadwDrgn** [comment]
looks like this is only in firefox. Not sure if i should just close this or if it should be used as the bug for firefox.

**Comment by crnormand** [comment]
Yeah, we don't really have the resources to debug all the different browsers.   

Sorry.  I am going to close this.
