### ISSUE TITLE
Added Notes to Advantage/Disadvantage section are not importing into Foundry

### ISSUE THREAD

**Issue by paladiusdarkhelm** [crnormand/gurps#1897]
After updating to the most recent version of GURPS Game Aid for Foundry and the most recent GCS, the Notes I added in GSC in the Advantages and Disadvantages section of the character sheet are not included after an import into Foundry. The Notes added to skills import. Is there a new option I need to turn on in this version of GCS to allow the Advantage/Disadvantage Notes to import into Foundry? I like to see extra info and make OTF formulas on the Advantages and Disadvantages section of the sheets to help me run play. My older sheets still have all their notes. If I make a change in GCS and refresh one of these older sheets, it still refreshes with the added info in those sections. Hopefully, there is something silly I'm doing on my end causing this with brand new sheets. I've attached the brand new character created in this newest version of GCS as suggested by Nose. Thank you.
[Kar2.zip](https://github.com/crnormand/gurps/files/15248356/Kar2.zip)

**Comment by crnormand** [comment]
Thank you!  And I found it .    It will be fixed in 0.17.6.
