### ISSUE TITLE
Two or more PageRefs do not work

### ISSUE THREAD

**Issue by jhymesba** [crnormand/gurps#190]
When a character item has a page ref such as "B80, P71", clicking on it goes to the GURPS website rather than opening either Basic Set P. 80 or Powers p 71.

**Comment by crnormand** [comment]
Yeah... we assume that each page ref only has a single "book" identifier in it. 

Assuming the page refs are separated by commas, I should be able to open up both references (at the same time).   It would be too much work to try to open them up sequentially... unless.... hmmmm...

I could do this.   The first time you click on the link "B80, P71", it opens B80, AND THEN, it rewrites the page ref to be "P71, B80".   So the next time you click on it, it opens P71... and rewrites the page ref back to "B80, P71".

In the rare cases of 3 or more page refs, it would just cycle them through A1,B1,C1 => B1,C1,A1 => C1,A1,B1

This way, you are only opening one page ref at a time, but can cycle through them all.

Of course, opening both page refs at the same time might not be all that bad (and a bit easier to program)

**Comment by mjeffw** [comment]
Chris, can't we parse them as two different links, each clickable by itself?

**Comment by crnormand** [comment]
LOL, I was about to explain how I couldn't do it... and while writing it up, I figured out how to do it ;-)   It will be in the next release.
