### ISSUE TITLE
[Bug] Dice So Nice module doesn't roll dice (V12, GGA 17.1)

### ISSUE THREAD

**Issue by SageThalcos** [crnormand/gurps#1907]
When using the Dice So Nice module, clicking any GGA option (e.g. skill rolls, character sheet statistics, etc) does not visibly roll the dice anymore (you do still get the roll in the chat channel).

However, using FoundryVTT chat roll commands (e.g. /r 3d6) DOES roll the dice.

**Comment by NoOrangeSkitty** [comment]
Another related bug, when dice so nice is enabled and making a damage roll eg '/r [1d cr]' no die roll sound is made but with dice so nice disabled it does make a sound
