### ISSUE TITLE
"Dead" status wont show up on token

### ISSUE THREAD

**Issue by ThunderGad** [crnormand/gurps#1909]
Can't set Dead status to a token through Combat Tracker. Technically, it applies it, but visually, no skull appears above downed token, and console log reads the following:

Uncaught (in promise) Error: Invalid status ID "dead" provided to Actor#toggleStatusEffect
    at GurpsActor.toggleStatusEffect (foundry.js:15790:26)
    at CombatTracker._onToggleDefeatedStatus (foundry.js:89584:28)

**Comment by crnormand** [comment]
Fixed along with https://github.com/crnormand/gurps/issues/1918
