### ISSUE TITLE
Setting manoeuvres not working FVTT 12 Stable 4 (Build 327) and GGA 0.17.2

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1912]
Currently, when selecting a manoeuvre it does not set.  The options show up correctly, but they won't stick regardless of the means of setting them (console /man, token HUD, Token Action HUD, Character Sheet).

Images show various states and the console debug results.

![image](https://github.com/crnormand/gurps/assets/89975749/6adcbd76-9b5c-47fc-9f93-0556abd2762d)
![image](https://github.com/crnormand/gurps/assets/89975749/61ff8bed-7824-4e4e-b6e9-dd1b6638d682)
![image](https://github.com/crnormand/gurps/assets/89975749/4d0bda74-d07b-4f31-b2ee-63b6650619b0)
![image](https://github.com/crnormand/gurps/assets/89975749/41b41814-0133-4192-a9a7-f31e900ee287)
![image](https://github.com/crnormand/gurps/assets/89975749/901a0f01-7968-40e0-9caa-a29617033e84)
![image](https://github.com/crnormand/gurps/assets/89975749/e0a33b88-d191-4c0d-a232-b3763747b84b)
![image](https://github.com/crnormand/gurps/assets/89975749/e31a6b27-ecbf-47c8-85c7-a446e46c8e4e)

Reported on locally hosted and hosted on The Forge, and confirmed with all other modules inactive.

**Comment by mjeffw** [comment]
Fixed in next release.
