### ISSUE TITLE
Tokens don't display Combat Maneuvers

### ISSUE THREAD

**Issue by giggioz** [crnormand/gurps#1918]
Version 0.17.3
I noticed a couple of things, first:
When you mark a token as defeated (in combat) on the canvas there is no any icon to show it.
as you can see Colba is defeated but the canvas token does not show it
(probably related to #1909)

![image](https://github.com/crnormand/gurps/assets/6266740/0fa2cfd1-d827-41fc-b4a1-ed620de7428d)

Second thing:
if i select a maneuver from the token menù (same thing if i use the character sheet) it does not show it in the canvas, as you can see Akrul has an attack maneuver but it is now shown 

![image](https://github.com/crnormand/gurps/assets/6266740/ce8f2c2c-1f66-4798-a095-bc456e3c46a6)

Extra info: i reloaded the world because i added a new module and at least the manevuer icons are shown (pix1), but if i select another maneuver it disappears as before (pix2)

![image](https://github.com/crnormand/gurps/assets/6266740/70555eed-4eb2-4694-a108-9dd62e261ddb)
![image](https://github.com/crnormand/gurps/assets/6266740/ac14ca8a-2600-4979-bff2-5b2066008ddb)

**Comment by Gravydigger** [comment]
In addition to this, when moving to another tokens turn, the Maneuver also vanishes from the combat tracker.

Setting Maneuver on a tokens turn:
![1](https://github.com/crnormand/gurps/assets/53815736/e597abb7-91c9-4dd0-ab30-dcc7c3535bbe)
Moving to the next tokens turn
![2](https://github.com/crnormand/gurps/assets/53815736/0a59cbcb-7211-4035-85c1-42314d5cb339)

**Comment by Farmeroz** [comment]
Adding to this on behalf of a Discord user without a GitHub account (discussed in https://discord.com/channels/228546929494065152/788878698349723669 ).

Similar issues, and some errors from the console that might help - see images.
![image](https://github.com/crnormand/gurps/assets/89975749/faf4d0a1-b6a4-4075-a37b-ce6c054cb3b5)

This one when right clicking:

![image](https://github.com/crnormand/gurps/assets/89975749/49e7cfdf-67f7-4832-a2c7-413214e57a4f)

![image](https://github.com/crnormand/gurps/assets/89975749/b7f7405b-80ca-4748-9c1d-2e9747e5419c)

User advised this was with all modules disabled, V12, 0.17.3.

**Comment by giggioz** [comment]
![image](https://github.com/crnormand/gurps/assets/6266740/aea51a89-1b62-4fd2-aea3-74c0479ddc29)this was the culprit!

The flag was set to None.
I have now set it to Everyone and it works.

However, I believe there is some strange behavior when this flag is set to None.

For example when foundry restarts the icons are visible and instead they should not be.

**Comment by crnormand** [comment]
As of Foundry 12.328, the maneuver icons no longer throw exceptions when set to "None".   Also, they seem to stay associated with each token, as the combat tracker changes.

However, it does throw an exception when the status is set to "dead":

```
Uncaught (in promise) Error: Invalid status ID "dead" provided to Actor#toggleStatusEffect
    at GurpsActor.toggleStatusEffect (foundry.js:15878:26)
    at CombatTracker._onToggleDefeatedStatus (foundry.js:90211:28)
```
    
 So the question becomes... why isn't "dead" a valid status?  ;-)    I'm still investigating this.

**Comment by crnormand** [comment]
Ok, found it.     I've hacked the effects list to include 'dead' so it can be set (and displayed) from the combat tracker.
