### ISSUE TITLE
Control Points resource tracker modifiers not working

### ISSUE THREAD

**Issue by gmjasongurps** [crnormand/gurps#1919]
I can't click on the modifiers shown in the Control Points resource tracker at all. it SHOWS the right numbers, but they are not clickable.
I see this when I try to click on them
![Screenshot 2024-06-22 015843](https://github.com/crnormand/gurps/assets/172214771/847302c3-d6c7-4fa3-ab91-c0ff3869d5c8)

**Comment by crnormand** [comment]
Found it.   Fixed in 0.17.6
