### ISSUE TITLE
[Bug]  Physical Dice not working, rolling 0s

### ISSUE THREAD

**Issue by sw1v3l** [crnormand/gurps#1924]
![image](https://github.com/crnormand/gurps/assets/12145111/f827a83d-e9f2-4bd5-8dad-b455843edcb2)

In the above image, the first roll is selecting "Roll for me" at the prompt with Physical Dice enabled.  It rolled a 0 on 3d6.  The second roll is with a manually entered number, still showing a roll of 0.

**Comment by crnormand** [comment]
Found it!   It will be fixed in 0.17.6
