### ISSUE TITLE
Equipment files - v12 does not accept blank spaces in file names

### ISSUE THREAD

**Issue by Battenhatch** [crnormand/gurps#1926]
I have encountered an issue where import of equipment files to a compendium in GGA v0.17.4 would fail in Foundry v12.328 (and 327) on Forge, if they have blank spaces in their names. Replacing the blank spaces with underscores or hyphens solves this.

**Comment by crnormand** [comment]
Can you give me more context?    Which equipment file were you trying to import?   Can you attach it to this issue so i can try to import on my machine?

**Comment by Battenhatch** [comment]
I was importing the "Basic Set Equipment.eqp" file. When replacing the blank spaces with underscores or hyphens, there is no problem.
