### ISSUE TITLE
Updated GCS and importing a .gcs file now zeroes all skills

### ISSUE THREAD

**Issue by Coppini** [crnormand/gurps#1934]
I've recently updated GCS (both the program and the library), and now when I import a character sheet updated by the newer GCS version the skills are not properly imported on Foundry, listing all the skills but with both SL and RSL empty, while the Pts field lists `0` for all skills.

![image](https://github.com/user-attachments/assets/a5f577b5-b516-4216-839c-f10ca0de67a0)

**Comment by SavageGM** [comment]
GCS update ver 25 did not resole this issue.

**Comment by jutis** [comment]
I have the same issue. Using v5.25.1 of GCS

**Comment by RevenantBob** [comment]
This is still an issue in 5.25.1. They probably changed the sheet format in the JSON to put the skill value elsewhere.

**Comment by Coppini** [comment]
The latest updates (either 0.17.7 or 0.17.8) fixed this issue and it's working fine for me now. Could properly import from the latest GCS version :)
