### ISSUE TITLE
Feature request - Customisable and floating Roll 3d6 button

### ISSUE THREAD

**Issue by Xain3** [crnormand/gurps#1942]
The Roll 3d6 button is the most GURPSy thing that GURPS for Foundry has - I am fully ready to admit that.
However, sometimes, when you use a lot of modules like I do, the button becomes a bit cumbersome.
It would be great if the button could be resized, moved, or maybe (Steve Jackson forgive me for what I am saying) hide it altogether.
Less crucial, but since we're going down this road why not also give the option to customise the button image? This way we could maybe adapt it to the setting and the tone of the campaign?

**Comment by chrismaille** [comment]
Current solution:

### Settings:
![image](https://github.com/user-attachments/assets/50ad9a7d-564d-415b-9776-3f3eebcaa725)

Positions are:
* Left, neat user toolbar
* Right, near chatbox

### Bucket at left (default position, custom 3d6 dice):
![image](https://github.com/user-attachments/assets/6760364f-1bb3-4834-b23c-9109352acba4)

### Bucket at right, defaut 3d6 icon
![image](https://github.com/user-attachments/assets/c800da82-042d-4dde-8d7a-b161f8c9611b)

**Comment by IHappyEndI** [comment]
@chrismaille Hi! Thanks for implementing the idea, but there is one small bug. If you use a user interface module that centers the macro panel, then with these changes applied, this does not happen, and the macro panel remains in its normal position

**Comment by IHappyEndI** [comment]
@chrismaille for example RPG Styled UI

**Comment by chrismaille** [comment]
I see. [RPG Styled UI](https://github.com/Xbozon/rpg-styled-ui?tab=readme-ov-file) is a v11 module that mainly hardcode the hotbar CSS in the new position. I think it's risky to try to support this changing foundry interface CSS like they do. But I might look at this module again if they port it to v12.

As a workaround, my suggestion is to use the `right` option. Please let me know if this helps.

**Comment by IHappyEndI** [comment]
@chrismaille I'm using a fork of this module, I don't know how much suitable it is for use in V12 - https://github.com/Oxy949/rpg-styled-ui . Unfortunately, using different positions does not change anything ; ( . But anyway, thanks for the new feature!
![image](https://github.com/user-attachments/assets/c65bf565-6dfd-4cf6-b428-1cf4e7a07b7b)
