### ISSUE TITLE
Some parts of the character sheet seem to be affected by the foundry font size while the rest is not

### ISSUE THREAD

**Issue by Wilou1428** [crnormand/gurps#1945]
![image](https://github.com/user-attachments/assets/2e01157c-b000-4991-872c-96ee5141f83a)

The solution would probably be to override font for the these special foundry inherited elements if they are inside the character sheet, in addition to preventing the character sheet looking wonky it should make that part of the sheet fit in more with the rest of the sheet.

A less drastic solution would be to just override the font-size.

**Comment by mjeffw** [comment]
Which character sheet is this?
