### ISSUE TITLE
Several of the Cool Macros are not functioning

### ISSUE THREAD

**Issue by SavageGM** [crnormand/gurps#1952]
[Cool Macros](https://github.com/crnormand/gurps/wiki/Cool-Macros)

Clear & Toggle Active Effect is not functioning
Roll Attack and critical  and others

**Comment by mjeffw** [comment]
I did a pass through this weekend on these -- still a few more to go. Everything up to "Create and Toggle an Active Effect" are now working as intended.

**Comment by mjeffw** [comment]
Updated.
