### ISSUE TITLE
Increase Tracker slots

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#1955]

**Comment by mjeffw** [comment]
When you say "I can't give them all slots" what do you mean? That they don't all show up on the character sheet, or what?

**Comment by Farmeroz** [comment]
There are only 4 slots available for a GM to create templates - 0, 1, 2, and 3.  You can create more than that for a given actor as per my image above but only the ones in created by the GM in slots 0, 1, 2, and 3 show up in the ADD.

It would also be ideal if the GM could create all the requisite trackers and then players can add them by copying them.  Also, I've had some difficulty clearly referencing the trackers in JS.  I'm not sure how to differentiate between names and numbers and actors when calling them - if there was some clear structure on how to do that it would be handy for building things like the Heroic Archer macro and turning it into other things more easily (that's a side request, but came to mind thinking about this).

**Comment by mjeffw** [comment]
![image](https://github.com/user-attachments/assets/3adff56b-40ca-4394-bbf1-cdbb555c5787)
![image](https://github.com/user-attachments/assets/0acbc3dc-8f9b-4d8b-b49a-e05cfef42552)
![image](https://github.com/user-attachments/assets/9e407dc9-e9ea-4e6a-b6fc-7019b705b2d4)

**Comment by Farmeroz** [comment]
Thank you :-)
