### ISSUE TITLE
Error Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by Gizmo3030** [crnormand/gurps#1972]
hello I'm having a issue with GGA in foundry, I'm getting a error Cannot read properties of undefined (reading '0') when click certain things on any character sheet.

Foundry version 331 12 stable
GURPS 4e Game Aid 0.17.10
GCS 5.27

![image](https://github.com/user-attachments/assets/efcaa28a-bd36-4849-9f81-60ced39ea87f)

Console Log:
![image](https://github.com/user-attachments/assets/ad40c177-0930-44f6-8dae-aae08746793e)

Uploaded the log as well:
[Console.log](https://github.com/user-attachments/files/16852894/Console.log)

**Comment by chrismaille** [comment]
Hi, just to be sure, can you try again, but disabling all modules first?

Also, can you kindly provide the GCA/GCA exported file? I can make some tests here.

**Comment by Gizmo3030** [comment]
> Hi, just to be sure, can you try again, but disabling all modules first?
> 
> Also, can you kindly provide the GCA/GCS exported file? I can make some tests here.

Hello,

 I don't have any modules on at the moment, but i can definitely upload the .gcs file i used.

[Sergeant_Alex__Eagle__Johnson.zip](https://github.com/user-attachments/files/16884083/Sergeant_Alex__Eagle__Johnson.zip)

**Comment by mjeffw** [comment]
I tried to recreate the problem by importing the attached character into a world with no modules and it worked without problems. I see from the console log it looks like you have the Tokenizer module turned on. Please ensure all modules are turned off in the settings, delete this character, and reimport it. Then see if you still have the problem.

**Comment by Gizmo3030** [comment]
Good news, i fixed it.

After @mjeffw mentioned they got it working fine, I realized something was off. I had disabled all my addons, and as you can see in the screenshot, there were no active addons. However, it turned out that an addon called Tokenizer was still running in the background. Rather than spending time troubleshooting that, I decided to back up Foundry and do a fresh installation of the latest version. I reinstalled the GURPS system, set up a new map, and imported the characters, and everything worked perfectly. I suspect that my heavily modified and frequently upgraded version of Foundry had become corrupted over time. Starting with a clean slate seems to have resolved the issue.
