### ISSUE TITLE
Feature Request: Add the ability to translate some elements

### ISSUE THREAD

**Issue by IHappyEndI** [crnormand/gurps#1975]
Good afternoon. Could you add a translation option in en.json for new items in the tab-sheet. Namely GURPS.pesonalTab and GURPS.resourcesModsTab. 

And is it possible to add a translation option for these elements of the character sheet?
![image](https://github.com/user-attachments/assets/ec94f420-5e95-40e5-8e16-dd3f4ec48913)

**Comment by chrismaille** [comment]
Hi @IHappyEndI, thanks for the message. I did not find the `GURPS.personalTab` and `GURPS.resourcesModsTab` locations in Actor Sheet. If you can send a screenshot I'll look again.

For the Encumbrance section, current thinking is to 1) localize level labels and 2) add a small icon which indicates if Auto Encumbrance is enabled.  Something like this (using pt-BR translation):

![image](https://github.com/user-attachments/assets/a2f3b5a4-25c1-47e4-a4c2-7bcfaf55bf78)

**Comment by IHappyEndI** [comment]
gurps\templates\actor\actor-tab-sheet.hbs  line 36-37 GURPS.pesonalTab and GURPS.resourcesModsTab.

It's great that the translation feature will be added soon. Thanks!

**Comment by IHappyEndI** [comment]
@chrismaille Thanks a lot, the translation is working!
![image](https://github.com/user-attachments/assets/535981e6-982e-42bf-856d-a5b9bd80695f)
