### ISSUE TITLE
Feature Request: When import GCS Equipment Pack use extended values for Cost and Weight

### ISSUE THREAD

**Issue by chrismaille** [crnormand/gurps#1980]
This is a new feature: Use calculated extended values from GCS, when importing equipment via .eqp file.

### Example:
Item: Battle Suit (`etDAIqmoV3Q2hyPVZ`)
![image](https://github.com/user-attachments/assets/67640c62-9bf8-4752-a13b-3f4e0df97e73)
![image](https://github.com/user-attachments/assets/be5c59cf-da60-4cbd-9d29-cd2245d5ed36)

Inside .epq file:
```json
{
  "modifiers": [
    {
      "id": "fTUIkwIiZwQG8OJ-I",
      "name": "Test Modifier",
      "cost": "+30000",
      "weight": "+500 lb"
    }
  ],
  "quantity": 1,
  "calc": {
    "extended_value": 110000,
    "extended_weight": "650 lb"
  }
}
```

On GGA enable the new Settings option: `Import Extended Values from GCS Compendiums`
![image](https://github.com/user-attachments/assets/2311e5bc-df5c-4ce6-baf5-ab5d69edc611)

After new import:
![image](https://github.com/user-attachments/assets/6be32eda-8c33-4c10-aeec-939714065c86)

**Comment by IHappyEndI** [comment]
@chrismaille Thanks for adding it! But there is a small bug in this import, if the item initially has base values of 0, then it does not import extended ones.
