### ISSUE TITLE
Bug: When switching targets, the new traget is not diplayed in the Effect Modifier Window. 

### ISSUE THREAD

**Issue by StefanLeng** [crnormand/gurps#1985]
To reproduce: 
Have a token selected and another set as target. In target mode, klick on a third token to select it. This automatically deselects the old target.

Current behavior: The old target entry in the effect modifier window is removed, but the new target is not displayed. If you close and reopen the window, the new target is correctly displayed.

Expected behavior: The old target entry is removed and the new one immediately displayed.

**Comment by StefanLeng** [comment]
I debuged this a little bit: 
When switching target, the targetToken hook is called twice. First for detargeting the old target. This triggers a rerender of the Effect Modifier Window. At his time, the traget list is empty when read during getData. Then the hook is called for adding the new target, while the window is still rendering. The handler again triggers a rerender for the window, but this rerender is canceled by foundry because state of the window is "rendering".

**Comment by StefanLeng** [comment]
As I actually had the same problem in a module I am working on, I tried to solve this, but failed to find a non hacky solution. There seems to be no hook the fires after the rendering is completed.

I ended up with the following code in my sheet:

```
 /** @override */
  constructor (object : any, options : any) {
    super(object, options);
    //register a hook on targetToken to refesh when the target changes
    this._targetHook = Hooks.on('targetToken', this.targetToken); 
  }

  targetToken = () => {//needs to be an lambda to capture this in the clousure
    if (this._state === Application.RENDER_STATES.RENDERING){
      setTimeout(this.targetToken, 5);
    }
    else
    {
      this.render(false);
    }
  }
```
That works, but is so hacky that I hestitate to submit a pull request with a similar solution for the effect modifier window.

**Comment by mjeffw** [comment]
I wonder if the "target token" hook could store each event it receives in a global queue, pause for a few milliseconds, and then look into the queue to see if there are more than one event. If there are more than one event in the queue, and they are an "untarget" followed by a "target" discard the untarget and only process the target.

**Comment by StefanLeng** [comment]
Yes, this could also be a solution. This way, the app would only be rerenderd once instead of twice, that would be a big plus,
On the ohter hand, for this I need to decide how long to wait for the second event. I have no idea how much this would vary with the power of the client computer. That was the main reason I did not choose this solution. But maybe I am overthinking it and it would never take more than say 5 ms?

**Comment by mjeffw** [comment]
Even if it was 50 ms or 250 ms, that's within user expectations.

**Comment by StefanLeng** [comment]
OK, this works quite well for me:

```
  /** @override */
  constructor (object : any, options : any) {
    super(object, options);
    //register a hook on targetToken to refesh when the target changes
    Hooks.on('targetToken', this._targetToken); 
  }

  _targetToken = () => this.targetTokenInner(true);

  _tokenTrageted :boolean = false; 

  /*
    when an user switches targets, there are two calls to the targetToken hook, one for the old target and one for the new target
    if we rerender on the first call, we will miss the second call, because we are allready rerendering.
    Therefore we  need to wait and check  for the second call. 
  */
  _targetTokenInner = (newEvent : boolean) => {//needs to be an lambda to capture this in the clousure
    if (this._tokenTrageted){//this is either a second call or we have waited 30 ms since the last call
      if (this._state === Application.RENDER_STATES.RENDERING){
        setTimeout(() => this._targetTokenInner(newEvent), 5); //wait if already rendering 
      }
      else
      {

        this._tokenTrageted = false;
        this.render(false);
      }
    }
    else if(newEvent)//this is the first call, we need to wait if ther is a second one
    {
      this._tokenTrageted = true;
      setTimeout(() => this._targetTokenInner(false), 30);
    }
  }
```
Should I prepare a pull request with a similar solution for the effect modifier window?

**Comment by mjeffw** [comment]
Yes! Thank you.
