### ISSUE TITLE
[Bug]: Move is not displayed correctly when using the "Combat Sheet" or "Tabbed Sheet".

### ISSUE THREAD

**Issue by Grayscalae** [crnormand/gurps#1997]
As per title.

![image](https://github.com/user-attachments/assets/2626e59b-082a-4ab2-a5b7-2277e1ac2260)

**Comment by chrismaille** [comment]
Hi @Grayscalae , thanks for the message. Can you check if the "Auto Encumbrance" option is enabled in your settings?

**Comment by Grayscalae** [comment]
hi!

If yoy mean this one, it's off:
![image](https://github.com/user-attachments/assets/674e35bc-5852-4425-868a-307abc847a6f)

**Comment by chrismaille** [comment]
That one. If you enable this option, the combat/tab sheets start to calculate the correct number?

**Comment by chrismaille** [comment]
I can not reproduce the issue. Can you send to me the GCS/GCA exported file for this actor?

**Comment by Grayscalae** [comment]
Sorry for the delay.  Checking the Calculate Encumbrance option seems to make Move behave as expected.

Unrelated, and please let me know if I should open an issue for this: 
Importing a character from GCS with all his weapons and armor in "Other Equipment", and then moving to "Carried Equipment" whatever pieces you want them to have equipped, does not update DR or the Weapons list. It does update Weight, Encumbrance Move (as previously stated) and Dodge. Here's a gif (there's some CSS stuff but I don't think it should interfere with anything):

![2024 10 19 - 09h19m01s](https://github.com/user-attachments/assets/ab391adc-7e05-456b-9816-16d312323730)

If I import the character with armor and weapons under Carried Equipment, GGA displays both melee attacks and DR correctly. Moving said weapon back and forth from Carried to Other updates everything accordingly, moving armor however, does not. DR does not change. This time I imported the character with a Broadsword and some armor equipped:

![2024 10 19 - 09h26m30s](https://github.com/user-attachments/assets/4a722a67-5fb9-4a6e-820c-f71ad3e33982)

Also, in at least one instance, testing and moving equipment from Carried to Other resulted in duplication under Other Equipment.

**Comment by mjeffw** [comment]
@Grayscalae GGA does not calculate DR based on equipment; it only takes what is present in the GCS export file. So moving things from carried to equipped does not change the DR. That functionality should work out of the box with GCSGA, whenever that is released; otherwise it is a future enhancement to GGA. I'm closing this issue.
