### ISSUE TITLE
Damage dropping not working as intended

### ISSUE THREAD

**Issue by TheFabulousIronChef** [crnormand/gurps#2007]
When I drag damage to a hex, it should apply damage to that character. I understand if there is more than one character in the hex. But there isn't. And it asks who I want to apply it to. Here, that's not so bad--it's easy enough to see the difference. But when you have five guys named "Guard" it can be maddening. Yeah, the workaround is to give everyone different names, but the problem is it shouldn't be doing that.

[discord link with video example](https://discord.com/channels/228546929494065152/788878698349723669/1298106229482328084)

**Comment by chrismaille** [comment]
Current proposal:

1. When drag damage on token, open ADD (Apply Damage Window)  for that token.
2. If you have multiple targets selected, open ADD for each of one of them.
3. AAD will show now the token image and name.
4. If you drag to a empty space, do nothing, and show a warning.
5. If you want to use the old behavior, disable the `On drag, apply damage to selected token` in settings.

### Example
![GGADrag](https://github.com/user-attachments/assets/c1c25e6c-64a2-4583-b54e-567ebdbc2e89)

### New settings option
![image](https://github.com/user-attachments/assets/a9feddfe-670a-45be-aba6-3b877710d07a)

### Simple ADD Example
![image](https://github.com/user-attachments/assets/ae113ed3-763d-4a08-95c1-a10038bddf67)


Please let me know if this helps with the issue.

**Comment by TheFabulousIronChef** [comment]
Yes, I think that would help. Previously, dragging worked just as above, but something happened that affected the hex boundaries or something, so the game now gets confused and thinks everyone surrounding the damaged token is in the hex you dragged it to (even though there's only one guy in that hex). 

So, in your GIF, right now, if I drag that damage to MacChicun, it asks me if I want to apply it to MacChicun, or any adjacent tokens.

**Comment by TheFabulousIronChef** [comment]
I guess it requires you to select the token first under this proposal?

**Comment by TheFabulousIronChef** [comment]
Which shouldn't be a huge issue because as the GM, I probably just had it selected to make a defense roll, which fails.

**Comment by chrismaille** [comment]
You don't need to select the token before dragging, only if you want to open multiples ADDs at once.

**Comment by mjeffw** [comment]
I found the source of the original bug -- how Foundry selects tokens changed somewhere along the way. The new fix will correctly only try to apply damage to any token under the mouse pointer at the point of dropping the damage. It no longer incorrectly selects nearby tokens.

**Comment by TheFabulousIronChef** [comment]
Yeeeeeeeha! Can't wait for the new release, looks like a lot of cool stuff
in there.

**Comment by mjeffw** [comment]
This took way too long. I blame GenAI.

**Comment by mjeffw** [comment]
@chrismaille Did your fix include updates to the code that selects the token under the mouse pointer? It is not clear in your description above.

**Comment by chrismaille** [comment]
Yes, when using the fixed code, system will look for the token at the cursor's point. You only need to "target" tokens if you want to open one ADD for each token at once.
