### ISSUE TITLE
[Bug] The "roll for me" option does not work

### ISSUE THREAD

**Issue by Grayscalae** [crnormand/gurps#2010]
The "roll for me " option when using the Physical Dice setting seems to have broken for me - it returns only zero as result.

![2024 10 20 - 22h10m28s](https://github.com/user-attachments/assets/da3d7556-f47e-46eb-bfee-de87f717b3be)

**Comment by chrismaille** [comment]
## Current fix
![GGAPhysicalDice](https://github.com/user-attachments/assets/badf2bb7-3547-4243-9609-d1f9159fc7f6)

Please let me know if this helps.

**Comment by Grayscalae** [comment]
The gif seems perfect, however I just updated to 0.17.15 and still have the same behaviour as before. Perhaps a matter of module interference, or not having started a world from scratch with the new version?

**Comment by chrismaille** [comment]
The fix is not on 0.17.15 - the code is ready for next window available to release.

**Comment by Grayscalae** [comment]
Nice!
