### ISSUE TITLE
Add a setting to toggle  system wide "if Attack roll succeeds, roll damage automatically" 

### ISSUE THREAD

**Issue by Grayscalae** [crnormand/gurps#2011]
I know this can be done via On the Fly formulas, but I think this would be handy as a system wide option - especially for the GM. 

As side thought, something like: "if Token A has a target, and Token A succeeds an Attack roll, roll damage for the Attack and Dodge for the target", could be interesting too. But this has a narrower use case.

**Comment by chrismaille** [comment]
### Proposed solution:
A "Auto-Dodge" button on Combat Tracker. When you toggle, system will roll a simple dodge for the token (no modifiers at this point) and if it fails, roll the damage for the attack.

![GGAAutoDodge](https://github.com/user-attachments/assets/9d5c1957-122a-497f-b943-f8ea58123088)

I've put more details and context here: https://github.com/crnormand/gurps/issues/2013#issuecomment-2451192596

**Comment by Grayscalae** [comment]
I really like the additions, and they are ones I hadn't thought about. Regarding Auto-Dodge, I like it a lot, but I would still like to have a more simple simpler option for "Roll Attack and if it succeeds. roll damage", for the following reasons: 

- The Auto-Dodge solution works great when the GM is defending, but does not help when the GM is rolling attacks (I doubt many players would enjoy having their Active Defenses automated). So, when rolling monster attacks, the "Roll Attack and then Damage" would speed things up for the GM, especially for mobs and the like (as you accurately pointed up on your post). It could also dispense with the need for targeting, which people might forget, specially in fights with a large number of combatants. 
- Still, it would also speed up things for the GM when he is defending, if he wishes to select an Active Defense other than Dodge vs the PC's attacks.

I'm no programmer, but perhaps a logic like this could be interesting: 

- Option toggle for "Roll Attack and if successful then Damage" (I'll call it "Auto Damage") - ideally as a setting and also per token (though this granularity is less important). 
- Option toggle for Auto-Dodge on the Combat Tracker.  

Then, these possibilities: 
**Scenario A - Auto Damage On, Auto-Dodge Off**
The Attack roll is made, and if successful, the damage roll is made. Active Defenses follow, mannualy. 

**Scenario B - Auto Damage On, Auto-Dodge On** 
Works exactly like your GIF example. Attack roll > Auto Dodge Roll > if failure, Damage roll.  

**Scenario C - Auto Damage off, Auto-Dodge On**
Same as Scenario B, putting here just for completion. 

As a final thought, keeping in mind [mjeffw](https://github.com/mjeffw) comments regarding limits on automation imposed by SJG, at the very least the "Attack and then Roll damage" option seems to be a safe bet, seeing as we can already accomplish it vi OtF formulas. It would just be convenient to have it come straight from a button on the sheet, instead of the macro bar. 

In any case, I appreciate your hard work and the time you took to respond!

**Comment by StefanLeng** [comment]
How would you apply damage modifier with this feature?

**Comment by Grayscalae** [comment]
Good question, hadn't thought of it. 

How about a "Add to Basic Damage" button on the Damage Chat Card? You click, what what you want, and it modifies the result.

There could also exist a "Add to Basic Damage" on the ADD dialog box. 

We could have both of them available.
