### ISSUE TITLE
Importing a Character Causes Endless Error Loop

### ISSUE THREAD

**Issue by baoghal** [crnormand/gurps#2019]
I'm using GCS 5.28.1 and GGA 0.17.15. When I import a new character, the resource tracker goes bananas. The console also spams errors until I delete the actor.
![image](https://github.com/user-attachments/assets/ae887258-3f48-4c11-b499-828971dd29a9)
Going to try removing all addons and see what happens.

**Comment by chrismaille** [comment]
Hi @baoghal, thanks for the message. Looking at the images, it seems something related a additional tracker configured in your CGS file. Can you put here the GCS file here, please? Also the GCS version you're using? Thanks.

**Comment by baoghal** [comment]
I can, but this error occurs with any imported character. I can provide some additional context. Immediately before this, I created a new GCS template based off of GCS\Master Library\Dungeon Fantasy RPG\Monsters\Horde Zombie.gcs which does not have a fatigue pool so I removed it from the list of attributes before I tried to import it.
[Zombie A.zip](https://github.com/user-attachments/files/17599969/Zombie.A.zip)
I try this again and it works fine now, so weird.
Other context
The game was a game created with a previous GGA version.
I don't remember trying anything wild with the games before this one.
I think the import might be a red herring, because I vaguely remember messing with this screen:
![image](https://github.com/user-attachments/assets/82577930-fa7c-49b9-bd89-4e29a03dfe63)
but I had returned the resource tracker to what it looks like here.
Im not sure where the JSON is for the world settings but I will poke around in there and see if something looks wild.

**Comment by baoghal** [comment]
Ah nuts, the data\settings is no longer human readable. I am not sure how to open that stuff.

**Comment by Battenhatch** [comment]
Seeing this when creating a Mook also - trackers are going nuts. Flickering on and off. 

Console says (over and over):

![MookError](https://github.com/user-attachments/assets/768e267b-3606-4ae2-be7d-a39aa8735de2)

**Comment by mjeffw** [comment]
@Battenhatch and @baoghal -- I am having trouble reproducing the problem. Maybe it would help if you can send me the Foundry export of an actor that exhibits the bug, the GCS character that matches, and a screenshot of any resource tracker templates from the GGA settings.

**Comment by baoghal** [comment]
1. Create test world
2. Create character
3. import any GCS character
4. Settings -> Resource Tracker Manager
5. Control points Assigned Slot to Tracker 0 and save
6. Import character again
7. Settings -> Resource Tracker Manager
8. Control points Assigned Slot to Nothing and save
9. Import character again.
10. BANANAS :)

1. Create test world
2. Create character
3. import any GCS character
4. Settings -> Resource Tracker Manager
5. Control points Assigned Slot to Tracker 0 and save
6. Delete the tracker from the character sheet.
7. Import character again
8. Character broken now.

**Comment by Battenhatch** [comment]
Hi

I've tried it in a clean, newly created world, with no trackers defined - no problems. The world with the issue has several trackers defined

**Comment by IHappyEndI** [comment]
I faced the same problem in my world and roughly understood why this is happening. If you start making a lot of resource counters and then start assigning them to slots, one will end up empty at one time (see screenshot) and now with such a set of trackers, one will always be in a similar state. And as long as at least one tracker is in the empty field state, an infinite number of trackers are always created during import
![image](https://github.com/user-attachments/assets/174f065c-2666-4169-90d3-2cd813ef23fe)
