### ISSUE TITLE
[BUG] Players get "User lacks permission to update ActiveEffect" error message when mooks take damage

### ISSUE THREAD

**Issue by grevillewhittle** [crnormand/gurps#2021]
Last week we resumed our GURPS game after a hiatus of several months. I updated the GURPS Game Aid to the current release. Now in combat the players get error messages when mook take damage that results in a status change (especially when going from no status to reeling). Here is what shows in the logs:

foundry.js:72076 User Kirsten lacks permission to update ActiveEffect [FmyDLKVaBndg5gr0] in parent ActorDelta [tOGvVkReScjsw36B]

Uncaught (in promise) Error: User Kirsten lacks permission to update ActiveEffect [FmyDLKVaBndg5gr0] in parent ActorDelta [tOGvVkReScjsw36B]
[No packages detected]
    at file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:5101
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async ServerDatabaseBackend._updateDocuments (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:4748)
    at async Semaphore._try (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)

**Comment by grevillewhittle** [comment]
I should add I also get the error with all modules disabled

**Comment by grevillewhittle** [comment]
With a little more experimentation, the players don't get this error if I make sure no tokens are selected by me (the GM) so we can close it

**Comment by grevillewhittle** [comment]
With a little more experimentation, the players don't get this error if I make sure no tokens are selected by me (the GM) so we can close it

**Comment by mjeffw** [comment]
That's still so weird.
