### ISSUE TITLE
Remove the homebrew rules from the modifier bucket, add MA maneuvers to the bucket, and/or allow users to edit the modifier bucket.

### ISSUE THREAD

**Issue by PrinceOfIonia** [crnormand/gurps#2023]
Hello, the modifier bucket is a great tool for quickly adding modifiers quickly to your rolls, however the current modifier bucket does not include some common ones from Martial Arts such as Committed Attack and Defensive Attack. Some players might even have homebrew rules, so allowing users to edit the modifier bucket would be amazing.

Here is my complete list of suggestions for the modifier bucket.

1. Rapid Strike (B370) should be on the "Melee" section in the modifier bucket.
2. Committed Attack (MA99) should be on the "Melee" section in the modifier bucket, it should have two options, the "Determined" version which gives +2 to Hit, and the "Strong" version gives +1 to damage or +1 to damage per every 2 damage dice (whichever is better, at the GMs option).
3. Defensive Attack (MA100) should be both on the "Melee" and "Defense" sections. The "Melee" version should grant -2 to damage or -1 to damage per die, whichever is worse. The "Defense" version should grant you +1 to Parry/Block, as the GM should know what to do if the weapon is Unbalanced.
4. Pop-Up Attack (B390) should be added to the "Ranged" section. It should incur a -2 penalty to hit. 
5. Riposte (MA124) should be added to the "Defense" section. It should be listed as a generic -1 penalty, so that both attackers and defenders can apply the modifier to their own rolls, as Riposte can go both ways.
6. There should be a +3 to Parry via Retreat for using Fencing Weapon / Judo / Karate
7. -4 to Dodge should be removed entirely. Nick himself even said this was a homebrew rule from Nose66. ![image](https://github.com/user-attachments/assets/07ec1c41-6bbd-47fd-9200-fd2859f20040)
8. -4 to Parry from behind should replace the -4 to Dodge listing.
9. -2 to Dodge (Attacked From Side) should be renamed to -2 to Active Defenses (Attacked From Side)
10. +2 to Damage from All-Out Attack Strong should be changed to +2 Damage or +1 per Die, whichever is better.

**Comment by TheFabulousIronChef** [comment]
Interestingly enough, what I've been doing for retreating fencing parries is just clicking the "+1 to parry (retreat)" or whatever it says three times, and that works nicely while saving some space. 

Definitely would like Committed Attack and Pop-Up Attack--those would be great (also added to Maneuvers).

**Comment by PrinceOfIonia** [comment]
> Interestingly enough, what I've been doing for retreating fencing parries is just clicking the "+1 to parry (retreat)" or whatever it says three times, and that works nicely while saving some space.
> 
> Definitely would like Committed Attack and Pop-Up Attack--those would be great (also added to Maneuvers).

Yeah, you're right, you could do that to save space. And you also make a great point, Committed Attack, Defensive Attack, and Pop-Up Attack should also be added to maneuvers.

**Comment by Grayscalae** [comment]
I think the better approach would to be to have the default modifiers be customized. You can even have options such as "Basic Set only", "Basic Set + Martial Arts" and the like. Currently using journal entries to add to the right side panel is great, but the ability to customize the central panel would be cool too.

**Comment by PrinceOfIonia** [comment]
> I think the better approach would to be to have the default modifiers be customized. You can even have options such as "Basic Set only", "Basic Set + Martial Arts" and the like. Currently using journal entries to add to the right side panel is great, but the ability to customize the central panel would be cool too.

I agree, being able to customize the central panel would be cool, but I'm not sure how easily that can be done. I'm hoping for a more short term solution before the whole thing gets reworked. I mostly rely on the central panel, and the fact that a total homebrew rule is still on it is quite bizarre to me.

**Comment by mjeffw** [comment]
> Committed Attack (MA99) should be on the "Melee" section in the modifier bucket, it should have two options, the "Determined" version which gives +2 to Hit, and the "Strong" version gives +1 to damage or +1 to damage per every 2 damage dice (whichever is better, at the GMs option).

"Determined" and "Strong" are already there. It just doesn't say "Committed" in addition.

> I mostly rely on the central panel, and the fact that a total homebrew rule is still on it is quite bizarre to me.

Hey, go easy on us. :-)

**Comment by mjeffw** [comment]
Current revision:
![image](https://github.com/user-attachments/assets/65b2f5a1-1b85-4336-9ce0-28eb9b5372d8)

**Comment by PrinceOfIonia** [comment]
@mjeffw Looks great so far! The only things I can't spot are the -4 to Parry from being attacked from behind, Rapid Strike granting -6 to attack, and AoA Strong granting +1 damage per die if that would be better. I assume the AoA one might not make it due to it being more complex to add in. You can probably squeeze "Defensive Attack" instead of "Defensive" just to make the wording clearer, but if not its fine (you can also do "Defense Attack" if that grants enough room). Thanks a ton for making these changes; I think this would be a great addition to the system. 👍

**Comment by TheFabulousIronChef** [comment]
Looking good. I think Committed: Determined is +2 for one step, and a net 0
for two steps (I don't think it is +4) but this frankly looks pretty great.
You guys are the best.

**Comment by mjeffw** [comment]
@PrinceOfIonia @TheFabulousIronChef  @Grayscalae I'm opening a separate issue for "Allow users to modify the Modifier Bucket center panel": #2037 

I see no reason this can't be done.
