### ISSUE TITLE
Duplicating the specialization name to other skills

### ISSUE THREAD

**Issue by IHappyEndI** [crnormand/gurps#2035]
On version 0.17.15, if you import an actor who has the same skill with different specializations, then in total everyone has the same specialization in the title
![image](https://github.com/user-attachments/assets/feaa4f81-1c44-4cb5-9f6f-ae45be2b8fef)
![image](https://github.com/user-attachments/assets/127e1165-58f7-43ec-9432-b42d7d1ebca1)

**Comment by Tunzen** [comment]
I met same issue, when imported characters have one skill with several different specialities, they all would be imported with same speciality in name as first skill in group, but with correct skill levels

![image](https://github.com/user-attachments/assets/0a47611e-c09f-4d6e-a7d0-6eef50058452)

![image](https://github.com/user-attachments/assets/1f88e268-b686-495a-9765-331ed3e84e26)
"Use Foundry Items for Player Data" is On
GCS 5.28.2; GGA 0.17.15; Foundry v12.331
