### ISSUE TITLE
[Bug] Weapons created in Foundry do not create parry and block

### ISSUE THREAD

**Issue by IHappyEndI** [crnormand/gurps#2036]
When you use inventory in foundry (i.e. you don't import weapons from "GCS", but create them as an item in foundry), then block and parry are not calculated for them

**Comment by chrismaille** [comment]
Using the file `test.cgs` available in Discord:

### Using Foundry Items:
![FoundryItem](https://github.com/user-attachments/assets/f4890669-0ec2-4a92-bad6-dbe7f75ebb78)

### Using Actor Components
![ActorComponent](https://github.com/user-attachments/assets/7d7700a9-a5d1-4c36-9fba-05c3c4a0d2c9)

### The `traits` key in `test.gcs`
```json
{
	"traits": [
		{
			"id": "tqj42LxM3rQ7p2Gd4",
			"name": "Естественная атака",
			"reference": "B271",
			"weapons": [
				{
					"id": "wYJf741QOGbZ9xg1t",
					"damage": {
						"type": "cr",
						"st": "thr",
						"base": "-1"
					},
					"usage": "Укус",
					"reach": "C",
					"defaults": [
						{
							"type": "dx"
						},
						{
							"type": "skill",
							"name": "Драка"
						}
					],
					"calc": {
						"level": 10,
						"damage": "1d-3 cr"
					}
				},
				{
					"id": "wFtE3rEZmq8lZHiZF",
					"damage": {
						"type": "cr",
						"st": "thr",
						"base": "-1"
					},
					"usage": "Удар",
					"reach": "C",
					"parry": "0",
					"defaults": [
						{
							"type": "dx"
						},
						{
							"type": "skill",
							"name": "Бокс"
						},
						{
							"type": "skill",
							"name": "Драка"
						},
						{
							"type": "skill",
							"name": "Каратэ"
						}
					],
					"calc": {
						"level": 10,
						"damage": "1d-3 cr",
						"parry": "8"
					}
				},
				{
					"id": "wfczYJp442J4KNRJ6",
					"damage": {
						"type": "cr",
						"st": "thr"
					},
					"usage": "Пинок",
					"reach": "C,1",
					"defaults": [
						{
							"type": "dx",
							"modifier": -2
						},
						{
							"type": "skill",
							"name": "Драка",
							"modifier": -2
						},
						{
							"type": "skill",
							"name": "Удар ногой"
						},
						{
							"type": "skill",
							"name": "Каратэ",
							"modifier": -2
						}
					],
					"calc": {
						"level": 8,
						"damage": "1d-2 cr"
					}
				}
			],
			"calc": {
				"points": 0
			}
		},
          ...
     ]
}
```

Looking at the GCS/JSON file, the equipment was exported as a trait, and in the `weapons` section, only one Parry was exported. No `Block` was found in GCS file for this equipment.

It's seems, at first, system correctly import the GCS file. If you send another file I can check again.

**Comment by IHappyEndI** [comment]
@chrismaille Good afternoon! I probably don't write well in English, which is why there was such a misunderstanding. This error, if you can call it that, is not related to the import. 

The problem is that the weapon that was originally created in the foundry ("GCS" is not involved here at all) or weapons imported by the  library from "GCS" (i.e. also considered to be the item of the foundry), and not in the character, do not have parry and block calculation fields. You need to manually enter the calculated value of the final protection in the line "Parry Bonus" or "Block bonus". Is it possible to calculate such protection for a weapon automatically from a skill, or were these fields originally needed for this?

**Comment by IHappyEndI** [comment]
For example, screenshots from the foundry. Here there is a customized weapon in the foundry, but when you drag it to the sheet, it will have a parry of 0.
![image](https://github.com/user-attachments/assets/b11115ae-9d73-4068-82a3-5b9d08cea516)
![image](https://github.com/user-attachments/assets/ab8be0e7-b529-4709-8be0-1624f04e5b6c)

**Comment by Tunzen** [comment]
GGA can't calculate Parry, but pick whatever number is in Weapon Item Parry field, skill level OTF also not picked (no difference for  Weapon Items imported from GCS eqt lib or created straight in foundry)
AFAIK it is not possible in GGA to automate such calculation right now (at least if it's not addition and subtraction operations).
Writing skill level OTF with division not working, too (probably operator issue because of "/"-sign).
![image](https://github.com/user-attachments/assets/6afbb0f0-2b53-4e8b-9cb6-9f732be4bd47)

**Comment by mjeffw** [comment]
What @Tunzen said is correct -- at this point, GGA cannot calculate parry. To do so will require improvements in OTF, to cover multiplication and division and multiple term arithmetic  (skill ÷ 2 + 3) PLUS we would need to be able parse and understand advantages such as "Enhanced Parry" to properly automate it. 

The work around is to drag the item onto the actor, and then edit the attack from the actor sheet to add the parry value.
