### ISSUE TITLE
Injury Tolerance: Damage Reduction in the Damage Calculator does not allow decimal inputs for values less than 2.

### ISSUE THREAD

**Issue by PrinceOfIonia** [crnormand/gurps#2043]
As the title says. The IT:DR option in the Damage Calculator does not allow decimal values for numbers less than 2. But it WILL allow decimal values for numbers above 2.

For example, if you try to type in 1.5, it will be corrected to 2, but if you type in 2.5, it will stay 2.5

**Comment by mjeffw** [comment]
Not really a bug. The feature was implemented on purpose to disallow IT:DR values under 2. I've changed the validation to disallow values less than 1.

**Comment by PrinceOfIonia** [comment]
> Not really a bug. The feature was implemented on purpose to disallow IT:DR values under 2. I've changed the validation to disallow values less than 1.

Why though? Just let people have their fun, if you want someone to calculate an attack and they have IT:DR 0.7231 I'd say let them. I would only restrict the calculator to anything 0 or below so that it doesn't break completely.

**Comment by mjeffw** [comment]
For DR values less than 1 it would be a disadvantage and increase damage, not reduce it. 

I generally implement features by the book. 

I'm not trying to reduce anyone's fun, though!

**Comment by PrinceOfIonia** [comment]
> For DR values less than 1 it would be a disadvantage and increase damage, not reduce it.
> 
> I generally implement features by the book.
> 
> I'm not trying to reduce anyone's fun, though!

Yes, it could be a debuff added by a mage or something, who knows.

Ok, IT:DR 1.5 was seen in book... soooo
