### ISSUE TITLE
[Bug] Incorrect damage from the slams calculator /slam

### ISSUE THREAD

**Issue by IHappyEndI** [crnormand/gurps#2051]
Foundry v12.331
GGA v 0.17.16

Hello. When you check the box to use Dungeon Fantasy rules, the damage is considered as thrust, not thrust-2 (according to the DFRPG Exp pg. 40 rule)_((If you hit, you each roll your thrust-2 crushing damage on the other))_

**Comment by mjeffw** [comment]
Duplicate of #2053
