### ISSUE TITLE
Item Statistics missing with GCA4 import.

### ISSUE THREAD

**Issue by bristol454** [crnormand/gurps#2057]
When importing characters from GCA4 equipment does NOT have cost or weight in VTT. 

Created a clean world with no mods, only GGA and replicated with new and old character import files from GCA4.

**Comment by mjeffw** [comment]
Can you upload some export files that show this behavior?

**Comment by bristol454** [comment]
[(new Export)Geoffrei du Guesclin.gca4.TXT](https://github.com/user-attachments/files/18155922/new.Export.Geoffrei.du.Guesclin.gca4.TXT)
[(Old Export)AEthelwulf.gca4.TXT](https://github.com/user-attachments/files/18155924/Old.Export.AEthelwulf.gca4.TXT)

Attached are the 2 export files.

**Comment by bristol454** [comment]
Just uploaded... I think I accidentally closed the issue....
