### ISSUE TITLE
/iftest applies bonuses twice

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#2059]
Example:
`/if [@IsCritFailure] [HT+6] [HT-2]`

On success, a total of +12 is applied to the HT roll.

Screenshot:
![image](https://github.com/user-attachments/assets/766662b3-7149-49ad-8b91-e658b591d894)

**Comment by chrismaille** [comment]
Was resolved with this? https://github.com/crnormand/gurps/pull/2064/commits/95ecae0fb7adac99fa79ac03727d0447f96bb31f
