### ISSUE TITLE
GURPS.executeOTF is broken when using /if [On-the-Fly] cs:{ critsuccessclaus } s:{ thenclaus } f:{ elseclause } cf:{ critfailureclause }

### ISSUE THREAD

**Issue by devakm** [crnormand/gurps#2060]
As best I can tell after much testing and trying different combinations of wording, the GURPS.executeOTF(OtF) parser got broken somewhere along the way from V9 to V12.

Maybe it works fine for simple OtFs, but it definitely does not work for `/if [On-the-Fly] cs:{ critsuccessclaus } s:{ thenclaus } f:{ elseclause } cf:{ critfailureclause }`

I say this because even very long and complex wording in this format works perfectly if activated manually. If I copy-and-paste the command into chat then it works, or if I use JS to generate a chat message that the user has to click, then it also works.

If I try to use GURPS.executeOTF to run the same OtF (with extra `\\` ) then it always fails by either giving the Unbalanced error or by silently skipping down to run extra commands from subsequent clauses.

Is it a coincidence that GURPS.executeOTF is no longer in the Guide?  (This is a depressing idea and I really hope I'm wrong about this.)

Not sure what to try next other than forcing player to run the macro then also click a chat message for things that used to work by just clicking the macro.

**Comment by mjeffw** [comment]
@devakm 
It's a bug. `GURPS.executeOTF` as a whole is not broken (indeed, much of the rest of GGA uses this internally), but its very probable that the `/if [On-the-Fly] cs:{ critsuccessclaus } s:{ thenclaus } f:{ elseclause } cf:{ critfailureclause }` parsing is broken. I'll try to get this into the next release (hopefully this week!).

**Comment by devakm** [comment]
After converting more of my v9 scripts to work with v12, I can confirm what you stated: most OtFs work fine using `GURPS.executeOtF`. So far this is the only major issue I've encountered. Thank you for taking a look at it!

**Comment by crnormand** [comment]
I haven't set up my replacement computer yet.    But I'll look into this as soon as I can.
