### ISSUE TITLE
17.17 Beta - Move and Attack did not work on Confirmation Dialog

### ISSUE THREAD

**Issue by TheFabulousIronChef** [crnormand/gurps#2075]
Not sure about this: I click the move and attack maneuver, then apply the modifier in the bucket, and then try rolling from the sheet and I get this (after I ended the combat and restarted it):

![image](https://github.com/user-attachments/assets/2e3f3d80-ac80-4f9f-8901-6faa3e0027e7)

Also, not sure how to edit "Max actions per turn," since this guy has extra attack. Maybe some instructions are needed before the beta? (I realize this is a beta, of course, but I'm trying to test it).

**Comment by TheFabulousIronChef** [comment]
It also somehow keeps clearing the mod bucket every time I click to roll.

**Comment by TheFabulousIronChef** [comment]
Apparently I need to turn off the used tagged modifiers. 

![image](https://github.com/user-attachments/assets/b71594af-ab09-43e4-9850-03bce660ced2)

**Comment by TheFabulousIronChef** [comment]
But...

1. The allow max actions reached seems to be ... for the entire combat, and not just the turn? Maybe if I advance through an entire "round" it will work? 
2. Cannot roll with maneuver...what? 
3. It shows net skill 21 (25-4) in the roll confirmation but does parse it as Max 9 in the chat.

![image](https://github.com/user-attachments/assets/75536e81-28a1-42c0-a14b-7b61221932c1)

![image](https://github.com/user-attachments/assets/4b6c606c-813d-4318-ba0b-4ce1e3b1036a)

**Comment by TheFabulousIronChef** [comment]
Defense rolls seem to work? 

![image](https://github.com/user-attachments/assets/d7e11c34-294c-4b55-b7cc-1c01549cc049)

**Comment by mjeffw** [comment]
@TheFabulousIronChef  Lol, I didn't expect anyone to download and try this out.
Anything weird with the new features, you need to alert @chrismaille .
But hold off for a moment, he's been addressing some of these bugs but I haven't updated the beta yet. I'll let you know when I've updated it.

**Comment by mjeffw** [comment]
@TheFabulousIronChef Okay, 0.17.17-beta.2 is ready for you to test.

**Comment by TheFabulousIronChef** [comment]
No worries, thanks, though!

**Comment by chrismaille** [comment]
@TheFabulousIronChef you can change the max Actions per turn on the character sheet:
![image](https://github.com/user-attachments/assets/b4cddf4f-dbcd-4adb-be20-c6a44b7b3c19)
Please click on "Editor" option in the sheet and set the max actions for that token/actor.
