### ISSUE TITLE
/r [+1 anything] breaks executeOTF

### ISSUE THREAD

**Issue by devakm** [crnormand/gurps#2076]
This OtF worked fine using executeOTF in v9 (with extra \\):

`[/if [S:Fast*Draw*Arrow] s:{/r [+0 Fast-Draw (Arrow) Ready success] \\You <strong>Fast-Draw</strong> your arrow in no time! You can attempt to position your bow right away.} cs:{/r [+3 Fast-Draw (Arrow) Ready crit] \\You <strong>Fast-Draw</strong> your arrow with such precision that you gain +3 to position your bow!} f:{/r [+0 Fast-Draw (Arrow) failed] \\You fail to <strong>Fast-Draw</strong> an arrow this turn. You can position your bow next turn.} cf:{/tr(Arrows) =0 \\You fail so badly at <strong>Fast-Draw</strong> that you scatter the contents of your quiver everywhere! Take a turn to pick up 1/4 of the arrows that were left in your quiver and then try again.}]`

Now in V12 it gives error "did not parse into a valid On-the-Fly formula". 

The culprit appears be my use of the "roll modifier" OtF:  `/r [+1 anything]`

It works fine in chat.

**Comment by devakm** [comment]
Better examples. This:

`let OtF = '[/if [Sk:Fast*Draw*Arrow] s:{/r [+1 Fast-Draw (Arrow) Ready success]} cs:{/r [+3 Fast-Draw (Arrow) Ready crit]} f:{/r [-1 Fast-Draw (Arrow) failed]} cf:{/r [-3 Fast-Draw (Arrow) crit failed]}]';
await GURPS.executeOTF(OtF);`

works fine if the ONLY outcome is a modifier, but adding any other outcome breaks it. This

`let OtF = "[/if [Sk:Fast*Draw*Arrow] s:{/r [+1 Fast-Draw (Arrow) Ready success] \\\\/r [3d cut]} cs:{/r [+3 Fast-Draw (Arrow) Ready crit] \\\\/r [4d cut]} f:{/r [-1 Fast-Draw (Arrow) failed] \\\\/r [2d cut]} cf:{/r [-3 Fast-Draw (Arrow) crit failed] \\\\/r [1d cut]}]";
await GURPS.executeOTF(OtF);`

rolls all of the outcomes.

**Comment by mjeffw** [comment]
It's the embedded `\\` that causes the error. The current code doesn't handle chat commands with `\\` nested inside another chat command.

I'm putting out a fix, but we will have to see if this breaks any other OTF syntax.
