### ISSUE TITLE
17.17-beta 2 Confirmation Dialog Roll #2030 fails to recognize maneuver and character portrait

### ISSUE THREAD

**Issue by devakm** [crnormand/gurps#2080]
![image](https://github.com/user-attachments/assets/b02d9aa8-aae1-42b3-9fd5-22a619f13bd0)
It's not recognizing that Maneuver: Attack is selected, and it does not show the character portrait.

**Comment by chrismaille** [comment]
Can you please give the GCA/GCS exported file for this character?

**Comment by devakm** [comment]
> Can you please give the GCA/GCS exported file for this character?

[Bruja.zip](https://github.com/user-attachments/files/18276087/Bruja.zip)

I also clarified this one a bit in follow-up #2082. Looks like the art problem is with .webm token art. Works fine with .png.

**Comment by chrismaille** [comment]
Thank you - can you also attach here the .wbem token art, please?
