### ISSUE TITLE
Explosion damage

### ISSUE THREAD

**Issue by gtludwig** [crnormand/gurps#219]
As per GURPS rules, the damage from explosions diminishes drastically the farther one is from where the explosion started.

If an explosion happens in any particular hex, the six adjacent hexes, at radius 1, take 1/3 of the initial blast. All hexes at radius 2 take 1/9 of the initial blast. And so on.

If an explosion delt an astonishing 27 points of damage where it took place, at radius 1 it causes 9 points of damage. At radius 2, 3 points of damage. And at radius 3, 1 point of damage.

Two questions on this:
1. Do we want (and/or can) to automate this?
2. At what point the explosion damage would be negligible and would stop propagating? When it is 1/3 of point of damage?

**Comment by crnormand** [comment]
This seems like it _could_ fit in the ADD (Apply Damage Dialog).   The question is, where?  And how?  Personally, I always thought the drop off in explosion damage was too severe, so if we implement something, I would like the chance to set that value.

Maybe something like: Explosion distance: 0 (100%), 1hex (33%), 2hexes (11%), 3hexes ...

Of course, the GM can just calculate this in their head, and type in the new starting value and let the ADD do its thing.

So, I leave it up to Jeff.

**Comment by gtludwig** [comment]
This is a _suggestion only_!

That being said, I would love to help out!

**Comment by trev-dev** [comment]
For us OCD GMs, we like to do separate damage rolls for everyone caught in a blast and measure out the distance + do the math. I had written a macro for this in the past. If this were a feature of the Appy Damage Dialogue, I would use it. It would save me a macro in the very least :)

**Comment by gtludwig** [comment]
Separate damage rolls for everyone in the blast radius? That's news to me! I always thought that for the explosion damage (say from an Explosive Fireball), the GM or Player rolls the damage and this damage is, then, divided by three for radius 1, divided by nine at radius 2, and so on.

**Comment by trev-dev** [comment]
The rules state you can do separate or just one if I recall correctly :) I like separate as it allows for a little extra chaos, like miraculous survival or devestation

**Comment by crnormand** [comment]
Off the top of my head, I don't see that fitting into the ADD, mainly because its purpose is to calculate the damage to a single target.  However, I like the idea of a macro... something that could roll damage and apply explosion distance, and it would create a separate damage chat message for each, so the GM could drag and drop on the appropriate target, and then go through the usual ADD functions (DR, etc.).

It would probably be a chat macro, something like:  /exp <damage> <dist in hexes>

/exp 3d burn 2

Of course, going forward, I should probably open up the damage api so that we could write script macros (this is all pseudo code, because I don't know the actual Foundry structures for this)

// Roll separate 3d burn damages for each targeted token and create the Damage chat msg that can then be used by the ADD
game.canvas.tokens.filter(t => t.isTargeted()).forEach(e => GURPS.makeDamage("3d burn"))

// Roll separate 3d burn explosion damage for each targeted token, calculating distance from the selected token
game.canvas.tokens.filter(t => t.isTargeted()).forEach(e => GURPS.makeExplosionDamage("3d burn", game.canvas.selectedToken))

I'm just brainstorming... don't expect this in a release anytime soon.

**Comment by gtludwig** [comment]
I agree this something for down the road.

On that, it could be nice for the GM to type in the chat a macro like the one below:

/exp burn <number-of-die>

Or click on a button in the GMs screen. 

Then the game aid would ask the GM to click on the location.

Once this is entered, the game aid asks the player to roll the explosion damage and applies to the actors. And moves affected actors as per knockback rules! 

Yeah, I went to town on this...

**Comment by crnormand** [comment]
Ok, after some brainstorming (and decent cup of coffee), I've come up with a plan.   Take it or leave it ;-)  J/K

Let me go over the process so you can see how it would be accomplished.

Assume a party of 3 player characters (Tom, Dick and Harry), where 2 are in the blast radius of a trap (Tom is 1 hex away and Dick is 2 hexes away from the center of the blast).

**Example 1 (using the same damage for each character):**
The trap explodes and does 3d burn damage.    The GM types in "/r [3d burn]" in the chat log which rolls damage and creates a chat msg like:
![image](https://user-images.githubusercontent.com/8931036/106487106-58013e00-6480-11eb-8615-4478231cab87.png)

The GM drags that chat message onto Tom's character sheet and uses the "Explosion" distance multiplier to select "1 hex, 1/3 damage".   And then applies the damage (after selecting the usual options, DR, etc.).

* Jeff/Nick is going to add an "Explosion" distance multiplier to the Apply Damage Dialog (ADD), so the GM will be able to select 1/3, 1/9 and 1/27th damage.    

The GM now drags the **same** damage chat message onto Dick's character sheet and selects the "Explosion" distance of "2 hexes, 1/9 damage".    And then applies the damage (after selecting the usual options, DR, etc.).

**Example 2 (rolling individual damage for each character):**
The trap explodes and does 3d burn damage.   The GM types in "/ev 3d burn" in the chat log, and it will roll 3d burn damage for each character in the scene. 

* /ev (or /everyone) is a new chat command

Which means that if there are 3 player characters, it will create 3 damage chat messages (that will have a labels like "Damage for 'Tom'", "Damage for 'Dick'", "Damage for 'Harry'").   
Ex: 
![image](https://user-images.githubusercontent.com/8931036/106490805-30ac7000-6484-11eb-9a51-fafb5280a94e.png)
The GM drags "Damage for 'Tom'" onto the Tom character (and applies the damage as above) and then drags the "Damage for 'Dick" onto the Dick character and just ignores the "Damage for 'Harry'" chat message as superfluous. 

The only real downside is that you will be filling up the chat log with damage messages (and some won't even be used... although that might be a fun talking point "Look Harry, if you had been 1 step closer, you would have taken 18 points of damage!   Lucky you!").

**Comment by mjeffw** [comment]
What if we were to compress the multiple damage chats into a single message, like this mockup?
![image](https://user-images.githubusercontent.com/7349413/106498524-70c42080-648d-11eb-9c70-a90b3ea107dd.png)
This would save space, especially since I've run at least one encounter with 6 PCs + 10 or more foes. 
Clicking on the disclosure arrow would open up the complete panel. Each bordered area is a separate draggable element.

**Comment by gtludwig** [comment]
This is awesome!
I'm so happy this nice-to-have crazy idea of is picking up steam!

**Comment by crnormand** [comment]
Even better (of course, it means a bit more work on our part).   Jeff, how hard would it be to make such a damage chat?
Right now we call "GURPS.damageChat.create(actor, formula, damagetype, event)" to create a single chat msg.   Would you create a new method, or detect the type of the first parameter, and if it was an array, create the new multi-damage chat message?  Either way, "if you build it, he (I) will come"

**Comment by mjeffw** [comment]
We'll use the same method, I'll check to see if it is a string or an array.

**Comment by gtludwig** [comment]
A complimentary idea for the explosion damage is to use consider the average DR.

**Comment by mjeffw** [comment]
ADD already handles that, via the "Large-Area Damage" setting.

**Comment by mjeffw** [comment]
I merged this solution today. Here's how it works:

Create an OtF damage formula for the explosion, '6dx4 burn' for example. We don't currently need the 'ex' after it.

Roll damage. This will produce a single damage result that can be applied to all the actors that are in the blast radius. (Individual rolls are enabled but we don't have a way to select the possible targets yet.)

Drag the damage onto each actor. The ADD opens. There is a new checkbox "Explosions" under Special Situations.

If you click that a drawer will open beneath it to enter the range in hexes from the center of the blast. (The hit location will update to "Large-Area Injury" automatically, and any armor divisor is dropped.) Enter that value and the ADD will calculate the appropriate damage divisor (1/3, 1/6, 1/9, etc...). Unchecking Explosion will reset the hit location to what it was previously, and reapply the armor divisor.

![image](https://user-images.githubusercontent.com/7349413/107156526-cc3e5480-694c-11eb-83db-000c2f87b570.png)

![image](https://user-images.githubusercontent.com/7349413/107156538-dfe9bb00-694c-11eb-9637-dca92b0ee292.png)

**Comment by mjeffw** [comment]
I'm going to leave this open until we know how to selectively generate rolls for individual actors.

**Comment by crnormand** [comment]
Honestly, this is better than I could have asked for.   And it fits the 80% mark (heck, I think we are getting towards the 90% mark).   The GM can generate damage somehow (OtF, NPC ranged attack, whatever), and then drag that single damage onto each target that they determine is in range.   And then just have to click the "Explosion" checkbox and enter a number and all the rules are followed... PERFECT!   And to stave off any SJG objections... it is all optional.   If they want to follow explosion RAW, then we can do the math for them.   Of not, ... you've heard my rant before ;-)

Sure, we can try to create something for those 1% of the GMs (you know who you are) who like individual rolls per target...  but I'm fine for saving that for the future.   We have won our battle today.

**Comment by mjeffw** [comment]
I'm adding the ability to generate multiple damage rolls via a right-click on the damage formula. Closing this issue.
