### ISSUE TITLE
Structural damages from explosions

### ISSUE THREAD

**Issue by gtludwig** [crnormand/gurps#220]
I know I am jumping a lot of hoops here and this might be best if inherited from either from the Foundry-VTT core or a module, but it would be really cool if explosions would be that they actually damage structures like walls, doors, etc.

Of course, this would need to assume that structures would be each an actor and have individual HP and DR stats. No dodge or block, though!

**Comment by crnormand** [comment]
Unfortunately, Foundry doesn't model structures.   They model "lines", and only in terms of lines of sight/lighting.   Any walls you see on a map, are just that, on the map.   You might be able to model walls using tiles (I've never looked into tiles), and therefore could replace a tile with a damaged tile to indicate, but from our game aid perspective, there isn't much we can do.

**Comment by gtludwig** [comment]
Again, this could be a feature from Foundry, but I would assume it would take a lot more time to model the walls like that. I suppose tiles could be a way to go because they do block light and line of sight. In any way, it would take a lot of time to model thick walls and doors and its HP and DR. 
But it would be cool!

**Comment by trev-dev** [comment]
As cnormand said walls do not and cannot yet have actor properties. What I have done in the past with Foundry and other VTTs is refer to B558 in advance or in the moment to decide what my walls are made of, then determine if they were close enough to be blown up by explosion damage, then delete segements/entire walls to let vision through. 

Then you can use a [clever search](site:dundjinni.com explosion) to find some image to use as an explosion tile, or perhaps fire ;)

Seems to work well.

Example:

![Screenshot_20210131_092048](https://user-images.githubusercontent.com/28788713/106392192-a4c41680-63a5-11eb-923b-e9bcb05efc18.png)
