### ISSUE TITLE
GCS Item Values over 1000 are being set to 0

### ISSUE THREAD

**Issue by trev-dev** [crnormand/gurps#229]
Just noticed this after updating to 0.8.9 - any item in the inventory that's worth more than $1000 is being imported at $0. I checked the XML and the numbers are as they should be there.

If I go into the XLM and drop the comma on the thousands separator, the import works fine.

Either GCS needs to avoid inserting commas our the import parser needs to prune them.

**Comment by crnormand** [comment]
Can't beat that... the person who makes the issue, also provides the bug fix!   Thanks!

**Comment by trev-dev** [comment]
At some point a code refactor happened that reversed the fix for this issue.

**Comment by crnormand** [comment]
My bad.   I didn't move the comma check when refactoring.    It as been fixed https://github.com/crnormand/gurps/pull/305
