### ISSUE TITLE
Self Control Rolls [GCS]

### ISSUE THREAD

**Issue by trev-dev** [crnormand/gurps#240]
Looks like SC checks (for traits like Bad Temper or Blood lust) from GCS aren't being parsed into the sheets as "note" macros. 

The SC details are being omitted entirely so we have to go to GCS to reference what number to roll for as well.

**Comment by crnormand** [comment]
Hmmm... that used to work.   Checking....

**Comment by crnormand** [comment]
Found it.   In one of the "cleanups" I did of the export script, I removed on of the Advantage keys, which specifically printed out the modifiers.

I've attached the latest script and I will make a PR for GCS (again... man, I hope Rich doesn't get annoyed with me ;-) ).
[Foundry VTT.zip](https://github.com/crnormand/gurps/files/5900499/Foundry.VTT.zip)
