### ISSUE TITLE
Status Icons

### ISSUE THREAD

**Issue by trev-dev** [crnormand/gurps#242]
I have reached out to R.K. Media with regards to their [status icon](https://marketplace.roll20.net/browse/markerset/5809/rpg-condition-markers) package that I paid for while using Roll20. I figure these would be a great, easy drop-in upgrade for our current status icons.

R.K. Media has agreed to let us use them for the project provided that:
1. They're given credit for their work
2. The project remains free for everyone to enjoy at no cost
3. To be in touch with him if #2 ever changes

I would be _happy_ to do the work to implement these icons. What do you guys think?

**Comment by crnormand** [comment]
What?!?!?   You don't like the icons I literally spent whole minutes searching for on the interwebs?  

I would be fine with it.   And actually, I think that could be a good system setting.   Keep the current set, and then allow the user (I think it would be a client side setting) to pick which icon set they want to use.   

Not that I think the original icons are anything to write home about... but rather, we might get more contributions of icon sets and/or, it would make it easier for a module to extend and add even more if there was some kind of framework.

Thoughts?

**Comment by trev-dev** [comment]
No offense bossmang, but I think the suggested set is clean and uniform ❤️ 

I'll update our icons and would love to look at making this an extensible feature/setting

**Comment by crnormand** [comment]
BTW, as you get to know me, you will learn that I am overly sarcastic and try to be funny way too often ;-) 

I love their icons, and I really appreciate you asking them if we could use them.   Just let me know how I need to acknowledge their work, and I will do it.

**Comment by trev-dev** [comment]
The artist would like credit in the README.md and/or anywhere else we feel it's appropriate :)

I have submitted a list of icon requests as well as they're willing to make them for their pack (and us)

**Comment by TheFabulousIronChef** [comment]
Just checking -- the status icons do not seem to work for me--they just provide black squares on the token. 

I also think it would be helpful to have 14. Prone (that happens a lot) and 15. Unconscious (also true). Right now the only way to take a token out of the initiative order is to declare it "dead," but that's a little inelegant and the skull overlay is somewhat confusing for the players if the enemy is just KO'd.

**Comment by trev-dev** [comment]
I am currently waiting for fulfillment from the artist before I push any code/icons. If you're seeing black squares, that may be a separate issue as I haven't broken anything yet. 

The Icon pack already has Prone/Unconscious :)

**Comment by cefasheli** [comment]
I just replaced the icons change the names one by one.

**Comment by trev-dev** [comment]
@cefasheli That works, though, I would be worried about having things overwritten in updates?

Closing this "issue" for now as I can't recall any missing icons. Whoever needs to re-open this to make a suggestion can do so.
