### ISSUE TITLE
Change the UI weight symbol from lb and Σ lb to a more universal reference.

### ISSUE THREAD

**Issue by gtludwig** [crnormand/gurps#260]
In the equipment container, the weight column header displays lb and Σ lb (see image below).

![image](https://user-images.githubusercontent.com/7466706/106722598-10a0bc00-65fe-11eb-8f40-11150d602bd5.png)

Since we want to look into unit conversion, we could simply replace the lb text with something like:

![image](https://user-images.githubusercontent.com/7466706/106723584-29f63800-65ff-11eb-9f2b-3ea65bb9ea77.png)

**Comment by trev-dev** [comment]
I thought Sigma was mathematical for "summation", I'm not sure how to get more universal than math. Just my (not very helpful) 2 cents.

**Comment by gtludwig** [comment]
@trev-dev you are correct, sir!
The issue is not the sigma, but the "lb".

**Comment by mjeffw** [comment]
file:///var/mobile/Library/SMS/Attachments/ec/12/14A89FE0-3F0C-4AB7-B418-094FB31FB2EA/Image%202-23-21%20at%2012.00%20PM.jpeg

**Comment by mjeffw** [comment]
![Image 2-23-21 at 12 00 PM](https://user-images.githubusercontent.com/7349413/108879459-4ae2f500-75cf-11eb-8036-ce862f0401d4.jpeg)

Done.
