### ISSUE TITLE
Chat rolling maybe broken since 0.8.11

### ISSUE THREAD

**Issue by trev-dev** [crnormand/gurps#267]
Since updating to 0.8.11 we are unable to do the /r /roll command. Screenshot provided by @Onlinemph on Discord, who replicated this issue.

Reference: https://discord.com/channels/228546929494065152/788878698349723669/807120762308919296

![chatrolls](https://user-images.githubusercontent.com/28788713/107071566-bd637080-6799-11eb-8d07-91b800dc37eb.png)

**Comment by crnormand** [comment]
Yep... my bad.   My fancy schmancy chat handler was getting in the way of regular chat messages.  
Fixed in 0.8.12.    It still isn't perfect, but at least now, it stays out of the way if you aren't invoking one of our special commands.
