### ISSUE TITLE
Wiki-ifying Documentation

### ISSUE THREAD

**Issue by trev-dev** [crnormand/gurps#271]
@crnormand has an exhaustive guide for using G4eGA(U):

https://docs.google.com/document/d/1NMBPt9KhA9aGG1_kZxyk8ncuOKhz9Z6o7vPS8JcjdWc

Wouldn't it be nice :tm: if this were a wiki instead? Github supports them, we could always deploy our own elsewhere too, there are many affordable/free options.

Suggestion only :)

Discuss?

**Comment by crnormand** [comment]
No need to discuss.   I'm all for wikis.   It just wasn't the first thing that came to my mind as I started documenting.    I will look into as soon as I can.

**Comment by trev-dev** [comment]
I can help if this is an approval, just another way to keep familiarizing myself with the project more.

**Comment by crnormand** [comment]
Approved.  Do I need to do anything to start it?  Does it work like PRs, or can anyone edit it?  I know nothing.

**Comment by trev-dev** [comment]
Oddly enough never used Github's built in wiki system, but it's just sitting there waiting for us. Let me look into getting it started and I'll connect with you on Discord.

**Comment by crnormand** [comment]
I've changed my mind.... I am going to stick with the Google DOC, but also export to PDF (to a well known location).    Having the ability to automatically attempt to translate the document is just too good to pass up.

**Comment by trev-dev** [comment]
For what it's worth Google Translate is built into Chrome and there may be other extensions that translate websites in general.

**Comment by crnormand** [comment]
Agreed.  But the advantage to the Google doc method is that someone can make an automatic translation of the doc (say to Portuguese), and then go in and manually edit their Portuguese copy where the automatic translation didn't quite make sense.    I was hoping that someday (when the doc gets "close" to being finished), Gus might go through and take an editorial pass through a Portuguese version and then post it to the Brazilian GURPS group.

You don't get that as easily if you always just rely on an automatic translation.
