### ISSUE TITLE
[Feature Request] Apply damage dialog should have an option to apply the damage multiple times

### ISSUE THREAD

**Issue by woefulhc** [crnormand/gurps#273]
For high RoF (greater than 1) weapons, the apply damage dialog should allow the option to apply the damage several times

**Comment by trev-dev** [comment]
You mean you _don't_ want to roll damage separate for each hit on a margin of 6 and a recoil of 1? :laughing:

**Comment by woefulhc** [comment]
in today's game it was margin of 14 rof 10 and rcl 1...

**Comment by crnormand** [comment]
This is a hack, and I know Nick will hate it :-), but we could keep the Damage Dialog open if you press the SHIFT key when clicking on the Apply buttons (sorry Nick).

Quick, simple, effective (for those that know the magic keyboard combination).   Would that work for you Woeful?  (at least in the shortterm?)

**Comment by woefulhc** [comment]
While I recognize it as a hack, it would address my immediate pain. :) My fantasy is that it pay attention to the number of hits from a rapid fire weapon, but I can see too many ways for that to go wrong.... The hack seems like it may be more generally applicable than my initial thoughts about how it could/should work.

**Comment by crnormand** [comment]
And while I like to tease Nick about my hacks, he has a valid point.   If we want this feature to be used, it would be better if we could figure out a visual cue.   Hiding it on a shift key means that only you will know how to do it 😳

So I'm am leaving this open until we can do that.

**Comment by woefulhc** [comment]
I have no idea on the level of effort involved in this but.... maybe if we could drag the hit result (which says potential of X hits based skill and rcl) onto the ADD it could then give a spinner to allow reducing from that number for dodging or other defenses.

**Comment by mjeffw** [comment]
Do you really want the same damage applied X times, or X number of damage rolls?

**Comment by dv-extrarius** [comment]
> Do you really want the same damage applied X times, or X number of damage rolls?

Somebody with gunslinger and ultra-tech weapons can get a _lot_ of hits at close range. Rolling damage 30 times (without miscounting) then the GM having to do their part to apply each roll seems like way too much work when you want to keep the game going. Maybe you could add some kind of "multi-roll" command (that would have to be used manually since the button won't know how many things hit) that would make one dragable box, but I'd be fine with a multiplier box when applying damage.

**Comment by woefulhc** [comment]
The specific instance which lead to me filing the feature request was a high skill shooter with a laser rifle (RoF 10, 6d (2) burn, rcl 1) making their to hit roll by more than 10. The though of him hitting the 6d on the sheet 10x and then manually applying each sounds unfun (and is not what I've have done when at a physical table). 

I think an ideal solution would allow for either multiple hits from a high rof weapon to be rolled individually but applied as a group or allow for a single roll to be applied multiple times. I think the second of those would be easier to implement and would  suit how many actually run an encounter when many hits are scored with a high damage, high RoF weapon. I would lean much more towards rolling multiple times for lower damage weapons (1 or 2 dice) as they have much less of a central tendency than weapons with 5+ dice of damage.

**Comment by trev-dev** [comment]
> I think an ideal solution would allow for either multiple hits from a high rof weapon to be rolled individually but applied as a group or allow for a single roll to be applied multiple times. I think the second of those would be easier.

The only problem with the second option is that it isn't _really_ representative of the intended damage outcome. One roll, low or high, wrecks the variance between hits and the overall average damage. Especially when taking DR into account (which we would need to inflate by the number of hits as well).

**Comment by mjeffw** [comment]
@dv-extrarius @woefulhc @trev-dev 

What if we do this?

The weapon skill roll already calculates total number of potential hits:
![image](https://user-images.githubusercontent.com/7349413/107287330-ce2d1400-6a2f-11eb-8797-0a099375bb83.png)

The GM makes a note of that number. Then he right-clicks on the damage roll, and this pops up:
![image](https://user-images.githubusercontent.com/7349413/107287434-f3ba1d80-6a2f-11eb-8b4b-ab74729663ef.png)

If he selects "Send roll to..." then the current functionality is triggered:
![image](https://user-images.githubusercontent.com/7349413/107287697-4e537980-6a30-11eb-8f78-e013b6ee8398.png)

If he chooses "Multiple rolls" then the damage is resolved for every hit and combined into one chat message, like this:
![image](https://user-images.githubusercontent.com/7349413/107287813-77740a00-6a30-11eb-814a-3b7708592953.png)

Picking up the "All" segment and dropping it on the target actor applies all (4, in this case) hits.

Not prototyped: Change the ADD to show the list of damage rolls to apply:

At the top of the ADD:
"Apply [2, 2, 3, 4] points of imp damage to Bjorn Bjornsson"

In the "CALCULATION & RESULTS" section, I'd show all (4) results by having a pagination widget, similar to this:

![image](https://user-images.githubusercontent.com/7349413/107287870-8fe42480-6a30-11eb-974e-e15a9f188016.png)

Clicking on each entry would show the results for a specific damage roll.

Finally, I'd have a new button on the bottom right, that does "Apply All" to the target.

**Comment by crnormand** [comment]
And Apply All Quietly?

BTW, I love it!

**Comment by woefulhc** [comment]
that looks great!

**Comment by dv-extrarius** [comment]
It looks good, but it'd be nice if players could roll their own damage. Maybe if a player right clicks, they get the dialog with just the option for multiple rolls?

**Comment by mjeffw** [comment]
Good idea! I'll add that.

**Comment by mjeffw** [comment]
@crnormand said:
> And while I like to tease Nick about my hacks, he has a valid point. If we want this feature to be used, it would be better if we could figure out a visual cue. Hiding it on a shift key means that only you will know how to do it 😳

> So I'm am leaving this open until we can do that.

We could use a "Split Button" from Bootstrap (see the image below):

![image](https://user-images.githubusercontent.com/7349413/108608182-6feb2400-7393-11eb-813d-db3851fbecb3.png)

Imagine this button says "Apply Damage" instead of "Large Split Button". If you press the part of the button that contains that label, it just does that action.

If you click the part of the button with the down arrow, a menu pops up:

![image](https://user-images.githubusercontent.com/7349413/108608233-a7f26700-7393-11eb-87cf-9a50b21440f9.png)

Here you could put all manner of various qualified actions, such as "apply silently", "apply and keep open", "apply X times" (along with a text field in the popup). @crnormand, would this be sufficient to close this issue?

**Comment by crnormand** [comment]
Sounds good to me!

**Comment by woefulhc** [comment]
I like this approach! It makes it obvious there are other options (and I don't need remember key combos regardless of whether they've been documented or not).

**Comment by mjeffw** [comment]
Implemented:
![Image 2-24-21 at 12 50 PM](https://user-images.githubusercontent.com/7349413/109043312-34a46a00-769f-11eb-9372-8fa551a98fcc.jpeg)
