### ISSUE TITLE
Containers in containers (for skills) get lost

### ISSUE THREAD

**Issue by woefulhc** [crnormand/gurps#274]
If there is a parent item (skill) which has a child item that is also a parent, the import does not maintain the visual relationship between the parent, child and grandchild. See attached screenshots

**Comment by woefulhc** [comment]
Screenshots

![screenshot_from_game_aid](https://user-images.githubusercontent.com/77212217/107129844-a601b180-6885-11eb-99a7-fec3e1cad051.png)
![screenshot_from_gca](https://user-images.githubusercontent.com/77212217/107129845-a601b180-6885-11eb-8db6-eeb5e3b7ebe3.png)

**Comment by crnormand** [comment]
Can you attach the GCA4 file for this character?   The GCA export script "should" be exporting the parent id's (which is all I need to determine if something is contained in something else).  However, I don't fully understand the parent-child relationship in GCA.

**Comment by woefulhc** [comment]
Here is the zipped gca4 file
[stavros_supti.zip](https://github.com/crnormand/gurps/files/5941319/stavros_supti.zip)

**Comment by crnormand** [comment]
Ok, I understand.   I didn't know that GCA could handle parent-child relationship with skills.   My bad.   I only put the code in for Equipment.     It works like a charm when I add it for Skills:
![image](https://user-images.githubusercontent.com/8931036/107263411-b0e84d80-6a0f-11eb-9c12-bda31174ba52.png)

Can you also create parent-child relationships with Spells?   What about Advantages/Disads/Quirks/Perks?   If so, can you create an example for me (I am not the best at GCA4) and I can verify that the export will process them correctly.

**Comment by woefulhc** [comment]
Yes on the advantages. I think so on spells (been a while since I did anything with those). I'll get you a sheet later today.

**Comment by woefulhc** [comment]
[grandchild_testcase.zip](https://github.com/crnormand/gurps/files/5946902/grandchild_testcase.zip)
Sample character with grandchild advantages and spells. It looks like gca has a little problem with displaying the spells, but that might just be the sheet I'm using (using containers on spells makes a little less sense to me than doing so on advantages and skills, but I haven't made characters with spells in 4 years or so).

**Comment by crnormand** [comment]
Looks like Ronnke only every used Ritual Path magic.  The export script (which I stole!) dies horribly on regular Magic spells.    All fixed now.
