### ISSUE TITLE
Installing and activating recommended modules

### ISSUE THREAD

**Issue by gtludwig** [crnormand/gurps#291]
Modules can provide a rather unique experience for GM and players. But it is necessary to install them individually and, in the game, activate them all.

I was wondering if there would be a way to offer GMs along the import system.json a list of modules that would be installed alongside the game aid and automatically activated when the world is created.

**Comment by cefasheli** [comment]
This is complicated. First, some GMs may not want certain modules. Some modules have dependencies and installing many modules at once can give you some conflicts. I as a gm prefer to go testing one by one the modules that best suit to my needs.

**Comment by crnormand** [comment]
I am going to close this, since this seems to be more of a "Foundry" thing, than a "GURPS" thing.
