### ISSUE TITLE
OtF Formulas and Macros: Weird Formatting Error

### ISSUE THREAD

**Issue by TheFabulousIronChef** [crnormand/gurps#309]
OtF formulas work pretty great. I have managed to replicate an error, however, when using one that rolls using this syntax while also having modifiers: [/r [A:*_words_], whether the modifiers are put inside the brackets or already in the modifier bucket, and it only appears to happen with attacks that have multiple words. So, for example:

If I do either /r [-4 Deceptive Attack] and then follow that command with /r [A:*Ebon], or if I do /r [A:*Ebon-4 Deceptive Attack], I will get something that has markup or html formatting (not sure which) in it (see the example in my second post below--I can't replicate it by typing it out). 

Seems to only be affected by multiple word attacks. So when I call for /r [A:Concussion-4 Range] that works fine, but /r [A:"Stone Missile"-4 Range] I get the garbled text.

**Comment by TheFabulousIronChef** [comment]
Aaargh that is not just a parentheses and then a new line in the example above, it is < *then br *then >

**Comment by TheFabulousIronChef** [comment]
Oh boy, there's lots of formatting that didn't get in there. Here's a screenshot:
![Screen Shot 2021-02-16 at 10 21 25 PM](https://user-images.githubusercontent.com/46587602/108151695-50a77a80-70a5-11eb-8efb-fc206165e7b2.png)

**Comment by crnormand** [comment]
Has this disappeared in 0.8.15?   I re-wrote a bunch of this code... and this may, may I say, have been resolved ;-)

**Comment by TheFabulousIronChef** [comment]
Looks like it's fixed, thanks!

**Comment by mjeffw** [comment]
It was fixed with one of my commits. I saw this and fixed it.
