### ISSUE TITLE
Applying 1/2 Move, 1/2 Dodge (and 1/2 ST)

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#314]
@InexplicableVic had a suggestion.   A status that would apply 1/2 move, 1/2 dodge (and 1/2 ST) for 1/3 fatigue or 1/3 HP.

Originally, I didn't want to do this because of the automation aspect.   I didn't want to "automatically" apply 1/2M,D(,ST).    But if we make the GM manually apply the status, all it would do would be to lower those values.    1/2 Move and 1/2 Dodge would be easy enough.   I don't know what we would do with 1/2ST.   Does that affect weapon damage or encumbrance or anything like that?   If not, I guess we could 1/2 ST as well.

One problem is NPCs.   The GM might not want the players to know if the NPC is 1/3 FP or 1/3 HP.    So we might not be able to use the standard Status Effects, and instead, make it some kind of GM only flag that can be set per character.    

Thoughts?

**Comment by TheFabulousIronChef** [comment]
For the most part, 1/2 move and 1/2 dodge come up a lot in combat (it's all part of that fun "death spiral"). And if you have less than 1/3 of your HP *and* less than 1/3 of your FP, you then have 1/4 move and 1/4 dodge. GCS has that built in, IIRC. The ST is really just for ST rolls (like forcing a door, pinning someone), but doesn't lower HP or damage, so that's not as big a deal, and candidly doesn't come up a lot. 

With regard to NPCs--yeah, I can see GMs not wanting players to know that (I don't let them know exactly, but they always have a good idea). I think it could be a status effect, but it could just be something built into the sheet, kind of like how in GCS, if you lower current HP to less than 1/3, it adjusts move and doge (same for FP, and then for both--see below). I have *no idea* how that gets implemented in the code, but it does know to signal death checks at -1x HP, etc., so perhaps it is similar to that function? (Forgive my lack of understanding when it comes to coding).  

![Screen Shot 2021-02-18 at 8 29 21 PM](https://user-images.githubusercontent.com/46587602/108444137-0bf81c80-7228-11eb-8e55-9529211db0d8.png)

![Screen Shot 2021-02-18 at 8 29 29 PM](https://user-images.githubusercontent.com/46587602/108444154-13b7c100-7228-11eb-8746-91ed2a5d97ea.png)

![Screen Shot 2021-02-18 at 8 29 37 PM](https://user-images.githubusercontent.com/46587602/108444162-174b4800-7228-11eb-8f8b-ccd685800606.png)

**Comment by crnormand** [comment]
I don't have an implementation yet, but I was playing around with an interface idea, and I think it could work.   Since 1/3 FP and 1/3 HP are MOSTLY related to combat, we could enhance the combat tracker to add 2 new icons (and only the GM can see these), something like:

![image](https://user-images.githubusercontent.com/8931036/108555721-dc96ed80-72c3-11eb-9b07-47ab915c1e02.png)

Also, we could enhance the character sheet to show icons, which only the GM can see, and they could click on (RED) or leave off (grey) to turn on/off the 1/3 FP or 1/3 HP status.

**Comment by crnormand** [comment]
![Uploading image.png…]()

**Comment by crnormand** [comment]
![image](https://user-images.githubusercontent.com/8931036/108557666-ebcb6a80-72c6-11eb-8eb2-4c6da10b6177.png)

**Comment by gtludwig** [comment]
I get the "get-that-automation-outta-here!" approach.

I can't say about Fantasy Grounds, but Roll20 applies 1/2 move, 1/2 dodge (and 1/2 ST) for 1/3 fatigue or 1/3 HP.

Maybe it would be something the GM would apply via a `/you-are-busted <actor>` function?

**Comment by trev-dev** [comment]
I personally liked this idea enough to write it into my last "system" for maptool directly. As much as I think it's a good idea, it is opinionated in the sense that all of the GURPS rules are optional. Other GMs may not want to use that rule and an automatic thing will obfuscate the numbers they're hoping to find.

So yes, this feature is a good idea, but there should be some sort of "opt-out" option somewhere.

>  I don't know what we would do with 1/2ST. Does that affect weapon damage or encumbrance or anything like that? If not, I guess we could 1/2 ST as well.

@crnormand I _think_ the strength penalty is just for lifting/strength contests, but I may be wrong about that.

**Comment by crnormand** [comment]
Sorry, I didn't explain it well (and the pictures implied more than they should).   The "Opt-Out" options are the icons themselves.   

Until we are allowed to do the automation... the GM will have the manually click the icons to enable the 1/2 Move/Dodge, etc.    If/when we are allowed to automate this, I would add a system setting to allow the GM to control how it works.   

But my proposal is completely manual.   I just placed the icons in the HP and FP condition fields since there was some room, and it could be a gentle reminder to the GM (as the condition background changes from green to cyan and others), the "heart" icon will stay gray, until the GM clicks on it.
![image](https://user-images.githubusercontent.com/8931036/108560081-34385780-72ca-11eb-9ec5-abc30b0826a5.png)

Actually, thinking about it, if the GM turns on one of the options, it will probably display the red icon on the player sheet (but not the gray one).   As a reminder to the player why their move and dodge (and maybe ST) are down.   It would not be clickable by the player... it would just be there as a visual reminder.

**Comment by TheFabulousIronChef** [comment]
@trev-dev I read it as not affecting damage or encumbrance (the person's move is already brought down significantly due the status, so it probably doesn't matter). It would affect ST checks (wrestling, forcing doors, etc.).

**Comment by mjeffw** [comment]
I'm *okay* with this. I would like it if the meaning of the icons were clearer, but I can't think of good, compact, images that say 'tired' or 'reeling'. I say go for it. The icons should have the standard red glow that all buttons do in Foundry when hovered over to indicate that they do something, and there should be a tooltip that says 'Apply 1/2 Move, Dodge, ST' etc.

**Comment by TheFabulousIronChef** [comment]
Wow, I really like these ideas and the implementation. Yeah, clicking on reeling or tired and having that affect move & dodge? That is _really great_. I'd love to see that implemented.

**Comment by crnormand** [comment]
I am about 50% done with this.   But right now, the GM/Owner can click on the grey 'heart' icons in the codition area to turn on/off "Reeling" or "Tired" (or both).   A whisper is sent to the owner to remind them of this fact,  **And when they are on, they pulsate red.**  
 
![recording](https://user-images.githubusercontent.com/8931036/109067342-64159f80-76bc-11eb-930d-6607436521a8.gif)

At some point in a future, I will probably add a system setting to do this automatically (depending on SJG)

**Comment by TheFabulousIronChef** [comment]
Lookin' GOOOOOOOOOOD. Thanks, man.

**Comment by crnormand** [comment]
I've cleaned up the chat message and implemented the feature in the Full and Combat sheets.    https://github.com/crnormand/gurps/pull/338   It doesn't make as much sense in the Simplified or NPC sheet.   If the GM really needs the functionality, they can always switch to the Full sheet.
I am going to investigate if I can actually put it in the combat tracker... the earlier pic was just for show.... the buttons didn't work.

**Comment by crnormand** [comment]
Added buttons to Combat tracker as well.   https://github.com/crnormand/gurps/pull/342.   Closing.
