### ISSUE TITLE
Incorrect maximum HP values of limbs and extremities

### ISSUE THREAD

**Issue by WeirdBread** [crnormand/gurps#317]
Rules say (B421) that limb has to take Injury _over_ HP/2 to become crippled and Extremity has to take Injury _over_ HT/3. But currently, maximum injuries to limbs and extremities are calculated wrong. I guess current formula of Max Injury is HP/2 (or HP/3) rounded down. But it should be HP/2+1 rounded down. For example, character with 10 HP would suffer from crippling injury to the arm if it gets at least 6 Injury to the arm because 5 Injury is not enough as one may think (That example can be seen on the B421). That's because 5 isn't over 10/2, 5 is exactly 10/2.

On the screenshot below Location max should be 6 because 11/2+1=6.5 rounded down to 6.  

![изображение](https://user-images.githubusercontent.com/79375204/108604292-10563e00-73be-11eb-8d26-121d67f829bb.png)

**Comment by mjeffw** [comment]
You're correct, based on my re-reading of the rules. I'll fix the formula and it will be in the next release.

**Comment by mjeffw** [comment]
![image](https://user-images.githubusercontent.com/7349413/108607958-9f992c80-7391-11eb-8f46-87f8608c9794.png)
