### ISSUE TITLE
Parse input from NPC Generator

### ISSUE THREAD

**Issue by MikeHinds42** [crnormand/gurps#319]
is there any plan for mook to parse the output of  Gurps NPC Generator  (http://ayinger.no-ip.info/NPCGen/NPCGen) it can output in text format ?
ie
Human Archer: Peter Denk                147.5 points

sex: male                     age: 25                       nationality: Human
hair: sandy-blonde            height: 6'2"                  tech-level: 3
eyes: blue                    weight: 186lbs.               genre: fantasy

STATS _______________________ SECONDARY STATS __________________________________________
strength: 13                  hit-points: 13                will: 12
dexterity: 13                 fatigue: 10                   vision: 11
intelligence: 11              speed: 6.0                    hearing: 12
health: 9                     move [enc]: 6[4]              taste-smell: 11

ADVANTAGES __________________ DISADVANTAGES _______________ QUIRKS _____________________
combat-reflexes               bad-smell                     always lies about urban legends
fit: 1                        compulsive-wackiness: 1       indifferent about siege engines
                              pyromania                     really obsessed with elves
                                                            really terrified of hot weather
                                                            wants to love being called ugly

SKILLS _________________________________________________________________________________
axe-mace: 13                  first-aid: 10                 short-sword: 14
bow: 14                       hobby:kite-flying: 10         spear: 14
brawling: 13                  knife: 13                     stealth: 14
broad-sword: 13               law:contractual: 9            tactics: 10
camouflage: 10                pick-pocket: 13               two-hand-sword: 11
climbing: 12                  shield: 13                    

COMBAT _________________________________________________________________________________
-] encumbrance: Medium [2](78lbs)  carrying 58.26lbs (43.5lbs armor, 14.76lbs weapons)
-] dodge [enc]: 10[8]   block: 10  parry: (broad-sword)10 (brawling)10   base-dr: 0
-> damage: th 1d+0, sw 2d-1      punch:  th 1d-1  kick: th 1d+1 

Weapons/Equipment ______________________________________________________________________
Composite bow              damage: th 2d-1, sw -  ss:14 acc:3 rof:1/3 st:10 ammo:23
Large Knife                damage: th 1d+0, sw 2d-3  st:-  rch:c,1 note: max dam 1d+2
Scramsax                   damage: th -, sw 2d+1  st:11 rch:1 note: U, no thrust
Small Knife/Dagger         damage: th 1d-1, sw 2d-4  st:-  rch:c,1 note: max dam 1d+1
Torch(es)                  quantity:3 note: lasts 1hr each

ARMOR __________________________________________________________________________________
Buckler                    db:1 dr:3 area:shield-arm weight:2lbs note: [1hit/hp] 5/20
Light Chain Mail Armor     db:0 dr:4/1 area:body  weight:39lbs
Leather Helm               db:0 dr:2/1 area:head  weight:1lbs
Soft Leather Boots         db:0 dr:2/0 area:feet  weight:1.5lbs

**Comment by crnormand** [comment]
Unfortunately, no.   There are too many differences from the "standard" stat block.    The stat block parser is a huge collection of special cases and guesses, where the order of of the data is rather important.

To be able to parse this, we would have to create a new parser, one specifically designed to look for data in this order.    I won't close this issue, since there is always the possibility that we will have time to do just that.   But it won't happen in the near future.

**Comment by mjeffw** [comment]
As a stop gap, perhaps we can allow the user to define macros that work on the current raw import text of the Mook generator? That way they can define macros to do text substitutions, etc, to pre-sanitize the text.
