### ISSUE TITLE
[Feature Request] Floating skills to different attributes in OtF formulas

### ISSUE THREAD

**Issue by Exxar** [crnormand/gurps#322]
A lot of games float skills to different attributes using the relative skill level, for example Traps is IQ/A by default and you roll it like that for disarming traps, but base it on Per instead for detecting traps. OtF formula support for this would be nice.

**Comment by mjeffw** [comment]
I propose using the modifier description to do this. The 'formula' for a skill roll OtF is:

[S:\<skill-name\>\<optional-modifier\> \<description\>

**Comment by Exxar** [comment]
Looks good

**Comment by mjeffw** [comment]
![Image 3-1-21 at 3 11 PM](https://user-images.githubusercontent.com/7349413/109553323-e3321b80-7aa0-11eb-8d26-1b39ed91f276.jpeg)

**Comment by Exxar** [comment]
Awesome!
