### ISSUE TITLE
Bucket could be activated only by click 

### ISSUE THREAD

**Issue by cefasheli** [crnormand/gurps#324]
We are having a small issue in our table. Sometimes when e pass the mouse over the bucket he opens without we really need to open it. My suggestion is make the bucket be clickable. Some people use laptops without mouse so they are always stumbling on the bucket... 

I don't know if you can understand me Chriss, my english is terrible but i'm trying! 

cheers

**Comment by mjeffw** [comment]
You can change the Modifier Bucket to be displayed only on a click by opening the System Settings and selecting "Show Modifier Tooltip."

Você pode alterar o Modifier Bucket para ser exibido apenas com um clique, abrindo as Configurações do Sistema e selecionando "Show Modifier Tooltip".
