### ISSUE TITLE
My feedback

### ISSUE THREAD

**Issue by cefasheli** [crnormand/gurps#325]
@gtludwig  can you help me with the translation? 

Um feedback sobre o Gurps Game Aid. 

Eu mestro quatro mesas no Foundry/Gurps Game Aid: Japão, Napoleão, Fantasia e viagem no tempo, já mestrei supers. Apenas digo isso para demonstrar que tive necessidades variadas do sistema

O Bucket é uma ferramenta excelente e fundamental, mas coisas poderiam mudar. 
Ele deveria ser clicável e não acionado quando alguém passa o mouse por cima, as vezes a pessoa esbarra e é chato ter que ficar fechando. Quando o Foundry está muito lento devido às coisas carregadas isso acontece muito ou quando alguém está usando uma resolução fora do comum e ou está indo clicar nas macros. 

Tivemos muita necessidade de usar barra de condições, mas as figuras não batiam com as nossa necessidades então tivemos que trocar as figurinhas para nos atender, talvez um meio mais natural de trocá-las seria legal.

Ficha

A ficha tem o problema conhecido que foi bem explicado aqui nesse site sobre as dificuldades, eu entendo isso. A minha sugestão para ela é ter um campo para inserir dinheiro (Não precisa fazer nenhum cálculo). Abrir ficha e rolar até as notas é meio chato.

Itens 

Eu entendo que ainda não tem integração para o game aid mas seria interessante que a gente pudesse criar ali uma lista de itens com lugar para colocar os status das armas manualmente, sem nenhum cálculo. Talvez pudesse ser um formato de ficha onde só mostrasse o campo de armas. Isso seria útil para o mestre criar uma lista de armas disponíveis para os jogadores sem precisar de criar uma library no GCS pra isso, atualmente eu uso um personagem para gaurdar essas informações.

**Comment by mjeffw** [comment]
Using Google Translate, I can understand most of this.

Responses to specific feedback:

>Bucket is an excellent and fundamental tool, but things could change.
It should be clickable and not triggered when someone passes the mouse over it, sometimes the person bumps and it is annoying to have to keep closing.
>O Bucket é uma ferramenta excelente e fundamental, mas coisas poderiam mudar.
Ele deveria ser clicável e não acionado quando alguém passa o mouse por cima, as vezes a pessoa esbarra e é chato ter que ficar fechando. 

You can change the Modifier Bucket to be displayed only on a click by opening the System Settings and selecting "Show Modifier Tooltip."

Você pode alterar o Modifier Bucket para ser exibido apenas com um clique, abrindo as Configurações do Sistema e selecionando "Show Modifier Tooltip".

>We had a great need to use the conditions bar, but the figures did not match our needs, so we had to change the stickers to suit us, maybe a more natural way of changing them would be nice.

>Tivemos muita necessidade de usar barra de condições, mas as figuras não batiam com as nossa necessidades então tivemos que trocar as figurinhas para nos atender, talvez um meio mais natural de trocá-las seria legal.

What conditions did you need that do not exist? Or was it just personal preferences of which icons to use?

Que condições você precisava que não existiam? Ou eram apenas preferências pessoais de quais ícones usar?

> A ficha tem o problema conhecido que foi bem explicado aqui nesse site sobre as dificuldades, eu entendo isso. A minha sugestão para ela é ter um campo para inserir dinheiro (Não precisa fazer nenhum cálculo). Abrir ficha e rolar até as notas é meio chato.

I don't understand -- perhaps @gtludwig can help here.

Não entendo - talvez @gtludwig possa ajudar aqui.

> Eu entendo que ainda não tem integração para o game aid mas seria interessante que a gente pudesse criar ali uma lista de itens com lugar para colocar os status das armas manualmente, sem nenhum cálculo. Talvez pudesse ser um formato de ficha onde só mostrasse o campo de armas. Isso seria útil para o mestre criar uma lista de armas disponíveis para os jogadores sem precisar de criar uma library no GCS pra isso, atualmente eu uso um personagem para gaurdar essas informações.

>I understand that there is still no integration for the game aid, but it would be interesting if we could create a list of items there with a place to place the weapon status manually, without any calculation. Maybe it could be a card format where it only showed the weapons field. This would be useful for the GM to create a list of weapons available to players without having to create a library in the GCS for that, currently I use a character to keep this information.

Agreed! I will talk with @crnormand about this and see what we can do.

Acordado! Vou falar com @crnormand sobre isso e ver o que podemos fazer.

**Comment by gtludwig** [comment]
@mjeffw,

> A ficha tem o problema conhecido que foi bem explicado aqui nesse site sobre as dificuldades, eu entendo isso. A minha sugestão para ela é ter um campo para inserir dinheiro (Não precisa fazer nenhum cálculo). Abrir ficha e rolar até as notas é meio chato.

This is a suggestion to put a link to the notes section somewhere it would make access to it a bit easier. He mentioned that opening the character sheet and scrolling to the notes section is annoying. This section could be used for a no-calculations money tracker.

Because the sheet can be minimized by double-clicking the title, can we put a link there to the notes section?

**Comment by cefasheli** [comment]
Using Google Translation

Thank you guys, I'm happy to be heard.

My suggestion is that the user can change the figures easily.

The user and the players determine what is easy for them to understand. Some condition markers were needed on my desk, in my time travel campaign I needed a seasickness marker and another for time travel sickness, these are two different things for us. I remember having a marker for "stuck in the ground", "slow" etc.

I also know that money is an equipment and that rolling the sheet down is no big effort but people want comfort and quick viewing.

Regarding the items, although it is not allowed by the foundry and we do not use all of its functionality, could be  interesting to have a place so that we could put some items there and the player could copy it to their sheets.As I said in the discord, I run a campaign that needs to modify the list of equipment a lot and if I give the player the option to choose what he wants in the book this will cause problems. Maybe that place could import a GCS sheet and just show the equipment part.

E eu estou fazendo uns videos para a comunidade no brazil sobre foundry espero poder ajudar mais gente que tenha mais dificuldade com a língua do que eu.

**Comment by mjeffw** [comment]
I understand your desire to either add new conditions, or easily replace existing condition icons. Let me open a feature request for this and @crnormand and I will investigate how to do that.

Compreendo seu desejo de adicionar novas condições ou substituir facilmente os ícones de condições existentes. Deixe-me abrir uma solicitação de recurso para isso e @crnormand e investigarei como fazer isso.

**Comment by mjeffw** [comment]
> A ficha tem o problema conhecido que foi bem explicado aqui nesse site sobre as dificuldades, eu entendo isso. A minha sugestão para ela é ter um campo para inserir dinheiro (Não precisa fazer nenhum cálculo). Abrir ficha e rolar até as notas é meio chato.
> 
> This is a suggestion to put a link to the notes section somewhere it would make access to it a bit easier. He mentioned that opening the character sheet and scrolling to the notes section is annoying. This section could be used for a no-calculations money tracker.
> 
> Because the sheet can be minimized by double-clicking the title, can we put a link there to the notes section?

New issue created/
Novo problema criado: #327

**Comment by cefasheli** [comment]
Ty for answering!

**Comment by mjeffw** [comment]
> Eu entendo que ainda não tem integração para o game aid mas seria interessante que a gente pudesse criar ali uma lista de itens com lugar para colocar os status das armas manualmente, sem nenhum cálculo. Talvez pudesse ser um formato de ficha onde só mostrasse o campo de armas. Isso seria útil para o mestre criar uma lista de armas disponíveis para os jogadores sem precisar de criar uma library no GCS pra isso, atualmente eu uso um personagem para gaurdar essas informações.

> I understand that there is still no integration for the game aid, but it would be interesting if we could create a list of items there with a place to place the weapon status manually, without any calculation. Maybe it could be a card format where it only showed the weapons field. This would be useful for the GM to create a list of weapons available to players without having to create a library in the GCS for that, currently I use a character to keep this information.

New issue created/
Novo problema criado: #328

**Comment by mjeffw** [comment]
Since I've opened other issues for each of these suggestions I am closing this one.
