### ISSUE TITLE
[Feature Request] Quickly open the Notes area of the actor sheet

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#327]
From @cefasheli:

> This is a suggestion to put a link to the notes section somewhere it would make access to it a bit easier. He mentioned that opening the character sheet and scrolling to the notes section is annoying. This section could be used for a no-calculations money tracker.

**Comment by crnormand** [comment]
I had this in the Users Guide TODO list:   

Add “Combat Notes” display under Melee/Ranged.

Which is sort of the same concept.    The user wants to have a place where they can enter OtF formulas near the top of the character sheet, so they don't have to scroll down to the notes section.

The reason why I suggested adding a separate notes section is that some players use the Notes to capture a LOT of information (I've seen one character with 20+ notes... about 3 pages), and moving the whole Notes section to the top of the character sheet just means that all of the other useful stuff is now scrolled to the bottom of the sheet.

What if we allow the display of a single Note neat the top of the character sheet (culled from the complete list of Notes).   We could look for a specific string, like "Combat Notes", so it could be created in GCA/GCS and if we detect the "magic string", we display it near the top.

**Comment by mjeffw** [comment]
I'm adding a navigation bar to the full character sheet that allows quick access to any of the sections. Whether or not we add a combat notes section, I would consider this issue solved on the next release.
