### ISSUE TITLE
Token "Quick" actions (feature)

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#330]
Can we provide "actions" that a player can perform when working with a character's token so that they don't have to open the whole character sheet?

For example:  
Roll an Attack Skill
Roll Dodge (or Parry)

I am not certain how we would present them...   maybe as a pulldown list in between the Target symbol and the Combat symbol on the token context menu.

**Comment by cefasheli** [comment]
It could be a few floating buttons and the player could move where he wanted or take up space in the macro bars. Many players do not use macros for lack of interest in understanding how they work.

**Comment by cefasheli** [comment]
Something like shift+ click and open floating buttons and each button is a configurable action maybe setted my own player.

**Comment by cirelli** [comment]
it would be amazing if we could just drag a roll from the sheet to the hotbar

**Comment by mjeffw** [comment]
You will be able to drag rolls from the character sheet onto the macro bar in the next release.

**Comment by crnormand** [comment]
Closing since this functionality is provided by Token Action HUD
