### ISSUE TITLE
Allow player to drag and drop damage to token

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#331]
To help the GM, could we allow a player to roll damage, and then drag and drop the damage onto their intended target.

The ADD would appear on the GM's screen (not the player's), and the GM would still have to "apply" the damage.    This would just reduce the inevitable confusion when players are fighting multiple targets

"I hit the goblin"
"Is that goblin #1?"
"I don't know, it is the one at the top"
"The top one is #3"
"No, not at the top of the screen, the one on top of the barrel"
"Oh, that's not a goblin..."

To do this, we would have to (finally) implement a client server framework using the sockets.   And if we do this, I definitely want to rewrite the Modifier Send Bucket functionality to use the socket.

**Comment by crnormand** [comment]
I had another thought (along the lines of trying to help the GM).    It should be much easier to implement.

If a player makes an attack roll (and we can tell because they clicked on an attack skill column in melee or ranged or they executed an Otf formula like [A:name]), AND they have a token targeted (using Foundry targeting system),  could we add "something" to the result chat indicating the possible target?  For example:

![image](https://user-images.githubusercontent.com/8931036/109092052-e2396c80-76e3-11eb-9c5b-2062167b0c4e.png)

And make it a drag target for the damage chat?

If the GM determines that the attack hits, they could drag the damage onto this new chat (or just onto the target icon) and it would bring up the ADD.

We wouldn't force them to select a target, but if they did, we could enhance the chat message, and possibly add this functionality to save the GM some time.   

Jeff, this one is a question for you... I don't have a lot of experience embedding data in a chat message (or handling the drag and drop messages).

**Comment by mjeffw** [comment]
Well you could even give them a button on the chat message that says apply to the targeted character.

**Comment by mjeffw** [comment]
I think this is doable. We'd need to store the target actor's ID in the chat message, probably in an attribute (data-value?) of an HTML element. We would have to add a drop handler on the chat message as well, one that accepted the damage chat's data-transfer data (the drag-and-drop damage data). We would then have to get a reference to the actor whose ID is in the chat message, and call the ADD constructor with that actor reference and the damage data.

**Comment by mjeffw** [comment]
Here's another idea: if the player has another token targeted, and makes a damage roll, we put an "Apply to Xxxxx" on the damage chat message, where "Xxxxx" is the name of the targeted token. Then there's no drag-and-dropping at all.

**Comment by crnormand** [comment]
I like it.   Can we make it such that the Apply button only shows to the GM?   And everyone else just sees the damage?

**Comment by cefasheli** [comment]
I like this idea!

**Comment by mjeffw** [comment]
I implemented this yesterday; it should be in the next release. Is that good enough to close this issue?

**Comment by mjeffw** [comment]
The player with character Björn targets a zombie, and rolls damage. This is what he sees in the chat:
![Image 2-26-21 at 5 45 PM](https://user-images.githubusercontent.com/7349413/109392124-65c3ab00-78e8-11eb-833b-bdafcaa36fa9.jpeg)

The GM sees this instead:
![Image 2-26-21 at 5 45 PM](https://user-images.githubusercontent.com/7349413/109392138-7bd16b80-78e8-11eb-8822-8d3d858cbc04.jpeg)

Clicking the "Apply All to Zombie" button on the chat message opens the ADD with the damage applied to the zombie.

**Comment by cefasheli** [comment]
For simple damages rolls is pretty good. But what if the player uses Hit Location?

**Comment by mjeffw** [comment]
I'd like to separate that as a different feature request. It is going to be much harder, because we'll have to associate the weapon skill roll to the damage roll, and also detect if there was a modifier based on hit location.

**Comment by crnormand** [comment]
@Gus discusses another damage scenario in https://github.com/crnormand/gurps/issues/348.

**Comment by crnormand** [comment]
> The work-around for now is to use the ADD to manually apply the hit location.

Yeah, I wasn't going to go that far.   Remembering hit locations based on the modifiers applied to a roll are just a bit too much automation.     I am perfectly fine with the GM having to do that work manually.

**Comment by cefasheli** [comment]
I'm wondering if this is really good. Speed ​​is not always our best ally, but quality is. As a master I prefer to control all damage variables to aply and not let the player do that.
If the player does this, the gamemaster will have two jobs instead of one. First inform the all the  modifiers and second check if the modifiers are right. In addition, he will have to give information that maybe he didn’t want to give, such as DR, HP

**Comment by crnormand** [comment]
Agreed.    The GM is still the only person that can Apply Damage.     We are just discussing ways that the Player can help the GM when trying to resolve damage in an attack.   @mjeffw implemented a nice feature that will save the GM some time (and possible miscommunication), and that is all we were asking for.

**Comment by cefasheli** [comment]
Sure!

**Comment by gus** [comment]
> @gus discusses another damage scenario in #348.

Wrong Gus, but without any context, definitely a fun thread :)

**Comment by crnormand** [comment]
LOL, sorry about that.   I forget that Github has its own @ notation.     You don't happen to play roleplaying games?

**Comment by gus** [comment]
> LOL, sorry about that. I forget that Github has its own @ notation. You don't happen to play roleplaying games?

No worries. And no, don't play any, but not for any reason I can think of. I guess I just haven't.

**Comment by crnormand** [comment]
I'm good with our current implementation, so I am going to close this.
