### ISSUE TITLE
More Chat command ideas

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#334]
To help people "macro" their character, I am just brainstorming some ideas for new chat commands to:

Increment/decrement trackers
Increment/decrement FP/HP
Reset FP/HP to max
Set encumbrance level (if "automatic encumbrance is turned off)
Increment/decrement quantity (Qty) on equipment
Increment/decrement Uses  on equipment
Equip/unequip equipment

GM only:
/sendmb [+1 aim & -2 darkness] <player>
Update the /sendmb command to send the OtF modifier to all (or a specific player), instead of forcing the GM to set their own MB, and then send it.

**Comment by cefasheli** [comment]
OtF macros are amazing but my players just don't use them. They believe it is difficult and complicated (it is not a joke). I have at least 10 players and none of them were interested in looking at the document that teaches how to make macros. Ideally, GM should be able to create and send ready-made macros. I don't know if it make sense to you. Could be better something like: DRAG THiS TO YOUR BAR AND JUST CLICK ON IT! lol

**Comment by crnormand** [comment]
We don't have the ability to send macros to the chat... since that would just execute the macro ;-), but you can "GM Send" an On-the-Fly formula...  maybe that would be enough?    

We describe it in the Users Guide, here:  https://docs.google.com/document/d/1NMBPt9KhA9aGG1_kZxyk8ncuOKhz9Z6o7vPS8JcjdWc/edit#heading=h.byo9169m97u7

Basically, you right mouse click on ANY rollable item or On-the-Fly formula), and you will be asked who you want to send it to.

![image](https://user-images.githubusercontent.com/8931036/109312976-adc5cd80-7815-11eb-81bc-65b27046b7a5.png)

You can create Journal entries with On-the-Fly formulas, and send them to your players whenever you want.   Here I have right clicked on 1d+3 healing (from my OtF Testcases Journal entry:

![image](https://user-images.githubusercontent.com/8931036/109313260-02694880-7816-11eb-8dcc-148771c8cd6b.png)

**Comment by cefasheli** [comment]
i'll try to explain better to Gus in portuguese so he can explain to you.

**Comment by crnormand** [comment]
As of https://github.com/crnormand/gurps/pull/350 we now support a single line "/sendmb":

`/sendmb [+1 aim & -2 darkness] `

Replacing:
```
/clearmb
/r [+1 aim & -2 darkness] 
/sendmb
```

**Comment by gtludwig** [comment]
This is nifty!

**Comment by crnormand** [comment]
More commands implemented:
/hp +/-X
/fp reset

https://github.com/crnormand/gurps/pull/353

**Comment by crnormand** [comment]
/tracker0 +/-/=X
/tr1 reset
/rt2     "resource tracker"
We support 0-3

**Comment by mjeffw** [comment]
> /tracker0 +/-/=X
> 
> /tr1 reset
> 
> /rt2     "resource tracker"
> 
> We support 0-3

We should also support identifying the tracker by name if it has one. E.g., 

/tr(Arrows) -1

**Comment by crnormand** [comment]
Good idea.  https://github.com/crnormand/gurps/pull/366

**Comment by crnormand** [comment]
Added `/status on|off|+|-|t|toggle <status name>` to apply statuses to the SELECTED TOKENS.    You must have tokens selected for this to work.

**Comment by crnormand** [comment]
Added /uses +/-/=X Equipment
And @self to /status (uses GURPS.LastActor)

**Comment by crnormand** [comment]
Added
/select ActorName
/status clear
