### ISSUE TITLE
Adding Shotgun Calculator to the current Damage Calculator

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#336]
I would like to request adding a shotgun calculator from the book page B409 to the current calculator.

**Comment by mjeffw** [comment]
I could add a checkbox for "Shotgun, extremely close" and if checked asked the user for the multiplier ("9", in RoF 3x9). Then multiply damage and DR by (multiplier / 2).

**Comment by mjeffw** [comment]
![Image 2-24-21 at 3 29 PM](https://user-images.githubusercontent.com/7349413/109081150-ce840b00-76cf-11eb-8664-5ab712b02fbb.jpeg)

![Image 2-24-21 at 5 57 PM (1)](https://user-images.githubusercontent.com/7349413/109081157-d3e15580-76cf-11eb-9329-0d16ee4d121a.jpeg)

Done.
