### ISSUE TITLE
Odd behaviour with HP tracker input field

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#339]
If the character has 17 HP, and you enter -10 in the input field (not using one of the quick buttons... but just typing it in to the input field), and you TAB away, it is set to -10.    If you press Enter instead, you get 16.

If the character has 17 HP, and you enter 15 in the input field (not using one of the quick buttons... but just typing it in to the input field), and you TAB away, it is set to 15.    If you press Enter instead, you get 16.

If you just click into the HP input field, and press Enter, it subtracts one from the number.

**Comment by mjeffw** [comment]
It's even weirder than you know. On the Combat sheet, if I hit Enter on the Fatigue field, it subtracts one from the HIT POINTS field. I'm looking.

**Comment by mjeffw** [comment]
I had no idea what was going on. It is fixed by disabling the Enter key from the resource tracker text input fields.
