### ISSUE TITLE
Conditional Otf checks

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#352]
@mjeffw: I would like a way to send everyone an OtF skill or attribute check, and if successful, whisper to the player some text. E.g.: Send a blind Perception check, and if successful send this whisper: "You catch a glimpse of a figure ducking behind the doorway."

It would have to be embedded in the OtF formula itself... just because we only care about stuff surrounded by square brackets, so, it could be something like:

[!PER @"You catch a glimpse of a figure ducking behind the doorway", "You see nothing"]

I'm not married to that format, and the second string could be optional... it is just the "false" case.

**Comment by mjeffw** [comment]
I like it! And I like having something for the false case.

**Comment by crnormand** [comment]
After thinking about it, I think the format will be:

[!Per | !IQ-6 ?"true text", "false"]

Or 

[!Per ?"true text", "false" | !IQ-6 ?"true2", "false2]

You only need one true text.  The false test is optional.   

But if you want different responses depending on which attribute/skill Works, we should be able to support it.

**Comment by crnormand** [comment]
Done.  You can use the form:

`[!Per|!IQ-6?"You see something"]`

or (if you like spaces for readability)

`[!Per | !IQ -6 ? "You see something" ]`

And if the character is successful, it shows:
![image](https://user-images.githubusercontent.com/8931036/109601031-31204100-7aec-11eb-9015-2ea2c146f91d.png)
(Unfortunately, I can't seem to get the whisper to come from the GM... so the user whispers to themselves.   diceroll.js line 119 if you know how to fix this.

You can add the false case:

`[!Per|!IQ-6 ?"You see something", "You see nothing!"]`

or for the Javascript devs out there, we also support ":"

`[!Per|!IQ-6 ?"You see something": "You see nothing!"]`

and with spaces

`[!Per | !IQ -6 ?  "You see something"  : "You see nothing!" ]`

If you have more that one Attribute/Skill check, you can give different positive and negative responses:

`[!Per ? "You sense something" : "You sense nothing" | !IQ-6 ?"You know something is there"]`

If the character uses PER (because it is better that IQ-6), then the follow on text will be "You sense something" or "You sense nothing".   But if the character uses IQ-6 (because their perception is total crap), then you will only see the follow on text "You know something is there" if they succeed.

The only other funky thing is that if you have Dice So Nice loaded... the follow on text will "appear" first... 
![image](https://user-images.githubusercontent.com/8931036/109604043-d9d09f80-7af0-11eb-83d7-ed450fa90b8b.png)

but once the Dice are rolled, it is placed in the correct location.    
![image](https://user-images.githubusercontent.com/8931036/109604085-e9e87f00-7af0-11eb-82ab-d0a88674af16.png)
And since that would be a beast to fix... I am going to leave it alone for now.
