### ISSUE TITLE
Perception Checks

### ISSUE THREAD

**Issue by cefasheli** [crnormand/gurps#356]
The check that I do most is the perception checks. For that I would like to suggest a feature that would help GMs a lot. GM click in one button and i new window opens asking:
Vision Hearing taste or smell
For this example we are going to choose vision. The modifiers are presented for the GM to choose.
Accute hearing, Hyperspectral vision with a check box and Distance, darkness or technological device that give bonuses with a field for the GM to insert modifiers.  Apply to bucket...
The modifiers are applied to the bucket and voilá. The modifiers is on B358

**Comment by crnormand** [comment]
This is a specific case of https://github.com/crnormand/gurps/issues/165 (for perception checks), so I am going to close this issue.
Please note that until we can update the Modifier Bucket Tooltip to allow user input, you can always create Journal entries with On-the-Fly formulas, and share it with your players.

For Example:
![image](https://user-images.githubusercontent.com/8931036/109697819-b04d5d80-7b5c-11eb-9012-5dfa6ee0a7a5.png)
Becomes:
![image](https://user-images.githubusercontent.com/8931036/109697890-c6f3b480-7b5c-11eb-9c9b-ddec10825302.png)

And you can use a combination of "Send Modifier Bucket to" (in the Tooltip) and "GM Send" (Right Mouse Click on any On-the-Fly formula to send it to the chat), or chat macros to prepare the correct list of modifiers, send them to your players, and then display a button for the correct skill.

For example:   You want your players to make a Blind Vision roll in total darkness (-10).   One of the players (Bob) has a character with Hyperspectral vision.    In release 0.8.16 (coming very soon), you could create the chat macro:

```
/sendmb [-10 Total Darkness]
/sendmb [-10 Total Darkness & +3 Hyperspectral vision] Bob
[!Vision]
```
This will set everyone's modifier bucket to -10, and then set Bob's modifier bucket to -7 (-10+3) and then show this:
![image](https://user-images.githubusercontent.com/8931036/109698999-04a50d00-7b5e-11eb-9236-197cfd28bcd4.png)
In everyone's chat log.

If you name this macro "Total Darkness check", you can then create an On-the-Fly formula to execute that macro from a button:

`[/:Total Darkness check]`

Becomes:
![image](https://user-images.githubusercontent.com/8931036/109699525-ad536c80-7b5e-11eb-9e33-796992f52470.png)

And when you click on it, it will execute the macro.
