### ISSUE TITLE
[Enhancement] Option to NOT automatically target a token when dropping damage

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#358]
@InexplicableVic
Hello, all. In GURPS Game Aid, after I drag and drop damage from the chat window onto a target and apply the damage, the target is "sticky" and won't release unless I go to the "Select Targets" tool and then click on the target to get rid of it. Any way to make that easier for the GM?

**Comment by crnormand** [comment]
It now remembers what was targeted, saves it, targets the token to drop damage on it, and then resets the targets back to the original set (or none, if nothing was targeted).
