### ISSUE TITLE
[Improvement] Bucket - add reference to modifiers

### ISSUE THREAD

**Issue by gtludwig** [crnormand/gurps#359]
When the bucket modifier is open, it would be handy to place the reference for the modifiers (B365 for Determined Attack).

**Comment by crnormand** [comment]
Nice idea.... want to do it?  ;-)  It is simple:

In the modifiers.js file, line 582+ are some static strings that "feed" that various boxes in the tool tip.
Just append the OtF formula for the PDF page at the end of the string.   For example:

```
const MeleeMods = `[+4 to hit (Determined Attack)] [PDF:B365]
[+4 to hit (Telegraphic Attack)] 
[-2 to hit (Deceptive Attack)] [PDF:B369]
[-4 to hit (Charge Attack) *Max:9] [PDF:B365]
[+2 dmg (Strong Attack)]
${horiz('Extra Effort')}
[+2 dmg (Mighty Blow) *Cost 1FP]
[+0 Heroic Charge *Cost 1FP]`
```
Note, however, that things may not fit (especially as the button is hovered over):
![image](https://user-images.githubusercontent.com/8931036/109713488-48ecd900-7b6f-11eb-99de-3e529f88819a.png)

**Comment by gtludwig** [comment]
Trying my hand at it!

**Comment by crnormand** [comment]
Thanks Gus.   https://github.com/crnormand/gurps/pull/364
