### ISSUE TITLE
navigation footer not working with Google Chrome Version 89.0.4389.82  (64-Bit)

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#382]

**Comment by mjeffw** [comment]
@LordOHelmet ,
I can't recreate this error. I've made a short video to show how the navigation bar should work, and have given some steps to try and help me diagnose the problem.

Video: https://youtu.be/ej9In4zNbpk

Another thing we can try is for me to use the same character you are using for testing. If you are creating this character from a GCS or GCA import, you can send me the exported character data file (the .xml file) and I can test using your character.

**Comment by mjeffw** [comment]
One more thing: Did you have more than one character sheet open? I found a bug where clicking on the navigation footer scrolled a *different* character sheet instead. That is fixed in the next release.
