### ISSUE TITLE
[Feature Request] Allow players to copy OTFs embedded in the sheet

### ISSUE THREAD

**Issue by Exxar** [crnormand/gurps#383]
A player of mine expressed frustration that he can't "drag the parry roll" from the sheet onto his macro bar. It would be great it that were possible, but in a pinch it would also be fine if players could copy such automatically generated OTFs in a similar manner as the GM can by right clicking on a roll on the sheet and then selecting "copy to chat input".

**Comment by crnormand** [comment]
I like this.    Now that we understand drag and drop more, we should be able to implement this for both the GM and the players.   I like to provide multiple ways for doing things, since we never know how the user will interact with our code.

**Comment by crnormand** [comment]
I haven't implemented the drag and drop (that will take a while), but I have implemented the Right Mouse Click action.   If a non-GM right clicks on a button/modifier, it will paste the On-the-Fly formula into the chat input box.

I'll leave this open until I can figure out the drag and drop.

**Comment by mjeffw** [comment]
I implemented the drag-and-drop for embedded OtFs on the character sheet to the macro bar. It does NOT work for text entered into the notes field of an advantage or skill, like '[CR: 12 (Resists often)]'.

**Comment by Exxar** [comment]
Nice, ty!
