### ISSUE TITLE
[Feature Request] Allow ADD to apply damage to resource trackers

### ISSUE THREAD

**Issue by Exxar** [crnormand/gurps#385]
People may use resource trackers for ablative DR, control points in FDG or any other number of uses where it would make sense for damage to be applied to them, so it would be great if we could select resource trackers in addition to HP and FP as the "target" of damage in the ADD.

**Comment by mjeffw** [comment]
If you have checked the "Use as Damage Type" in the Resource tracker template (see https://github.com/crnormand/gurps/issues/386), then you can apply the damage to a resource:

![Image 3-18-21 at 11 38 AM](https://user-images.githubusercontent.com/7349413/111657810-2a7b1480-87e2-11eb-8339-59139ce6d436.jpeg)

![Image 3-18-21 at 11 39 AM](https://user-images.githubusercontent.com/7349413/111657839-31098c00-87e2-11eb-8647-6d74584e0642.jpeg)
