### ISSUE TITLE
A New Feature.

### ISSUE THREAD

**Issue by cefasheli** [crnormand/gurps#407]
I don't know if this should be from GGA or should be in a module but my suggestion is:

A big problem for those who play gurps is knowing where the front and the back of the miniatures are. For this we use something like this:
![teste-de-token](https://user-images.githubusercontent.com/21176804/110988109-dfc74b80-834e-11eb-848c-84ef8c538731.png)

Visually I think that they visually pollute the maps a lot. Would it be possible to show this colored hexagon only when anyone press alt?

**Comment by crnormand** [comment]
Our game aid isn't providing the colored hexagons.

Either the color hexagon is part of the token image, and there is nothing we can do.
Or, it comes from the module About Face, and if so, you should open this issue there:   https://github.com/League-of-Foundry-Developers/about-face

**Comment by cefasheli** [comment]
Sorry for the inconvenience. i Solved doing this

let aName =
'worlds/japao/Tokens%20Samurais/Macros%20com%20bordas/005-a.png';
let bName =
'worlds/japao/Tokens%20Samurais/Macros%20com%20bordas/005-b.png';

let tok = canvas.tokens.controlled[0];
let img = tok.data.img;
img = (img == aName ? bName: aName);
tok.update({ img });

Em sex., 12 de mar. de 2021 às 16:44, Chris Normand <
***@***.***> escreveu:
