### ISSUE TITLE
DR for arms does not appear in game aid

### ISSUE THREAD

**Issue by woefulhc** [crnormand/gurps#409]
DR for arms shows up in the GCS character sheet on 32 lines. However, the imported character sheet it shows on 3 of the 4 lines displayed. Will attach screenshots and source character file

**Comment by woefulhc** [comment]
Source character file
[Sizh'zaia II.zip](https://github.com/crnormand/gurps/files/6136120/Sizh.zaia.II.zip)
GCS screenshot
![gcs_source](https://user-images.githubusercontent.com/77212217/111057861-c48c3700-8447-11eb-9f63-55da84d6309f.png)
game aid screen shot
![game_aid_result](https://user-images.githubusercontent.com/77212217/111057866-cd7d0880-8447-11eb-925b-0600bef5a69f.png)

**Comment by mjeffw** [comment]
Looks like the body parts for snake men did not align with the names used in RAW. I'll look for either "arm" or "left/right arm".

**Comment by mjeffw** [comment]
Fixed! Next release (which is probably tonight).
