### ISSUE TITLE
Importing a character from GCS no longer works in 0.7.5.

### ISSUE THREAD

**Issue by Mobenator** [crnormand/gurps#41]
I have tried to import a character from GCS into foundry.

This exact character was imported successfully in 0.7.4, using the native .gcs file type.

I have tried the fantasy grounds PC export xml as well, which also doesn't work. 

[Colonist.zip](https://github.com/crnormand/gurps/files/5579413/Colonist.zip)

**Comment by mjeffw** [comment]
@crnormand can correct me if I'm mistaken, but we don't import .gcs files directly; only XML files that have been exported from GCS using the Fantasy Grounds PC Export template. @crnormand is adding more import formats, so he can answer to what those are.

In the prerelease of v8.0 I was able to import and open the character from the XML file, so this may be a short term problem until that version is released.

**Comment by crnormand** [comment]
Correct.   We don't import the native GCS file directly.   You must export the file first using an output template.   You can use the Fantasy Grounds PC export, or soon a Foundry VTT specific export will be available.

But this does give me an idea for a feature.   We should be able to detect if someone is trying to import a .gcs file directly and inform the user of the proper procedure.

**Comment by mjeffw** [comment]
@Mobenator -- Make sure you have the correct project. There are currently 2 GURPS projects on FoundryVTT that I'm aware of -- this one and another one here: https://gitlab.com/gurps-foundry

**Comment by Mobenator** [comment]
Thanks for looking into this, I'm definitely importing the xml but I'll wait until the next release to see if that fixes it. Thanks.

**Comment by crnormand** [comment]
> Thanks for looking into this, I'm definitely importing the xml but I'll wait until the next release to see if that fixes it. Thanks.
Feel free to upload the GCS and XML files, and we can take a look at it.
