### ISSUE TITLE
Skills with specializations (text in parens) are not found when the button in chat is pressed

### ISSUE THREAD

**Issue by woefulhc** [crnormand/gurps#410]
When the GM right clicks a skill level and sends a roll request to the specific player or the whole party. It can return "no skill or spell named X (y) was found on $character_name". Skills in containers are found. Skills with TL are found (as long as they lack a specialization). Sample character attached.
[Momoku no neko (Harold).zip](https://github.com/crnormand/gurps/files/6136164/Momoku.no.neko.Harold.zip)

**Comment by crnormand** [comment]
Thanks!    Fixed.   The "(" and ")" in the skill name were confusing the RegEx pattern.   
![image](https://user-images.githubusercontent.com/8931036/111084908-26ea4380-84eb-11eb-894d-227a93fe5fe6.png)
