### ISSUE TITLE
Possible hits not calculating shotgun ROF correctly

### ISSUE THREAD

**Issue by benjaminitz** [crnormand/gurps#411]
Hi, thanks so much for all the work you guys are doing. This project is the best thing that's happened to gurps in a while. Seriously. I was playing with shotguns today, and noticed that the possible hits calculation is using the first ROF number (shots) instead of multiplying shots by pellets. (B409)

![image](https://user-images.githubusercontent.com/80612960/111058469-716cb100-8454-11eb-9764-99357bb56a93.png)

**Comment by mjeffw** [comment]
Thanks for the bug report! This issue was reported earlier and it will be fixed when we release the next version. Thanks for the encouragement!
