### ISSUE TITLE
Feature: Pop out character sheet in separate window

### ISSUE THREAD

**Issue by trev-dev** [crnormand/gurps#413]
One of my players would like to be able to look at their character sheet in another monitor while enjoying the game in their primary monitor. This can be accomplished with the window.open() method while passing the context of the primary window to that new window.

https://www.w3schools.com/jsref/met_win_open.asp

**Comment by cefasheli** [comment]
For this have a module called popout https://github.com/League-of-Foundry-Developers/fvtt-module-popout

**Comment by mjeffw** [comment]
I just tested the PopOut! module mentioned by @cefasheli , above, and it works great. Screenshot below. I'm closing this as unnecessary.

![image](https://user-images.githubusercontent.com/7349413/111914724-9a3f0880-8a49-11eb-9a28-6d9505f3e300.png)
