### ISSUE TITLE
[Bug] Modifier bucket window shows up when not expected to

### ISSUE THREAD

**Issue by WeirdBread** [crnormand/gurps#417]
When I try to use any skillcheck, OtF or macro the modifier bucket shows up automaticly despite it's not expected behavior. This only occurs when "Show Modifier Tooltip on mouse hover" system option is turned off and if I ever tried to roll smth while mod bucket window was opened. Here is the [GIF ](https://drive.google.com/file/d/1lgFB9mTmJqJKBYkX6toFp9y1xsyl3GkX/view?usp=sharing) of the bug

Steps to reproduce:
1. Turn off "Show Modifier Tooltip on mouse hover" option at System Settings
2. Open a char sheet
3. Open the modifier bucket
4. Click on any check or OtF at char sheet
5. Close the modifier bucket
6. Click on any check or OtF at char sheet again

**Comment by crnormand** [comment]
Thanks for the GIF!   That is a beautiful map, by the way.    Yes, I see the issue, and I think I have a fix for it.

**Comment by crnormand** [comment]
Yep, that fixed it.   We will probably make another release tonight (fixing a few bother bugs).   Thank you again for letting us know.
