### ISSUE TITLE
/status command

### ISSUE THREAD

**Issue by cefasheli** [crnormand/gurps#423]
How to use theses status with number  like Shock(1-4),  Tipsy (1-2), Mild Pain(1-6)  and counter(1-10)?

**Comment by crnormand** [comment]
By using the status id.   Ex: /status toggle shock1

The status ids are:
shock1, shock2, shock3, shock4
tipsy, drunk
mild_pain, moderate_pain, moderate_pain2, severe_pain, severe_pain2, terrible_pain
num1, num2, num3, num4, num5, num6, num7, num8, num9, num10

**Comment by cefasheli** [comment]
ty

**Comment by cefasheli** [comment]
num1 is apointing to 10

**Comment by cefasheli** [comment]
Could be better the name be the same name when we mouseover the images, is more intuitive.

**Comment by crnormand** [comment]
The problem is that "Shocked" is the name for all 4 shock statuses.    Which is why I also included the IDs.

**Comment by benjaminitz** [comment]
Hi! I was wondering where in the gurps system folder I can find the status ids? I'm trying to either a) make a macro that toggles the specific statuses I use most often, or even better b) remove the statuses I never use from the status effect token dropdown.

**Comment by crnormand** [comment]
module/GURPS.js.  Starting at line 177.

**Comment by benjaminitz** [comment]
thank you!

**Comment by crnormand** [comment]
Added the `/st list` command to show all of the status names and IDs.
