### ISSUE TITLE
Drag Ruler module crashed

### ISSUE THREAD

**Issue by rodrigosinistro** [crnormand/gurps#424]
Hi All

After the last update the module Drag Ruler crashed.

https://github.com/manuelVo/foundryvtt-drag-ruler

Thanks

**Comment by crnormand** [comment]
I don't see how we could have interfered with their module.   The stack trace shows:

Uncaught TypeError: Cannot read property 'getAltOrientationFlag' of undefined
    at applyTokenSizeOffset (util.js:120)
    at Ruler.measure (foundry_imports.js:113)
    at Ruler.measure (main.js:100)
    at Ruler.onMouseMove (foundry_imports.js:97)
    at Token.onTokenLeftDragMove (main.js:172)
    at Token._onDragLeftMove (main.js:51)
    at MouseInteractionManager.callback (foundry.js:36392)
    at MouseInteractionManager._handleDragMove (foundry.js:36724)
    at MouseInteractionManager._handleMouseMove (foundry.js:36698)
    at e.a.emit (index.js:202)

And the error occurs because the variable 'CONFIG.hexSizeSupport' is null.

```
// Tokens that have a size divisible by two (2x2, 4x4, 2x1) have their ruler at the edge of a cell.
// This function applies an offset to to the waypoints that will move the ruler from the edge to the center of the cell
export function applyTokenSizeOffset(waypoints, token) {
	if (canvas.grid.type === CONST.GRID_TYPES.GRIDLESS) {
		return waypoints
	}

	const tokenSize = getTokenSize(token);
	const waypointOffset = {x: 0, y: 0};
	if (canvas.grid.isHex) {
		const isAltOrientation = CONFIG.hexSizeSupport.getAltOrientationFlag(token);
		if (canvas.grid.grid.options.columns) {
			if (tokenSize.w % 2 === 0) {
				waypointOffset.x = canvas.grid.w / 2;
				if (!isAltOrientation)
					waypointOffset.x *= -1;
			}
		}
```

None of this is our code.   We do not set or use that variable.   Maybe the problem is with their module?  They made changes 9 hours ago.

**Comment by rodrigosinistro** [comment]
Hi Cris

I thank you for all the work you do.

Thank you for your quick feedback.

I opened a problem in the Drag Ruler github.

Thanks
