### ISSUE TITLE
Modifier “*Max:?” problem

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#425]
When a modifier with “*Max:?” (e.g.  -4 : to hit (Charge Attack) *Max:9) is combined with _another_ modifier, the skill cap (e.g. 9) isn't applied anymore.
![Skill Cap](https://user-images.githubusercontent.com/80178910/111365567-edecd300-8692-11eb-8d8f-738602d017a2.JPG)

**Comment by crnormand** [comment]
Yeah, the bug occurs because the Max: is the first modifier.   It will work if it is the last.   But it should work in any order.    It is fixed and will be in the next release.
