### ISSUE TITLE
Create a user editable field for the Initiative value

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#427]
Currently, we calculate the Initiative (turn order) value from the formula:
`
((@basicspeed.value*100) + (@attributes.DX.value / 100) + (1d6 / 1000)) / 100`

But this doesn't make it easy for a GM to assign a bonus.

We would use a portion of this formula to create a starting value:  `(@basicspeed.value) + (@attributes.DX.value / 100)`
And save the result in an editable field (initiative).   The GM could then increase or decrease that number.   We would then change the Foundry formula to be `@initiative.value + (1d6/1000)`

**Comment by cefasheli** [comment]
I do not understand you can click on inititave and change the value. TheFurnace does it, i think.

**Comment by crnormand** [comment]
I found out that you can manually edit an initiative value.   Just right click on a combatant, select "Update Combatant" and enter in a new value in the dialog:
![image](https://user-images.githubusercontent.com/8931036/113064647-69677d80-9185-11eb-9c67-73eb985eb771.png)

As such, this is a much lower priority... since the GM can literally edit the order any way they want.

**Comment by crnormand** [comment]
Done (for now).    https://github.com/crnormand/gurps/pull/496
The user can edit the formula (at their own risk).
