### ISSUE TITLE
Modular Modifier Bucket window

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#434]
Designate a "pane" of the modifier bucket window to display the contents of a journal. We could put a dropdown menu at the top of the frame (or an input field) and allow the user to select the journal contents to display. This way the MB window becomes easily customizable.

**Comment by crnormand** [comment]
Cool idea. I remember a module that Mook showed us that was called "GM screen". And I think it did something similar.    ￼

**Comment by cefasheli** [comment]
GM Screen is pretty usefull but you cannot run OTF through him... U can set sheets, journal, itens etc.

**Comment by crnormand** [comment]
Ahh.  Well, I shall look into that.   I want to make that work.

**Comment by cefasheli** [comment]
To use OTF trhough GM Scree, u need to write the OTfs one journal and import, could be nice write some stuf directly to gmscreen

**Comment by crnormand** [comment]
You need to open a ticket with the GMScreen module.   We don't control what they can and cannot edit.

**Comment by mjeffw** [comment]
In this next release you can create Journal entries with OtF formulas, and display them as panes on the Modifier Bucket. Here's a couple of journal entries:

![Image 4-23-21 at 10 50 AM](https://user-images.githubusercontent.com/7349413/115889563-0bdfed00-a422-11eb-9371-a604541ea1c9.jpeg)

![Image 4-23-21 at 10 50 AM](https://user-images.githubusercontent.com/7349413/115889579-113d3780-a422-11eb-8167-0d589f47a897.jpeg)

You specify that they should be displayed in the modifier bucket via a new System Setting:

![Image 4-23-21 at 10 49 AM](https://user-images.githubusercontent.com/7349413/115889708-2ca84280-a422-11eb-86b1-c48c1707ad53.jpeg)

![Image 4-23-21 at 10 49 AM](https://user-images.githubusercontent.com/7349413/115889733-32058d00-a422-11eb-9fd8-9754120f49b5.jpeg)

You can cycle through the standard modifier bucket and the journal entries via arrows on the "Common Modifiers" pane of the MB:

![Image 4-23-21 at 10 47 AM](https://user-images.githubusercontent.com/7349413/115889870-58c3c380-a422-11eb-8d75-2694095561a7.jpeg)

![Image 4-23-21 at 10 48 AM](https://user-images.githubusercontent.com/7349413/115889887-5f523b00-a422-11eb-81ae-463984384898.jpeg)

![Image 4-23-21 at 10 48 AM](https://user-images.githubusercontent.com/7349413/115889913-64af8580-a422-11eb-9ae7-aee5a3aa9178.jpeg)
