### ISSUE TITLE
Reset modifier bucket to some previous/last entry.

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#435]
Often the player uses the same modifiers over and over during a scene. It would be nice if we could give them a way to select and apply all the previous modifiers at one go.

For example, the player is in a combat with the following modifiers:

* -5 Dim lighting
* -2 Bad footing
* +3 Night Vision
* -2 Deceptive attack

Unless something changes, he's always going to have those first 3 modifiers. I'd like to be able to click or enter something that would restore all of those modifiers on my turn, and either just use them as is, or further modify them, before my attack.

**Comment by cefasheli** [comment]
EXCELENTE IDEIA

**Comment by crnormand** [comment]
Drag and Drop into macros.

**Comment by crnormand** [comment]
You can now drag the modifier bucket into a macro slot.   When you click the macro slot, it will clear the MB and set it each to the "saved" bucket.
