### ISSUE TITLE
Some non-ascii characters (in character names) do not import from GCA

### ISSUE THREAD

**Issue by woefulhc** [crnormand/gurps#437]
I suspect this may be an encoding issue but am unsure. The character names are: Ælin Rock-Talker and Grükuk Kzaash and do show correctly in GCA and in the export xmls, but the resulting import in Foundry looks like the attached pic.
![imported_names](https://user-images.githubusercontent.com/77212217/111894576-822ba280-89d1-11eb-9712-5a79acccf069.png)
[non-ascii.zip](https://github.com/crnormand/gurps/files/6176877/non-ascii.zip)

**Comment by crnormand** [comment]
I figured it out... whew... this was a B I T C H.   JS's own FileReader was converting the unicode character into something unusable.

It will be fixed in the next release.
![image](https://user-images.githubusercontent.com/8931036/113070309-47272d00-9190-11eb-941b-1898205417ae.png)
