### ISSUE TITLE
[Bug] Pi-, Pi+ and Pi++ damage types are not recognised within damage rolls

### ISSUE THREAD

**Issue by WeirdBread** [crnormand/gurps#439]
Pi-, Pi+ and Pi++ damage type become simple Pi in damage chat message, therefore damage is incorrect if you try to apply it to Actor/Token.

![изображение](https://user-images.githubusercontent.com/79375204/112159475-4293cf00-8bfa-11eb-9047-148ee2b5a9d8.png)

![изображение](https://user-images.githubusercontent.com/79375204/112159519-4f182780-8bfa-11eb-8556-f7ed4903ec9d.png)

**Comment by cefasheli** [comment]
This window is no longer opening for me `

  | (anonymous) | @ | foundry.js:250
-- | -- | -- | --
  | Promise.catch (async) |   |  
  | render | @ | foundry.js:250
  | handleDamageDrop | @ | actor.js:559
  | (anonymous) | @ | gurps.js:563
  | _call | @ | foundry.js:132
  | call | @ | foundry.js:130
  | _onDrop | @ | foundry.js:618
  | callOriginalFunction | @ | Patches.js:18
  | (anonymous) | @ | Tokens.js:5
  | handleDrop | @ | dragupload.js:13
  | callback | @ | foundry.js:789
  | _handleDrop | @ | foundry.js:793

`

**Comment by mjeffw** [comment]
I found the problem; a fix is coming shortly.

**Comment by mjeffw** [comment]
The fix will be in the next release.
