### ISSUE TITLE
[Bug] Multiple damage rolls now cannot be applied to token/actor

### ISSUE THREAD

**Issue by WeirdBread** [crnormand/gurps#449]
Apply damage dialog does not appear when I try to drag&drop "ALL DAMAGE" message to token or actor. Single damage roll still works correctly. 

![изображение](https://user-images.githubusercontent.com/79375204/112387272-98539e80-8d02-11eb-9853-a08cb71bce57.png)

![изображение](https://user-images.githubusercontent.com/79375204/112387429-cf29b480-8d02-11eb-8bcc-3fac8490b735.png)

**Comment by mjeffw** [comment]
Yep, I screwed up! I fixed it and it will be in the next release.
