### ISSUE TITLE
[Bug] Drag and Drop Macros for OtF attacks do not work if there is an apostrophe in the weapon name

### ISSUE THREAD

**Issue by TheFabulousIronChef** [crnormand/gurps#474]
Almost positive it is an apostrophe. Because dragging and dropping an item that is described as "Large Shield (Fine, Balanced) has no issue--drag and drop to the macro bar works fine. 

But if I drag and drop these three: "Veldran's Longsword (Fine, Magical (Puissance +1)," "Andrew's First Cutlass (Fine, Balanced)," and "Grabthar's Hammer," they all give me an error message:

Using F12 to open the console reveals the following:

foundry.js:32840 SyntaxError: missing ) after argument list
    at Macro.execute (foundry.js:32837)
    at Hotbar._onClickMacro (foundry.js:20566)
    at HTMLLIElement.dispatch (jquery.min.js:2)
    at HTMLLIElement.v.handle (jquery.min.js:2)

**Comment by crnormand** [comment]
Yep... that sounds about right.   I will update the code to check which string delimiter to use.

**Comment by crnormand** [comment]
It will be fixed in the next release.

**Comment by TheFabulousIronChef** [comment]
Cool cool cool
![image](https://user-images.githubusercontent.com/46587602/113357979-f1c75900-9312-11eb-86cd-57dfdb2f7bbe.png)
