### ISSUE TITLE
Bugs/minor improvements to the Resource Trackers

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#480]
- [x] Disable the Maximum, Minimum, and Current fields if opening a tracker editor from the Tracker Manager.
- [x] Add all resources tracked by a character sheet to the "Apply To" dropdown.
- [x] Add custom damage types for resource trackers when clicking the Update button on the Tracker Manager so that folks don't have to restart Foundry.

**Comment by cefasheli** [comment]
Could be possible to add an option to delivery damage to diferents trackers? like HP and Armor?

**Comment by mjeffw** [comment]
@cefasheli -- Just pushed a commit such that any resource on the character sheet with both a name and alias, and "Use as Damage Type" checked, will allow you to put any damage type on it. Alias and names must be unique for the trackers on a given character (i.e., no duplicates).

![image](https://user-images.githubusercontent.com/7349413/114279542-38980b80-9a03-11eb-913a-35c3568dae6f.png)

![image](https://user-images.githubusercontent.com/7349413/114279574-5a918e00-9a03-11eb-8da9-e9222d8c5b8d.png)

![image](https://user-images.githubusercontent.com/7349413/114279594-75fc9900-9a03-11eb-830f-f4e519e15211.png)

![image](https://user-images.githubusercontent.com/7349413/114279610-8a409600-9a03-11eb-9bc2-a9902257fe28.png)

**Comment by mjeffw** [comment]
Done: - Disable the Maximum, Minimum, and Current fields if opening a tracker editor from the Tracker Manager.
