### ISSUE TITLE
Add Pyramid 3/120 The Fifth Attribute (Quintessence) Support

### ISSUE THREAD

**Issue by Legendsmith** [crnormand/gurps#487]
I am working on adding Quintessence support to GCS and I've got it working, including exports.
The keys for Quintessence are ``@QN`` and ``@QP`` for Quintessence Points. I figure that part of the Resource tracker area could be used for Quintessence Points.

**Comment by mjeffw** [comment]
@Legendsmith, what needs to be done to close out this issue satisfactorily?

**Comment by Legendsmith** [comment]
@mjeffw - Import quintessence from the appropriate keys (QP, and QN, following the established schema with QP_Points, etc). Make Quintessence a 5th attribute that appears with the other 4 when Quintessence is enabled. Make it rollable.
And preferably, make Quintessence Points one of the presets for resource trackers that will also import the Quintessence Points value from sheets.

**Comment by Deliphin** [comment]
It would be best if you don't specifically look for those IDs (QP and QN), and instead look for any keys that don't match ones you're already manually handling.
 This would make it easier to handle if people wanted to add an attribute other than Quintessence. For example, my setting is simulation, and so I have an attribute called Stabliity- conceptually based on Quintessence, but has its own name and mechanically is heavily attached to magic. I don't want to have to call it Quintessence inside Foundry.
