### ISSUE TITLE
Support user entered damage types with (limited) ADD support

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#493]
It would not be hard to add new damage types to the standard GURPS ones (cr, cut, imp, etc...) if the only thing the new damage type did was to introduce a different wounding modifier (tbb, I'm looking at you!). But hardcoding these nonstandard values is less appealing to me. 

I propose we give the user a way to enter new damage types in the system settings, and automatically add them to the ADD. The editor would ask the user to enter the following three pieces of information:

 - Name of damage type (e.g., 'Crushing')
 - Its abbreviation used in attack specifications ('cr')
 - Its wounding modifier ('x1')

The damage type could then be added to the code to support OtF and the ADD.

**Comment by crnormand** [comment]
I am going to close this, since this feature has been fully (or partially) included by the resource tracker code.
