### ISSUE TITLE
[Feature Request] /ev everyone command limited to a scene

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#494]
The /ev OTF calls for a roll of every player character in the world. But since some of my Characters have multiple forms (Shapeshifters). There are way to many unneeded rolls.

It would be nice to have something like /ev limited just to the characters on the active scene.

**Comment by crnormand** [comment]
Good call.. that make more sense anyway.    Shouldn't be too hard.

**Comment by crnormand** [comment]
Done.   Now the /everyone command only looks for player owned tokens on the current scene.
