### ISSUE TITLE
Apply Damage Dialogue & Explosions Incorrect Calculation

### ISSUE THREAD

**Issue by Legendsmith** [crnormand/gurps#499]
The Apply Damage dialogue is really good, but there's a problem with explosions.
Explosion damage is divided by hexes from the center, but this should be done _before_ calculating DR, however at the moment it is done _after_ DR calculation.
As it is, explosions are monstrously and incorrectly effective against DR.
![image](https://user-images.githubusercontent.com/1914417/114332158-f8629580-9b88-11eb-9abc-7b1354d1538f.png)

**Comment by mjeffw** [comment]
![image](https://user-images.githubusercontent.com/7349413/114462034-800fca80-9bb0-11eb-94c6-8013906f331d.jpeg)

**Comment by mjeffw** [comment]
![image](https://user-images.githubusercontent.com/7349413/114464780-33c68980-9bb4-11eb-8cb2-88d0c149b6ea.jpeg)
