### ISSUE TITLE
Feature request: Add the Conditional Modifiers section to the character sheet

### ISSUE THREAD

**Issue by rinickolous** [crnormand/gurps#504]

**Comment by mjeffw** [comment]
Which ones are you looking for? The MB already has a number of conditions:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/7349413/114549192-b55afd80-9c2e-11eb-8125-c9b21aa42182.png">

**Comment by crnormand** [comment]
Or are you talking about GCS's new "Conditional Modifiers" feature that Rich put in a few releases ago?

**Comment by rinickolous** [comment]
> Or are you talking about GCS's new "Conditional Modifiers" feature that Rich put in a few releases ago?   

Yes, that's it. It's not that new, iirc.

**Comment by crnormand** [comment]
LOL, I guess it is just how we look at time... It was added in Nov 2020.    

> v4.26.0
> 
> @richardwilkes richardwilkes released this on Nov 20, 2020
> New Features
> 
>     Request #279: Add CTRL-TAB shortcut to switch current tab of dock container. SHIFT-CTRL-TAB goes in the opposite direction.
>     A new feature type can now be added: conditional modifiers.

Do you happen to know which output template KEY will export them?  https://gurpscharactersheet.com/output_templates.html

We already export DESCRIPTION_MODIFIER_NOTES for Advantages and include that text in the 'notes' section.

**Comment by richardwilkes** [comment]
CONDITIONAL_MODIFIERS_LOOP_START
    KEY_ID
    KEY_MODIFIER
    KEY_SITUATION
CONDITIONAL_MODIFIERS_LOOP_END

also slightly before that one was added:

REACTION_LOOP_START
    KEY_ID
    KEY_MODIFIER
    KEY_SITUATION
REACTION_LOOP_END

**Comment by crnormand** [comment]
[char.zip](https://github.com/crnormand/gurps/files/6314946/char.zip)
