### ISSUE TITLE
Modifier bucket goes off the bottom of the screen

### ISSUE THREAD

**Issue by woefulhc** [crnormand/gurps#524]
I have a 1920×1080 monitor. The bottom of the modifier bucket extends past the bottom of my screen unless I set it to use pop 
![mb_cutoff](https://user-images.githubusercontent.com/77212217/115480104-11152000-a207-11eb-8db9-0a4df2739895.png)
out.

**Comment by mjeffw** [comment]
There's something weird about the dimensions of the modifier bucket window from this screen shot.

I've completely reworked the sizing of the modifier bucket in the next release and I think it will fix this. (Shhh! Don't tell anyone but you can scale the modifier bucket size from 80% - 120% in that release as well...)
