### ISSUE TITLE
Some size modifiers apply a 0 modifier rather than the one selected

### ISSUE THREAD

**Issue by woefulhc** [crnormand/gurps#525]
Some modifiers (both + and -) only apply a 0 but leave the correct modifier in the description text

![size_modifiers](https://user-images.githubusercontent.com/77212217/115480222-4e79ad80-a207-11eb-8df0-5f200f54347b.png)

**Comment by crnormand** [comment]
We needed to trim() the text before we added it as a modifier.   Anything in the SIZE list with less than 10 digits has a leading space, which is causing the code to interpret that as a ZERO. 
It will be fixed in the next release.
