### ISSUE TITLE
CTRL+Click on buttons to perform a blind GM roll

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#539]
With the inclusion of Shift+Click as a self-roll, would it be possible to also allow for blind GM roll by doing similar? That way, the player doesn't have to switch between the different dropdowns for public, self, blind, etc.

**Comment by crnormand** [comment]
Yes, I think I can do that... and...

I am going to add a system setting "Players holding shift key during a roll makes it 'blind'" (or something like that).

When off, pressing shift will make a "self roll", only the current user can see it.   This is the behavior we have today.   When this setting is turned on, then when a GM presses "shift" it is a "self roll" (like it is now), but when a non-GM player presses shift, it will convert the roll into a Blind Roll.

This seems like the more common usage... the GM doesn't want players to see what they roll, and the players may be asked to roll "blind".

**Comment by crnormand** [comment]
Done.  It will be in the v0.9.1 release.

Ctrl click (or CMD click for Macs) will make any roll a Blind roll (if you are a player).   And there is a new system setting "SHIFT Click does a Blind roll for players, and a Self roll for GMs", that the GM can turn on to make the SHIFT key do blind rolls for players (and Self rolls for GMs)
