### ISSUE TITLE
Issues with Slam calculator?

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#544]
LordHelmet — 04/22/2021
I found another issue with the slam calculator.
In this example the attacker is rolling less than half the damage of the defender - so the attacker would automatically fall. But instead the defender falls!

![image](https://user-images.githubusercontent.com/7349413/115962791-f5ea2f00-a4ea-11eb-97c7-7f7d178939aa.png)

**FIXED with Issue #555 **

**Comment by mjeffw** [comment]
LordHelmet — 04/22/2021
Dear Nick, I guess the calculation for the slam damage is a bit off. When there is just 1 dice it seems fine. But I found an issue with 2d. In the example it is 1 die and the fraction is 0.54. So it should be 1d + 1d-1 = 2+-1.

![image](https://user-images.githubusercontent.com/7349413/115962829-1fa35600-a4eb-11eb-817e-8866403ac3d0.png)

**Comment by mjeffw** [comment]
Could you please expand the slam calculator to include an optional field to add Defense Bonus of shields for the extra damage when doing a Shield Rush. Much like you already did for All-Out-Attack. Thanks!

**Comment by LordOHelmet** [comment]
Could you please extend this description of the slam result in the chat to provide a cklickable button to toogle the appropriate status effect for being prone?
![slam auto](https://user-images.githubusercontent.com/80178910/115972318-e8b25c00-a54d-11eb-8c12-45f5eaaddaea.JPG)

Like `/status on prone` for this example.

Could you please extend this description to provide a cklickable button to toogle the appropriate status effect for a failed DX-roll?
![slam roll fall](https://user-images.githubusercontent.com/80178910/115972374-38912300-a54e-11eb-8096-aa64aeae0571.JPG)

Like `/if [DX] /else /status on prone`

This request is linked to  #549.

**Comment by mjeffw** [comment]
@LordOHelmet I'm checking on the correct Slam formula on the SJGames forums.

B371 states: "If damage is less than 1d, treat fractions up to 0.25 as 1d-3, fractions up to 0.5 as 1d-2, and any larger fraction as 1d-1. Otherwise, round fractions of 0.5 or more up to a full die."

The above implies that you don't consider fractions unless the total is less than 1, which is the way I programmed it. However, I like your interpretation, which gives more variation and finer-granularity between whole number results.

**Comment by mjeffw** [comment]
Confirmed: The slam calculation is correct as programmed. Here is how slam works where _value_ = HP x Velocity:

```
Value        | Dice
-------------|-----
0 < 0.25     | 1d-3
0.25 to < 0.5| 1d-2
0.50 to < 1   | 1d-1
1.0 to < 1.5 | 1d
1.5 to < 2.5 | 2d
2.5 to < 3.5 | 3d
... etc ...
```
