### ISSUE TITLE
[Feature Request] Expand injury description to toggle status effects

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#549]
You already provide a clickable injury description in the ADD.
![ADD injury desc](https://user-images.githubusercontent.com/80178910/115970712-7a1cd080-a544-11eb-8c09-b7b6671c23ea.JPG)

Which gives for example the description of Shock in the chat with the option to click the shock modifier to transfer it to the modifier bucket.

![shock chat](https://user-images.githubusercontent.com/80178910/115970745-bb14e500-a544-11eb-99a3-b5d03b690184.JPG)

Could you please extend this description to provide a cklickable button to toogle the appropriate status effect for Shock?
Like `/status on shock4` for this example.

The second part is about the Major Wound description.
You already provide a clickable HT check to avoid Stun.

![stun chat](https://user-images.githubusercontent.com/80178910/115970839-6d4cac80-a545-11eb-886c-002d5679e3e6.JPG)

Could you please extend this description to provide a cklickable button to toogle the appropriate status effect for a failed HT-roll?
Like `/if [HT] /else /status on stun`

I guess it could be nicely done with the new fantastic /if command.

**Comment by mjeffw** [comment]
file:///var/mobile/Library/SMS/Attachments/88/08/3A86024D-B20C-49E5-840C-AF49E72B80F5/Image%205-10-21%20at%2010.30%20AM.jpeg

**Comment by mjeffw** [comment]
![image](https://user-images.githubusercontent.com/7349413/117676126-431d0080-b17b-11eb-98e9-41e6a7322a56.jpeg)

**Comment by LordOHelmet** [comment]
Thank you! Looks great.
