### ISSUE TITLE
Apply Prone and (conditional) Prone statuses to Slam Calculator

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#558]
@LordOHelmet
Could you please extend this description of the slam result in the chat to provide a cklickable button to toogle the appropriate status effect for being prone?
![slam auto](https://user-images.githubusercontent.com/80178910/115972318-e8b25c00-a54d-11eb-8c12-45f5eaaddaea.JPG)

Like `/status on prone` for this example.

Could you please extend this description to provide a cklickable button to toogle the appropriate status effect for a failed DX-roll?
![slam roll fall](https://user-images.githubusercontent.com/80178910/115972374-38912300-a54e-11eb-8096-aa64aeae0571.JPG)

Like `/if [DX] /else /status on prone`

This request is linked to  #549.

**Comment by cefasheli** [comment]
Why do you think SJG could be against automations? This a common feature in any VTT system.

**Comment by mjeffw** [comment]
A bit of history: When we started, we hosted the link to our GURPS game aid on the Foundry just like all the other systems. Shortly thereafter, SJGames posted a DMCA Takedown Notice saying that it was possible we were violating their IP and copyright. Afterwards we began working with them to get the takedown removed and become an "official" game aid. 

Part of those discussions revolved around how much of the rules could be automated. SJG's concerns are that they want to maintain GURPS as a TTRPG, and not have it become a video game. (There are other concerns as well, such as whether a VTT would negatively impact their sales of GURPS rules and supplements.) 

@crnormand (Nose) and I (Nick Coffin, PI) are still awaiting for SJG's decision. As a part of that, we both agreed that we would need to err on the side of caution in automating game play. In general, the current game aid prevents you with the option to apply a rule, but doesn't automate the application of any rule for the GM or player. To do so without approval or discussion with then may tip the scales toward their rejecting our ability to host a link on the Foundry game systems list.

After we get SJG's blessing, we will have more free rein to discuss with them the limits of automation.

**Comment by LordOHelmet** [comment]
Both solutions sound good. However, I prefer the variant with the system setting.

**Comment by mjeffw** [comment]
I'm already working on it, LOL.

**Comment by mjeffw** [comment]
![Image 5-8-21 at 11 17 AM](https://user-images.githubusercontent.com/7349413/117544489-b265e980-afef-11eb-9e89-95c0c0679ed0.jpeg)
