### ISSUE TITLE
NPC/Mini sheet doesn't use Conditional Injury

### ISSUE THREAD

**Issue by Legendsmith** [crnormand/gurps#562]
Inserting the conditional injury block when CI is enabled into the NPC mini sheets seems like it'd be pretty doable, just between the existing attribute block, and the notes block.

**Comment by Legendsmith** [comment]
This is something what I would like, but the grid display system doesn't play nice with allowing things to appear or disappear because it expects stuff to be static. This is why I think flexbox is better.
![image](https://user-images.githubusercontent.com/1914417/116436515-d149da80-a88f-11eb-9421-ae7aa25b8da3.png)

**Comment by crnormand** [comment]
I agree completely.   I am NOT a UI designer.    This was an initial attempt to layout some items.   I would be more than happy to have someone re-write it for me ;-)
