### ISSUE TITLE
Modular Modifier Bucket cut off at umlaut

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#567]
The entries in the modular modifier bucket are cut off at an umlaut/mutated vowel.

![MB umlaut](https://user-images.githubusercontent.com/80178910/116570433-9042dc00-a90a-11eb-9146-cbcf2ecd2ec3.JPG)

**Comment by mjeffw** [comment]
Can you give me the text involved? Go to your Journal entry, right-click on it, and select "Export Data". Then send me that file in Discord.

**Comment by LordOHelmet** [comment]
Sent you the file in Discord.
It should look like this:
```DFS6

+1 für urzeitliche Wildnis

+0 gewöhnliche Wildnis

-1 Untergrund Dungeon

-1 bestellte Felder/Forst

-2 urbaner Park

-3 Stadt/Burg/Turm

-4 Gerberei/Schmiede/Industrie

-5 geschändet/Tagebau/verschmutzt

-1 pro weiter Stufe verschmutzt

-10 unnatürlich geschändet

-10 verrückte Zauberei/alchemische Halde/etc.

Zaubern während Aufrechterhaltung 
-3 auf andern Zauber konzentriert pro Zauber

-1 für Zauber der "an" ist pro Zauber

Zauberrituale M8

Mana Niveau DFS7

Magic Cheat Sheet DFS0```

**Comment by crnormand** [comment]
One place could be the top of the parselink method where we strip/convert some characters.  
Btw, this is where I was going to put in the code to convert the special "curly" double quotes into regular double quotes, in case someone copy and pastes an OtF.

**Comment by mjeffw** [comment]
Fixed. @crnormand, the fix is to let the DOM go ahead and interpret all escaped HTML entities, and use the unescaped text as input to the parselink() function. Can be done like this:

```js
    // this is a stupid trick to 'unescape' HTML entities, like converting '&uuml;' to 'ü'
    var template = document.createElement('textarea') // create a <textarea> DOM element
    template.innerHTML = str // set the inner HTML to our string
    str = template.childNodes[0].nodeValue // pull the unescaped string back out
```

![image](https://user-images.githubusercontent.com/7349413/116818523-cfa33f80-ab39-11eb-971b-38c56cf4111f.png)

**Comment by mjeffw** [comment]
BTW, those three lines of code took me WAAAY too long to figure out.
