### ISSUE TITLE
[Feature Request] Honor the GCA Hide(yes) Tag

### ISSUE THREAD

**Issue by engurrand** [crnormand/gurps#573]
In GCA, GMs often add traits to GCA character records that are of no interest nor use to players, but exist to manage some calculation regards to DR, Attack Modes, or other what have you. Such traits can canonically be hidden from the character record with the Hide(yes) tag in the trait definition, but different character sheets for GCA honor this or don't honor it. It would be once to be able to hide traits from displaying in Foundry VTT. For example, adding attack modes to the attacks blocks can only be done with whole traits, equipment, or modifiers on existing traits, but it's a waste of pixels to print the stats in the attacks block as well as the trait on the traits list.

Cheers.

**Comment by crnormand** [comment]
Odd.   The export "should" be honoring the "hide" flag.   I know it does for many things (but maybe not everything).  Can you zip up the gca4 file and attach it? (And let me know what shouldn't be importing)

**Comment by engurrand** [comment]
Sure thing. Here's a link to the .zip hosted by my onedrive: Testy McTestaroo.zip https://1drv.ms/u/s!AusoeXANkcEhhaVRjBZcc3ykO1EVzg?e=8DyNXC 
Testy McTestaroo has three advantages: 

- Astral Projection Talent 1 is hide(yes).
- Burning Attack 1 is hide(yes).
- The Sight 1 has no hide() tag.

Thanks for your attention! It would be ideal (for me at least) for the trait to hide but not its derivative data, eg Id like to be able to hide the burning attack in the traits list but leave its entry in the attacks blocks. Now that I'm thinking about it, I might be trying to use the tag for something it's not meant for. Still, thanks for your attention. Cheers!

**Comment by crnormand** [comment]
@engurrand sorry it has taken so long.   I am a bit leery of making this change, because I didn't originally write the GCA export, and I don't completely understand the GCA model.   The change should only affect Ads/Disads/Quirks/Perks.

It seems to work on Test McTestaroo.

Would you be willing to try this new export filter to make certain that it doesn't mess up any other attributes?

[export to Foundry VTT.zip](https://github.com/crnormand/gurps/files/6461301/export.to.Foundry.VTT.zip)

**Comment by engurrand** [comment]
I certainly understand tinkering with code you didn't write. I'll have a look and see if anything has exploded. Cheers!

**Comment by engurrand** [comment]
As far as I have been able to test, it seems to be working. Cheers and thanks!
