### ISSUE TITLE
[Bug] /status command doesn't really work when GURPS.lastActor is not the token selected on the map

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#574]
Steps to reproduce:

1. Create a scene with two tokens, A and B
2. Select A on the map, so that it has the orange highlight around it.
3. Enter chat command `/select B` and verify the selected actor text above the modifier bucket shows 'B'.
4. Enter chat command `/status on prone`

Result is that token A gets the prone status, not token B.

**Comment by crnormand** [comment]
Now the /select command will try to "control" the matching token on the current canvas, so you can now execute:
```
/select B
/status on prone
```
and it will work.
