### ISSUE TITLE
Create export script for GCA5

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#606]

**Comment by crnormand** [comment]
User jbalsle/jhymesba started work on this at https://dev.azure.com/jbalsle/FoundryXMLExport.   It works pretty well, except there seems to be a weird error that causes the character sheet to format wildly.
[Catarina_Sol_T_export.zip](https://github.com/crnormand/gurps/files/6466717/Catarina_Sol_T_export.zip)

![image](https://user-images.githubusercontent.com/8931036/117989192-1b0fd780-b30a-11eb-8e26-b4e9f2cc62e1.png)

**Comment by crnormand** [comment]
From jbalsle/jhymesba:

> That character, btw, is my 'break the system' character. She's a Palladium-converted character, with numerous sorcery-style spells with more modifiers per spell trait than you can shake a stick at. She's a 4k CP character that takes minutes (!) to merely change in GCA4. Despite her taking minutes to calculate in GCA5, at least you can change a stat or skill without locking the app down for minutes at a time now.

**Comment by cefasheli** [comment]
Is GCA5 Available?

**Comment by crnormand** [comment]
It is available as a Beta.
