### ISSUE TITLE
Translation Marks

### ISSUE THREAD

**Issue by Shepardieu** [crnormand/gurps#610]
https://github.com/crnormand/gurps/blob/0ac87a4cee12be0800e85347976e5e7ccd71e47f/lang/ru.json#L434

"Название счётчика ({name}) или Алиас ({alias}) не уникальны." - "Название счётчика ({name}) или псевдоним ({alias}) не уникальны."

**Comment by mjeffw** [comment]
After review with our Russian translator, we've decided the go with the current translation.
