### ISSUE TITLE
Mook effects [Enhancements]

### ISSUE THREAD

**Issue by cefasheli** [crnormand/gurps#627]
![image](https://user-images.githubusercontent.com/21176804/118345342-144fb300-b50a-11eb-8b6c-45f0d6092d7a.png)
Sometimes the attack doens't havee a damage but an effect. It's possible to create a "tag" to make mook ignore the damage? 

so instead 
Gaze(15) 1d+3 imp reach C
we may have 
Gase(15)  voodoo(Petrify Spell effect)

**Comment by crnormand** [comment]
Well, it was supposed to work:

Gaze (13) “Some non-rollable damage”

Put the non-rollable damage in double quotes... but it doesn't seem to be working right now.   I shall investigate.

**Comment by crnormand** [comment]
Ah... it does work, if I use REGULAR double quotes.    So you can create an attack like:

`Gaze (13) "Some text for damage" reach c,1 usage eyeballs`

Just make certain you are using double quotes (and not something pasted in from the internet).    NOTE, I have fixed that issue in the next release.   We now 'sanitize' the text being typed in so our parsers will recognize it.
