### ISSUE TITLE
[Feature Request] Ability to add Reaction Modifiers

### ISSUE THREAD

**Issue by Plape2021** [crnormand/gurps#642]
The ability to add new Reaction modifiers to a character sheet within Foundry, similar to how Notes and Equipment etc can be added.
Ideally would have a button to add one (like + button for Notes and Equipment) and can edit the modifier and the accompanying description, as well as the option to save on re-import.
Low priority, but my group likes to play around with Reaction modifiers (realistic setting and they enjoy micromanaging outfits, bathing, personal appearance etc. for social interactions), and it seems relatively simple to include. Presently we're just adding them under Quick Notes, but it would be nice if they were all organized under Reactions.
👍

**Comment by crnormand** [comment]
Actually, you can do this through the Editor.   Yes, it is old an ugly, but it gets the job done.  Click the Editor button in the title bar, and right click on the "Reaction" header bar:

![image](https://user-images.githubusercontent.com/8931036/121459263-ecbd0080-c978-11eb-9ec2-229f3eba739a.png)

And select "Add Reaction at the end", which will create a new Reaction:

![image](https://user-images.githubusercontent.com/8931036/121460045-4b36ae80-c97a-11eb-82a8-327ac8a40305.png)

Just click in the fields to add your own modifier (remember to add a plus (+) or minus (-) in front of the modifier) and description:

![image](https://user-images.githubusercontent.com/8931036/121460154-77522f80-c97a-11eb-8d77-3e7943ade83c.png)

And then click FullView to use (no need to 'save'):

![image](https://user-images.githubusercontent.com/8931036/121460219-951f9480-c97a-11eb-84d0-5d7cfc781fd7.png)

You can always go back into the Editor to change the modifier value or text.
To remove, go back into the Editor window, right mouse click on the Reaction, and select Delete:

![image](https://user-images.githubusercontent.com/8931036/121460346-cc8e4100-c97a-11eb-8034-eafb85f4d578.png)
