### ISSUE TITLE
Damage rolls don't work properly when armour divisors are involved

### ISSUE THREAD

**Issue by JanPolasek** [crnormand/gurps#66]
I've noticed that damage formulas that involve armour divisors such as `6d(2) burn` produce incorrect results.

I gave the code a quick look and noticed that `DamageChat.create()` assumes that the divisor will be in `damageType`, and `parselink()` seems to be designed to parse it as such, but that for some reason is not the case here. `diceText` will be `6d(2)` and `damageType` will be just `burn`. As a result, 6d6(2) will be passed to the roller which will interpret it as 6d62 (analogously `2d-1(2) cut` for example would end up being rolled as 2d6-12, always producing a 1).

Unfortunately I can't research this much further since I currently don't have a proper setup to debug this myself, all I have is a browser and my breakpoints just don't trigger in some cases for some reason. which makes things difficult.

**Comment by crnormand** [comment]
My apologies.    I did not make it clear enough in the video (and I haven't finished editing the users guide), but we don't have Armor Divisors completely working yet.    Jeff is finishing them now, and it will be available in the 0.8.1 release. 
I will leave this open, so you will be notified once the code has been pushed.

**Comment by crnormand** [comment]
Fixed in v0.8.1
