### ISSUE TITLE
[Feature Request] MOOK Generator basic thrust damage

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#663]
Could you please give the MOOK Generator a field that translates to basic thrust damage.

Currently the *Dmg* field only translates to Basic Swing.

**Comment by crnormand** [comment]
You can enter both in the damage field by separating them with /

1d-1/2d

And it will split into thrust and swing damage.

**Comment by LordOHelmet** [comment]
Great! I was so clueless!
