### ISSUE TITLE
[Feature Request] Setting - Only "Equipped" Items provide bonuses, attacks, etc.

### ISSUE THREAD

**Issue by Plape2021** [crnormand/gurps#678]
Currently you can "un-equip" an item (and remove the associated bonuses, DR, attacks) by dragging it into Other Equipment. In my games, we've been using Other Equipment to indicate stuff stored "back at home", or in the trunk of a car -- somewhere not on their person (this is also the intended usage according to GCS Rich). 
Adding the option for "carried but unequipped" would help a lot in certain cases, like if a character wants to remove a piece of armor but keep it handy. The current implementation of dragging to Other Equipment throws off the Auto-calculate Encumbrance feature in these cases. It would also help for characters who have many weapons in their bag, but only use one at a time, to clean up their character sheet from having an unwieldy number of melee/ranged attacks visible. 

Other Equipment = Left it at home
Equipment (unequipped) = Carried in bag; contributing to encumbrance but not providing features
Equipment (equipped) = Equipped; providing bonuses + attacks etc

**Comment by crnormand** [comment]
Fixed: https://github.com/crnormand/gurps/pull/684/commits/10f68a47f49d88c20ea919538ea5b90bf8e1aa25
