### ISSUE TITLE
Items Error after upgrade to 0.9.12

### ISSUE THREAD

**Issue by the2bad** [crnormand/gurps#690]
I created some items in the last version and they were working fine.  After upgrade to 0.9.12 they stop working.  I cannot click on them anymore because nothing happens.  If I use their formula (your healing potion formula) I get this error: Error: You must define a valid Item type.  Also if I create a new item I cannot edit either.

<img width="228" alt="Error" src="https://user-images.githubusercontent.com/84711864/119332819-a711ef80-bc78-11eb-97a6-503e46d03096.png">

**Comment by crnormand** [comment]
Yes, we had a snafu with our deployment.   It has been fixed and release 0.9.13 is out.   You will need to update and then exit/restart Foundry to apply these changes.
