### ISSUE TITLE
OTF translation

### ISSUE THREAD

**Issue by Frerol** [crnormand/gurps#692]
Is it possible to somehow "translate" the attribute names for otf's? e.g.: will in portuguese is vontade, abbreviated vont
So it would be useful to type in [vont] instead of [will]
;)

**Comment by crnormand** [comment]
Note:   We should be able to add mappings to GURPS.PARSELINK_MAPPINGS based on the translations, and OtF should work.   Must verify no keys overlap.   I think we have all of the translations now... but they are not uniform.   Some are in the form "GURPS.Vision" and others "GURPS.attributesIQ".

**Comment by crnormand** [comment]
Done.   Will be in the 0.10.0 release.
![image](https://user-images.githubusercontent.com/8931036/120671975-e3ef9a80-c45f-11eb-8a8b-c8f441ac6865.png)
