### ISSUE TITLE
[BUG] Put created item into created item

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#700]
When putting one item, created with the item editor, into another item, created the same way, it leads to an error.
![equipment error](https://user-images.githubusercontent.com/80178910/119655596-0f540300-be2a-11eb-8c29-329fe60b5f7e.JPG)

**Comment by crnormand** [comment]
Until I can sort this out... I am going to disable Foundry Items from containing other things.  I know Foundry Items can be contained by non-Foundry Items.

**Comment by crnormand** [comment]
I've done a bunch of work on this for the 0.10.0 release.   This will work now.   However, you cannot transfer Items that contain things to other characters/players.   Which means if you a make a Bag of Holding that contains a magic sword, you will have to transfer the sword first, and then you can transfer the bag.   The recipient can add the sword back into the bag.
