### ISSUE TITLE
Support in-person play

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#701]
Just that, assume the players have paper copies of character sheets and roll their own dice. What needs to change?

**Comment by cefasheli** [comment]
I used to play in person so i have some experience on it. You don't need nothing more what we have today.

**Comment by LordOHelmet** [comment]
You should be able to quickly open the ADD and insert the damage.

So there should be a button or shortcut to open the ADD from the character sheet and/or the token.

**Comment by LordOHelmet** [comment]
Have a form factor that makes the game aid easily usable on small screens like smartphones or tablets which the players bring to the game table.
Maybe another charactersheet would be needed for this to work.

**Comment by mjeffw** [comment]
I've implemented a way to roll physical dice and enter them into the game system.
Damage can be applied by using chat commands. Example, to add 12 points of cut damage, type `/r [12 cut]`. If there is a target selected, the "Apply All to Mook" button will appear on it.

I'd say it's usable now. I'm closing this issue, but as we think of other things, please open issues for them.

@LordOHelmet -- We can't do much about the form factor of the game, Foundry is in charge of that. I can imagine a really cool system where what the player has is ONLY his character sheet on a phone or tablet, and he taps on OtF buttons which sends the command to the instance of Foundry that is running, but that's almost science fiction right now.
