### ISSUE TITLE
[Bug] created items don't add Attribute bonus correctly

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#702]
When equipping a created item that gives a bonus to DR it is not added to the DX-Number but instead it is appended.
![Arctic Clothing](https://user-images.githubusercontent.com/80178910/119972013-fbd3a400-bfb1-11eb-88ef-fd2958990258.JPG)

![attributes](https://user-images.githubusercontent.com/80178910/119972029-0130ee80-bfb2-11eb-9ae2-45a25bffe697.JPG)
DX was 10 before!

When the item gives a negative bonus it looks like this.
![negative attrib](https://user-images.githubusercontent.com/80178910/119972250-481ee400-bfb2-11eb-8f6d-cef0caff769f.JPG)

**Comment by crnormand** [comment]
Try executing the chat command /forcemigrate.   Somehow that character's DX is a string (not an integer) and JS is appending the bonus, and not adding it.   But I will leave this open, because the code should handle this anyway.

**Comment by crnormand** [comment]
Found the issues and it will be fixed in the 0.10.0 release
