### ISSUE TITLE
[Feature Request] OtF Formula: *Costs X[tracker alias]

### ISSUE THREAD

**Issue by engurrand** [crnormand/gurps#708]
Need I say more? 
I will say more: the uses would be legion. Using an elegant tracker template for the seven rounds of .45 colt government ammunition in my m1911's magazine would be all the sweeter if the attack roll could have a *Costs 1GovBullet OTF so when I roll, it auto-deducts the ammo from the mag. (Side-note, appending this OTF to the RoF selection in the modifier bucket would be even more mind-blowing but how would it know which ammunition you're using?).
Example the second: my group uses threshold limited magery (Thaumatology p76). I've already got an elegant and finely crafted template for the Tally with correct thresholds (thank you very much for that feature). It would be lovely to be able to charge Tally instead of FP for my spell costs and/or power stunts with a *Costs XTally OTF. Or, similarly, divert those costs to an ER tracker instead of FP.

Cheers.

**Comment by mjeffw** [comment]
I think this is a great enhancement; I'll see when I can squeeze this in. We may have to tweak the syntax a little bit. Maybe something like:

*Costs 1Tr:Tally

'Tr:' would indicate that the cost will be paid via a resource tracker, then followed by the tracker name (allowing for wildcards or quotes).

**Comment by engurrand** [comment]
this is Engurrand's giant grin of anticipation.

**Comment by crnormand** [comment]
Done.
You can use `*Costs X trN` or `*Costs X tr(Name)`  (which uses the same syntax as the /tr chat command).

![image](https://user-images.githubusercontent.com/8931036/120684123-56ff0e00-c46c-11eb-8112-730732cc4c39.png)
