### ISSUE TITLE
Dodge Scores Disappear at High Encumbrance

### ISSUE THREAD

**Issue by Snailramp** [crnormand/gurps#709]
Foundry 0.7.9, GGA .9.14, Encumbrance Light and above makes Dodge Scores/Buttons blank in Encumbrance/Move/Dodge block.  Reducing Encumbrance to None brings Dodge scores/buttons back.  Reproduced across multiple characters, no errors in console.  No modules active.

**Comment by crnormand** [comment]
Yup... I got the order of 2 methods wrong.    It has been fixed in 0.9.15.      Load the latest release and they should start appearing again.
