### ISSUE TITLE
[Bug] Resource Tracker setting

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#711]
Foundry 0.7.10
NaN 0.9.15
no modules active

1. When I try to edit a ressource tracker from the system setting it is no longer possible to enter "$" as an alias.
2. In the system setting it is no longer possible to edit the field for "current", "minimum" or "maximum". (from the character sheet it is still possible).

**Comment by mjeffw** [comment]
@LordOHelmet These aren't bugs, they work as designed. But we can enhance the trackers if it makes sense to do so.

For number 2 above:

**Current value**: In a template, it makes no sense to me to set the current value. That is a value that changes in play. The current value should always be '0' in a template where "Damage Tracker" is true (checked) and 'maximum' when 'Damage Tracker' is false (unchecked). 

**Maximum value**: The intent is to use the 'Initializer' field in the template list to determine the maximum value of a tracker. That may contain an exact number (just type that value into the initializer field in the table) or the value of a character attribute (using the Foundry's data path). For example, typing `attributes.IQ.value` into the initializer field means that the tracker will set the maximum to the character's IQ when it is added to the character sheet.

**Minimum value**: This is normally zero. It may make sense in some scenario to set it to some other value, but I don't know of any of those scenarios.

What do you intend to do with these fields in a resource tracker *template*?

For number 1: There is some reason I restricted the value of the alias. I will have to research it. What is your scenario for wanting to use a '$'? Is it to track money? Or something else?

**Comment by LordOHelmet** [comment]
@mjeffw 
Thanks for the clarification.

The intend is to use it for money.

**Current value** is for the starting wealth of the character.

**Maximum value** would be an abstract maximum of money the characters could gain. Obviously there is no real upper limit. But I just use it to calculate the thresholds for the tracker.

**Minimum value** would be sub zero - the characters could have depts.

But since it is no big deal to edit in on a character basis I will just do that. So there is no real need to change anything. I guess you have a lot to work on so don't bother _fixing_ this.
And for the alias I can go for something different.

**Comment by mjeffw** [comment]
Nice! In a game where money and debts are important and thematic, I suppose it is nice to have a graphical way to show the various thresholds you've got set up.

**Comment by cefasheli** [comment]
Why do you not create an item for it? Is easy, they can share between players etc.

**Comment by LordOHelmet** [comment]
For a better overview I like to keep it in one place. With items there could be multiple which could lead to confusion.

Secondly I like to be able to use thresholds and like to have color indicators for this.
