### ISSUE TITLE
[Bug] skills granted by items aren't used by the item itself

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#712]
When an item is created to give the user a skill

![Axe](https://user-images.githubusercontent.com/80178910/120449617-dff44780-c38f-11eb-91b0-bdbfb58d9d94.JPG)

this skill isn't used by the item itself for the porpuse of attack.

![Item Skill](https://user-images.githubusercontent.com/80178910/120449717-fb5f5280-c38f-11eb-9c8d-32ae94ed16a3.JPG)

**Comment by crnormand** [comment]
It works in the upcoming 0.10.0 release, so I am going to close this.

![image](https://user-images.githubusercontent.com/8931036/120574699-d4376e00-c3ed-11eb-81cc-05a5168a1db6.png)

![image](https://user-images.githubusercontent.com/8931036/120574762-e9140180-c3ed-11eb-8c0f-2eb33029e7f0.png)

![image](https://user-images.githubusercontent.com/8931036/120574912-21b3db00-c3ee-11eb-824a-8d715452ddc4.png)

**Comment by LordOHelmet** [comment]
The issue still persists.
![Broadsword](https://user-images.githubusercontent.com/80178910/120857954-5bb5e600-c582-11eb-967a-e387138043dd.JPG)
![Skill](https://user-images.githubusercontent.com/80178910/120857967-607a9a00-c582-11eb-9e14-368dcad20870.JPG)

**Comment by crnormand** [comment]
Granted

**Comment by crnormand** [comment]
Ok, I "think" I fixed it this time ;-)   It will be in 0.10.3.
