### ISSUE TITLE
[Feature Request] Add Margin of Failure/Success of Previous Roll to a Roll Formula

### ISSUE THREAD

**Issue by Plape2021** [crnormand/gurps#713]
The specific use case I'm imagining would be rolling against an Attribute and adding the Margin of Failure/Success to the formula of a Rollable Table.
I guess the example from Basic Set would be Fright Check (roll vs. Fright Check and add the result to a 3d6 roll to determine effects). B360

The Rollable Table's formula could be something like 3d6 + /mof [Fright Check] etc.

**Comment by crnormand** [comment]
How about this... when you make a "targeted roll", one that determines success or failure, if the margin of success (or failure) is not zero, the chat window will show a "modifier" OtF button, which you can click on, or drag to the modifier bucket,

![image](https://user-images.githubusercontent.com/8931036/121464257-8e485000-c981-11eb-825c-cc08acff6c69.png)

Then the reaction table formula just needs to be "3d6 + @gmodc" which rolls 3d6, and then adds the **G**lobal **MOD**ifier bucket (and then **C**lears it).

**Comment by crnormand** [comment]
I am going to close this, because I think this does what you need... but not in the way you asked for it.   I think this is a bit more generic, since the GM might add the margin of success, plus some luck, and other factors into the modifier bucket, and THEN roll the reaction/fright check.
