### ISSUE TITLE
[request] ADD Apply Injury opening direction

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#714]
In the ADD the "Apply Injury" dropdown opens donwards which lets it partly dissapear.
![ADD pop up](https://user-images.githubusercontent.com/80178910/120657949-49a24d80-c485-11eb-9173-e4e514e1e4e0.JPG)
It would be nice if it opened upwards.

It would also be nice if there would be a shortcut, to "Apply Injury (Quietly)". Like holding Shift with skill rolls to make them private.

**Comment by mjeffw** [comment]
Fixed. I'll take some time to consider how I want to implement the shortcut.

**Comment by mjeffw** [comment]
file:///var/mobile/Library/SMS/Attachments/43/03/F6D527A0-69A8-4658-95F5-DE77CA1C3369/Image%206-7-21%20at%204.19%20PM.jpeg

**Comment by mjeffw** [comment]
![image](https://user-images.githubusercontent.com/7349413/121082595-520fc680-c7ac-11eb-90bc-3bbb01068f18.jpeg)
