### ISSUE TITLE
/mook doesn't allow skills with hyphens in the name like "knot-tying"

### ISSUE THREAD

**Issue by dripton** [crnormand/gurps#716]

**Comment by dripton** [comment]
I created a mook with /mook and then edited it to have "Knot-Tying-15".  The parser didn't like the hyphen in mid-skill-name and when I clicked "TEST MOOK" said "Unable to create Mook error in skills" and the skills box said "???: tying-15" is not a number.

Looks like you need to find the last hyphen in the skill line rather than the first.  Not exactly a show-stopper though; I can just call it "knottying" for now.

**Comment by crnormand** [comment]
Good catch!   It will be fixed in the new release.
