### ISSUE TITLE
[Bug] items no longer dragable

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#721]
Foundry via Forge 0.8.6
NaN 0.10.0
No modules

After the latest update, characters freeze and can no longer be opened after an item is droped on them.

**Comment by crnormand** [comment]
I believe was an issue with unlinked actors (namely mooks).   The 0.10.2 update fixed code that failed horribly if an Item was given to an unlinked actor (it worked for linked actors).   

I am going to assume this was the issue, and close this.
