### ISSUE TITLE
Blocking chaacter sheet imports

### ISSUE THREAD

**Issue by cefasheli** [crnormand/gurps#727]
I have 5 tables with 4~6 players each and is being hard to mantaing the control over it. Have some way to block players to upload character sheet?

**Comment by 3darkman** [comment]
this would be some system setting like "can actor owner use import function?"

**Comment by crnormand** [comment]
Added to 0.10.3.
![image](https://user-images.githubusercontent.com/8931036/121423951-cb3f2300-c93e-11eb-9122-fe3f16b68271.png)
