### ISSUE TITLE
Item Cost/Weight Counted Twice (GCA Parent/Child Containers)

### ISSUE THREAD

**Issue by CorvusCaurinus** [crnormand/gurps#729]
I'm using GCA for my characters, and within GCA we can set a piece of equipment as the "Child" of a "Parent" container. This updates the total weight and cost of the Parent item to include the weight and cost of the Child items:

![ParentEquipGCA](https://user-images.githubusercontent.com/85463974/120944343-d3058a00-c6e8-11eb-897f-af85164e1262.PNG)

However, when I import this character the Foundry sheet keeps the combined weight/cost from GCA, and then adds the cost and weight of the Child items a second time:

![ParentEquipFoundry](https://user-images.githubusercontent.com/85463974/120944413-368fb780-c6e9-11eb-8902-1b6b96f0f3d3.PNG)

I can of course get around this by removing the Parent/Child relationship in GCA, and I'm not sure if this is something that would even be fixable, but it would be nice to be able to keep that relationship for item organization and so on. 

Here's a sample GCA character sheet, if it helps:
[ParentEquipTest.zip](https://github.com/crnormand/gurps/files/6605189/ParentEquipTest.zip)

**Comment by crnormand** [comment]
Hmmm.. this is an incompatibility with GCS and GCA.   GCS sends "weight" and "weightsum" for each object... and currently, we only get "weight" from the GCA export.   And the GCA "weight" is the sum of all of the weights inside of it.

**Comment by crnormand** [comment]
Ah, I found it.   GCA has "baseweight" and "weight", and GCS has "weight" and "weightsum".    I've updated the GCS export script.

You can download it from the Google drive location:  https://drive.google.com/file/d/1vbDb9WtYQiZI78Pwa_TlEvYpJnR_S67B/view?usp=sharing

Or I've attached it here:  
[export to Foundry VTT.zip](https://github.com/crnormand/gurps/files/6626957/export.to.Foundry.VTT.zip)

**Comment by CorvusCaurinus** [comment]
I just noticed that it appears this is back, unfortunately—and it's doing the same thing with the item costs, as well. 

In GCA:
![image](https://user-images.githubusercontent.com/85463974/126860185-a36d1687-a897-43c9-8c8a-5683f84b87af.png)

In Foundry:
![image](https://user-images.githubusercontent.com/85463974/126860201-3c322c1a-ab15-48ee-849c-ec1cd2dbd3ea.png)

For the costs, GCA appears to have "basecost" and "cost"—and I see it's also got "childrencosts" and "childrenweights" if that might be useful?

Here's a .zip of the test character file and export I was using:

[GCAParentChild.zip](https://github.com/crnormand/gurps/files/6872029/GCAParentChild.zip)
