### ISSUE TITLE
Injury Tolerance: Unliving hit location modifiers do not match the GURPS: Zombies clarification

### ISSUE THREAD

**Issue by JordanMcCray** [crnormand/gurps#758]
The damage calculator doesn't incorporate the clarifications from Zombies (page 110) of the interaction between the Unliving advantage and the various hit locations (IE Unliving doesn't include No Brain so everything [except toxic] still does x4 on Skull hits, but in the damage calculator Unliving still decreases certain damages from x4 to the reduced Torso damage.)

**Comment by mjeffw** [comment]
Fixed with issue #815
