### ISSUE TITLE
Item DR doesn't allways add up

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#761]
Adding two items to a character that give a DR bonus:
![leather armor](https://user-images.githubusercontent.com/80178910/121708964-5a337300-cad8-11eb-8726-b726a2629aa3.JPG)
`DR+2 torso groin vitals`
![Arctic](https://user-images.githubusercontent.com/80178910/121709076-76cfab00-cad8-11eb-91fd-efdb96a5bec9.JPG)
```
DX-1
DR+1
```
The result doesn't add up.
![character sheet](https://user-images.githubusercontent.com/80178910/121709231-9ff03b80-cad8-11eb-95f8-1d50309122fc.JPG)

This happens when the areas where the DR should be applied aren't the same.
In this case the first item gives DR to torso groin and vitals, the second item to all areas. This doesn't match.

**Comment by LordOHelmet** [comment]
I mitigated it be using
`DR+1 eye skull face *arm *leg torso groin hand foot neck vitals`
on the second item.

**Comment by crnormand** [comment]
Good workaround!

I found the issue and it will be fixed in 0.10.5.
