### ISSUE TITLE
Items within container not sortable

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#764]
![sorting](https://user-images.githubusercontent.com/80178910/121736887-7515df80-caf8-11eb-8d3f-1b2650448e52.JPG)

**Comment by crnormand** [comment]
I got rid of the 'add' menu options (I mean, who really uses them?  If a player wanted to add equipment, they will most likely just press the "+" sign in the header).    And added 2 sort menu options:

![image](https://user-images.githubusercontent.com/8931036/121742957-906bf500-cace-11eb-97bc-ec40118dd70f.png)

It will be in 0.10.5
