### ISSUE TITLE
Quantity of items is overwritten during import

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#766]
The quantity of items is reset to the original value the item had when created.
Later changes to quantity on the character sheet are overwritten.

**Comment by crnormand** [comment]
Can you explain this more?   To have equipment ignore the imported QTY/Count value, you must open the editor for that equipment (double click on it), and turn on "Check this to save the current County/QTY/Uses during import".

![image](https://user-images.githubusercontent.com/8931036/121743191-f789a980-cace-11eb-86ae-b8f9201350bf.png)

**Comment by LordOHelmet** [comment]
I create a new item using the Foundry "Create Item" panel:
![create item](https://user-images.githubusercontent.com/80178910/121744045-98de2300-cb02-11eb-8283-2b224e7f07bb.JPG)

I edit the item and set a quantity - e.g. 15:
![arrow quantity](https://user-images.githubusercontent.com/80178910/121744098-adbab680-cb02-11eb-8eae-640ab55cac98.JPG)

I drag the item on a character. Reduce the quantity with the minus button.

And when the character gets reimported the quanitity is reset to - in this example 15.

This als ohappens when the quantity is changed on the character and than the item is reopened on the character sheet by double clicking it.

![lantern](https://user-images.githubusercontent.com/80178910/121744664-86181e00-cb03-11eb-9f81-7d5f5e6c5ba0.JPG)

**Comment by crnormand** [comment]
Yep.. understood now.   THANK YOU, and I mean it.   You are a great help to Nick and me!

**Comment by crnormand** [comment]
Fixed.   My update path was wrong.   I had "data.count", and it was supposed to be "data.eqt.count".   It will be in the 0.10.5 release.
