### ISSUE TITLE
Need a spot for TL on itens

### ISSUE THREAD

**Issue by cefasheli** [crnormand/gurps#780]
This is pretty important when you are dealing with diferent itens with same name like assault boots or tactical vest, some of them the only difference is the DR. So you need to open the iten and go in another tab to the DR to identifiy an item. A spot for TL can solve it. And GCS give this data

**Comment by crnormand** [comment]
Done.   https://github.com/crnormand/gurps/pull/781

![image](https://user-images.githubusercontent.com/8931036/121930184-162ab300-cd10-11eb-95a7-6f23f0b0c613.png)
![image](https://user-images.githubusercontent.com/8931036/121930241-26db2900-cd10-11eb-97d0-27eaaf5a4e8f.png)
