### ISSUE TITLE
Make multiple rolls for large numbers of NPCs/Mooks with a "single" click

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#785]
Useful for when a GM needs to make a mass roll for a lot of characters.

**Comment by mjeffw** [comment]
Here's a common use case:

Bard plays "Song of Warning"; all enemies within 8 yards have to win a Quick Contest of Will. If an enemy fails, it must move outside the radius and remain outside for Margin of Failure rounds.

I think the flow is like this:

1. Bard rolls Will + Bardic talent, notes the Margin of Success
2. GM selects all enemies within 8 yards; "requests" them to make a Will + Magic Resistance roll with a target of Bard's Margin of Success.
3. Any failures, add a "Warning" Active Effect with a duration of enemy's Margin of Failure seconds.

**Comment by crnormand** [comment]
Fixed/closing.   You will soon be able to accomplish this with the following:

Determine the margin of success (X), and use it in this OTF:

`/sr [/if ! [Will - X] {/st +  mentalstun @self}]`

Which will execute the IF check against all of the selected tokens, and if it fails, it will turn on mentalstun.

The "@self" is required so that it only executes against the current token in the "selected roll" command.     NOTE:   This requires code that will be in the next 0.15.X release.
