### ISSUE TITLE
[Feature Request] Allow hiding/showing the navigation tabs at the bottom of the sheet without going to the settings

### ISSUE THREAD

**Issue by Grayscalae** [crnormand/gurps#799]
As per title, allow the user to hide or show the bottom navigation tabs at the bottom without leaving the character sheet enviroment.

**Comment by crnormand** [comment]
I don't know of a good way to show this.     But it seems to me there are 2 camps of users... the users that want to see and use the navigation bar, and the users that don't want it (I am one of these).     So it seems to me that the the real issue is if you accidentally turn off the feature, there is no quick way to turn it back on.

So I included a dialog that is displayed if you click on the close gadget:
![image](https://user-images.githubusercontent.com/8931036/122653435-68097980-d112-11eb-8384-4557c2de95d1.png)

**Comment by mjeffw** [comment]
I think we can use CSS to hide the navigation bar when the 'X' is clicked, and also redisplay it.

**Comment by Grayscalae** [comment]
That's useful. 

Alternatively, I'd also consider:

- adding a "show/hide navigation buttons" at the top of the sheet, next to import, editor, sheet etc
- in addition to the above, make it so the bar is fixed at the bottom and the scrollable part of the sheet considers it as part of the window frame (in essence, make it behave like the ribbon bar in the Office line of products).

Or something else along these lines.

**Comment by mjeffw** [comment]
> in addition to the above, make it so the bar is fixed at the bottom and the scrollable part of the sheet considers it as part of the window frame (in essence, make it behave like the ribbon bar in the Office line of products).

That will be harder, because the parts of the window outside the character sheet are actually managed by the base Foundry software. I'll look at it though.


>

**Comment by Grayscalae** [comment]
I see. 
Something for the back burner I guess, things work great as they are already.

> > in addition to the above, make it so the bar is fixed at the bottom and the scrollable part of the sheet considers it as part of the window frame (in essence, make it behave like the ribbon bar in the Office line of products).
> 
> That will be harder, because the parts of the window outside the character sheet are actually managed by the base Foundry software. I'll look at it though.
> 
> >

I see. 
Something for the back burner I guess, things work great as they are already.

**Comment by mjeffw** [comment]
I'm actively working on this issue. 😐

**Comment by crnormand** [comment]
Sorry.. I thought you were working on https://github.com/crnormand/gurps/issues/800

**Comment by mjeffw** [comment]
![image](https://user-images.githubusercontent.com/7349413/123278806-4115c380-d4d5-11eb-8ab9-2cc78664b0e9.jpeg)
