### ISSUE TITLE
Actor -> handleItemDrop can be improved

### ISSUE THREAD

**Issue by typhonrt** [crnormand/gurps#803]
Greets.. In fixing the following bug for the latest significantly improved Forien's Quest Log I have some suggestions for how `handleItemDrop` can be improved.

https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/issues/25

The code in question is [handleItemDrop](https://github.com/crnormand/gurps/blob/main/module/actor.js#L1847-L1858)

Typically the complete item / `document.data` in 0.8.x is in the `data` field of dragData. 

`handleItemDrop` attempts to retrieve the item data from the game.items for `dragData.id` instead of accepting the item data in `dragData.data`. A better method is either accepting `dragData.data` as the item drop or constructing a UUID from the data drop and then invoking fromUuid(<uuid>) and get the document back from Foundry core. 

You can construct a UUID like this:
```
const uuid = typeof data.pack === 'string' ? `Compendium.${data.pack}.${data.id}` : `${data.type}.${data.id}`;
```

A compendium item drop will have this data:
```json
{
  "type": "Item",
  "pack": "world.test",
  "id": "4zmX7jjSoyZ2BvRr"
}
```

This certainly got me to improve the FQL data transfer of items to add an `id` field and also `uuid` and `pack` if a compendium item which fixes the current situation w/ the Gurps implementation of `handleItemDrop`. Of course this only works for item drops that are stored in world items / `game.items` given the current implementation of `handleItemDrop`. I suggest improving this method to accept the `dragData.data` as the item being dropped if that field exists or as described above create a UUID and invoke fromUUID to get the document and not search `game.items`.

**Comment by crnormand** [comment]
Thanks for the issue... but something is odd here.  When I drag an item from the Foundry Item's list, the dragData only contains:

{
	type: "Item",
	id: "wnbucpjnMmXKqwx0"
}

Under what circumstances would it contain a 'data' element?

**Comment by typhonrt** [comment]
When you drag sheet to sheet or anywhere there is a data copy. More important probably is to support compendium packs.

**Comment by crnormand** [comment]
Your point about compendiums is great.   And I will implement the fromUuid() query so that it can handle Items drops from anywhere.  We already handle drags between sheets (and yes, it passes the data ;-) )

Thanks for pointing this out!

**Comment by crnormand** [comment]
Done... and tested with a compendium Item.
