### ISSUE TITLE
[BUG] Collapse container

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#838]
When a item container is collapsed it is displayed in an awkward way, overwriting other lines.

Open:
![open](https://user-images.githubusercontent.com/80178910/123464187-c93abc80-d5ec-11eb-8f4d-e634b6ae4f67.JPG)

Collapsed:
![collapsed](https://user-images.githubusercontent.com/80178910/123464213-d3f55180-d5ec-11eb-8821-fee7636f7243.JPG)

**Comment by crnormand** [comment]
Odd... what browser are you using?   It works on Windows Chrome:
![image](https://user-images.githubusercontent.com/8931036/123464844-58c77780-d5bb-11eb-8920-8f214dbe174f.png)

![image](https://user-images.githubusercontent.com/8931036/123466289-29196f00-d5bd-11eb-9893-d386b60a0cb8.png)

**Comment by LordOHelmet** [comment]
It seems to be an issue with another module. When I deactivate everything it works!
Now I just have to figure out which one it is of the 85 modules I am using . . .

**Comment by LordOHelmet** [comment]
![chrome](https://user-images.githubusercontent.com/80178910/123469437-55e87900-d5f3-11eb-9280-407a93343d59.JPG)

**Comment by LordOHelmet** [comment]
Found the culprit Fantasy UI https://github.com/iotech-fvtt/fantasy-ui/tree/0.1.21
