### ISSUE TITLE
[BUG] /light command LightIntensity sets wrong value

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#840]
When the `/light` command is used in conjunction with a LightIntensity value the actual value on the character is set differently.

`/light 6 2 360 #dcc86e:0.5 torch 2 2`
Should produce a Light Intensity of **0.5** but after calling the command in chat the actual Light Intensity of the token is set to **0.7**!

0.1 results in 0.3
0.2 results in 0.45
0.3 results in 0.55
0.4 results in 0.65
0.6 results in 0.75
0.7 results in 0.85
0.8 results in 0.9
0.9 results in 0.95
1.0 results in 1.0

**Comment by crnormand** [comment]
There isn't anything I can do here.   We are SENDING the correct lightAlpha setting... and Foundry, under the covers, is changing it.

Executing:   `/li 6 2 360 #dcc86e:0.1 torch 2 2`

Sends the following update,

```
Token Light update: {
	dimLight: 6,
	brightLight: 2,
	lightAngle: 360,
	lightAnimation: {
		type: "torch",
		speed: 2,
		intensity: 2
	},
	lightColor: "#dcc86e",
	lightAlpha: 0.1
}
```

But afterwards, it shows:
![image](https://user-images.githubusercontent.com/8931036/123473263-53235f00-d5c6-11eb-8f21-2886aaa7d795.png)

**Comment by LordOHelmet** [comment]
Ok, I`ll adjust my light sources accordingly.
