### ISSUE TITLE
[BUG] executing /anim command

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#841]
I just tried to call the `/anim` command.

Activated modules:
![modul](https://user-images.githubusercontent.com/80178910/123473150-75ce6b80-d5f8-11eb-8bd4-6c53166ed70c.JPG)

Called animations:
![anim](https://user-images.githubusercontent.com/80178910/123472963-2ee07600-d5f8-11eb-8493-c9add2e61921.JPG)

Error:
![error](https://user-images.githubusercontent.com/80178910/123472990-3a33a180-d5f8-11eb-99b5-644d95ff4b96.JPG)

**Comment by crnormand** [comment]
Hole crap... they changed the damn API.     Thanks

**Comment by crnormand** [comment]
Found it.    It will be fixed in the next release.
