### ISSUE TITLE
"Level" column in melee/ranged weapons goes blank or NaN after using resource tracker.

### ISSUE THREAD

**Issue by Snailramp** [crnormand/gurps#848]
For items not including punch/kick, when incrementing a resource tracker (+/- buttons or with an OTF), the "level" column for melee and ranged weapons goes blank or NaN.  Equipping and unequipping an item in inventory, or closing and reopening the character sheet fixes the problem.  Using Foundry 0.8.7, Gurps system .11.3.

**Comment by crnormand** [comment]
Thanks for finding this.   I have a hack that will make this work in the next release (until I can find a better solution)
