### ISSUE TITLE
[Enhancement?] "Cautious Gamemaster's Pack" Compatibility

### ISSUE THREAD

**Issue by patrickburk1988** [crnormand/gurps#850]
This isn't a high-priority issue or anything, but I discovered today that the GURPS system has a minor incompatibility with the Cautious Gamemaster's Pack module.

The original issue (and the module developer's suggestion) can be found here: https://github.com/cs96and/FoundryVTT-CGMP/issues/4

**Comment by crnormand** [comment]
After a great discussion:   https://github.com/cs96and/FoundryVTT-CGMP/issues/4
It is fixed.
It will work in the next release.
