### ISSUE TITLE
[Feature request] make available Character Sheets a system setting

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#855]
Would it be possible to make it a system setting which Character Sheets are available to switch between?

With the latest release the Combat sheet has been demoted to the frustration of some players. Because now in Tabbed View they always have to switch between Stats, to have their Dodge, Encumbrance, HP, FP etc at the ready, and Combat to have their attacks.
And players can't switch their Character Sheets to combat view. So only Full, Tabbed and Simple is available to them.

**Comment by crnormand** [comment]
Done.
![image](https://user-images.githubusercontent.com/8931036/124325507-becf7400-db52-11eb-8a30-07c1aaf26965.png)

![image](https://user-images.githubusercontent.com/8931036/124325536-ce4ebd00-db52-11eb-9a3c-8c7ff53e99fa.png)
