### ISSUE TITLE
GCA Export: Equipment with Modified Weight Retains Unmodified Weight when Imported

### ISSUE THREAD

**Issue by CorvusCaurinus** [crnormand/gurps#864]
In GCA, equipment that has a modifier that changes the weight of an item retains the unmodified "baseweight" in the .gca4 file, but also has a modified "weight" that is displayed to the user. 

So, we end up with something like this in GCA:
![GCAweight](https://user-images.githubusercontent.com/85463974/124510681-2f5fd600-dd89-11eb-9a06-414ef6eabb9b.PNG)
(Unmodified; weight x0.70; weight x0.25)

When I export that, I get both original "weight" (GCA "baseweight") and "weightsum" (GCA modified "weight") in the export file. 

However, when I import into Foundry, I get this:
![Foundryweight](https://user-images.githubusercontent.com/85463974/124510781-6d5cfa00-dd89-11eb-87f2-fe79064cd7f2.PNG)

It looks like the import is ignoring the "weightsum" because there are only one of each of the items—if I add a second one of either of the modified breastplates in GCA and import again, it then starts displaying the "weightsum" as the "weight":

![Foundryweight2](https://user-images.githubusercontent.com/85463974/124512221-b2cef680-dd8c-11eb-84f7-7321f305820f.PNG)

Here's a .zip with the GCA character file and the export:
[EquipModWeightChar.zip](https://github.com/crnormand/gurps/files/6765965/EquipModWeightChar.zip)

If it helps, the Masterful Tailoring modifier is from the Low-Tech GCA data file, and the SM -2 modifier is from the Low-Tech Companion 2 - Weapons and Warriors data file.

**Comment by crnormand** [comment]
Fixed in next release
