### ISSUE TITLE
[BUG(?); QoL] Display Chat message and assing Status Icons when using "Status Effects: Auto Reeling and Tired"

### ISSUE THREAD

**Issue by Grayscalae** [crnormand/gurps#877]
Using 
![image](https://user-images.githubusercontent.com/86167546/125520983-8f7cb0f8-8667-437d-8852-629baef7ee8c.png)

When a token reaches such value, no message is displayed on chat, neither the tokens assumes the Reeling/Tired Icon (as is the case with the HT check for Stun and Knockdown, for instance).

Suggestion: make it so when the option is checked, when a token reaches <1/3 the score, that a chat message is displayed and the token is assigned the appropriate Status Icon automatically.

**Comment by crnormand** [comment]
As of 0.12.x, reeling and tired are now status tokens that are applied to the token.
