### ISSUE TITLE
[Feature Request] In the Tabbed Sheet, show current Dodge and Current Move when under "Combat"

### ISSUE THREAD

**Issue by Grayscalae** [crnormand/gurps#881]
As for the title, add a line for Current Dodge (with rollable button) and Current Move in the Combat tab, like this:

![image](https://user-images.githubusercontent.com/86167546/125871957-e06fae66-6066-4bbe-b424-a1ce5351afde.png)

Cheers

**Comment by crnormand** [comment]
I've added a quick line that displays the Dodge and Move (and allows you to click on the Dodge button to roll it).     When Nick gets time, he will make it look better.

![image](https://user-images.githubusercontent.com/8931036/126224226-87a14f44-5301-4e3c-b733-4fbb55857afd.png)

So I am leaving this issue open until he can apply his magic.

**Comment by mjeffw** [comment]
Added Encumbrance, Dodge, Move and Lifting Things panels to Combat sheet.

**Comment by mjeffw** [comment]
![image](https://user-images.githubusercontent.com/7349413/132402462-7038984c-0af2-4639-a223-fd4f70949498.jpeg)
