### ISSUE TITLE
[Feature Request] Hide Item icons

### ISSUE THREAD

**Issue by GuineaThePig** [crnormand/gurps#884]
Imported items that do not have a unique icon still have the default one pop out and it can cover some of the description text and look a bit jarring. Having the option to disable icons for those of us that do not use them would be much appreciated. Even better would be an option to only show the icon if it's not the default satchel one, that way we can still have unique icons for cool items if we want them.

**Comment by crnormand** [comment]
Done.   Items that use the default item-bag.svg will not show the icon
