### ISSUE TITLE
[Feature Request] Always display the Maneuver Status Icon as the first Status on a token

### ISSUE THREAD

**Issue by Grayscalae** [crnormand/gurps#887]
The default behavior for status are to be displayed newest to oldest. It would be nice, and easier to assess at a glance, if the Maneuver Status Icon was always displayed first, regardless of other conditions.

**Comment by mjeffw** [comment]
I've completed this and it appears to work unless a module interferes. For example, with Illandril's Token HUD Scaler, it randomly goes back to unsorted order (probably the order in which the effects were turned on). I've opened an issue with the author of Illandril's Token HUD Scaler to see if there is something he or I can do to address that. Closing this issue for now.
