### ISSUE TITLE
Light Command Doesn't Take Decimals

### ISSUE THREAD

**Issue by CorvusCaurinus** [crnormand/gurps#888]
When using the /light command, it will only take whole numbers. 

For instance, if I try to use /light 2.9 0.7, I wind up with:

![image](https://user-images.githubusercontent.com/85463974/126116042-c85e28b2-3f13-459e-bdb2-9bf70b4600db.png)

**Comment by crnormand** [comment]
Fixed in next release.   Thanks for pointing this out!
