### ISSUE TITLE
Disable Weapons Stats When Weapons Are In Other Equipment Or Unequipped

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#891]
I would like to suggest the option to disable weapons in the melee/ranged weapon tabs when the said weapons are in Other Equipment or Unequipped. This helps the players when they have a bunch of stuff on them, especially if they have chests or lockers that they dump into to store it.

**Comment by crnormand** [comment]
Ohhh.... I like this idea... Thanks!   It won't make it into the current release (0.11.5), but hopefully soon afterwards.

**Comment by crnormand** [comment]
This was just such a cool idea, I had to implement it.   https://github.com/crnormand/gurps/pull/907
It will be in the next release.
![image](https://user-images.githubusercontent.com/8931036/126830087-6b494cd5-46c0-460e-8dc8-500d26c7c8d1.png)
