### ISSUE TITLE
GCA Export - Flexible DR (*) Multiplies if Combined With Other DR

### ISSUE THREAD

**Issue by CorvusCaurinus** [crnormand/gurps#908]
This appears to be related to [Issue 865](https://github.com/crnormand/gurps/issues/865), or the fix for it. 

If a character has two different types of DR, they will multiply rather than add if one of them is flexible, almost certainly because of the asterisk:
```
<location type="string">Vitals</location>
<dr type="string">2*+3</dr>
</id-00005>
```

Gives:
![image](https://user-images.githubusercontent.com/85463974/126859431-c4c4e84e-93ad-4f98-82bd-f0077191f88a.png)

**Comment by CorvusCaurinus** [comment]
This new issue: https://github.com/crnormand/gurps/issues/922 seems to be connected with this one.

**Comment by crnormand** [comment]
The code to try to automatically add DR bonuses together was trying to convert that to a math formula.   I've changed it to only convert simple X + Y formulas and let all of the rest go through.   It will be fixed in the next release.
