### ISSUE TITLE
Rolling issue after upgrading from v0.11.4.

### ISSUE THREAD

**Issue by mehalforc** [crnormand/gurps#914]
After I updated from v0.11.4 to any of the other versions higher, I have an issue on the character sheet.
If I, the GM, click on (IQ lets say), it rolls as if the GM clicked on it instead of saying the name of the character that rolled it, in the chat window.
In v0.11.4, it said the character name in the chat window.
I would like to roll as the character, as before. (Unless this is a bug/change?)
I have the same character sheet, just downgraded until it started working as desired...  v0.11.4.
I have a fresh install of Foundry VTT and the game aid, to latest versions. (That is how I found out.)

Thanks

**Comment by mjeffw** [comment]
@crnormand I reproduced this behavior. If there is no token selected, the roll is done as "Gamemaster". If a token is selected, the roll is done as that character regardless of who the character sheet belongs to.

In the image attached, all three of these rolls where made by clicking on Drex's character sheet. 

![image](https://user-images.githubusercontent.com/7349413/128604377-3dc7c1db-2c7f-44d6-b9ff-5a4c4452b9fa.png)

Do you want to fix this, or shall I take a look?

**Comment by mjeffw** [comment]
Fixed, and will be in the next release.
