### ISSUE TITLE
Add knockback calculation B378

### ISSUE THREAD

**Issue by ssveter1** [crnormand/gurps#918]
I would like to see the addition of a knockback macro with inputs for double knockback, reduced knockback, and so on.
This would be a great addition to the Supers genre games.

**Comment by mjeffw** [comment]
I propose adding a new System setting for the double knockback damage modifier, "Standard" or "Modified". Standard would be the modifier as written on page B104: calculate knockback as usual and double the number of hexes. Modified would be the alternate approach from Powers, page P101: calculate basic damage x 2 for the purposes of determine knockback only.

Either way, the NaN GURPS game aid will look for 'dkb' following the damage type, such as `[3d cr dkb]`.

**Comment by mjeffw** [comment]
"dkb" was implemented, will be in the next release.

**Comment by mjeffw** [comment]
@ssveter1 -- where are the rules for reduced knockback? I'm not seeing it in Basic and Powers and I don't know where else it might be.

**Comment by mjeffw** [comment]
"nkb" (no knockback) damage modifier was implemented, will be in next release.

**Comment by benz-72** [comment]
Will the implementation cause tokens to move, or output a knockback vector, or list text with knockback magnitude?

**Comment by mjeffw** [comment]
The Apply Damage Dialog has always calculated knockback. I've simply added 'dkb' and 'nkb' damage modifiers.
 
Below is an image of knockback being applied.

![image](https://user-images.githubusercontent.com/7349413/130365363-f426b2a0-5bd4-4532-89b2-144fe01c023c.png)

If you click on the button to the right of the text, it will put the knockback effect in the chat window:

![image](https://user-images.githubusercontent.com/7349413/130365401-01c31c3e-d836-4ac6-ae54-7d6891a6f464.png)

If you click on the button with the text "Drex: roll DX-5, Acrobatics-5, or Judo-5 or fall!" the game system will roll that character's best attribute between DX, Acrobatics, and Judo, and if that roll fails, it will apply the 'prone' status effect to the character's token:

![image](https://user-images.githubusercontent.com/7349413/130365496-618f3e77-0463-4056-8cd5-ece5518be922.png)

There are no plans to actually move the token or display the vector of movement; that will be left to the GM/player.

**Comment by benz-72** [comment]
Excellent, thank you very much. Sorry I didn’t see that before. 

Have a fantastic day.

**Comment by mjeffw** [comment]
I'm closing this issue as I've implemented 'nkb' and 'dkb'. Please open a new issue for other damage modifiers.
