### ISSUE TITLE
Broadcast lastTargetedRoll information to all clients.

### ISSUE THREAD

**Issue by crnormand** [crnormand/gurps#920]
So that a GM could use a macro like:

```
let sel = canvas.tokens.controlled
if (sel.length == 2) {  
  let a1 = sel[0].actor
  let a2 = sel[1].actor
  let d1 = GURPS.lastTargetedRoll[a1.id]
  let d2 = GURPS.lastTargetedRoll[a2.id]
  if (d1 && d2) {
    if (d1.margin > 0 & d1.margin > d2.margin)
      ui.notifications.info(a1.name + ' wins')
    if (d2.margin > 0 & d2.margin > d1.margin)
      ui.notifications.info(a2.name + ' wins')
  }
}
```
To do a quick contest between characters, etc.

**Comment by mjeffw** [comment]
You read my mind! That's always been the plan. 

One thing that I don't like about lastTargetedRoll is that it is tied to the actor only. Unlinked tokens from the same actor overwrite each other.

**Comment by crnormand** [comment]
Done.   

GURPS.lastTargetedRoll is local to the current client and is NOT broadcast to all clients.
GURPS.lastTargetedRolls is an object of last targeted roll chatdatas, indexed by both the actor ID and the token ID.    This information is broadcast to all clients.
