### ISSUE TITLE
GCA Export - SyntaxError: Unexpected End of Input when importing Flexible DR (*)

### ISSUE THREAD

**Issue by CorvusCaurinus** [crnormand/gurps#922]
This appears to be related to https://github.com/crnormand/gurps/issues/908.

In this case, the import process is attempting to use the asterisk for flexible DR as a multiplier, but if the character only has that one source of DR, there's nothing for it to multiply by, which appears to be causing the Unexpected End of Input.

**Comment by crnormand** [comment]
Agreed.   Closing
