### ISSUE TITLE
Blind Roll does not work on standard dice roll otf

### ISSUE THREAD

**Issue by Impyreah** [crnormand/gurps#924]
The blind roll modifier command does not work on a standard dice roll in a on-the-fly formula. The below macro correctly adds the modifier bucket however the roll that is executed is a public roll to everyone.

`/clearmb
/sel @self
/r [+2 Modifier 1]
/r [+4 Modifier 2]
/r [+2 Modifier 3]
/r [!3d6]`

Replacement commands such as /br 3d6 will not execute the modifier bucket. And command /br [3d6] is not recogized

**Comment by mjeffw** [comment]
Fixed in next release! Thanks for entering this issue.
