### ISSUE TITLE
GCA Export: basic speed format error

### ISSUE THREAD

**Issue by twzzl** [crnormand/gurps#933]
Hi,

I´m from Brazil, and my machine number format is configured with the number format decimal separator as , intead of . (00,00 insteal of 00.00). This cause the foundry being incapable of rolling initiative for number format error. maybe this could affect others parameter if decimal values. Maybe there is a way to force the import to correct the decimal separator.

Thanks

**Comment by mjeffw** [comment]
@twzzl Can you upload a sample export file for us to use for testing?

**Comment by twzzl** [comment]
Yes, tis is an example.

[Oficial de Segurança (GM).gca4.TXT](https://github.com/crnormand/gurps/files/7033289/Oficial.de.Seguranca.GM.gca4.TXT)

**Comment by mjeffw** [comment]
@twzzl  This will be fixed in the next release. Do you know why Basic Speed is entered as "6,25" but the weight of various equipment uses '.' as the decimal separator, as in `<weight type="number">1.4</weight>`? It would be nice if we could apply the same rule across all fields.
