### ISSUE TITLE
OtF that returns true if the actor has a specific Advantage

### ISSUE THREAD

**Issue by mjeffw** [crnormand/gurps#942]
There are several game rolls that are affected if the character has a specific advantage. Example: the roll to recover from mental stun is IQ unless the character has the Combat Reflexes advantage. Then it is IQ+6.

So I'd like to create an OtF that looks like this:

`/if [A:Combat Reflexes] [IQ+6] /else [IQ]`

**Comment by crnormand** [comment]
We might need to use a different character.  "A" is defined for "Attack" (Melee or Ranged).    What about '?'
`
/if [?:Combat Reflexes] [IQ+6] /else [IQ]`

or even just:
`
/if [?Combat Reflexes] [IQ+6] /else [IQ]`

We already have the function, GURPS.findAdDisad()

**Comment by crnormand** [comment]
Added https://github.com/crnormand/gurps/pull/1081
Format [?XX:name] where XX is:
    A: ads & attack (melee & range)
    AD: ads
    AT: attack (melee & ranged)
    M: melee
    R: ranged
    S: skills & spells
    SK: skills
    SP: spells

**Comment by crnormand** [comment]
`/if [?A:Bad Temper] {Has Bad Temper} {Does not have Bad Temper}`
