### ISSUE TITLE
Remember Last Rolls

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#943]
Would it be possible for the player to go through their older chat logs in the chat entry to their older rolls? It was something that was really good in Roll20 that I thought would be a great QoL change. This helps to reduce the "GM, what do I need to roll again? I fudged up the dice"

**Comment by crnormand** [comment]
Wow, great idea.   It isn't complete yet, but I am working towards making the targeted rolls (with modifiers) clickable, so a user can just scroll back in the chat log and try again (they would have to re-apply all of the modifiers, of course... but they will be listed, so it wouldn't be too much work).

![image](https://user-images.githubusercontent.com/8931036/131908840-3d22ce8a-9d11-4aaf-93dd-efba6f7635a1.png)

**Comment by crnormand** [comment]
Done https://github.com/crnormand/gurps/pull/969
