### ISSUE TITLE
Mouseover Modifiers "Window" sits off screen if user's resolution is not wide enough

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#963]
For users with lower resolutions screens or 4:3 aspect monitors (yep, some exist), the pop up/mouseover modifiers windows from the modifiers bucket opens at a fixed position about the bucket, which means the right side of it is off screen for those users.

Also happens if you have your browser window smaller, or a monitor in portrait mode (hence less width).

Slightly related, would be good if it was a click to open click to close rather than mouseover to avoid accidentally triggering it and/or having it close when you don't want to.

**Comment by mjeffw** [comment]
@Farmeroz -- there are two system settings that intend to deal with both small monitors, and clicking versus mouseover. Open the Game Settings dialog, and select "System Settings". Then scroll down looking for these two settings:

 - "Bucket: Show on mouse over" -- deselecting this and saving the settings prevents opening the modifier bucket unless it is clicked on. In this mode, the window also has a titlebar with a "✕ Close" button on it.
 - "Bucket: Scale Factor" -- Set this to scale the modifier bucket from 80% to 120%. Smaller works better for smaller monitors. 

Try using these settings to see if that works for your group and let me know so we can either fix the code, or close this issue. Thanks!

**Comment by Farmeroz** [comment]
@mjeffw Thanks, Nick - that's great!  Works well for my player with the smaller monitors.  He has asked if you might consider "click to open and click to close" in addition to the normal window close button, but that's just a minor enhancement, your solution works perfectly, thank you!
