### ISSUE TITLE
Popup To Add Or Reduce Uses In Equipment Sheet

### ISSUE THREAD

**Issue by Volksters** [crnormand/gurps#964]
A similar pop-up like the resource tracker to allow addition or reduction of uses instead of opening up the item window to do so will help with players who uses "uses" as ammo-track or magic uses.

**Comment by crnormand** [comment]
I added + and - buttons instead.
https://github.com/crnormand/gurps/pull/1117
![image](https://user-images.githubusercontent.com/8931036/143993878-75210c88-2e19-4ec4-9c75-6d63c44a208d.png)
