### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#970]
Note sure if this is Foundry side or GURPS side:

When you click on an Actor in the Combat Tracker, the token is highlighted with a thin line around the hex.  It's not very obvious.  It would be good to have a second click or long click generate a more obvious "beacon" to which token is related (flashing the ring around the hex, maybe?) - something to help identify quickly where various tokens are relating to the listed actors.  This can help in a large scene with lots of tokens.

Somewhat related, also the ability for a player or GM to click a hex and set off a "beacon" to indicate to someone exactly which hex they are indicating (this is something that exists in Roll20, for example).

**Comment by mjeffw** [comment]
> Somewhat related, also the ability for a player or GM to click a hex and set off a "beacon" to indicate to someone exactly which hex they are indicating (this is something that exists in Roll20, for example).

This can be accomplished using a module called Ping.
