### ISSUE TITLE
OtF query/help?

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#971]
So I worked out how to OtF to make several rolls at once, such as with a dual weapon attack.  Easy.  I worked out how to include the damage rolls as well, all in one click.

What I can't work out is how to if/then them so that the damage is only rolled if the attack succeed.  I know normally there'd be a defence before damage, but one click for all would be nice for multi-attacks and then the GM can apply if they aren't defended.

Example of what I have now:

GURPS.executeOTF(`A:"Masterpiece Katana (1H Swing)"-5 "Scissor Attack to the Neck!"`)
GURPS.executeOTF(`A:"Masterpiece Wakizashi (Swing)"-5 "Scissor Attack to the Neck!"`)
GURPS.executeOTF(`D:"Masterpiece Katana (1H Swing)"`)
GURPS.executeOTF(`D:"Masterpiece Wakizashi (Swing)"`)

Is there a way to make that all conditional?  Also, is there a way to add text to the damage roll output to identify which weapon it relates to?  In this case I know the katana does more, but that's not always the case.

On this generally, what's the maximum complexity of if/then?  Can they be nested (say, Excel style) to perform more than 1 test on the way to a result?  Like, check Blind Fighting and if successful roll weapon skill with a random location and then damage but if not roll a wild swing and if successful roll a random location and then damage otherwise miss.

**Comment by crnormand** [comment]
Yes, you can do that, and you don't need to make it a script macro.   It can be a straight chat macro:

`/if [A:"Masterpiece Katana (1H Swing)"-5 "Scissor Attack to the Neck!"] [D:"Masterpiece Katana (1H Swing)"]`

But if you need it to execute in a script macro, it would be:

`GURPS.executeOTF('/if [A:"Masterpiece Katana (1H Swing)"-5 "Scissor Attack to the Neck!"] [D:"Masterpiece Katana (1H Swing)"]')`

If you need to use nested IF statements, replace the` /then` with `{ }`.  The following will attempt the attack, and if successful, will attempt a DX check, and then if successful, do the damage for the katana.
`
/if [A:"Masterpiece Katana (1H Swing)"-5 "Scissor Attack to the Neck!"] { /if [DX] { [D:"Masterpiece Katana (1H Swing)"] } }`

As very common OtF is the Acrobatic Dodge:

`["Acro" ! /if [S:Acrobatics] [Dodge+2] [Dodge-2]]`

**Comment by Farmeroz** [comment]
Thanks, Chris - this is excellent - appreciate it.
