### ISSUE TITLE
Fireball Damage Macro does not apply FP

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#983]
Hi guys,

function fireballDamage(energy) {
 GURPS.executeOTF(`/r [${energy}d burn] *Cost ${energy}FP`)
}

new Dialog({
  title: `Fireball Damage`,
  content: `<div><label for="energy">Energy</label><input id="energy" type="text" /></div>`,
  buttons: {
    confirm: {
      label: "Confirm",
      callback: async (html) => fireballDamage(html.find('#energy').val())
    }
  }
}).render(true);

As per the GGA guide, works to ask for energy level and roll dice, but it's not applying to FP (and therefore I also couldn't make it apply to a different tracker I have running, being Threshold for a Threshold mage in the party - initially I assumed I didn't know how to rename FP to the right tracker (and some guidance there would be awesome :-) ) but then I tested it straight and saw FP wasn't being applied either.

**Comment by crnormand** [comment]
The On-the-Fly formula is incorrect.

The "*Costs X" needs to be inside of the square brackets.

`/r [ ${energy}d burn *Cost ${energy}FP ]`

**Comment by Farmeroz** [comment]
> The On-the-Fly formula is incorrect.
> 
> The "*Costs X" needs to be inside of the square brackets.
> 
> `/r [ ${energy}d burn *Cost ${energy}FP ]`

Currently it's:

function fireballDamage(energy) {
 GURPS.executeOTF(`/r [${energy}d burn] *Cost ${energy}FP`)
}

If I change it  to :

function fireballDamage(energy) {
 GURPS.executeOTF(`/r [ ${energy}d burn *Cost ${energy}FP`) ]
}

Then it doesn't run.

So then I tried adding the additional  [] whilst keeping the original []:

function fireballDamage(energy) {
 GURPS.executeOTF(`/r [ [${energy}d burn] *Cost ${energy}FP`)]
}

But that doesn't run either.

It only runs in the original syntax (which was copied from your original posting of it from somewhere, but  unhelpfully I can't remember where you posted it, sorry :(

But basicallly, changing the syntax as described above stops the script from working and leaving it the same stops the FP from being reduced.

Obviously I'm doing something wrong, but I can't figure it out?
