### ISSUE TITLE
[Bug] Character sheets become inaccessible after toggling Full/Tab view

### ISSUE THREAD

**Issue by SageThalcos** [crnormand/gurps#988]
I noticed an issue in the new 0.11.8 release in that in two of my worlds I can't open some character sheets anymore (i.e. double clicking on the actors or their tokens doesn't do anything). I was able to reproduce this issue by creating a new actor and switching back and forth between Tabbed View and Full View. After one or two flips, the sheet becomes inaccessible. Interestingly, this happens only once a character has been imported (GCA). It also happens separately between players. For example, my player flipped back and forth and couldn't get back into the sheet, but I still could as GM. But once I flipped back and forth, it broke. 

Similarly,  I also noticed that sheets sometimes get confused about what status they're in. For example, here's a character that says it's in Tabbed view, but thinks it's not.

![image](https://user-images.githubusercontent.com/92134248/136490636-031a6721-688a-46a0-99b3-457626e2b900.png)

**Comment by crnormand** [comment]
Are you running 0.11.8?    This was a known issue in 0.11.7 and I "thought" I fixed it (but maybe not ;-) )

**Comment by Farmeroz** [comment]
Also definitely 0.11.8 - I never exerpeiicned this with 0.11.7.

Where can  I find (and edit) actor-sheet-gcs.hbs on my side?

**Comment by Farmeroz** [comment]
Sorry, just realised you had realesed 0.11.9 - can confirm this bug is fixed.
