### ISSUE TITLE
Script Macros run for GM but not Players

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#991]
This issue became apparent in 0.11.7 and still appears in 0.11.8 and 0.11.9.

As a Player or Trusted Player, *some* Script Macros will not run (but Chat macros do).

Global settings for user levels are all set to allow Scripts and individual macro permissions are also set correctly.

Example of Script Macros that won't run for players but work for GM:

GURPS.executeOTF(/if [S:"Acrobatics"] [Dodge +2] /else [Dodge -2])

(I know this can be run as a chat macro, and it works in that case, but the above works for a GM level user but not a Player - and changing access level changes the ability to run it)

function fireballDamage(energy) {
 GURPS.executeOTF(/r [${energy}d burn] *Cost ${energy}FP)
}

new Dialog({
  title: Fireball Damage,
  content: <div><label for="energy">Energy</label><input id="energy" type="text" /></div>,
  buttons: {
    confirm: {
      label: "Confirm",
      callback: async (html) => fireballDamage(html.find('#energy').val())
    }
  }
}).render(true);

This works for GM but not player or trusted player.  Note, it also does not adjust FP (or any other stat - please see other bug post).

Example of a Script Maco that *does* work:

if (game.paused) game.togglePause()

So a player who can't press space to unpause the game can run the above to do so.

**Comment by crnormand** [comment]
I am unable to recreate your problem.  

I created a brand new world (in 0.11.9), 1 player and 2 actors.    The gamemaster was logged into my local Foundry VTT, and the "player" logged into the world using Chrome (on my Windows 10 machine).   I assigned ownership of the actors to the player, and when I clicked on the Execute Macro button (in Chrome), it showed:
![image](https://user-images.githubusercontent.com/8931036/136666685-9d2cdd16-09f1-439e-95c5-eb9084f68b84.png)


I tried the second macro (I didn't have the HTML, so I just put in a fixed number), executing the macro displayed:
![image](https://user-images.githubusercontent.com/8931036/136666788-8562a218-1715-4a56-816d-2ae16392c934.png)

And when I pressed Confirm, it showed the damage in the chat log:
![image](https://user-images.githubusercontent.com/8931036/136666810-345efc48-3d81-46ae-ad98-7768146f4416.png)

There do not seem to be any permission issues.    I know that the `GURPS.executeOTF()` function by itself does not do anything that requires permission.

Can you ZIP up your world and attach it?    If you are running Foundry locally, it will be located in the Users Directory under Data/worlds.
