### ISSUE TITLE
Query regarding Initiative Formula

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#992]
I can see how the initiative formula works.  That's all good.  I'm wondering if there's way to test for advantages like Enhanced Time Sense (or custom variants) and then add in a modifier (i.e. characters with ETS should always go first, so adding, say, 10 to the initiative calculation should boost them above everyone else (and if multiple characters have ETS  then the usual formula would  apply to determine who went first).

**Comment by crnormand** [comment]
You can do it in two stages... first you need to run a macro that checks each actor for whatever advantages or skills you want to check for, and then store that information in the actor.

Second, you use that new information in the initiative formula.  Here is an example macro that searches for Combat Reflexes and Tactics:

```
game.actors.contents.forEach(actor => {     
  let crb = 0
  if (!!GURPS.findAdDisad(actor, "Combat Reflexes")) {
    crb = 1
    ChatMessage.create({content:actor.name + " has Combat Reflexes!"})
  }
  let tact = 0
  if (!!GURPS.findSkillSpell(actor, "Tactics")) {
    tact = 1
    ChatMessage.create({content:actor.name + " has Tactics"})
  }
  actor.update({"data.additionalresources.crb": crb})
  actor.update({"data.additionalresources.tact": tact})
})
```


And now you can use the crb and tact values in the initiative formula,   Here is an example:

`@basicspeed.value + 1d6 +@additionalresources.crb + @additionalresources.tact`

This just takes basic speed, plus 1 for Combat Reflexes, plus 1 for Tactics and adds 1d6.   Of course, you can define anything you want.   The important step is executing the macro, and setting whatever values you want in the "data.additionalresources" section.

**Comment by Farmeroz** [comment]
Thanks, Chris - this works perfectly!
